### ISSUE TITLE
xmipp_movie_estimate_gain

### ISSUE THREAD

**Issue by rmarabini** [I2PC/scipion#1001]
#1000 coss

The command 

 scipion xmipp_movie_estimate_gain -i Runs/000002_ProtImportMovies/extra/FoilHole_3923121_Data_2880742_2880743_20161005_0234_frames.mrc --oroot Runs/008489_XmippProtMovieGain/movie_000001 --iter 1 --singleRef

fails with error:

00015:   XMIPP_ERROR 48:  Incorrect MultidimArray size.
00016:   Array_by_array: different shapes (+)
00017:   File: software/em/xmipp/libraries/data/multidim_array.h line: 3893

Input is a 4096*4096*32 movie that looks OK with scipion show. I can provide the movie if needed (to large to be uploaded here)

**Comment by josuegbl** [comment]
@cossorzano, this issue is fixed? If so, could you close it?

**Comment by cossorzano** [comment]
Yes
