### ISSUE TITLE
new label with relion

### ISSUE THREAD

**Issue by rmarabini** [I2PC/scipion#1005]
When running scipion 1.1 + relion 2 I get the warnings (executing 3d classification)

WARNING: Ignoring unknown column: rlnIgnoreHelicalSymmetry
WARNING: Ignoring unknown column: rlnHelicalKeepTiltPriorFixed

So it seems that there are two new labels in relion that was not been ported to scipion.

**Comment by azazellochg** [comment]
fixed in #1088
