### ISSUE TITLE
protocol "opic - localized subparticles"  fails when vector given

### ISSUE THREAD

**Issue by JuhaHuiskonen** [I2PC/scipion#1006]
I am running the test
tests.em.protocols.test_protocol_localized_reconstruction.TestLocalizedRecons

This works. However, if I change the input Vectors from type "cmm file" to "string" I get the following error:
Protocol failed: [Errno 2] No such file or directory: ' '

It seems there is a space instead of an empty string passed for the cmm file name.

**Comment by josuegbl** [comment]
Ok, Ill see this error. I could reproduce it.

**Comment by josuegbl** [comment]
Done!
