### ISSUE TITLE
resmap in scipion release 1.1

### ISSUE THREAD

**Issue by carmensmp** [I2PC/scipion#1013]
Hi,

when I try to run ResMap with two half volumes (box size=752px) the protocol just stalls at 
00016:   2017-05-18 14:08:06,512 INFO:  STARTED: estimateResolutionStep, step 2
00017:   2017-05-18 14:08:06,512 INFO:    2017-05-18 14:08:06.512385
00018:   2017-05-18 14:08:06,516 INFO:  Entered into dir: cd 'Runs/008888_ProtResMap'
and does nothing -- it does not die but it does not use any CPU. 

If I run ResMap on each of the half volumes separately it runs without problem.

**Comment by Vilax** [comment]
Hi, Carmen

Can you check if in the terminal appears a segmentation fault? I got a similar situation with large volumes and not enough RAM memory

Regards

Vilas

**Comment by carmensmp** [comment]
Hi, yes there is a segmentation fault message. My RAM is 256 GB, and
according to the system monitor the max RAM use was ~6%.

I have run ResMap (the original standalone program) in the same machine and
it did run.

  -------------------------------------------------------------
  Carmen San Martín, Ph. D.
  Centro Nacional de Biotecnología (CNB-CSIC)
  Darwin, 3
  28049-Madrid (SPAIN)
  Email:  carmen@cnb.csic.es
  Phone:  34-91-5855450
  Fax:     34-91-5854506 <http://www.cnb.csic.es/>
  http://tinyurl.com/carmensanmartinlab
  https://sites.google.com/site/adenonet/
  ------------------------------------------------------------

**Comment by azazellochg** [comment]
same as #704

**Comment by pconesa** [comment]
![image](https://user-images.githubusercontent.com/785633/50392774-8a90c680-0751-11e9-862d-472db3179948.png
I wish we could transfer this to the resmap plugin
