### ISSUE TITLE
gctf

### ISSUE THREAD

**Issue by rmarabini** [I2PC/scipion#1020]
After gctf installation the binary file has the following file modes:

-rwxr--r-- 1 roberto roberto 2091780 Sep 29  2016 /usr/local/scipion/software/em/Gctf-1.06/bin/Gctf-v1.06_sm_20_cu7.5_x86_64

That is, it can only be executed by the person who install it. file modes should be changed to

rwxr-xr-x so everybody can use it.

**Comment by azazellochg** [comment]
I thought this was fixed several times already... apparently not

**Comment by pconesa** [comment]
Me too! Thanks roberto.

**Comment by pconesa** [comment]
Done
