### ISSUE TITLE
gctf-2

### ISSUE THREAD

**Issue by rmarabini** [I2PC/scipion#1021]
each step in gctf takes about 2 seconds. Unfortunately process 74 micrographs takes about 10 minutes= 600 seconds, most of the time the computer is just waiting for the next step. It will save a lot of time to enable threads here so the workflow engine may start several works in parallel

**Comment by delarosatrevin** [comment]
Yes, totally agree. But you need to be careful about the load (cpu or ram) of the GPU. Moreover, it would be nice that threads could expand through many cards.

**Comment by rmarabini** [comment]
Another alternative is modify the wrapper so each step processes 10 micrographs

**Comment by delarosatrevin** [comment]
This is something we could discuss during my visit. Indeed, when not in streaming, it is a big difference between processing one by one versus in "batch" mode where more than one are processed in one shot.

**Comment by azazellochg** [comment]
A single Gctf job cannot run on multiple GPUs since it's not supported, however I like the idea of parallelisation over multiple GPUs in batch mode.
