### ISSUE TITLE
relion extract particle does not keep the id particles if extract from a subset

### ISSUE THREAD

**Issue by josuegbl** [I2PC/scipion#1022]
If you extract from a subset, the Id coming from coordinates is not kept in the extracted particles.
@delarosa, if you have not time, please tell me and ill try to fix it.

**Comment by delarosatrevin** [comment]
Fixed in 99b7fe183cb9f36c359f63a9df4f1226e7ad9ec9. 
Actually this problem was not only for the subset, but for any extraction with this protocol.
