### ISSUE TITLE
magnification distortion estimation fails

### ISSUE THREAD

**Issue by josuegbl** [I2PC/scipion#1025]
with the following error:

00036:   forrtl: error (65): floating invalid
00037:   Image              PC                Routine            Line        Source             
00038:   mag_distortion_es  0000000001780DF9  Unknown               Unknown  Unknown
00039:   mag_distortion_es  000000000177F770  Unknown               Unknown  Unknown
00040:   mag_distortion_es  000000000169BDC2  Unknown               Unknown  Unknown
00041:   mag_distortion_es  000000000164CDD8  Unknown               Unknown  Unknown
00042:   mag_distortion_es  0000000001653AE1  Unknown               Unknown  Unknown
00043:   mag_distortion_es  00000000016348E0  Unknown               Unknown  Unknown
00044:   mag_distortion_es  00000000004A0144  mag_distortion_es         565  mag_distortion_estimate.f90
00045:   mag_distortion_es  00000000004A51FB  mag_distortion_es         407  mag_distortion_estimate.f90
00046:   mag_distortion_es  000000000173AA43  Unknown               Unknown  Unknown
00047:   /bin/sh: line 17:  7066 Aborted                 /usr/local/scipion/software/em/mag_distortion-1.0.1/bin/mag_distortion_estimate_openmp.exe  > Runs/000412_ProtMagDistEst/extra/mag_dist_estimation.log <<eof
00048:   Runs/000412_ProtMagDistEst/tmp/input_stack.mrc
00049:   Runs/000412_ProtMagDistEst/extra/output_amp.mrc
00050:   Runs/000412_ProtMagDistEst/extra/output_amp_rot.mrc
00051:   Runs/000412_ProtMagDistEst/extra/output_amp_corrected.mrc
00052:   3.540000
00053:   YES
00054:   2.500000
00055:   2.100000
00056:   0.030000
00057:   0.000500
00058:   0.000000
00059:   180.000000
00060:   0.100000
00061:   0.200000
00062:   0.010000
00063:   512
00064:   eof
00065:   
00066:   Traceback (most recent call last):
00067:     File "/usr/local/scipion/pyworkflow/protocol/protocol.py", line 182, in run
00068:       self._run()
00069:     File "/usr/local/scipion/pyworkflow/protocol/protocol.py", line 228, in _run
00070:       resultFiles = self._runFunc()
00071:     File "/usr/local/scipion/pyworkflow/protocol/protocol.py", line 224, in _runFunc
00072:       return self._func(*self._args)
00073:     File "/usr/local/scipion/pyworkflow/protocol/protocol.py", line 1077, in runJob
00074:       self._stepsExecutor.runJob(self._log, program, arguments, **kwargs)
00075:     File "/usr/local/scipion/pyworkflow/protocol/executor.py", line 56, in runJob
00076:       env=env, cwd=cwd)
00077:     File "/usr/local/scipion/pyworkflow/utils/process.py", line 51, in runJob
00078:       return runCommand(command, env, cwd)
00079:     File "/usr/local/scipion/pyworkflow/utils/process.py", line 65, in runCommand
00080:       check_call(command, shell=True, stdout=sys.stdout, stderr=sys.stderr, env=env, cwd=cwd)
00081:     File "/usr/local/scipion/software/lib/python2.7/subprocess.py", line 540, in check_call
00082:       raise CalledProcessError(retcode, cmd)
00083:   CalledProcessError: Command 'export NCPUS=1 ; /usr/local/scipion/software/em/mag_distortion-1.0.1/bin/mag_distortion_estimate_openmp.exe    << eof > Runs/000412_ProtMagDistEst/extra/mag_dist_estimation.log
00084:   Runs/000412_ProtMagDistEst/tmp/input_stack.mrc
00085:   Runs/000412_ProtMagDistEst/extra/output_amp.mrc
00086:   Runs/000412_ProtMagDistEst/extra/output_amp_rot.mrc
00087:   Runs/000412_ProtMagDistEst/extra/output_amp_corrected.mrc
00088:   3.540000
00089:   YES
00090:   2.500000
00091:   2.100000
00092:   0.030000
00093:   0.000500
00094:   0.000000
00095:   180.000000
00096:   0.100000
00097:   0.200000
00098:   0.010000
00099:   512
00100:   eof
00101:   ' returned non-zero exit status 134
00102:   Protocol failed: Command 'export NCPUS=1 ; /usr/local/scipion/software/em/mag_distortion-1.0.1/bin/mag_distortion_estimate_openmp.exe    << eof > Runs/000412_ProtMagDistEst/extra/mag_dist_estimation.log

**Comment by azazellochg** [comment]
works for me with same params (pix size is different)
```
00017:   export NCPUS=1 ; /home/gsharov/soft/scipion/software/em/mag_distortion-1.0.1/bin/mag_distortion_estimate_openmp.exe    << eof > Runs/000460_ProtMagDistEst/extra/mag_dist_estimation.log
00018:   Runs/000460_ProtMagDistEst/tmp/input_stack.mrc
00019:   Runs/000460_ProtMagDistEst/extra/output_amp.mrc
00020:   Runs/000460_ProtMagDistEst/extra/output_amp_rot.mrc
00021:   Runs/000460_ProtMagDistEst/extra/output_amp_corrected.mrc
00022:   1.100000
00023:   YES
00024:   2.500000
00025:   2.100000
00026:   0.030000
00027:   0.000500
00028:   0.000000
00029:   180.000000
00030:   0.100000
00031:   0.200000
00032:   0.010000
00033:   512
00034:   eof
00035:   
00036:   FINISHED: runJob, step 2
00037:     2017-05-24 12:01:28.754380
00038:   STARTED: createOutputStep, step 3
00039:     2017-05-24 12:01:28.765187
00040:   FINISHED: createOutputStep, step 3
00041:     2017-05-24 12:01:28.771592
00042:   Not cleaning temporarly files since SCIPION_DEBUG_NOCLEAN is set to True.
00043:   ------------------- PROTOCOL FINISHED
```
In your case looks like the program crashes not the scipion.. weird

**Comment by azazellochg** [comment]
@josuegbl is it still the case? Could you dropboxed me the movie?

**Comment by azazellochg** [comment]
@josuegbl can I close this?
