### ISSUE TITLE
problem to plot ctf resolution histogram when ctffind4 gives Inf

### ISSUE THREAD

**Issue by carmensmp** [I2PC/scipion#1032]
Sometimes ctffind4 assigns "Inf" value to the maximum resolution ("Thon rings with good fit up to"). This appears in the protocol analyze results as "Infinity" in the _ctffindr_ctfResolution column. Plotting this column as histogram produces an empty plot. Error in terminal says:

/usr/local/scipion/software/lib/python2.7/site-packages/numpy/core/function_base.py:88: RuntimeWarning: invalid value encountered in multiply
[ctfs.sqlite.zip](https://github.com/I2PC/scipion/files/1040564/ctfs.sqlite.zip)

  y = _nx.arange(0, num) * step + start
/usr/local/scipion/software/lib/python2.7/site-packages/numpy/lib/function_base.py:998: RuntimeWarning: invalid value encountered in subtract
  return a[slice1]-a[slice2]

A good solution would be to allow the user to define the histogram range. This would be useful in general, not just to solve this problem.

**Comment by azazellochg** [comment]
Same as #768

**Comment by pconesa** [comment]
addressed in scipion3.0
