### ISSUE TITLE
Relion-1.x  particle extraction does not work.

### ISSUE THREAD

**Issue by pconesa** [I2PC/scipion#1035]
@delarosatrevin . I'm getting an error, not sure if it should work or it was only for Relion 2.0.

If I point to Relion-2.0 it works.

**Comment by delarosatrevin** [comment]
@pconesa The particles-extraction protocol was developed specifically for Relion-2.x versions. I don't think it worth to make it work for 1.x versions (Indeed it was not even included in the previous release of Scipion).

**Comment by pconesa** [comment]
Ok, I'll add a validation for that. Thanks @delarosatrevin

**Comment by delarosatrevin** [comment]
I think we can do the same as in picking protocol...if it is not version 2.x or greater, we could hide the protocol. This will be even more clear than the validation.
