### ISSUE TITLE
Bug in OF movie alignment

### ISSUE THREAD

**Issue by delarosatrevin** [I2PC/scipion#1040]
It seems that there is a bug in the OF protocol working (when detecting new output, even if the input is not in streaming). I have seen this error a couple of times before this new one. 

@rmarabini , @josuegbl Has this error appeared at the CNB??

Following is the log:

5/  11 sec. xmipp_movie_optical_alignment_cpu -i Runs/000137_XmippProtOFAlignment/tmp/movie_000033/input_movie.xmd -o Runs/000137_XmippProtOFAlignment/extra/FoilHole_2052809_Data_2047433_2047434_20161203_0435_frames_aligned_mic.xmd  --frameRange 0 16  --winSize 150 --groupSize 1 --oavg Runs/000137_XmippProtOFAlignment/extra/FoilHole_2052809_Data_2047433_2047434_20161203_0435_frames_aligned_mic_DW.mrc --oavgInitial Runs/000137_XmippProtOFAlignment/tmp/movie_000033/uncorrected_mic.mrc --cropULCorner 0 0 --cropDRCorner -1 -1  --doseCorrection 2.260000 1.100000 200.000000 0.000000 post --oUnc Runs/000137_XmippProtOFAlignment/tmp/movie_000033/FoilHole_2052809_Data_2047433_2047434_20161203_0435_frames_unWt_mic.mrc Runs/000137_XmippProtOFAlignment/tmp/movie_000033/FoilHole_2052809_Data_2047433_2047434_20161203_0435_frames_unWt_movie.mrcs
00655:      6/  12 sec. Traceback (most recent call last):
00656:     File "/nethome/josem/scipion/pyworkflow/protocol/protocol.py", line 185, in run
00657:       self._run()
00658:     File "/nethome/josem/scipion/pyworkflow/protocol/protocol.py", line 1090, in _run
00659:       self._runSteps(startIndex)
00660:     File "/nethome/josem/scipion/pyworkflow/protocol/protocol.py", line 974, in _runSteps
00661:       self._stepsCheck)
00662:     File "/nethome/josem/scipion/pyworkflow/protocol/executor.py", line 220, in runSteps
00663:       stepsCheckCallback()
00664:     File "/nethome/josem/scipion/pyworkflow/em/protocol/protocol_movies.py", line 150, in _stepsCheck
00665:       self._checkNewOutput()
00666:     File "/nethome/josem/scipion/pyworkflow/em/protocol/protocol_align_movies.py", line 225, in _checkNewOutput
00667:       'outputMicrographs')
00668:     File "/nethome/josem/scipion/pyworkflow/em/protocol/protocol_align_movies.py", line 196, in _updateOutputMicSet
00669:       micSet = self._loadOutputSet(SetOfMicrographs, sqliteFn)
00670:     File "/nethome/josem/scipion/pyworkflow/em/protocol/protocol_align_movies.py", line 123, in _loadOutputSet
00671:       outputSet.loadAllProperties()
00672:     File "/nethome/josem/scipion/pyworkflow/object.py", line 1196, in loadAllProperties
00673:       for key in self._getMapper().getPropertyKeys():
00674:     File "/nethome/josem/scipion/pyworkflow/mapper/sqlite.py", line 920, in getPropertyKeys
00675:       return self.db.getPropertyKeys()
00676:     File "/nethome/josem/scipion/pyworkflow/mapper/sqlite.py", line 1017, in getPropertyKeys
00677:       self.executeCommand(self.SELECT_PROPERTY_KEYS)
00678:   OperationalError: no such table: Properties
00679:   ------------------- PROTOCOL FAILED (DONE 2/210)
00680:      3/  10 sec.

**Comment by pconesa** [comment]
This does not happen always, right?

**Comment by pconesa** [comment]
It seems there is a problem where mic have to be saved without the Dose.

**Comment by rmarabini** [comment]
Some time ago we indrocude a dose filter in optical flow. If the dose is
not set and the filter is ON many nasty things may happend. I  guess
validate should check this.

   Roberto
