### ISSUE TITLE
ctffind protocol does not accept SetOfMovies as input

### ISSUE THREAD

**Issue by JuhaHuiskonen** [I2PC/scipion#1041]
Ctffind4 works on movies in addition to micrographs but the scipion protocol does not have an option for this yet.

**Comment by delarosatrevin** [comment]
Yep, other people has asked this feature as well. Do you know if there are any special consideration for calling ctffind4 with micrographs?

**Comment by JuhaHuiskonen** [comment]
Some people prefer to use unaligned movies, some prefer micrographs (without dose weighting) so would be good to have both options (maybe add a radio button asking 'use movies instead of micrographs'). Cant think of anything else.

**Comment by delarosatrevin** [comment]
Yes...I know. I was thinking more about the ctffind4 command line and
params.

**Comment by JuhaHuiskonen** [comment]
Ah sorry - don't know, thanks to Scipion I rarely use command line nowadays
;-)

**Comment by azazellochg** [comment]
That's on my todo list as well, for a long time  :) As well as per-particle CTF refinement. Ctffind4 cmd line in case of movies requires a couple of additional options, but the rest is the same. The only thing is movies must have .mrc extension (not mrcs), however simple link/rename works.

**Comment by delarosatrevin** [comment]
@azazellochg do you have a branch with something for this? @JuhaHuiskonen I'm not sure if this will be ready for release-1.1, but we are planning a quick 1.1.1 release with some features for facilities such as picking and extraction in streaming. So we could add this feature in this one.

**Comment by azazellochg** [comment]
@delarosatrevin  I only started to modify gctf protocol for particle ctf refinement but this is now very much outdated. Nothing for movies though

**Comment by pconesa** [comment]
Good to know, and thank you all for this. We are about to release 1.1, hopefully today, so no time for this. Sorry. But we can have it in the "facilities" branch. or in a later "patch".

**Comment by JuhaHuiskonen** [comment]
@azazellochg great to hear per-particle CTF estimation is coming, I was just today looking for that feature. When do you think you will have something ready? Many thanks.

**Comment by azazellochg** [comment]
same as #146 
@JuhaHuiskonen I will close this and keep the original issue open. Can tell for sure when this is ready, but I'll tell you as soon as it comes to devel :)
