### ISSUE TITLE
continue streaming protocols

### ISSUE THREAD

**Issue by rmarabini** [I2PC/scipion#1045]
this is a reminder for @delarosatrevin about allowing streaming protocols to continue. At present if a streaming protocol ends there is no way to continue it. This is specially important for the scipionbox

**Comment by delarosatrevin** [comment]
Thanks for the remainder @rmarabini, I will take a look at it, as soon as I can

**Comment by delarosatrevin** [comment]
@rmarabini Can we close this? I think it is already fixed.

**Comment by rmarabini** [comment]
No sure about this. I think the situation is as follows.

- If a protocols closes there is no way to continue it  (I do not think
this is a bad decision)
- But thinking in facilities it would be great to "continue" an import
movie process even if it has close. Think in the following case: You start
to collect your data, for some reason The data acquisition is stopped and
you want to continue 2, 3 days later
- What we agree was to add to the import movies protocol the option
"continue". When this option is enabled the input is another movie import.
The second movie import should check which movies are already imported and
continue with the rest

    I think I can volunteer for this.

            Roberto

**Comment by pconesa** [comment]
I think this is covered in scipion 2.0.
I'm closing this issue. Feel free to reopen it if I'm wrong or missed something.

**Comment by cossorzano** [comment]
Here in Leeds, we are experiencing all kinds of problems with the stop, continuation, and restart from here. We may leave the issue closed, but it is certainly something to invest some time, because in facilities, it is really needed.

**Comment by pconesa** [comment]
Thanks @cossorzano it would be nice to have a more detail description of what are the issues. I'm sure when you come back, we will talk about them.
