### ISSUE TITLE
./scipion test tests.em.workflows.test_workflow_relion.TestWorkflowRelionPick is failing

### ISSUE THREAD

**Issue by pconesa** [I2PC/scipion#1049]
Check buildbot.

**Comment by ldelcano** [comment]
On that builder Relion2 was compiled with CUDA 5.5, which is insufficient. Remake link /usr/local/cuda to point to cuda-7.5 and reinstalled packages. Also recompiled Xmipp since opencv / optical flow was compiled also with cuda 5.5.
