### ISSUE TITLE
mrc, convert

### ISSUE THREAD

**Issue by rmarabini** [I2PC/scipion#1051]
This is a reminder for myself

ccp.convert -> fix writeHeader

a) dictionary should be ordered dictionary
b) writeHeader mast provide a dictionary with the same size that chain
c) function checkScipionCCPHeader is missing

**Comment by delarosatrevin** [comment]
@rmarabini, have you already addrees this? If not, is it still remembering you to do it? ;)

**Comment by rmarabini** [comment]
I think we can close this. We have now a class that handles mrc header
related issues. If somebody, someday process the model 05 pull request the
class should be public
