### ISSUE TITLE
Buildbot: tests.em.workflows.test_workflow_relion.TestWorkflowRelionExtract fails cause defocusU is not ok

### ISSUE THREAD

**Issue by ldelcano** [I2PC/scipion#1053]
Test is failing on the following assertion:
self.assertAlmostEqual(ctfModel.getDefocusU(), 23467, delta=10)
because:
AssertionError: 27938.115234 != 23467 within 10 delta

have a look at it to see if there is a problem or delta is not big enough (random output number?)

**Comment by pconesa** [comment]
There is a subset step based on random going from 20 mics to 10.

If the first mic, is randomly selected, then the test for the CTF values of the first particle extracted matches (case for yesterday successful run in buildbot). however, if the random step does not select the mic, then the first particle is not from the first mic and therefore the ctf is not the one expected and the test fails.

This is a test "bug", to be fixed but not needed for the release.

**Comment by dmaluenda** [comment]
The third extraction test (Relion) is to check the correct particles extraction from
a subset of the initial set (i.e. smaller than the CTFs and coords)

This subset was depending to the random subset, thus the assertation procedure with
the first item of the final output sometimes was failed.

Now the subset is done with the splitSet with NO randomize, thus the first item is correct.

Commited in Facilities-fixes [b330c8af5b8b04ee2b0f2865f4cbb07b0c887790]
