### ISSUE TITLE
Showj crash when averaging particles from a class.

### ISSUE THREAD

**Issue by delarosatrevin** [I2PC/scipion#1055]
It seems that Showj is crashing (not always) when averaging particles from a 2D class. In my case I have been able to reproduce many times, but not always. I have got this error in the cluster here and also in my Linux workstation. The sequence is as follows:

1) Visualize SetOfClasses2D (either from Relion2D or CL2D)
2) Open the particles of a given class
3) Compute STD and AVG images (in some cases work and in others crash)

Its seems to be related to the native function MDL::isTextFile (see two error logs attached)
[showj_crashes.txt](https://github.com/I2PC/scipion/files/1067700/showj_crashes.txt)

**Comment by pconesa** [comment]
Thanks @delarosatrevin this is the same as #837. I'm removing the milestone.

**Comment by delarosatrevin** [comment]
Ok, I didn't noticed the previous one, where @josuegbl seems to be shouting out with big bold letters ;)
