### ISSUE TITLE
./scipion test tests.em.workflows.test_workflow_high_throughput FAILS

### ISSUE THREAD

**Issue by pconesa** [I2PC/scipion#1056]
hi Laura, could you please double check that your latest changes actually improved the test uncovering a bug in highres, and if so, talk to @coss?

Traceback (most recent call last):
77  File "/home/buildbot-slave/data/slave/release11_Workflows_Tests/build/software/lib/python2.7/unittest/case.py", line 329, in run
78    testMethod()
79  File "/home/buildbot-slave/data/slave/release11_Workflows_Tests/build/pyworkflow/tests/em/workflows/test_workflow_high_throughput.py", line 98, in test_workflow
80    self.assertSetSize(protCAPCA.imcFile, msg="There was a problem with Spider Dimension Reduction")
81  File "/home/buildbot-slave/data/slave/release11_Workflows_Tests/build/pyworkflow/tests/tests.py", line 148, in assertSetSize
82    self.assertNotEqual(object.getSize(), 0, msg)
83AttributeError: 'PcaFile' object has no attribute 'getSize'

**Comment by coss** [comment]
Hmm?

**Comment by pconesa** [comment]
Don't worry @coss , this was us messing up with the test. It's already fixed locally.

**Comment by pconesa** [comment]
Sorry @coss I didn't want to to mention you. I really meant @cossorzano .
