### ISSUE TITLE
MPI missing, couldnt run parallel nodes 

### ISSUE THREAD

**Issue by sunnoon** [I2PC/scipion#1066]
I am using cluster to run scipion. As a beginner, I dont know if my problem is a common problem.
I installed the software as tutorial. But, there is no MPI can choose on the all GUI in micrographs and particles catalogs(protocols SPA). When I run the movie alignment, for example, the cluster was not used. so the process is very slow, can take weeks. 
And not only i have the same problem, I know one guy in our institute also has same problem. But he use GPU, so the speed is not slow. 
Is there some solution to solve the problem, if i want to run it on cluster.
looking forward to your reply.
![gui of mine](https://user-images.githubusercontent.com/27296912/27221547-39d7d464-5289-11e7-8dc8-a50b12a72a9d.PNG)

**Comment by delarosatrevin** [comment]
Hi,
You are running the previous version of Scipion, where some movie alignment
protocols where all together in the same protocol.
Another disadvantage is that it was only working with threads, not with
MPI. I would recommend to updated the recently (yesterday)
released 1.1 version. In that one the movie alignment protocols are
separated and you can also use MPI in some cases.

Hope that helps,
Jose Miguel
