### ISSUE TITLE
continue crashed relion runs

### ISSUE THREAD

**Issue by JuhaHuiskonen** [I2PC/scipion#1082]
Sometimes runs crash if max walltime on a cluster is reach. I can't see an option to continue a run in this case. Perhaps the relion protocols could create/update a relion refinement object after each completed iteration? I think it would be enough to have this object for the last current iteration only.

**Comment by delarosatrevin** [comment]
Hi @JuhaHuiskonen, you can make a copy of the protocol and then set 'Continue from previous protocol?' to yes and then use as input the crashed protocol. The new protocol (in continue mode) will continue from the last iteration of the previous one. Is this what you are asking for?

For the future maybe we should consider to allow the 'Continue' to be done within the same protocol to avoid extra (and superfluous) boxes, although they really reflect how the processing was done.

**Comment by JuhaHuiskonen** [comment]
Hi @delarosatrevin, ok I agree with that logic and it does work as you say. However, the protocol for the crashed run is in a funny state. If I make a copy of if and try to continue to run, I get an error "Error during EXECUTE: unable to close due to unfinalised statements". The same happens if I create a fresh protocol and try to continue from the crashed run. The status of the crashed run is 'failed (done 2/3)', it crashed in the last iteration (this time due to memory requirement).

**Comment by JuhaHuiskonen** [comment]
Hi @delarosatrevin. I got a bit further with my tests. The fact that I have two different Scipion installations that both see the same file system and project has probably something to do with this. If I create a continuation protocol on the same machine (a GPU cluster) where the crash occurred, it works. However, when I execute it on the other machine (a CPU cluster) I get again errors. This time not in a pop-up window as last time but on the terminal only (Operational Error: unable to close due to unfinalised statements). The job does get submitted so it should be fine.

**Comment by delarosatrevin** [comment]
Hi @JuhaHuiskonen, This is a bit strange. Could you check in your project folder if there are some *sqlite.journal files? These files are produced when some sqlite database files are in use and locked, I'm not sure if that could be the case here. 

You said the job get submitted despite the errors in the command line, does it status get updated in the project GUI?

**Comment by JuhaHuiskonen** [comment]
Hi  @delarosatrevin. There are no journal files in the project folder.  The status of the protocol remained as 'saved' (the job is still in the cluster queue).

**Comment by delarosatrevin** [comment]
If you close and open again the GUI, do you still have similar Sqlite errors?
Could you double-check that are not Scipion related processing hanging around and locking .sqlite files?

**Comment by delarosatrevin** [comment]
@JuhaHuiskonen Is this problem still happening?

**Comment by JuhaHuiskonen** [comment]
I think we can close this. I haven't been able to reproduce this lately

**Comment by delarosatrevin** [comment]
Thanks!
