### ISSUE TITLE
HTML Report of ProtMonitorSummary

### ISSUE THREAD

**Issue by yaizar** [I2PC/scipion#1097]
Retouch report design and add more info about the monitored protocols - for now, add a Micrograph gallery.

**Comment by delarosatrevin** [comment]
This is the viewer in desktop, it could be a good starting point for the web report:

![screenshot_20170628_173350](https://user-images.githubusercontent.com/8441688/27858845-0c4c05f4-6177-11e7-8113-81a1f79513f8.png)

**Comment by yaizar** [comment]
I started with the gallery, it would look something like this - probably without the titles under the image, and adding the rest of the information in the table when we open each single image?
![image](https://user-images.githubusercontent.com/4609687/27859998-045cc794-617b-11e7-91c7-fce23fc66083.png)
![image](https://user-images.githubusercontent.com/4609687/27860066-432869a6-617b-11e7-9bfd-a1e9ae64b159.png)

We also considered having a table, would this be preferable? It didn't make a lot of sense to me because the report is much narrower than the desktop viewer, so the thumbnails looked a bit too small.. but I can go for that if it's easier to read.

**Comment by delarosatrevin** [comment]
I think it would be very useful for the users to see the Thong rings, shift plots and defocus values (column values) all at a glance for the movie/micrographs that are visible.

**Comment by pconesa** [comment]
let's tweak it a bit.....even if not perfect is great to have something to show in the facilities meeting, and then we will gather feedback.

**Comment by delarosatrevin** [comment]
Yes, but when we discuss about it during my last visit to Madrid...we talk about something similar to the desktop viewer...and it also seems very similar to what people in NeCen had. I think the feedback would be good for further improvement, but I think the desktop one cover the very basic needs of what users are interesting to look. Do you think is to complicated to have something similar in web?

**Comment by pconesa** [comment]
No, I agree. I'm not saying to stop here....replicating the "viewer" is 
what we had in mind.

**Comment by yaizar** [comment]
OK so here the table:
![image](https://user-images.githubusercontent.com/4609687/27951332-d1bf9628-6304-11e7-8daa-f7d6f14e2275.png)

Images are clickable and when we open them it looks like this:
![image](https://user-images.githubusercontent.com/4609687/27951462-50b72400-6305-11e7-911b-
c3abc28e730b.png)

Let me know if you have any thoughts.

One question, the report dir and the content is destroyed and re-generated all the time, do we want to keep it this way?

**Comment by delarosatrevin** [comment]
Hi @yaizar, It looks really great! One more request (sorry for that), could the height of the thumbnails be somehow configured from the monitor? This will provide some flexibility to decide in each site to have less rows but bigger thumbnails view or the other way around. 

Regarding the other point, I think re-generating all the time is acceptable for the one html file of the general report, but for this one we should consider if there is a performance penalty for the size of the expected datasets. Nowadays, it can goes from 1000 movies to 5000. This, in terms of lines of text in a file is not much.

**Comment by yaizar** [comment]
I think getting the thumbnail size from the monitor should be possible, I'll look into it. With bigger thumbnails the table will have to be horizontally scrollable though i.e. people won't see the numeric columns at a glance.

About the other point: Okay, I was asking  because I was putting the thumbnails in the same directory as the report and they're getting removed and rewritten every time, so I think I'm gonna have it remove only the html file but not the directory where it's contained.

**Comment by delarosatrevin** [comment]
How much will be seen will also depends on how big will be the displaying monitor. 

I will try to avoid deleting and copying all thumbnails all the time.

**Comment by yaizar** [comment]
well yeah but the rest of the content has a fixed width of 800px, would we want the table to overflow this width?

**Comment by delarosatrevin** [comment]
I think it could be useful to make the best use of the available screen. I would say that users in the facilities will have pretty big monitors for that. With boostrap (and I guess other js libraries) it is possible to query the display size or something like that.
