### ISSUE TITLE
Streaming end token file

### ISSUE THREAD

**Issue by yaizar** [I2PC/scipion#1098]
Shows up in the streaming tab of import movies but I don't think it's  implemented. 
Should we implement it or remove it? The expected behavior of this param would be to enter a filename, say movie21.mrcs, so that the protocol stops when this movie is imported?

**Comment by yaizar** [comment]
@delarosatrevin can you confirm if this is missing or I'm mistaken?

**Comment by delarosatrevin** [comment]
Hi @yaizar I think we could remove that option. Now there is a more clear way to stop the streaming. The operator can just right-click -> STOP STREAMING and this will generate an special file (which name can not be changed now) that will stop the polling and close the set.
