### ISSUE TITLE
relion 2 "Inf" values in star files

### ISSUE THREAD

**Issue by azazellochg** [I2PC/scipion#1110]
When displaying results of 2D classification in relion 2.1 I get tons of warnings:
```
WARNING: MetaData: Error parsing column 'rlnEstimatedResolution' value.
WARNING: MetaData: Error parsing column 'rlnOverallFourierCompleteness' value.
WARNING: MetaData: Error parsing column 'rlnClassPriorOffsetX' value.
WARNING: MetaData: Error parsing column 'rlnClassPriorOffsetY' value.
```
The problem is that in new Relion the values that are supposed to be floating point numbers (DOUBLE) sometimes have "inf" value (in old versions they were 999.99 I guess). Is there a way to fix this special case without touching xmipp metadata code? ([here?](https://github.com/I2PC/scipion/blob/master/software/em/xmipp/libraries/data/metadata_label.cpp#L652))

**Comment by josuegbl** [comment]
@delarosatrevin, could you check this or remove the milestone?

**Comment by pconesa** [comment]
This is becoming frequent. I'm moving this to "Ready" at least for devel.

**Comment by pconesa** [comment]
@azazellochg , @delarosatrevin , @cossorzano  and @josuegbl , I'm looking at this at least to have something  "working" when those inf values appear.
I see 2 options now:

1.- Allow "inf" values for DOUBLE types in metadata....which seems to work but I'm concern about a future problem when something else expecting number will find the "inf"

2.- Redefine that relion field (rlnEstimatedResolution) to String.

I feel more comfortable with 2 now, but I want to hear from you.

**Comment by azazellochg** [comment]
I'm still gettting this in scipion-2.0.0-fixes and relion3:
```
WARNING: MetaData: Error parsing column 'rlnEstimatedResolution' value.
WARNING: MetaData: Error parsing column 'rlnOverallFourierCompleteness' value.
WARNING: MetaData: Error parsing column 'rlnClassPriorOffsetX' value.
WARNING: MetaData: Error parsing column 'rlnClassPriorOffsetY' value.
WARNING!!! valueIn.failed = True, binding NULL
WARNING!!! valueIn.failed = True, binding NULL
WARNING!!! valueIn.failed = True, binding NULL
WARNING!!! valueIn.failed = True, binding NULL
WARNING!!! valueIn.failed = True, binding NULL
```
