### ISSUE TITLE
volume wizards issue

### ISSUE THREAD

**Issue by azazellochg** [I2PC/scipion#1115]
I might be missing something, but in 1.1 version the filter wizard shows incorrect image on the left panel - it looks like masked something... This is the case with all wizards working on volumes. When I look at the volume itself it looks fine.
![screenshot_20170712_155500](https://user-images.githubusercontent.com/6952870/28128891-32641f58-6729-11e7-9546-c444941b7492.png)

**Comment by azazellochg** [comment]
If I import this volume and then use any wizard then it looks ok.

**Comment by pconesa** [comment]
Hi, @azazellochg , I'm looking at this. I've added a xmipp volume filter protocol after the last protocol in TestRelionClassify3D and don't see it wrong....any idea how to reproduce this behavior?
![Screenshot from 2017-10-05 09-29-50.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/5695f1039397ed1300826771/125516c66e82c728ace21e0d46db978826878dba87e6ab03a24fff99691477227e49f27b3dd5b668ef1b365356424bac53444d04bea6d37ef5f22e7a98590de4d46b5871c73d43febb8b4ebc03ba20d94f86bebd8f5edcfa7f74b9dfd0126754505a9bf54f34a8934acd58f14ae94553a4163661e0647b.png)

**Comment by pconesa** [comment]
Wait...this is a different wizard,right?

**Comment by azazellochg** [comment]
Hi @pconesa ! I have just checked this a bit more thoroughly:
branch release-1.1.facilities-devel
Looks like this bug is present only when using wizard of XmippProtFilterVolumes and relion auto-refine 3d output volume (output from other relion protocols or subsets/imported volumes are ok).
