### ISSUE TITLE
gCTF failing, missing file at tmp folder...

### ISSUE THREAD

**Issue by pconesa** [I2PC/scipion#1118]
Does anyone have a clue to what is happening with gCTF protocol:

2017-07-12 16:21:17,658 INFO:  STARTED: _estimateCTF, step 1
2017-07-12 16:21:17,658 INFO:    2017-07-12 16:21:17.658304
2017-07-12 16:21:18,734 INFO:  /scipion/release-1.1-headless-devel
 /scipion/release-1.1-headless-devel/scipion/software/em/Gctf-1.06/bin/Gctf-v1.06_sm_20_cu7.5_x86_64  --apix 1.060000 --kV 300.000000 --cs 2.700000 --ac 0.100000 --dstep 5.000020 --defL 2500.000000 --defH 40000.000000 --defS 500.000000 --astm 100.000000 --resL 21.200000 --resH 3.028571 --do_EPA 0 --boxsize 512 --plot_res_ring 1 --gid 0 --bfac 150 --B_resH 2.120000 --overlap 0.500000 --convsize 85 --do_Hres_ref 0 --EPA_oversmp 4 --do_validation 0 Runs/000118_ProtGctf/tmp/FoilHole_11970051_Data_11970680_11970681_20170712_1409-frames_aligned_mic.mrc > Runs/000118_ProtGctf/extra/FoilHole_11970051_Data_11970680_11970681_20170712_1409-frames_aligned_mic/ctfEstimation.txt
2017-07-12 16:21:18,966 ERROR:  Protocol failed: [Errno 2] No such file or directory: 'Runs/000118_ProtGctf/tmp/FoilHole_11970051_Data_11970680_11970681_20170712_1409-frames_aligned_mic.ctf'
2017-07-12 16:21:18,977 INFO:  FAILED: _estimateCTF, step 1

**Comment by azazellochg** [comment]
what does the output (Runs/000118_ProtGctf/extra/FoilHole_11970051_Data_11970680_11970681_20170712_1409-frames_aligned_mic/ctfEstimation.txt) shows? Did it calculate ctf?

**Comment by kevinpetersavage** [comment]
There is a completely empty file there.

**Comment by azazellochg** [comment]
Does it run if you launch it through "scipion run... " ?

**Comment by azazellochg** [comment]
Great! Btw, there is a binary for Gctf compiled with CUDA 8:
http://www.mrc-lmb.cam.ac.uk/kzhang/Gctf/Gctf_v1.06/bin/

**Comment by pconesa** [comment]
Thank you @azazellochg
