### ISSUE TITLE
Movie Extract Particles Failing (XMIPP_ERROR 47)

### ISSUE THREAD

**Issue by joshuamhardy** [I2PC/scipion#1119]
I am trying to use the movie extract particles protocol but it keeps crashing. I have tried with two datasets and I get the same error. I am using manually-picked coordinates and motion corrected movies as input.

I am using the binary version of scipion v1.1.

00001:   RUNNING PROTOCOL -----------------
00002:             PID: 25020
00003:         Scipion: v1.1 (2017-06-14) Balbino
00004:      currentDir: /media/data2/20170626_test
00005:      workingDir: Runs/002715_XmippProtExtractMovieParticles
00006:         runMode: Restart
00007:             MPI: 1
00008:         threads: 1
00009:    Starting at step: 1
00010:    Running steps 
00011:   STARTED: processMovieStep, step 1
00012:     2017-07-14 16:01:21.496499
00013:   Processing movie: Runs/002715_XmippProtExtractMovieParticles/tmp/movie_000001/0000.mrc
00014:   Index:  0 [0.0, 8.92, 7.76, 4.08, 0.64, -1.6, -5.28, -7.7, -8.96, -9.94, -11.84, -12.56, -13.42, -12.94, -13.1, -13.86, -14.84, -15.32, -15.52, -15.5, -15.74, -15.66, -15.78, -15.82, -16.64] [0.0, -4.7, -4.42, -3.9, -2.02, -1.26, -0.62, -0.36, -0.5, 0.28, 0.96, 0.96, 0.68, 0.96, 1.52, 1.94, 3.16, 3.24, 3.9, 3.62, 4.2, 4.26, 4.86, 5.48, 6.08]
00015:   Writing coordinates metadata: Runs/002715_XmippProtExtractMovieParticles/tmp/movie_000001/frame_01_coordinates.xmd, with shifts: 0.0 0.0
00016:   Writing frame: Runs/002715_XmippProtExtractMovieParticles/tmp/movie_000001/frame_01.mrc
00017:   Passing Ih:  1 Runs/002715_XmippProtExtractMovieParticles/tmp/movie_000001/0000.mrc:mrcs Runs/002715_XmippProtExtractMovieParticles/tmp/movie_000001/frame_01.mrc
00018:   Removing Dust
00019:   xmipp_transform_filter  -i Runs/002715_XmippProtExtractMovieParticles/tmp/movie_000001/frame_01.mrc -o Runs/002715_XmippProtExtractMovieParticles/tmp/movie_000001/frame_01.mrc --bad_pixels outliers 3.500000
00020:   Input File: Runs/002715_XmippProtExtractMovieParticles/tmp/movie_000001/frame_01.mrc
00021:   Output File: Runs/002715_XmippProtExtractMovieParticles/tmp/movie_000001/frame_01.mrc
00027:     19/  19 sec. ............................................................
00028:   Extracting particles
00029:   xmipp_micrograph_scissor -i Runs/002715_XmippProtExtractMovieParticles/tmp/movie_000001/frame_01.mrc --pos Runs/002715_XmippProtExtractMovieParticles/tmp/movie_000001/frame_01_coordinates.xmd -o Runs/002715_XmippProtExtractMovieParticles/tmp/movie_000001/frame_01_images --Xdim 800 --invert --downsampling 0.500000 
00030:   XMIPP_ERROR 47:  Incorrect MultidimArray dimensions.
00031:   Micrograph::open_micrograph: Only files with a single micrograph may be processed. Error reading Runs/002715_XmippProtExtractMovieParticles/tmp/movie_000001/frame_01.mrc
00032:   File: software/em/xmipp/libraries/data/micrograph.cpp line: 95
00033:   Traceback (most recent call last):
00034:     File "/usr/local/scipion/pyworkflow/protocol/protocol.py", line 182, in run
00035:       self._run()
00036:     File "/usr/local/scipion/pyworkflow/protocol/protocol.py", line 228, in _run
00037:       resultFiles = self._runFunc()
00038:     File "/usr/local/scipion/pyworkflow/protocol/protocol.py", line 224, in _runFunc
00039:       return self._func(*self._args)
00040:     File "/usr/local/scipion/pyworkflow/em/protocol/protocol_movies.py", line 267, in processMovieStep
00041:       self._processMovie(movie)
00042:     File "/usr/local/scipion/pyworkflow/em/packages/xmipp3/protocol_extract_particles_movies.py", line 243, in _processMovie
00043:       self.runJob('xmipp_micrograph_scissor', args)
00044:     File "/usr/local/scipion/pyworkflow/protocol/protocol.py", line 1077, in runJob
00045:       self._stepsExecutor.runJob(self._log, program, arguments, **kwargs)
00046:     File "/usr/local/scipion/pyworkflow/protocol/executor.py", line 56, in runJob
00047:       env=env, cwd=cwd)
00048:     File "/usr/local/scipion/pyworkflow/utils/process.py", line 51, in runJob
00049:       return runCommand(command, env, cwd)
00050:     File "/usr/local/scipion/pyworkflow/utils/process.py", line 65, in runCommand
00051:       check_call(command, shell=True, stdout=sys.stdout, stderr=sys.stderr, env=env, cwd=cwd)
00052:     File "/usr/local/scipion/software/lib/python2.7/subprocess.py", line 540, in check_call
00053:       raise CalledProcessError(retcode, cmd)
00054:   CalledProcessError: Command 'xmipp_micrograph_scissor -i Runs/002715_XmippProtExtractMovieParticles/tmp/movie_000001/frame_01.mrc --pos Runs/002715_XmippProtExtractMovieParticles/tmp/movie_000001/frame_01_coordinates.xmd -o Runs/002715_XmippProtExtractMovieParticles/tmp/movie_000001/frame_01_images --Xdim 800 --invert --downsampling 0.500000 ' returned non-zero exit status 47
00055:   Protocol failed: Command 'xmipp_micrograph_scissor -i Runs/002715_XmippProtExtractMovieParticles/tmp/movie_000001/frame_01.mrc --pos Runs/002715_XmippProtExtractMovieParticles/tmp/movie_000001/frame_01_coordinates.xmd -o Runs/002715_XmippProtExtractMovieParticles/tmp/movie_000001/frame_01_images --Xdim 800 --invert --downsampling 0.500000 ' returned non-zero exit status 47
00056:   FAILED: processMovieStep, step 1
00057:     2017-07-14 16:02:17.640064
00058:   ------------------- PROTOCOL FAILED (DONE 1/1886)

**Comment by azazellochg** [comment]
@joshuamhardy Thanks for reporting this!
I had the same error yesterday, but was able to reproduce it only once. Somehow ImageHandler converts the whole movie into Runs/002715_XmippProtExtractMovieParticles/tmp/movie_000001/frame_01.mrc instead of a single frame.

**Comment by pconesa** [comment]
Thank you both! I believe that this is fixed at https://github.com/I2PC/scipion/commit/4245d227d238adb771ce0da5f556f5ffad830999

@delarosatrevin , could you confirm this is the same issue?.

If so, branch release-1.1.1 has it.

**Comment by delarosatrevin** [comment]
It could be...but better to check with @josuegbl, who fixed that.

**Comment by azazellochg** [comment]
yes, I can confirm this is the fix ;)

**Comment by delarosatrevin** [comment]
Great! Thanks @azazellochg
