### ISSUE TITLE
relion2 movie refinement fails

### ISSUE THREAD

**Issue by azazellochg** [I2PC/scipion#1121]
1.1.1 branch:
Output movie_particles.sqlite from this protocol has empty _coordinate._micnName field, so then Relion "continue" with movie processing creates movie particles star file with "fake_movie" names. This leads to the fact that there is no way relion can tell the which movie the particles come from and crashes:
```
00060:    Reading in pre-expanded data model for movie frames... 
00061:   ERROR: 
00062:   MlModel::adjustGroupsForMovies ERROR: cannot find fake among the groups of the model!
```

**Comment by azazellochg** [comment]
Okay, finally I figured out the cause of the problem, which has nothing to do with micName :D 
Relion expects _rlnGroupName to be equal to micname or micname+smth. Looks like Scipion just puts groupname=groupId which is not what Relion expects when expanding the movies.

**Comment by azazellochg** [comment]
Did a few tests. 

relion 1.4, no grouping, movie ref works:
```
data_model_groups

loop_ 
_rlnGroupNumber #1 
_rlnGroupName #2 
_rlnGroupNrParticles #3 
_rlnGroupScaleCorrection #4 
           1          1           78     0.993351 
           2         10           67     0.963998 
```
relion 1.4, grouping, movie ref works:
```
data_model_groups

loop_ 
_rlnGroupNumber #1 
_rlnGroupName #2 
_rlnGroupNrParticles #3 
_rlnGroupScaleCorrection #4 
           1 ctfgroup_033645_00007          160     1.011369 
           2 ctfgroup_020509_00001          154     0.985586 
```
relion2, grouping or no grouping, movie ref fails:
```
00071:   ERROR: 
00072:   MlModel::adjustGroupsForMovies ERROR: cannot find fake among the groups of the model!
00073:   File: /net/nfs1/public/EM/RELION/relion-2.1/src/ml_model.cpp line: 785
```

**Comment by JuhaHuiskonen** [comment]
Hi @azazellochg thanks for the fix, I encountered today the same issue.

**Comment by azazellochg** [comment]
Hi @JuhaHuiskonen, it's fixed only in my branch so far (az-relion2.1). Also I have made a lot of changes and have to check later everything in old relion versions. 
There is still something wrong with movie refinement in scipion since my single-frame reconstructions during subsequent polishing look like nonsense
