### ISSUE TITLE
add cuda 8.0 binaries for Gctf/Gautomatch distribution

### ISSUE THREAD

**Issue by azazellochg** [I2PC/scipion#1125]
* http://www.mrc-lmb.cam.ac.uk/kzhang/Gautomatch/Gautomatch_v0.53/bin/Gautomatch-v0.53_sm_20_cu8.0_x86_64
* http://www.mrc-lmb.cam.ac.uk/kzhang/Gctf/Gctf_v1.06/bin/Gctf-v1.06_sm_20_cu8.0_x86_64
* http://www.mrc-lmb.cam.ac.uk/kzhang/Gctf/Gctf_v1.06/bin/Gctf-v1.06_sm_30_cu8.0_x86_64

**Comment by pconesa** [comment]
I've added Gautomatch one. The Gctf ones were already there, at least with the same name. Any reason to think are different?

**Comment by azazellochg** [comment]
@pconesa you are right, we already have them. Closed.
