### ISSUE TITLE
Relion groups are lost after subset selection

### ISSUE THREAD

**Issue by azazellochg** [I2PC/scipion#1126]
1) run e.g. relion 3d cls protocol with grouping by CTF:
```
loop_ 
_rlnGroupNumber #1 
_rlnGroupName #2 
_rlnGroupNrParticles #3 
_rlnGroupScaleCorrection #4 
           1 ctfgroup_033645_00007          534     1.016635 
           2 ctfgroup_020509_00001          485     0.986764 
```

2) select a subset from the output of (1)
3) run e.g. 3D refine relion protocol with (2) as input, no grouping.

Result: the input star files from (3) do not have any more _rlnGroupName column. Output file have the groups defined from scratch by Relion:

```
loop_ 
_rlnGroupNumber #1 
_rlnGroupName #2 
_rlnGroupNrParticles #3 
_rlnGroupScaleCorrection #4 
           1          1           55     1.000000 
           2         10           61     1.000000 
```

I am afraid that the other way around (first refine, then classify output) even without subset selection the groups will also be lost during convertInputStep

**Comment by josuegbl** [comment]
@azazellochg, from my point of view, this is not an error. When you run a relion protocol grouping by CTF, scipion add  _rlnGroupName column to the .star in convertInputStep. OF course, this information is not propagated to following sets of particles because the outputParticles are the same input set plus the transformation matrix (alignment). If you want to use again the grouping, in other Relion process, you need to set again the flag doCtfManualGroups to True. I think that in some cases the user does not want to use the groupName again after a process using it, and this is not possible if you propagate the info.

**Comment by azazellochg** [comment]
@josuegbl I am worried, so none of relion-produced metadata is saved  (when i.e. I run 3d refine and then classification) except the transformation matrix? 
As for grouping, I would disagree. Grouping itself is required for proper norm.correction & intensity scale estimation. If you have few particles per micrograph, you can group by either CTF or intensity scale factor (last one is btw not implemented in scipion). If user has grouped the particles, why would he remove groupname column later (when running everything in relion, not scipion)? He would have again the warning about small group size.
In general, we have to implement int.scale grouping as well, since CTF groups might be good at the beginning but scale grouping is a better parameter (after 2d/3d processing).

**Comment by delarosatrevin** [comment]
@azazellochg I think the general convention is that only the information in the Scipion standard (in this case Particle) is converted from temporary files (e.g star files) is converted. But of course, our model is flexible and contemplate that package protocols could add additional info to objects (not only Particles). So I guess the point here would be to discuss the implications of adding the groupName as a Relion-specific parameter to particles that could be propagated, it make sense for me your point. By the way, the convention for these cases is to star with _rln for Relion-specific values...as _xmipp for Xmipp-specific ones. 

The other point is to implement the other way of making the groups. Regarding the @josuegbl argument, we could allow to use existing groups (if present in the inputParticles) or generate them again (as it is now if the user select that option).

**Comment by azazellochg** [comment]
@delarosatrevin I see. At the moment I have added (in az-relion2.1 branch) the following: if groupname is defined, it is propagated, if not the groupname is set to micid (which relion will do anyway by default). In case user has grouped particles by CTF, this will be saved/propagated.

**Comment by josuegbl** [comment]
@azazellochg, You are right. I cannot imagine any case where the user would remove the groupName, although he could want re-group his particles after a subset selection. Regarding your question, none of  relion-produced metadata is saved, but only in the case of the particles. Maybe we should save it.
