### ISSUE TITLE
control error message for blacklisted machines

### ISSUE THREAD

**Issue by pconesa** [I2PC/scipion#1130]
notifier is failing on blacklisted machines...server is returning 500 error.
Either change the server to not return 500 error, or control exception in the notifier, and maybe warn that machine is blacklisted.

**Comment by pconesa** [comment]
it hapens that josu's machine was duplicated in the blacklist table. In any case, error massage should not appear in the console in case of another 500 error hapens on the server.

**Comment by delarosatrevin** [comment]
I think blacklisting @josuegbl  twice (or triple) is a good idea.

**Comment by pconesa** [comment]
;-), yes once error is catched, I'll blacklist @josuegbl 3 or 4 times!

**Comment by rmarabini** [comment]
This is fixed, the error has not in scipion code but in webservices code. File models.py has been modified so the same ip address can not be introduced twice in the blacklist table (see unique=True in client_ip atribute). I close the issue
