### ISSUE TITLE
plotting 2 values in cl2d fails

### ISSUE THREAD

**Issue by pconesa** [I2PC/scipion#1135]
when plotting the convergence of 2 series of cl2d it fails.
Plotting 2 series in other protocols seems to work fine.

**Comment by yaizar** [comment]
I've looked into this and it's a bit hard to debug - with cl2d  I'm unable to see prints I put inside  the function [plotFile](https://github.com/I2PC/scipion/blob/master/pyworkflow/em/plotter.py#L114). I can see them with the rest of the protocols, so I'm not sure how is cl2d making these plots...
