### ISSUE TITLE
time data error

### ISSUE THREAD

**Issue by JuhaHuiskonen** [I2PC/scipion#1138]
Hi @delarosatrevin 

I updated a couple of days ago to Scipion branch release-1.1.1

I opened an old project with this new release. Importing another set of movies worked. However protocol 'xmipp - extract coordinates' failed with this error:

'2017-07-21 13:49:35' does not match format '%Y-%m-%d %H:%M:%S.%f'

I closed Scipion and tried opening the same project from the older version (1.1). That gives now the same error - and even worse, I can't open in the new version either (same error). So basically I am stuck now and cannot continue with my project...

**Comment by delarosatrevin** [comment]
Hi @JuhaHuiskonen, 

Do you have more info about where in the code this error is raised? I will look at it and try to fixed as soon as possible for you to continue working. Sorry for that. 

@pconesa Do you have an idea about this %f femtoseconds change?

**Comment by pconesa** [comment]
@JuhaHuiskonen I think we might have identified the problem...do you get something else in the log or console?

**Comment by pconesa** [comment]
hi @JuhaHuiskonen , could you try now, pulling changes from release-1.1.1  branch? and feedback please?

**Comment by JuhaHuiskonen** [comment]
hi @pconesa 
I did a fresh pull in that branch and now I can open the project. Thanks for fixing it so quickly!

**Comment by pconesa** [comment]
Great! It's our responsability not to stop you from working. Actually, @delarosatrevin did the hot fix.
Thanks @delarosatrevin
