### ISSUE TITLE
relion viewer: particle angular assignment

### ISSUE THREAD

**Issue by azazellochg** [I2PC/scipion#1146]
opens a data star file with particles.. what is the purpose of this? 
PS. this is for auto-refine jobs

**Comment by delarosatrevin** [comment]
The purpose of this option is just to display the particles with the angular information per iteration...the *data.star file. I think it can be useful to check how the refinement (in this case) is going without converting to Scipion format yet.

**Comment by azazellochg** [comment]
Ah, all right then..
