### ISSUE TITLE
xmipp3 - extract movie particles fails if background radius default (-1) is set

### ISSUE THREAD

**Issue by JuhaHuiskonen** [I2PC/scipion#1154]
If I don't change the default value -1 under advanced options I get the following error:

in _runNormalize
    bgRadius = int(size/2)
TypeError: unsupported operand type(s) for /: 'NoneType' and 'int'
Protocol failed: unsupported operand type(s) for /: 'NoneType' and 'int'
FAILED: processMovieStep, step 1
  2017-07-25

**Comment by josuegbl** [comment]
@JuhaHuiskonen , im working on

**Comment by delarosatrevin** [comment]
Great @josuegbl ...check what @azazellochg has done in his branch for Relion 2.1

**Comment by azazellochg** [comment]
I remember this and haven't fixed it, so go ahead :)
