### ISSUE TITLE
xmipp picker issue

### ISSUE THREAD

**Issue by azazellochg** [I2PC/scipion#1164]
1.1.1 branch
Xmipp supervised picker seems not to take into account that I changed the threshold after training run. It 
 saves all autopicked particles (435) instead of 316+27
![screenshot_20170804_190229](https://user-images.githubusercontent.com/6952870/28981018-ce87b216-7947-11e7-8a73-1618c91b46ce.png)

**Comment by delarosatrevin** [comment]
@pconesa This seems like an important issue in Xmipp picker...who is now in charge of Java-base interfaces? Could someone take a look at this?

**Comment by pconesa** [comment]
I'm having a look....@azazellochg, it is even worse....different thresholds per micrographs are not handled correctly, it is stored but the "Automatic" count does uses per micrograph threshold.

**Comment by azazellochg** [comment]
@pconesa well, that's good that I dug this out :)

**Comment by pconesa** [comment]
@azazellochg ....if you have some time,....could you please test and feedback. Be aware that the threshold was mainly something visual. Now it has some use for the training and for filtering particles. @delarosatrevin is it ok for you to review the PR -- #1222 ?. I think you are the only Java guy around. right?
