### ISSUE TITLE
motioncor2-1.0.0 shifts differences respect to 17.01.30

### ISSUE THREAD

**Issue by delarosatrevin** [I2PC/scipion#1168]
This is just a reminder about the differences to clarify what is happening.

**Comment by azazellochg** [comment]
@delarosatrevin AFAIK, new version reports "better" shifts.. :)
Shall we add in the test protocol to just check if the number of shifts = N of frames

**Comment by delarosatrevin** [comment]
OK, maybe some like this is the best we can do in the test. 
Maybe apart from N of shifts = N of frames we can test that 
there are non-zero values (that is the default for no shift) in 
some of them. What do you think? With this we can close this issue.

**Comment by ldelcano** [comment]
Hi! test test_protocols_motioncor2.py is failing on this assert:
self.assertNotEqual(zeroShifts, shifts, msgShifts)
which was introduced on this issue. Do you have any idea why this could be happening?
It fails on buildbot with MOTIONCOR2_HOME = %(EM_ROOT)s/motioncor2-1.0.0
thanks
Laura

**Comment by azazellochg** [comment]
Hi, @ldelcano, that's strange. The test works for me in release-1.1.1 branch..

**Comment by ldelcano** [comment]
Hi @azazellochg. It seems the failure is because cuda 8 is not installed. There was a hidden error although protocol finished ok.
