### ISSUE TITLE
Error in relion -3D auto-refine

### ISSUE THREAD

**Issue by 1aviervargas** [I2PC/scipion#1173]
After 3D classification if I try to refine particles with alignment using auto-refine protocol with flag 'Consider previous alignment?' to Yes I get the following error at devel-fixes branch:

00011:   STARTED: convertInputStep, step 1
00012:     2017-08-11 13:55:14.025697
00013:   Converting set from 'Runs/002723_ProtUserSubSet/particles.sqlite' into 'Runs/003269_ProtRelionRefine3D/input_particles.star'
00014:   Traceback (most recent call last):
00015:     File "/home/jvargas/Linux/Proyectos/scipion/pyworkflow/protocol/protocol.py", line 182, in run
00016:       self._run()
00017:     File "/home/jvargas/Linux/Proyectos/scipion/pyworkflow/protocol/protocol.py", line 228, in _run
00018:       resultFiles = self._runFunc()
00019:     File "/home/jvargas/Linux/Proyectos/scipion/pyworkflow/protocol/protocol.py", line 224, in _runFunc
00020:       return self._func(*self._args)
00021:     File "/home/jvargas/Linux/Proyectos/scipion/pyworkflow/em/packages/relion/protocol_base.py", line 741, in convertInputStep
00022:       alignType=alignType)
00023:     File "/home/jvargas/Linux/Proyectos/scipion/pyworkflow/em/packages/relion/convert.py", line 564, in writeSetOfParticles
00024:       setOfImagesToMd(imgSet, partMd, particleToRow, **kwargs)
00025:     File "/home/jvargas/Linux/Proyectos/scipion/pyworkflow/em/packages/relion/convert.py", line 549, in setOfImagesToMd
00026:       imgToFunc(img, imgRow, **kwargs)
00027:     File "/home/jvargas/Linux/Proyectos/scipion/pyworkflow/em/packages/relion/convert.py", line 455, in particleToRow
00028:       imageToRow(part, partRow, md.RLN_IMAGE_NAME, **kwargs)
00029:     File "/home/jvargas/Linux/Proyectos/scipion/pyworkflow/em/packages/relion/convert.py", line 426, in imageToRow
00030:       alignmentToRow(img.getTransform(), imgRow, alignType)
00031:     File "/home/jvargas/Linux/Proyectos/scipion/pyworkflow/em/packages/relion/convert.py", line 332, in alignmentToRow
00032:       raise Exception("3D alignment conversion for Relion not implemented. "
00033:   Exception: 3D alignment conversion for Relion not implemented. It seems the particles were generated with an incorrect alignment type. You may either re-launch the protocol that generates the paticles with angles or set 'Consider previous alignment?' to No
00034:   Protocol failed: 3D alignment conversion for Relion not implemented. It seems the particles were generated with an incorrect alignment type. You may either re-launch the protocol that generates the paticles with angles or set 'Consider previous alignment?' to No
00035:   FAILED: convertInputStep, step 1
00036:     2017-08-11 13:55:14.124408
00037:   ------------------- PROTOCOL FAILED (DONE 1/3)

**Comment by azazellochg** [comment]
In release-1.1.1 I do not have this error. I did 3d classification, saved a subset and ran 3d refine considering previous alignment.

**Comment by 1aviervargas** [comment]
Thanks, I will check it also in release-1.1.1

**Comment by 1aviervargas** [comment]
I checked also with release-1.1.1 and it fails but seems that is a problem related with the particles (the project is old) maybe from may. If I do the same using the particles after auto-refine there is no problem.
