### ISSUE TITLE
Error compiling devel branch with CUDA = True and OpenCV=True because weird program 'xmipp_gpu_example'

### ISSUE THREAD

**Issue by 1aviervargas** [I2PC/scipion#1174]
In devel-fixes branch compiling with CUDA = True appears the following error shown below. 
@pconesa  Should a program called "xmipp_gpu_example" be in the remote devel branch?

**o software/em/xmipp/applications/programs/gpu_example/gpu_example.o -c -O3 -Isoftware/em/xmipp/external -Isoftware/em/xmipp/libraries -Isoftware/em/xmipp/None -Isoftware/em/xmipp/libraries -Isoftware/include -Isoftware/include/python2.7 software/em/xmipp/applications/programs/gpu_example/gpu_example.cpp
sh: o: command not found**

g++ -o software/em/xmipp/bin/xmipp_gpu_example software/em/xmipp/applications/programs/gpu_example/gpu_example.o -Lsoftware/em/xmipp/lib -Lsoftware/lib -Lsoftware/em/xmipp/None -Lsoftware/lib -L/scinet/gpc/mpi/openmpi/1.10.3-gcc-v4.8.1/lib -Lsoftware/em/xmipp/True -L/scinet/gpc/compilers/gcc-6.2.0/lib64 -L/scinet/gpc/src/scipion/scipion-release-1.1/software/lib -L/scinet/gpc/mpi/openmpi/1.10.3-gcc-v4.8.1/lib -L/scinet/gpc/mpi/openmpi/1.10.3-gcc-v4.8.1/lib/openmpi -L/scinet/gpc/Libraries/MXM_2.1/lib -L/scinet/arc/cuda-7.5/lib64 -lXmippAlglib -lXmippBilib -lXmippCondor -lXmippDelaunay -lXmippData -lXmippRecons -lXmippClassif -lsqlite3 -lfftw3 -lfftw3_threads -ltiff -ljpeg -lpng -lhdf5 -lhdf5_cpp -lcudart -lcublas -lcufft -lcurand -lcusparse -lnvToolsExt
g++: error: software/em/xmipp/applications/programs/gpu_example/gpu_example.o: No such file or directory
scons: *** [software/em/xmipp/bin/xmipp_gpu_example] Error 1
scons: building terminated because of errors.

**Comment by pconesa** [comment]
Hi @1aviervargas , I guess this is devel branch....maybe @rmarabini or @cossorzano know more about this gpu_example.cpp program.

**Comment by rmarabini** [comment]
Hi @1aviervargas ,

My guess is: in order to compile xmipp_gpu example you need a GPU compiler. The location of the compiler is defined by the environment variables

NVCC = nvcc --x cu -D_FORCE_INLINES
NVCC_INCLUDE = /usr/local/cuda/include
NVCC_LIBDIR = CUDA_LIB


These variables were not available at scipion 1.1. 

Solution: delete file config/scipion.conf and recreate it
   scipion install 

@1aviervargas please confirm if this is your problem

**Comment by pconesa** [comment]
@1aviervargas , After our conversation...I guess this is not solved right?

**Comment by rmarabini** [comment]
Just delete xmipp_gpu_example, It does not sense to keep it any longer.

    Roberto

**Comment by 1aviervargas** [comment]
Thanks Pablo,

The last time I installed Scipion I had the problem.

Best
Javier
