### ISSUE TITLE
IgnoreDuplicates not used?

### ISSUE THREAD

**Issue by cossorzano** [I2PC/scipion#1185]
In pyworkflow/em/protocol/protocol_sets.py, ProtUnionSet there is a form field called ignoreDuplicates, but it seems not to be used in the implementation

**Comment by pconesa** [comment]
This is old, but need to check the status.

**Comment by pconesa** [comment]
I'm closing this issue. Feel free to reopen it if I'm wrong or missed something. It's working in devel.
