### ISSUE TITLE
Protocol className 'XmippProtOFAlignment' not found!!!. 

### ISSUE THREAD

**Issue by kylelmorris** [I2PC/scipion#1204]
Does anybody know what this error means, reported to the terminal when trying to open previous projects?

Protocol className 'XmippProtOFAlignment' not found!!!. 
Fix your config/scipion.conf configuration.

The error is not consistently reported with some projects opening but others not.

Thanks for your help!

**Comment by azazellochg** [comment]
@kylelmorris thanks for reporting this. @delarosatrevin I was wondering whether this could be the case for old projects created in scipion 1.0 where we had one single movie protocol? I know there is a hack ProtMovieAlignment = XmippProtOFAlignment but was it tested?

**Comment by kylelmorris** [comment]
Thanks @azazellochg. Perhaps it’s this but it would be strange then there is not a correlation between project creation date, thus version, and this error. My oldest projects open fine. It’s a few RCT projects that fail to open. 

Where does the hack get used and I’ll try it?

**Comment by pconesa** [comment]
Could this be the other way around? Opening  a new project with
XmippOFAlignment (appeared in v1.1) with v1.0?...wild Saturday night
guess...but sober, I promise.

**Comment by delarosatrevin** [comment]
Yes, I would think is what Pablo suggested, that you are trying to open a
new project with an old Scipion version. Kyle, could you confirm which
Scipion version are you using? In the protocols output log file the version
should also be printed. Moreover, we also added a "LegacyProtocol" class in
Scipion v1.1 but for backward compatibility...i.e that you could open
projects with protocols that could be deprecated.
