### ISSUE TITLE
facilities-devel: render images by default in motioncorr/ctffind viewer

### ISSUE THREAD

**Issue by rmarabini** [I2PC/scipion#1212]
visualization of motioncorr and CTFFind4. I do not see movies/micrographs by default (need to play with render option). This was not the previous behavior. I like to see the images by default.

**Comment by delarosatrevin** [comment]
Hi @rmarabini, some answers about that. 

Currently, only the motioncor2 (or even motioncorr) can generate the micrograph thumbnail (using Eman2 command underneath). This option is not checked by default (I thought that we will have the release 1.1.1 sooner and didn't want to change the default behaviour), I have it in our wizard in Stockholm. Of course, this thumbnail generation could (should?) be extended to other movie alignment such as unblur, crosscorrelation, OF, etc (maybe goes into the base class, maybe not so easy). After this, the thumbnail should be visible when showing results both for SetOfMicrographs and SetOfCtf.

**Comment by rmarabini** [comment]
Not sure we are speaking about the same problem. I use to be able to see the movie/micrograoh in motioncor AND ctffind and now I cannot see it. I will bug Pablo with a face to face presentation

**Comment by azazellochg** [comment]
Gctf and Ctffind4 produce a psdfile rendered by default. Motioncor2 does not produce thumbnails unless you tick this option in the protocol. Default is false because we cant force users to have eman2 installed so this protocol works.
