### ISSUE TITLE
facilities-devel: Export html report to web-server doesn't work

### ISSUE THREAD

**Issue by rmarabini** [I2PC/scipion#1214]
exporting  html reportto a external web server  does not seem to work

**Comment by yaizar** [comment]
Hi @rmarabini, which command are you using to export it? can you confirm your command works in your terminal? I've tried rsyncing my report and it worked OK

**Comment by yaizar** [comment]
Spoke to @rmarabini and it seems this issue doesn't belong to facilities branch, closing it.
