### ISSUE TITLE
facilities-devel: improve gain protocol speed and viewer

### ISSUE THREAD

**Issue by rmarabini** [I2PC/scipion#1215]
Gain protocol:

Suggestions:

1) Now gain protocol process all available movies. In a single CPU gain needs 100 minutes to process a movie (motioncor process 100 movies in this time) so it makes sense to process 1 of each 100 movies or even better the last movie available. Should we put default step to 100 instead of 1?

2) If gain is "viewed" though "monitor summary" you get a plot. If gain is "viewed" directly you get a gallery of images. Could we see the plot also in the gain viewer, it is a faster way to see the information when you have many movies

**Comment by majtner** [comment]
@rmarabini Thank you for suggestions.

Ad 1: We will look at default values and yes, we can certainly change it

Ad 2: Here I want to point out that there is also a "movie gain monitor", which is producing this required plot. If we add the plot to "movie gain" protocol, this "movie gain monitor" protocol would be redundant (the same holds true for CTF monitor, therefore it is probably more general question, how we want to design it)

**Comment by azazellochg** [comment]
I guess this is done.
