### ISSUE TITLE
A few comment about release-facilities-level (20-september) -VI

### ISSUE THREAD

**Issue by rmarabini** [I2PC/scipion#1218]
protocol ctf selection. 
option use xmipp crtireria 
criteria "CritCorr" should be general (fitQuality) and not restricted to xmipp.

I assign this to myself

**Comment by delarosatrevin** [comment]
Muself, another member of the crew?

**Comment by rmarabini** [comment]
you are a mean one  ;-)

**Comment by delarosatrevin** [comment]
There is a well-know saying: "If you drink, don't git."

**Comment by pconesa** [comment]
What is the status of this?
