### ISSUE TITLE
Some conversions from CTF are failing, after changes in #1201

### ISSUE THREAD

**Issue by delarosatrevin** [I2PC/scipion#1219]
Some of the following test are failing:

./scipion test tests.em.protocols.test_protocols_xmipp_mics.TestXmippExtractParticles
./scipion test --grep ctf --skip program stream monitor --run

**Comment by josuegbl** [comment]
It seems these tests not fails in release-1.1.facilities-stream-picking branch.

**Comment by dmaluenda** [comment]
It seems that are fixed.

I have check it in facilities-devel (in Nolan) and in Buildbot (see http://heisenberg.cnb.csic.es:9980/#/builders all green in Protocols_tests and the 7th in Workflows_tests)
