### ISSUE TITLE
Micrograph contrast inversion+downsampling

### ISSUE THREAD

**Issue by cossorzano** [I2PC/scipion#1220]
It annotates the SetOfMicrographs with the incorrect size

**Comment by pconesa** [comment]
ummm, behaves correctly here....
[Uploading Screenshot from 2017-10-03 08-39-59.png...]

**Comment by pconesa** [comment]
Was it in streaming?

**Comment by pconesa** [comment]
Tomas, kindly agreed to have a look at it, since it seems to be something in devel, maybe related with latest "streamification" of the protocol.

**Comment by majtner** [comment]
I have tested it in streaming and also without streaming in devel and in both cases I see correct size:
1024x1024, 4.00 Å/px  ->  512x512, 8.00 Å/px
Could you, please, specify the problem a bit more?
