### ISSUE TITLE
Exception when boxes of a project are colored by time

### ISSUE THREAD

**Issue by delarosatrevin** [I2PC/scipion#1235]
>>>>> python  /nethome/josem/scipion/pyworkflow/apps/pw_manager.py 
Can't calculate box color:must be string, not None
Can't calculate box color:must be string, not None
Can't calculate box color:must be string, not None
Can't calculate box color:must be string, not None

**Comment by pconesa** [comment]
thanks @delarosatrevin , Is there a exception......or just ugly, log lines.

**Comment by delarosatrevin** [comment]
Not sure.

**Comment by pconesa** [comment]
I mean, you've titled this issue with "Exception".......is there an exception?

**Comment by delarosatrevin** [comment]
Yes...maybe a more appropriate title would be: Error message when...

**Comment by pconesa** [comment]
@delarosatrevin could you just send me the project.sqlite?
