### ISSUE TITLE
Motioncor2 shifts plot (wish list made by B13 people-IV)

### ISSUE THREAD

**Issue by rmarabini** [I2PC/scipion#1239]
What is the meaning of the motioncor2 shift plots (since it can not be shifts). I will (@rmarabini) look into it.

**Comment by delarosatrevin** [comment]
@azazellochg, can you comment on this? My understanding is that the plot are the average shift in a frame in x and y...

**Comment by azazellochg** [comment]
@delarosatrevin yes, you are right. Those are cumulative per-frames shifts in pixels, first frame shift is always set to 0,0

**Comment by rmarabini** [comment]
Hi @delarosatrevin  and @azazellochg,

 I have plots in which the difference between last and first frames is 600 pixels. If you look to the original movie versus the corrected one you can see a small improvement but there is no way the difference between first and last image is 600 px. Furthermore, if you open the log files the shifts are around 1 pixel beetwen frames. There is something fishy here

**Comment by azazellochg** [comment]
Hi @rmarabini, could you attach the log file here? I can have a look

**Comment by rmarabini** [comment]
@azazellochg <https://github.com/azazellochg>, give me a few days to
analyze the problem properly and I will send you the log files and the
plots.

  roberto

**Comment by delarosatrevin** [comment]
@rmarabini , any news on this? There is a user that gave some feedback about the plots to @cossorzano , @pconesa and @josuegbl. It would be good to take a look into this.

**Comment by rmarabini** [comment]
Hi @delarosatrevin,

I am working on it.

   Roberto

**Comment by azazellochg** [comment]
I guess this is solved now.
