### ISSUE TITLE
Error on test:  scipion tests em.workflows.test_workflow_xmipp

### ISSUE THREAD

**Issue by stetner** [I2PC/scipion#1247]
Hi,

I have an error on the above test.  Maybe a needed package missing?

Output (test_output.txt) and logs attached.

~/ScipionUserData/projects/TestXmippWorkflow/Runs/000269_XmippProtExtractParticles/logs/run.stdout
~/ScipionUserData/projects/TestXmippWorkflow/Runs/000269_XmippProtExtractParticles/logs/run.log

I am not sure exactly why it is failing though (I am a sysadmin not a researcher).

I am also not sure what packages are needed for all the tests to run.  Currently have:
$ scipion install --help

Scipion v1.1 (2017-06-14) Balbino

Usage: /opt/Modules/scipion/1.1/scipion install [<target>] [--no-scipy] [--no-opencv] [--show]

Installs Scipion. Also used to install only part of it, as specified
in the <target>, or to add extra em packages to Scipion.

Arguments:
  <target>      a library, a python module, an em package or a xmipp file.
                Version can be specified after a hyphen (-)
   -j N         where N is the number of processors to use during installation
  --help        show this help message
  --show        just show what would be done, without actually installing
  --no-opencv   do not install opencv (big) or anything that depends on it
  --no-scipy    do not install scipy or anything that depends on it
  --no-xmipp    use this option only after a successful compilation of Xmipp
                to save some time when installing other packages

Example: scipion install eman-2.12

Available packages: ([ ] not installed, [X] seems already installed)
     Gautomatch      0.53 [ ]
           Gctf      0.50 [ ]     1.06 [ ]
          bsoft     1.8.8 [ ]    1.9.0 [ ]
        chimera    1.10.1 [ ]
         cryoem       1.0 [ ]
        ctffind       3.6 [ ]
       ctffind4    4.0.15 [ ]    4.1.5 [ ]    4.1.8 [ ]
      dogpicker     0.2.1 [ ]
           eman      2.11 [X]     2.12 [X]
          ethan       1.2 [ ]
       frealign      9.07 [ ]
      gEMpicker       1.1 [ ]
       localrec     1.1.0 [ ]    1.2.0 [ ]
 mag_distortion     1.0.1 [ ]
     motioncor2  16.03.16 [ ] 16.10.19 [ ] 17.01.30 [ ]
     motioncorr       2.1 [ ]
            nma           [ ]
         relion       1.3 [ ]      1.4 [ ]     1.4f [ ]      2.0 [ ]
         resmap   1.1.5s2 [ ]
         simple       2.1 [ ]
         spider     21.13 [X]
       summovie     1.0.2 [ ]
         unblur    1.0.15 [ ]    1.0.2 [ ]

**Comment by pconesa** [comment]
Hi, @stetner , did you forget to attach the files? Those you mention seems to be useful. And the output of the console might tell us something too.

for the scipion tests em.workflows.test_workflow_xmipp it's a pure Xmipp/Scipion workflow. No other em package should be needed. I know there are some dependencies for python libraries for some xmipp protocols, not sure if this is the case. But the logs and console output should be clear about this.

**Comment by stetner** [comment]
Yes I did.  here they are - sorry about that.
[run.log](https://github.com/I2PC/scipion/files/1370920/run.log)
[test_output.txt](https://github.com/I2PC/scipion/files/1370921/test_output.txt)
[run.stdout.txt](https://github.com/I2PC/scipion/files/1370924/run.stdout.txt)

**Comment by pconesa** [comment]
Thanks, @stetner . A first glance doesn't help much. It's failing at a third xmipp_downsample call.
Not sure what is the -7 exit code.

Could you please try this:

`cd ~/ScipionUserData/projects/TestXmippWorkflow`
`scipion xmipp_transform_downsample -i Runs/000002_ProtImportMicrographs/extra/BPV_1388.mrc -o Runs/000266_XmippProtExtractParticles/tmp/BPV_1388_downsampled_manual.xmp --step 8.000000 --method fourier`

And see if you get something more descriptive.

**Comment by stetner** [comment]
Sorry, I have been off sick. 

I did a rerun and it failed similarly.  The command itself seems to run fine.  It appears to me that the test may be running these commands simultaneously???  Could that be the trigger?

Doug 

Protocol failed: Command 'xmipp_transform_downsample -i Runs/000002_ProtImportMicrographs/extra/BPV_1388.mrc -o Runs/000269_XmippProtExtractParticles/tmp/BPV_1388_downsampled.xmp --step 8.000000 --method fourier' returned non-zero exit status -7

So :

$ cd ~/ScipionUserData/projects/TestXmippWorkflow
$ ls
Logs/  Runs/  Tmp/  Uploads/  project.sqlite  settings.sqlite
$ scipion xmipp_transform_downsample -i Runs/000002_ProtImportMicrographs/extra/BPV_1388.mrc -o Runs/000269_XmippProtExtractParticles/tmp/BPV_1388_downsampled.xmp --step 8.000000 --method fourier

Scipion v1.1 (2017-06-14) Balbino

>>>>> python  /opt/Modules/scipion/1.1/pyworkflow/apps/pw_program.py "xmipp_transform_downsample" "-i" "Runs/000002_ProtImportMicrographs/extra/BPV_1388.mrc" "-o" "Runs/000269_XmippProtExtractParticles/tmp/BPV_1388_downsampled.xmp" "--step" "8.000000" "--method" "fourier"
** Running command: xmipp_transform_downsample "-i" "Runs/000002_ProtImportMicrographs/extra/BPV_1388.mrc" "-o" "Runs/000269_XmippProtExtractParticles/tmp/BPV_1388_downsampled.xmp" "--step" "8.000000" "--method" "fourier"
Input File: Runs/000002_ProtImportMicrographs/extra/BPV_1388.mrc
Output File: Runs/000269_XmippProtExtractParticles/tmp/BPV_1388_downsampled.xmp

Looks like it ran fine.  re ran the test:

$ scipion tests em.workflows.test_workflow_xmipp

Scipion v1.1 (2017-06-14) Balbino

>>>>> python  scripts/run_tests.py em.workflows.test_workflow_xmipp
Running tests....
Creating project at:  /ram/tmp/ScipionUserData/projects/TestXmippWorkflow/project.sqlite
>>>> python /opt/Modules/scipion/1.1/scipion testdata --download xmipp_tutorial

Scipion v1.1 (2017-06-14) Balbino
...
...
Scipion v1.1 (2017-06-14) Balbino

>>>>> python  /opt/Modules/scipion/1.1/pyworkflow/apps/pw_protocol_run.py
"/home/d.stetner/ScipionUserData/projects/TestXmippWorkflow" "Runs/000269_XmippProtExtractParticles/logs/run.db" "269"
------------------- PROTOCOL FAILED (DONE 2/7)

>>> ERROR running protocol scipion - extract particles
    FAILED with error:

[   FAILED ] TestXmippWorkflow.testXmippWorkflow

Traceback (most recent call last):
  File "/opt/Modules/scipion/1.1/software/lib/python2.7/unittest/case.py", line 329, in run
    testMethod()
  File "/opt/Modules/scipion/1.1/pyworkflow/tests/em/workflows/test_workflow_xmipp.py", line 117, in testXmippWorkflow
    self.launchProtocol(protExtract)
  File "/opt/Modules/scipion/1.1/pyworkflow/tests/tests.py", line 102, in launchProtocol
    raise Exception("ERROR launching protocol.")
Exception: ERROR launching protocol.

[==========] run 1 tests (147.531 secs)
[  FAILED  ] 1 tests
[  PASSED  ] 0 tests

$ cd /home/d.stetner/ScipionUserData/projects/TestXmippWorkflow
$ cat Runs/000269_XmippProtExtractParticles/logs/run.stdout
RUNNING PROTOCOL -----------------
          PID: 134891
      Scipion: v1.1 (2017-06-14) Balbino
...
...
CalledProcessError: Command 'xmipp_transform_downsample -i Runs/000002_ProtImportMicrographs/extra/BPV_1388.mrc -o Runs/000269_XmippProtExtractParticles/tmp/BPV_1388_downsampled.xmp --step 8.000000 --method fourier' returned non-zero exit status -7
Protocol failed: Command 'xmipp_transform_downsample -i Runs/000002_ProtImportMicrographs/extra/BPV_1388.mrc -o Runs/000269_XmippProtExtractParticles/tmp/BPV_1388_downsampled.xmp --step 8.000000 --method fourier' returned non-zero exit status -7
FAILED: extractParticlesStep, step 4
  2017-10-13 10:16:55.210896
------------------- PROTOCOL FAILED (DONE 2/7)


$ scipion xmipp_transform_downsample -i Runs/000002_ProtImportMicrographs/extra/BPV_1388.mrc -o Runs/000269_XmippProtExtractParticles/tmp/BPV_1388_downsampled.xmp --step 8.000000 --method fourier

Scipion v1.1 (2017-06-14) Balbino

>>>>> python  /opt/Modules/scipion/1.1/pyworkflow/apps/pw_program.py "xmipp_transform_downsample" "-i" "Runs/000002_ProtImportMicrographs/extra/BPV_1388.mrc" "-o" "Runs/000269_XmippProtExtractParticles/tmp/BPV_1388_downsampled.xmp" "--step" "8.000000" "--method" "fourier"
** Running command: xmipp_transform_downsample "-i" "Runs/000002_ProtImportMicrographs/extra/BPV_1388.mrc" "-o" "Runs/000269_XmippProtExtractParticles/tmp/BPV_1388_downsampled.xmp" "--step" "8.000000" "--method" "fourier"
Input File: Runs/000002_ProtImportMicrographs/extra/BPV_1388.mrc
Output File: Runs/000269_XmippProtExtractParticles/tmp/BPV_1388_downsampled.xmp

$ scipion xmipp_transform_downsample -i Runs/000002_ProtImportMicrographs/extra/BPV_1386.mrc -o Runs/000269_XmippProtExtractParticles/tmp/BPV_1386_downsampled.xmp --step 8.000000 --method fourier

Scipion v1.1 (2017-06-14) Balbino

>>>>> python  /opt/Modules/scipion/1.1/pyworkflow/apps/pw_program.py "xmipp_transform_downsample" "-i" "Runs/000002_ProtImportMicrographs/extra/BPV_1386.mrc" "-o" "Runs/000269_XmippProtExtractParticles/tmp/BPV_1386_downsampled.xmp" "--step" "8.000000" "--method" "fourier"
** Running command: xmipp_transform_downsample "-i" "Runs/000002_ProtImportMicrographs/extra/BPV_1386.mrc" "-o" "Runs/000269_XmippProtExtractParticles/tmp/BPV_1386_downsampled.xmp" "--step" "8.000000" "--method" "fourier"
Input File: Runs/000002_ProtImportMicrographs/extra/BPV_1386.mrc
Output File: Runs/000269_XmippProtExtractParticles/tmp/BPV_1386_downsampled.xmp

$ scipion xmipp_transform_downsample -i Runs/000002_ProtImportMicrographs/extra/BPV_1387.mrc -o Runs/000269_XmippProtExtractParticles/tmp/BPV_1387_downsampled.xmp --step 8.000000 --method fourier

Scipion v1.1 (2017-06-14) Balbino

>>>>> python  /opt/Modules/scipion/1.1/pyworkflow/apps/pw_program.py "xmipp_transform_downsample" "-i" "Runs/000002_ProtImportMicrographs/extra/BPV_1387.mrc" "-o" "Runs/000269_XmippProtExtractParticles/tmp/BPV_1387_downsampled.xmp" "--step" "8.000000" "--method" "fourier"
** Running command: xmipp_transform_downsample "-i" "Runs/000002_ProtImportMicrographs/extra/BPV_1387.mrc" "-o" "Runs/000269_XmippProtExtractParticles/tmp/BPV_1387_downsampled.xmp" "--step" "8.000000" "--method" "fourier"
Input File: Runs/000002_ProtImportMicrographs/extra/BPV_1387.mrc
Output File: Runs/000269_XmippProtExtractParticles/tmp/BPV_1387_downsampled.xmp




[run.stdout.txt](https://github.com/I2PC/scipion/files/1381098/run.stdout.txt)
[run.log.txt](https://github.com/I2PC/scipion/files/1381099/run.log.txt)

**Comment by stetner** [comment]
OK, seems to be a simultanious run issue:

$ cat z
scipion xmipp_transform_downsample -i Runs/000002_ProtImportMicrographs/extra/BPV_1386.mrc -o Runs/000269_XmippProtExtractParticles/tmp/BPV_1386_downsampled.xmp --step 8.000000 --method fourier &
scipion xmipp_transform_downsample -i Runs/000002_ProtImportMicrographs/extra/BPV_1387.mrc -o Runs/000269_XmippProtExtractParticles/tmp/BPV_1387_downsampled.xmp --step 8.000000 --method fourier &
scipion xmipp_transform_downsample -i Runs/000002_ProtImportMicrographs/extra/BPV_1388.mrc -o Runs/000269_XmippProtExtractParticles/tmp/BPV_1388_downsampled.xmp --step 8.000000 --method fourier &
$ . ./z
$
Scipion v1.1 (2017-06-14) Balbino


Scipion v1.1 (2017-06-14) Balbino


Scipion v1.1 (2017-06-14) Balbino

>>>>> python  /opt/Modules/scipion/1.1/pyworkflow/apps/pw_program.py "xmipp_transform_downsample" "-i" "Runs/000002_ProtImportMicrographs/extra/BPV_1388.mrc" "-o" "Runs/000269_XmippProtExtractParticles/tmp/BPV_1388_downsampled.xmp" "--step" "8.000000" "--method" "fourier"
>>>>> python  /opt/Modules/scipion/1.1/pyworkflow/apps/pw_program.py "xmipp_transform_downsample" "-i" "Runs/000002_ProtImportMicrographs/extra/BPV_1386.mrc" "-o" "Runs/000269_XmippProtExtractParticles/tmp/BPV_1386_downsampled.xmp" "--step" "8.000000" "--method" "fourier"
>>>>> python  /opt/Modules/scipion/1.1/pyworkflow/apps/pw_program.py "xmipp_transform_downsample" "-i" "Runs/000002_ProtImportMicrographs/extra/BPV_1387.mrc" "-o" "Runs/000269_XmippProtExtractParticles/tmp/BPV_1387_downsampled.xmp" "--step" "8.000000" "--method" "fourier"
** Running command: xmipp_transform_downsample "-i" "Runs/000002_ProtImportMicrographs/extra/BPV_1386.mrc" "-o" "Runs/000269_XmippProtExtractParticles/tmp/BPV_1386_downsampled.xmp" "--step" "8.000000" "--method" "fourier"
** Running command: xmipp_transform_downsample "-i" "Runs/000002_ProtImportMicrographs/extra/BPV_1388.mrc" "-o" "Runs/000269_XmippProtExtractParticles/tmp/BPV_1388_downsampled.xmp" "--step" "8.000000" "--method" "fourier"
** Running command: xmipp_transform_downsample "-i" "Runs/000002_ProtImportMicrographs/extra/BPV_1387.mrc" "-o" "Runs/000269_XmippProtExtractParticles/tmp/BPV_1387_downsampled.xmp" "--step" "8.000000" "--method" "fourier"
Input File: Runs/000002_ProtImportMicrographs/extra/BPV_1386.mrc
Input File: Runs/000002_ProtImportMicrographs/extra/BPV_1388.mrc
Input File: Runs/000002_ProtImportMicrographs/extra/BPV_1387.mrc
Output File: Runs/000269_XmippProtExtractParticles/tmp/BPV_1386_downsampled.xmp
Output File: Runs/000269_XmippProtExtractParticles/tmp/BPV_1387_downsampled.xmp
Output File: Runs/000269_XmippProtExtractParticles/tmp/BPV_1388_downsampled.xmp
Traceback (most recent call last):
  File "/opt/Modules/scipion/1.1/pyworkflow/apps/pw_program.py", line 41, in <module>
    runProgram(program, params)
  File "/opt/Modules/scipion/1.1/pyworkflow/em/__init__.py", line 185, in runProgram
Traceback (most recent call last):
  File "/opt/Modules/scipion/1.1/pyworkflow/apps/pw_program.py", line 41, in <module>
    runProgram(program, params)
  File "/opt/Modules/scipion/1.1/pyworkflow/em/__init__.py", line 185, in runProgram
    pwutils.runJob(None, program, params, env=env)
      File "/opt/Modules/scipion/1.1/pyworkflow/utils/process.py", line 51, in runJob
pwutils.runJob(None, program, params, env=env)
  File "/opt/Modules/scipion/1.1/pyworkflow/utils/process.py", line 51, in runJob
        return runCommand(command, env, cwd)
return runCommand(command, env, cwd)
  File "/opt/Modules/scipion/1.1/pyworkflow/utils/process.py", line 65, in runCommand
  File "/opt/Modules/scipion/1.1/pyworkflow/utils/process.py", line 65, in runCommand
    check_call(command, shell=True, stdout=sys.stdout, stderr=sys.stderr, env=env, cwd=cwd)
  File "/opt/Modules/scipion/1.1/software/lib/python2.7/subprocess.py", line 540, in check_call
    check_call(command, shell=True, stdout=sys.stdout, stderr=sys.stderr, env=env, cwd=cwd)
  File "/opt/Modules/scipion/1.1/software/lib/python2.7/subprocess.py", line 540, in check_call
    raise CalledProcessError(retcode, cmd)
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command 'xmipp_transform_downsample "-i" "Runs/000002_ProtImportMicrographs/extra/BPV_1386.mrc" "-o" "Runs/000269_XmippProtExtractParticles/tmp/BPV_1386_downsampled.xmp" "--step" "8.000000" "--method" "fourier"' returned non-zero exit status -7
subprocess.CalledProcessError: Command 'xmipp_transform_downsample "-i" "Runs/000002_ProtImportMicrographs/extra/BPV_1387.mrc" "-o" "Runs/000269_XmippProtExtractParticles/tmp/BPV_1387_downsampled.xmp" "--step" "8.000000" "--method" "fourier"' returned non-zero exit status -7

[1]   Exit 1                  scipion xmipp_transform_downsample -i Runs/000002_ProtImportMicrographs/extra/BPV_1386.mrc -o Runs/000269_XmippProtExtractParticles/tmp/BPV_1386_downsampled.xmp --step 8.000000 --method fourier
[2]-  Exit 1                  scipion xmipp_transform_downsample -i Runs/000002_ProtImportMicrographs/extra/BPV_1387.mrc -o Runs/000269_XmippProtExtractParticles/tmp/BPV_1387_downsampled.xmp --step 8.000000 --method fourier
[3]+  Done                    scipion xmipp_transform_downsample -i Runs/000002_ProtImportMicrographs/extra/BPV_1388.mrc -o Runs/000269_XmippProtExtractParticles/tmp/BPV_1388_downsampled.xmp --step 8.000000 --method fourier

**Comment by stetner** [comment]
Run sequentially no problem.  Machine is an 18 core hyperthreaded machine with 128GB memory and I have exclusive use of it.

$ cat z
scipion xmipp_transform_downsample -i Runs/000002_ProtImportMicrographs/extra/BPV_1386.mrc -o Runs/000269_XmippProtExtractParticles/tmp/BPV_1386_downsampled.xmp --step 8.000000 --method fourier
scipion xmipp_transform_downsample -i Runs/000002_ProtImportMicrographs/extra/BPV_1387.mrc -o Runs/000269_XmippProtExtractParticles/tmp/BPV_1387_downsampled.xmp --step 8.000000 --method fourier
scipion xmipp_transform_downsample -i Runs/000002_ProtImportMicrographs/extra/BPV_1388.mrc -o Runs/000269_XmippProtExtractParticles/tmp/BPV_1388_downsampled.xmp --step 8.000000 --method fourier
$ . ./z

Scipion v1.1 (2017-06-14) Balbino

>>>>> python  /opt/Modules/scipion/1.1/pyworkflow/apps/pw_program.py "xmipp_transform_downsample" "-i" "Runs/000002_ProtImportMicrographs/extra/BPV_1386.mrc" "-o" "Runs/000269_XmippProtExtractParticles/tmp/BPV_1386_downsampled.xmp" "--step" "8.000000" "--method" "fourier"
** Running command: xmipp_transform_downsample "-i" "Runs/000002_ProtImportMicrographs/extra/BPV_1386.mrc" "-o" "Runs/000269_XmippProtExtractParticles/tmp/BPV_1386_downsampled.xmp" "--step" "8.000000" "--method" "fourier"
Input File: Runs/000002_ProtImportMicrographs/extra/BPV_1386.mrc
Output File: Runs/000269_XmippProtExtractParticles/tmp/BPV_1386_downsampled.xmp

Scipion v1.1 (2017-06-14) Balbino

>>>>> python  /opt/Modules/scipion/1.1/pyworkflow/apps/pw_program.py "xmipp_transform_downsample" "-i" "Runs/000002_ProtImportMicrographs/extra/BPV_1387.mrc" "-o" "Runs/000269_XmippProtExtractParticles/tmp/BPV_1387_downsampled.xmp" "--step" "8.000000" "--method" "fourier"
** Running command: xmipp_transform_downsample "-i" "Runs/000002_ProtImportMicrographs/extra/BPV_1387.mrc" "-o" "Runs/000269_XmippProtExtractParticles/tmp/BPV_1387_downsampled.xmp" "--step" "8.000000" "--method" "fourier"
Input File: Runs/000002_ProtImportMicrographs/extra/BPV_1387.mrc
Output File: Runs/000269_XmippProtExtractParticles/tmp/BPV_1387_downsampled.xmp

Scipion v1.1 (2017-06-14) Balbino

>>>>> python  /opt/Modules/scipion/1.1/pyworkflow/apps/pw_program.py "xmipp_transform_downsample" "-i" "Runs/000002_ProtImportMicrographs/extra/BPV_1388.mrc" "-o" "Runs/000269_XmippProtExtractParticles/tmp/BPV_1388_downsampled.xmp" "--step" "8.000000" "--method" "fourier"
** Running command: xmipp_transform_downsample "-i" "Runs/000002_ProtImportMicrographs/extra/BPV_1388.mrc" "-o" "Runs/000269_XmippProtExtractParticles/tmp/BPV_1388_downsampled.xmp" "--step" "8.000000" "--method" "fourier"
Input File: Runs/000002_ProtImportMicrographs/extra/BPV_1388.mrc
Output File: Runs/000269_XmippProtExtractParticles/tmp/BPV_1388_downsampled.xmp
$

**Comment by pconesa** [comment]
This is interesting @stetner. Thaks for your time and detailed explanation.  I'll involve Xmipp developers to see if they can find an explanation. Here test works and I don't see why 3 "very" independent processes like those, not sharing any file are failing when run simultaneously.
@cossorzano or @rmarabini , any idea why this could be happening?

**Comment by stetner** [comment]
One thing of note is that my home directory and the software install directory are on a lustre filesystem with no file locking.

I have symlinked both ~/ScipionUserData and scipion/data/tests to an xfs writeable lockable filesystem.

Doug

**Comment by cossorzano** [comment]
Dear Doug, I have run the test in the branch release-1.1 and it runs OK. Could you suggest some way to try to reproduce it? Cheers

**Comment by stetner** [comment]
OK, double checked and I think the reason was that my /tmp was only 2Gb.  I moved my ScipionUserData directory to /scratch and all seems good.  I was thinking locking was the issue, but it was also size I guess.

$ df -h /tmp/     /scratch/
Filesystem      Size  Used Avail Use% Mounted on
tmpfs           2.0G     0  2.0G   0% /ram/tmp
/dev/sdb2       1.1T  692M  1.1T   1% /scratch

Error was a bit cryptic though.

Thanks for your time.

Doug
