### ISSUE TITLE
html report - rsync processes stay alive when protocol not running

### ISSUE THREAD

**Issue by rmarabini** [I2PC/scipion#1255]
Each time html report (analyze) is pressed in monitor summary, an rsync process is launched that is never killed. Therefore, after a while many bogus rsync are been executed.  Very likely rsync should be started by the protocol and not by analyzed. rsync should be killed when the protocol is stopped.

**Comment by pconesa** [comment]
Are you sure is the analyze results.....or is is just restarting the protocol when it is "running ( a thing that should not be allowed? and is already happening.

**Comment by pconesa** [comment]
I confirm that this is about executing a protocol (at least the summary) when it is running.

**Comment by pconesa** [comment]
This is due to a bad use of scipion, but allowed. It is prevented since: https://github.com/I2PC/scipion/commit/a13b1034bf04143d928a70ff73dad2a892af7493
