### ISSUE TITLE
Can't copy monitor protocols

### ISSUE THREAD

**Issue by yaizar** [I2PC/scipion#1259]
When selecting a few protocols with a monitor among them to copy them, we get an error saying: 
`List.set: value should be a list.`
Then the gui doesn't work as expected (can't unselect boxes) and when we hit refresh we get the copies we wanted but attached to the wrong boxes:
![image](https://user-images.githubusercontent.com/4609687/31660506-ea0c6840-b337-11e7-864b-5d69c2a8676b.png)

**Comment by pconesa** [comment]
This is working for me. Probably fixed already.
