### ISSUE TITLE
picking in streaming questions

### ISSUE THREAD

**Issue by azazellochg** [I2PC/scipion#1266]
I am testing release-1.1-facilities-devel branch after PR #1249, so I'll put here my questions:
1. Xmipp manual picking step1 protocol now does not support restart? Save and Execute buttons are not active. So, the suggested way is to Analyze results and correct picking? What if I want to reset picking for all micrographs? Just copy the protocol?

**Comment by delarosatrevin** [comment]
@azazellochg I think this has been changed by @pconesa where the Excute button is disabled when is not allowed. @pconesa, can you confirm that? Have you taken into account the 'Interactive' state? (which I think is not active, not sure). Indeed the Xmipp manual picking has not been modified in the streaming branch.

**Comment by pconesa** [comment]
Sorry, I didn't consider this case. I used .isActive, which includes
interactive, should I exclude this status: if .isActive and not interactive
l--} disable? . Can anyone think in any other case?

**Comment by azazellochg** [comment]
@pconesa @delarosatrevin 
Another thing. I have just merged this into my eman22-dev, and now extract particle pairs is broken:
```
00009:   Traceback (most recent call last):
00010:     File "/lmb/home/gsharov/soft/scipion/pyworkflow/protocol/protocol.py", line 185, in run
00011:       self._run()
00012:     File "/lmb/home/gsharov/soft/scipion/pyworkflow/protocol/protocol.py", line 1087, in _run
00013:       self._insertAllSteps() # Define steps for execute later
00014:     File "/lmb/home/gsharov/soft/scipion/pyworkflow/em/packages/xmipp3/protocol_extract_particles_pairs.py", line 183, in _insertAllSteps
00015:       prerequisites=localDeps))
00016:     File "/lmb/home/gsharov/soft/scipion/pyworkflow/protocol/protocol.py", line 779, in _insertFunctionStep
00017:       "not member of the protocol" % funcName)
00018:   Exception: Protocol._insertFunctionStep: 'extractParticlesStep' function is not member of the protocol
```

**Comment by pconesa** [comment]
Thanks Gregory, we'll have a look.

**Comment by azazellochg** [comment]
Both my questions were addressed, so this is closed.
