### ISSUE TITLE
center1.spi is missing for spider align pairwise protocol

### ISSUE THREAD

**Issue by azazellochg** [I2PC/scipion#127]
When using center of gravity = RT180, the spider protocol fails at [this](https://github.com/biocompwebs/scipion/blob/master/pyworkflow/em/packages/spider/scripts/mda/pairwise.msa#L475) point with an error:

>00066:    *** ERROR: PROCEDURE FILE.spi DOES NOT EXIST: /home/sharov/soft/scipion/software/em/spider/spider/proc/center1.spi

The required spider script (not adapted) can be found [here](http://spider.wadsworth.org/spider_doc/spider/docs/techs/ranconical/center1.rct)

**Comment by delarosatrevin** [comment]
I have added center1 script and it is copied to the same location before runnig pairwise, but I think there is a bug in the spider script [here](https://github.com/biocompwebs/scipion/blob/6a22cc736c5e3d5d961a012ecc24eea0571e7d5b/pyworkflow/em/packages/spider/scripts/mda/pairwise.msa#L475). I tried to add an extra [ , but then it complate about [one] params. I think I have reached my limit in Spider. I would forward this issue to @taputechnic .
