### ISSUE TITLE
Set view list to SPA by default

### ISSUE THREAD

**Issue by azazellochg** [I2PC/scipion#1271]
For all new projects HEMNMA is the first list that pops up. I understand that the list (except All) was sorted alphabetically and this is the first one now :) I suggest revert it back to Protocols SPA that goes first, since these protocols are the main ones.

**Comment by pconesa** [comment]
@azazellochg , I've seen this before and think it was fixed but for some time, the code was sorting the protocols.conf. It should not this anymore.

Cloud you try to remove/remane protocols .conf
Run scipion config
and see if still HEMNMA is the first?

**Comment by azazellochg** [comment]
@pconesa indeed, you are right.
