### ISSUE TITLE
Protocol 'Relion - 3D auto-refine' with 'Second reference mask' crashes

### ISSUE THREAD

**Issue by JuhaHuiskonen** [I2PC/scipion#1276]
Protocol 'Relion - 3D auto-refine' with 'Second reference mask' crashes with error: 

00035:     File "/gpfs0/users/strubi/juha/apps/scipion-1.1.facilities-devel/pyworkflow/em/packages/relion/protocol_base.py", line 1028, in _setMaskArgs
00036:       solventMask = convertMask(self.solventMask, self._getTmpPath())
00037:     File "/gpfs0/users/strubi/juha/apps/scipion-1.1.facilities-devel/pyworkflow/em/packages/relion/convert.py", line 885, in convertMask
00038:       imgFn = getImageLocation(img.getLocation())
00039:   AttributeError: 'Pointer' object has no attribute 'getLocation'

If I omit this mask, it starts normally.

**Comment by JuhaHuiskonen** [comment]
Hi @delarosatrevin has anyone looked into this? I am still getting this error and my branch is up-to-date.  Also relion 3D classification crashes (with the same error) when this second mask (solventmask2) is given. BTW, I am not giving the first mask as a solventMask, as I specify the size of the particle with diameter.

**Comment by JuhaHuiskonen** [comment]
Also, I noticed that the mask values are scaled as follows using xmipp_image_transform:

if <0 set to 1
if >1 set to 1

shouldn't it be:

if <0 set to 0
if >1 set to 1

**Comment by azazellochg** [comment]
@JuhaHuiskonen you are right, these are trivial mistakes that are now fixed in release-1.1.facilities-fixes branch. Eventually (after #1373 ) they will land up in 1.1-devel. You can look at my two latest commits to fixes branch if you need an urgent fix.
Thanks for reporting!

**Comment by delarosatrevin** [comment]
@azazellochg Thanks a lot one more time for your help! I will take a look at the PR next week.
