### ISSUE TITLE
scipion test tests.em.workflows.test_workflow_xmipp

### ISSUE THREAD

**Issue by pconesa** [I2PC/scipion#1277]
Fails on buildbot
facilities branch

**Comment by delarosatrevin** [comment]
@pconesa I working on this right now, I think we need to be more careful when merging PR. Maybe this test was broken after the streaming merge. If buildbot if not agile, we need to define another way to launch some test and catch these errors quickly.

**Comment by pconesa** [comment]
Thanks, @delarosatrevin , we just need to pay more attention to buildbot, and hopefully, try to implement the PR feature in buildbot.

**Comment by azazellochg** [comment]
This is because extract tilt pairs is not working,  I think
