### ISSUE TITLE
2 bugs in spider classify k-means protocol

### ISSUE THREAD

**Issue by azazellochg** [I2PC/scipion#128]
I have used IMC file in the input. At the end of this protocol (step 3) I get an error:

>00060:   STARTED: createOutputStep, step 3
00061:     2015-11-18 17:59:53.854896
00062:   Traceback (most recent call last):
00063:     File "/home/sharov/soft/scipion/pyworkflow/protocol/protocol.py", line 167, in run
00064:       self._run()
00065:     File "/home/sharov/soft/scipion/pyworkflow/protocol/protocol.py", line 211, in _run
00066:       resultFiles = self._runFunc()
00067:     File "/home/sharov/soft/scipion/pyworkflow/protocol/protocol.py", line 207, in _runFunc
00068:       return self._func(*self._args)
00069:     File "/home/sharov/soft/scipion/pyworkflow/em/packages/spider/protocol/protocol_classify_kmeans.py", line 89, in createOutputStep
00070:       class2D.append(img)
00071:     File "/home/sharov/soft/scipion/pyworkflow/em/data.py", line 751, in append
00072:       if self.getSamplingRate() or not image.getSamplingRate():
00073:   AttributeError: 'NoneType' object has no attribute 'getSamplingRate'
00074:   Protocol failed: 'NoneType' object has no attribute 'getSamplingRate'
00075:   FAILED: createOutputStep, step 3

---

When I use SEQ file as input, I get a different error:

>00031:   STARTED: classifyStep, step 2
00032:     2015-11-18 12:57:53.066045
00033:   Copied file 'Runs/004282_SpiderProtCAPCA/CA/cas_SEQ.stk' to 'cas_SEQ.stk'
........
00050:   Running k-means classification
00051:   Wed Nov 18 12:57:53 CET 2015
00052:   *** FATAL ERROR ENCOUNTERED IN BATCH MODE
00053:   FINISHED: classifyStep, step 2

Looking deeper in the resulting spider file, I have found the error:

> .SYSTEM COMMAND: 
>  echo "Running k-means classification"; date
> .OPERATION: 
> .; run k-means classification: 
> .OPERATION: cl km x21,x22,x23,x24,x25  
>  YOU MAY USE A _SEQ, _PIX, or _IMC FILE
>  
> .CORAN/PCA FILE (e.g. CORAN_IMC):  cas_SEQ_IMC 
> *** FILE DOES NOT EXIST: cas_SEQ_IMC.stk
> TERMINATED ON ERROR IN BATCH MODE  18-NOV-2015 at 12:57:53

This is caused by the fact that [here](https://github.com/biocompwebs/scipion/blob/v1.0/pyworkflow/em/packages/spider/scripts/mda/kmeans.msa#L41) "_IMC" is used by default, not taking into account that _SEQ could be also chosen

**Comment by delarosatrevin** [comment]
1) When using the IMC file the error is weird, it seems like it has found an image id in the spider document file that is not present in the input particles set. I have added a warning and avoided to add "None" particles. Anyway this should help us to check what is going on.

2) You were right the k-means spider script had hard-code the _IMC extension, now I have modified to allow for _SEQ as well. I have also include the use of threads parameters, before was using 0, that means all available. This problem also affected Ward protocol. Diday seems to work only with IMC.

@taputechnic , could you check in detail the changes introduced in this commit (5cbb3b8)??
I have passed the tests and seems OK, but I would like to be sure. Can you check if make sense to merge this changes back to Spider scripts? I don't want that Scipion/Spider scripts diverge from the official ones.

@azazellochg , please test with this changes and let me know. Thanks.

**Comment by azazellochg** [comment]
@delarosatrevin , i have checked all 3 protocols: kmeans and ward seems work for me with both IMC/SEQ files, while as you said diday works only with IMC (not SEQ). 

**About missing particle id**:  I have located the problem in previous step - during particle extraction sometimes I have a message: "Particle 000052@Runs/........stk is very near the border, corresponding image is set to blank". That is why after extraction and in all following steps few ids are missing, while the counting is correct (e.g., I had 409 box coordinates and got 407 particles).

**Comment by azazellochg** [comment]
@delarosatrevin , I guess this can be closed now?

**Comment by delarosatrevin** [comment]
yep, done.
