### ISSUE TITLE
Resume protocols in streaming

### ISSUE THREAD

**Issue by pconesa** [I2PC/scipion#1286]
If a protocol fails or stops, allow the "continue"/resume to open the sets and continue the streaming.

**Comment by delarosatrevin** [comment]
This should be possible right now. Can you point to a specific case where it is not happening?

**Comment by pconesa** [comment]
I mean when it is finished.

**Comment by pconesa** [comment]
Meet Roberto to find a solution.

**Comment by pconesa** [comment]
Import, add a set to exclude
Increase streaming finish timeout to prevent import to close earlier than desired (3600*12) --> 12 hours? An allow empty value for an endless input.

**Comment by delarosatrevin** [comment]
I agree that increasing the stop time value is a good idea, specially since the operator can stop the streaming manually. I would not complicate the code with the endless input, since it is easy to add many zeroes to the stopping time.

**Comment by pconesa** [comment]
@delarosatrevin thanks!
