### ISSUE TITLE
Update motioncorr 2

### ISSUE THREAD

**Issue by pconesa** [I2PC/scipion#1291]
Dear Colleagues:

MotionCor2_1.0.1 has been released on our web site. You can download via the following link.

http://msg.ucsf.edu/em/software/index.html

This version has significantly improved the computational efficiency. Under the same setup, the computational time can be reduced by 50% as opposed to the older versions. This version also added two functions, one for dark subtraction and the other allowing users to use overlapped patches.

The updated user manual is also provided on our web site. 

Thank you for interest and look forward to your feedback.

Best

Shawn

**Comment by delarosatrevin** [comment]
@pconesa I will try this, since I'm already working in using multiple gpus for this program.

**Comment by pconesa** [comment]
Excellent! thank you. All yours! ;-)
