### ISSUE TITLE
Use multiple GPUs in MotionCor2

### ISSUE THREAD

**Issue by delarosatrevin** [I2PC/scipion#1294]
We should allow to use multiple GPU cards

**Comment by azazellochg** [comment]
@delarosatrevin great! just to re-iterate what is known: many people reported that running one movie per GPU card is much faster than 1 movie per multiple cards. So we need to split the list of movies into N available cards. It would be even more awesome to implement this in streaming as well. Another thing @delarosatrevin you could test is whether giving a dir with N movies to motioncor2 works faster (motioncor splits the movie list itself) than the first approach I mentionned,

**Comment by delarosatrevin** [comment]
Thanks @azazellochg.
I have observed the same, that using multiple motioncor2 in individual cards is faster. Even sometimes allocating more than one process per card...but now in the manual there is a big RED alert against that. 

I have done some test about the one after one vs the batch mode and I didn't saw much gain (less important in streaming) but I think there is a speed-up. We need to consider this case without complicating much the logic of the streaming now or making it too much specific.

**Comment by pconesa** [comment]
@delarosatrevin , I've assigned this to you since you are already exploring this.

**Comment by delarosatrevin** [comment]
This is more or less working at delarosatrevin/scipion (smaster branch). We need to merge back at some point.
