### ISSUE TITLE
protocol 'xmipp3 - break symmetry' fails

### ISSUE THREAD

**Issue by JuhaHuiskonen** [I2PC/scipion#1303]
Running with a subset of 500 random particles that have been aligned. Protocol fails with the error:

00001:   RUNNING PROTOCOL -----------------
00002:             PID: 8829
00003:         Scipion:  release-1.1.facilities-relion-fixes (2017-10-10) 0b5b9a5
00004:      currentDir: /gpfs2/well/strubi/juha/ScipionUserData/projects/HSV1-genome
00005:      workingDir: Runs/002257_XmippProtAngBreakSymmetry
00006:         runMode: Restart
00007:             MPI: 1
00008:         threads: 1
00009:    Starting at step: 1
00010:    Running steps 
00011:   STARTED: convertInputStep, step 1
00012:     2017-11-01 06:47:16.322630
00013:   Traceback (most recent call last):
00014:     File "/gpfs0/users/strubi/juha/apps/scipion-1.1.facilities-devel/pyworkflow/protocol/protocol.py", line 185, in run
00015:       self._run()
00016:     File "/gpfs0/users/strubi/juha/apps/scipion-1.1.facilities-devel/pyworkflow/protocol/protocol.py", line 231, in _run
00017:       resultFiles = self._runFunc()
00018:     File "/gpfs0/users/strubi/juha/apps/scipion-1.1.facilities-devel/pyworkflow/protocol/protocol.py", line 227, in _runFunc
00019:       return self._func(*self._args)
00020:     File "/gpfs0/users/strubi/juha/apps/scipion-1.1.facilities-devel/pyworkflow/em/packages/xmipp3/protocol_break_symmetry.py", line 71, in convertInputStep
00021:       writeSetOfParticles(self.inputParticles.get(), outputFn)
00022:     File "/gpfs0/users/strubi/juha/apps/scipion-1.1.facilities-devel/pyworkflow/em/packages/xmipp3/convert.py", line 866, in writeSetOfParticles
00023:       writeSetOfImages(imgSet, filename, particleToRow, blockName, **kwargs)
00024:     File "/gpfs0/users/strubi/juha/apps/scipion-1.1.facilities-devel/pyworkflow/em/packages/xmipp3/convert.py", line 845, in writeSetOfImages
00025:       setOfImagesToMd(imgSet, md, imgToFunc, **kwargs)
00026:     File "/gpfs0/users/strubi/juha/apps/scipion-1.1.facilities-devel/pyworkflow/em/packages/xmipp3/convert.py", line 817, in setOfImagesToMd
00027:       imgToFunc(img, imgRow, **kwargs)
00028:     File "/gpfs0/users/strubi/juha/apps/scipion-1.1.facilities-devel/pyworkflow/em/packages/xmipp3/convert.py", line 496, in particleToRow
00029:       imageToRow(part, partRow, xmipp.MDL_IMAGE, **kwargs)
00030:     File "/gpfs0/users/strubi/juha/apps/scipion-1.1.facilities-devel/pyworkflow/em/packages/xmipp3/convert.py", line 344, in imageToRow
00031:       ctfModelToRow(img.getCTF(), imgRow)
00032:     File "/gpfs0/users/strubi/juha/apps/scipion-1.1.facilities-devel/pyworkflow/em/packages/xmipp3/convert.py", line 539, in ctfModelToRow
00033:       objectToRow(ctfModel, ctfRow, CTF_DICT, extraLabels=CTF_EXTRA_LABELS)
00034:     File "/gpfs0/users/strubi/juha/apps/scipion-1.1.facilities-devel/pyworkflow/em/packages/xmipp3/convert.py", line 177, in objectToRow
00035:       row.setValue(label, valueType(getattr(obj, attr).get()))
00036:   TypeError: float() argument must be a string or a number
00037:   Protocol failed: float() argument must be a string or a number
00038:   FAILED: convertInputStep, step 1
00039:     2017-11-01 06:47:16.332003
00040:   ------------------- PROTOCOL FAILED (DONE 1/3)

**Comment by pconesa** [comment]
Thanks Juha. This should be already fixed in release-1.1.facilities-devel.
Not sure if you still need to stay in your current branch.  Probably is
safe to switch to release-1.1.facilities-devel.

**Comment by delarosatrevin** [comment]
Yes, I think that changes in 'release-1.1.facilities-relion-fixes' are already merged into release-1.1.facilities-devel
