### ISSUE TITLE
Extracting particles without CTF

### ISSUE THREAD

**Issue by majtner** [I2PC/scipion#1306]
Protocol for extracting particles (XmippProtExtractParticles) could be run/executed without CTF information. As a result, protocol could finish and no output is created. Probably some warning or error message should be produced, when there is no output.

**Comment by azazellochg** [comment]
Hi @majtner , I did not catch that. I can extract particles without any ctf.. in which case there is no output?

**Comment by majtner** [comment]
Hi @azazellochg , I do not exactly remember this one but we were testing something with @pconesa and there was no output of the protocol. When I was testing it now, everything worked ok, so probably it was already solved. I also remember from later discussion that maybe something else was the problem, not the CTF.

@pconesa do you maybe remember more details about it and/or could you confirm it was solved?

**Comment by pconesa** [comment]
Yep, I think it was a case, where some error was happening but the protocol showed as finished. But can't remember what was making it fail that way.
