### ISSUE TITLE
deal with launched protocols and button disabled.

### ISSUE THREAD

**Issue by pconesa** [I2PC/scipion#1314]

**Comment by pconesa** [comment]
Maybe allow to stop it or enabled the button as it were before.?

**Comment by dmaluenda** [comment]
Stop button added in protocol option when it is in launched status:

STATUS_LAUNCHED constant is added to stoppable condition in getActionsFromSelection(self) function.
     >>>   gui/project/viewprotocols.py:183

commit in facilities-fixes by commit d791c7a1067ed28bfeaa21431d5afcf786f0b3c2
