### ISSUE TITLE
document scipion in streaming use

### ISSUE THREAD

**Issue by pconesa** [I2PC/scipion#1317]
either a wiki page or a tutorial

**Comment by azazellochg** [comment]
The following two pages exist (could be updated) and have no links from any point in the wiki so far :)
https://github.com/I2PC/scipion/wiki/Streaming-Processing
https://github.com/I2PC/scipion/wiki/Simulate-streaming-processing

**Comment by pconesa** [comment]
Thanks, will update them and link them from somewhere.
