### ISSUE TITLE
Update motioncor2 1.0.1 ?

### ISSUE THREAD

**Issue by pconesa** [I2PC/scipion#1319]
> Dear Colleague:
> 
> A bug was reported in version 1.0.1. It happens when users want to output  the unbinned motion corrected stack. The fixed version 1.0.2 has been released on our website. My apology for this and many thanks for those who let me know this problem.
> 
> Best regards,
> 
> Shawn

**Comment by pconesa** [comment]
@delarosatrevin ,  shouldn't the default value in the config file point to:
1.0.2 --> %(EM_ROOT)s/motioncor2-1.0.2
and not %(EM_ROOT)s/motioncor2-1.0.0?

**Comment by pconesa** [comment]
or maybe, @josuegbl

**Comment by azazellochg** [comment]
done in  cfdb565
