### ISSUE TITLE
missing file on binaries

### ISSUE THREAD

**Issue by ldelcano** [I2PC/scipion#1321]
When installing scipion from binaries, if by mistake one tries to install without specifying --no-xmipp option, the compilation fails cause software/em/xmipp/external/image.tgz is missing (not only fails but scipion is unusable afterwards).
Add this file to binary that contains other sources.

**Comment by delarosatrevin** [comment]
What we should prevent is to NO USE --no-xmipp when using the binary. Or in a future, not have the xmipp installation by default as it is now.

**Comment by ldelcano** [comment]
We should give three distribution options: binaries (without source code at all), sources (with complete sources) and git. 
When downloading binaries it should not try to install (this is solved now I believe). 
When downloading sources they should be complete (now missing imagej.tgz)

**Comment by delarosatrevin** [comment]
Check this @ldelcano...I think the imagej.tgz it is there in the source code tar...but get scrambred by the wrong "build process" when not using --no-xmipp for installing other packages and trying to build the java part.

**Comment by ldelcano** [comment]
I doubt that image.tgz is on the source code tar since the scripts/tar.py that is used to create them has an --exclude='*.tgz' option.

**Comment by ldelcano** [comment]
Verified:
- source tar currently includes all sources but fails cause it is missing imagej.tgz file. I will include it on the tar.
- binary tar currently includes same sources as the other. I will remove them (all in scipion/software/em/xmipp/libraries or maybe only *.h, *.cpp, *.java?)

**Comment by ldelcano** [comment]
I was wrong: imagej.tgz IS on the source tar.
The only problem is with binaries, which should not include any source at all (*.h, *.cpp and *.java)

**Comment by ldelcano** [comment]
Centos_64 VirtualBox machine that existed on einstein to create binaries is gone (einstein was reformated). I instantiated a Centos6 VM on the Fedcloud to compile binaries but they are not working:
ValueError: unsupported hash type sha384
ERROR:root:code for hash sha512 was not found.
...
ImportError: cannot import name md5

there is another Centos64 VM in nolan but it shutoff nolan when we try to start it. I will try to recover it on my laptop to see it that works.

**Comment by ldelcano** [comment]
We will investigate how to set up a proper Centos machine to create binaries. In the mean time I have removed sources from the existing binary file and added piece of code to scipion script to check that if no source exists xmipp should not be compiled.

**Comment by ldelcano** [comment]
Done. Modified scripts/tar.py to exclude source files (*.h, *.cpp and *.java) when generating binaries (linux64).
