### ISSUE TITLE
prepare Copenhagen workshop

### ISSUE THREAD

**Issue by pconesa** [I2PC/scipion#1327]

**Comment by delarosatrevin** [comment]
@pconesa Would it be better to have this "related" issues in a different place? Not together with the other development issues? Maybe using the GitHub projects?

**Comment by pconesa** [comment]
@delarosatrevin , github projects are based on issues as well. For our week plan this works ok.

**Comment by delarosatrevin** [comment]
@pconesa In Projects you can have Cards, that are not issues...for me it sometimes seems like some noise in the Scipion repository...and not all task are strickly related...but I can live with that. ;)

**Comment by pconesa** [comment]
thanks @delarosatrevin , I'll think about it. Sometimes is better to have all in one place, but I agree that it is noisy!. I don't have a perfect solution here.
