### ISSUE TITLE
More HTML tweaks

### ISSUE THREAD

**Issue by pconesa** [I2PC/scipion#1333]
- [x] Try to adjust the table when it looks wrong (shifted)
- [x] resolution and defocus coverage plots in vertical?
- [x] Numeric values consistency: al values 0.2f format (resolution 6.02A, defocus 1.52um (please in microns, not Angstroms!!), ratio 1.25, astigmatism ..) for all tables/plots so it would be easy to comprehend
- [x] Shorter file names in thumbnails?

Extracted from #1326

**Comment by pconesa** [comment]
- [ ] gpu memory series are in MB not %
- [ ] Clarify temparature units: ºC.

**Comment by yaizar** [comment]
Here's the vertical version of the resolution and defocus histograms, feedback would be welcome before we push these changes! @cossorzano @rmarabini any thoughts?

![image](https://user-images.githubusercontent.com/4609687/32899305-e746ae7a-caea-11e7-8509-839b3b9c737e.png)

**Comment by pconesa** [comment]
@azazellochg might want to feedback too.

**Comment by azazellochg** [comment]
@pconesa @yaizar I'm thinking:
1) maybe reverse x-axis (start from 0)
2) x-labels can be every 2nd tick
3) for defocus maybe too many labels/numbers? 0,0.5,1.0,1.5 would look better?

**Comment by yaizar** [comment]
thanks for the feedback @azazellochg, with your suggestions we would have something like this
![image](https://user-images.githubusercontent.com/4609687/32903099-6c911de6-caf4-11e7-9198-6fff92968c6e.png)
The x-labels auto-adjust depending on screen size, I don't see them particularly crammed, did you mean this for defocus coverage or for both? Is it better now with the .5 step?

**Comment by azazellochg** [comment]
@yaizar looks nice! If x has auto-adjust then it's fine

**Comment by azazellochg** [comment]
Hi @yaizar , in which branch "Shorter file names in thumbnails?" was done? or it's not in upstream yet?
Also, now I realize that astigmatism angle is a useless parameter to track (since this is not amount of astigmatism present, but just an angle between two defocus axes). It would be much better to add things like drift, CC fit, iciness..

**Comment by yaizar** [comment]
it should be in release-1.1.facilities-fixes with the rest of the tweaks, I'm guessing it didn't work out? We're looking into removing the astigmatism angle, thanks

**Comment by azazellochg** [comment]
@yaizar I am running demo in this branch and it still looks the same.
Astigmatism angle can be easily replaced by the amount in Angstroms - e.g., calculate on-the-fly (defocusU-defocusV) - this would be an alternative parameter for ratio.

**Comment by azazellochg** [comment]
I have pushed a commit a77662a to release-1.1.facilities-fixes, please have a look and revert/modify if necessary.

**Comment by yaizar** [comment]
@azazellochg looks good to me, I'll take a closer look on Monday. Shorter thumbnail titles should be up now :-)

**Comment by azazellochg** [comment]
@yaizar ok! Another thing is that in Firefox special characters like Angstrom sign, um are displayed wrongly (Chrome is ok): like 54.79Ã… 3.30Î¼m
Also about shorter thumbnails, after "cutting" the filename there is no way to find the original name of any certain micrograph anymore, maybe something like:
1) removing folder name (it is useless anyway)
2) showing FoilHole.... (limit to 55 symbols), but upon mouse hover show complete name?

**Comment by rmarabini** [comment]
Hi,

    @yaizar <https://github.com/yaizar> if html report is more or lest
stable. Could you test it in einstein (user scipiouser) with a few hundred
of movies?
@pconesa knows the password and where are the movies.

The ideal test -may be we should this together the first time would be as
follows:

- open a vnc conection with Einstein
     - connect to Einstein using ssh as scipionuser
     - start the server:    killall Xvnc4; rm -rf /tmp/.X*-lock; vncserver
-geometry 1280x960
- in your computer opena vnc client; vncviewer einstein:PORTNUMBER (usually
1)
- launch django server. cd /home/scipionuser/webservices/EMadmin/src
- open browser and connect to server at URL http://127.0.0.1:8000
- create new project and lunch scipion
- execute scipion protocols
- check html report

    as you see this is a piece of cake

                  Roberto


Without that test I can not install it in Scipionbox.

**Comment by azazellochg** [comment]
I got another question: what does Search field in Micrographs table do? I can't figure out what it finds for me :)

**Comment by pconesa** [comment]
It filters the table by any value in any column is the standard behavior of the widget. Can be hidden , but it works and might be useful in few cases.

**Comment by azazellochg** [comment]
@pconesa thanks for fixing the table back again, there is just a couple of places left:
1) pixel size in summary monitor form
![screenshot_20171123_142132](https://user-images.githubusercontent.com/6952870/33177181-a64ebe5c-d059-11e7-9ee0-4667983496ae.png)
2) in html report, acquisition list: Pixel Size (Ã…/px): 7.08000404572 (Angstrom sign and numbers)

**Comment by azazellochg** [comment]
A different thing is: the micrograph table is empty when I'm running protocols on the image attached above.. would be nice to see ctf results, even if no shift plots are available (we can show simply "No data" or simply hide the column when no movie alignment is running).

**Comment by pconesa** [comment]
Hi @azazellochg , I could fix 1. and 2. (now in fixes branch) but his last one will take some time so I'm separating it in a different issue and will probably be fixed later. We want to freeze the code to prepare the new release and have to cut somewhere. ;-(

**Comment by rmarabini** [comment]
Is this already in lrelease-1.1.facilities-devel?
