### ISSUE TITLE
filesPath param adds '..' to the folder path

### ISSUE THREAD

**Issue by azazellochg** [I2PC/scipion#1363]
When I select a folder in any protocol for PathParam, two dots are added to the end of path - this should not happen (I end up in parent folder :-1: ).

![screenshot_20171123_202909](https://user-images.githubusercontent.com/6952870/33187866-fe59bbe6-d08c-11e7-96c1-946616952904.png)

**Comment by dmaluenda** [comment]
Thanks Gregory.

Now,  we check the path and if it ends with "/..", we pass the current dir (removing the "/.."). 

Commited in facilities-fixes [0c8370feff6212c9bb75c2e3741507022f3b1a0b]

**Comment by delarosatrevin** [comment]
Hum...this looks like a bit dirty workaround...I think the file browser should not add the extra ".." characters to the path. The problem with this workaround is that you will need to check it in every place of the code where the browser is used (or will in a future ;)

**Comment by dmaluenda** [comment]
Finally the solution have been very easy. We keep the focus on the first item of the browser, but it remains unselected (see a doted box on the item but not highlighted). Thus, the _lastSelected item still being the current dir.

Of course, if the user select the .. folder, the path will be \<currentDir>/.. but this is consistent. 

Committed in facilities-fixes [4ab256ec639a1f33f9852bc105022d320adb1095]

**Comment by delarosatrevin** [comment]
Great!

**Comment by azazellochg** [comment]
I guess I can close this now.
