### ISSUE TITLE
classes cannot be saved after 3D classification of subtracted data

### ISSUE THREAD

**Issue by JuhaHuiskonen** [I2PC/scipion#1371]
I have ran 'relion - subtract projection' followed by 'relion - 3D classification'. If I open the classes with 'Analyse results' -> 'show classification in Scipion' and try to save particles from one class, I get this error:

 STARTED: createSetStep, step 1
00012:     2017-11-29 10:57:01.770192
00013:   Traceback (most recent call last):
00014:     File "/wrk/project_cryoem/apps/taito/scipion-1.1.1_171124_gcc/pyworkflow/protocol/protocol.py", line 186, in run
00015:       self._run()
00016:     File "/wrk/project_cryoem/apps/taito/scipion-1.1.1_171124_gcc/pyworkflow/protocol/protocol.py", line 233, in _run
00017:       resultFiles = self._runFunc()
00018:     File "/wrk/project_cryoem/apps/taito/scipion-1.1.1_171124_gcc/pyworkflow/protocol/protocol.py", line 229, in _runFunc
00019:       return self._func(*self._args)
00020:     File "/wrk/project_cryoem/apps/taito/scipion-1.1.1_171124_gcc/pyworkflow/em/protocol/protocol_batch.py", line 72, in createSetStep
00021:       setObj = self.createSetObject()
00022:     File "/wrk/project_cryoem/apps/taito/scipion-1.1.1_171124_gcc/pyworkflow/em/protocol/protocol_batch.py", line 403, in createSetObject
00023:       os.rename(_dbName, self._dbName)
00024:   OSError: [Errno 2] No such file or directory
00025:   Protocol failed: [Errno 2] No such file or directory
00026:   FAILED: createSetStep, step 1
00027:     2017-11-29 10:57:01.801285

I am using release-1.1.facilities-devel branch. In the same workflow I can save particles form another classification run, that was using un-subtracted particles - so I suspect it is the  'relion - subtract projection' protocol that breaks something.

**Comment by pconesa** [comment]
Thanks @JuhaHuiskonen , I'll try to reproduce it here.

**Comment by JuhaHuiskonen** [comment]
OK, it's not a related to subtraction - I encountered the same error in a different project (no subtraction) and on a different cluster.  After repeating the selection and saving the particle subset, it suddenly worked.

**Comment by pconesa** [comment]
Thanks Juha for updating this. Still, we will keep an eye on this since it first error should not happen.
