### ISSUE TITLE
Interactive runs crash if the protocol is opened from another machine

### ISSUE THREAD

**Issue by JuhaHuiskonen** [I2PC/scipion#1386]
Some runs need to be run interactively (e.g. GPU jobs in our setup). If I accidentally open the project later from a different machine (after having closed it from the original machine), the job will immediately fail. It would be nice if this wouldn't happen. Maybe there could be a warning state for such situations where scipion cannot determine whether the job is running.

**Comment by delarosatrevin** [comment]
Yes, I agree with that. I think we need to store the hostname where a protocol was launched and then do no check the status if not in this machine...becase the process will not exist there and it will be (wrongly) marked as failed.

**Comment by azazellochg** [comment]
solved in https://github.com/delarosatrevin/scipion/commit/bda1585fd2310c5fa89bee8d05e18a8027711c7b

**Comment by delarosatrevin** [comment]
Now merged to release-1.2.1, a full hostname is stored and jobs will only be checked in the system if there launched in that host. @JuhaHuiskonen this should solve this issue.
