### ISSUE TITLE
xmipp - hires problem

### ISSUE THREAD

**Issue by JuhaHuiskonen** [I2PC/scipion#1387]
I have been testing the new 'xmipp - hires' protocol.  I can't seem to get it run, it crashes with an error:

00055:   XMIPP_ERROR 22:  It is not a file
00056:   FileName::isMetaData: File: 'Runs/012293_XmippProtReconstructHighRes/extra/Iter000/angles.xmd' does not exist
00057:   File: software/em/xmipp/libraries/data/xmipp_filename.cpp line: 560

I have about 4000 particles, my box size is 800 and I am testing with 8 threads.

**Comment by azazellochg** [comment]
I have got another issue when running with threads (not MPIs):
```
00704:      2/   2 sec. ......................................................00705:   xmipp_transform_adjust_image_grey_levels -i Runs/000162_XmippProtReconstructHighRes/extra/Iter005/images_corrected01.xmd -o Runs/000162_XmippProtReconstructHighRes/extra/Iter005/images_gray01.stk --sampling 2.333333 --Rmax 180 --padding 2 --ref Runs/000162_XmippProtReconstructHighRes/extra/Iter005/localAssignment/volumeRef01.vol --max_resolution 6.865384 --save_metadata_stack Runs/000162_XmippProtReconstructHighRes/extra/Iter005/images_gray01.xmd --max_gray_scale 0.500000 --max_gray_shift 3.000000 --Nsimultaneous 4
00706:   XMIPP_ERROR 1: Errors on command line parameters
00707:   Unrecognized parameter: --Nsimultaneous
00708:   
00709:   File: software/em/xmipp/libraries/data/argsparser.cpp line: 1036
```
The problem is that Nsimultaneous param exists only for mpi version of the program

**Comment by cossorzano** [comment]
Done, thank you Grigory, this program makes sense only in MPI

**Comment by cossorzano** [comment]
Solved in facilities-devel
