### ISSUE TITLE
Devel: Some viwers are not discovered now

### ISSUE THREAD

**Issue by pconesa** [I2PC/scipion#1390]
@rmarabini , we found out today that these [lines](https://github.com/I2PC/scipion/blob/devel/pyworkflow/em/viewer.py#L60) are actually needed, at least those for the Gain viewer and the Summary monitor.

I agree, that for the gain viewer (more an Xmipp viewer) should be place under xmipp, but not sure about the others.

**Comment by rmarabini** [comment]
Hi,

Fools rush in where angels fear to tread

I do not have a very clear vision on how the viewers are identified but I think the way to go is:
Restore 

# from viewer_fsc import FscViewer
# from viewer_pdf import PDFReportViewer
# from viewer_monitor_summary import ViewerMonitorSummary

And add the following imports to __init__,py in pyworkflow.protocol.monitors and see what happens

# from protocol.monitors.protocol_monitor_ctf import ProtMonitorCTFViewer
# from protocol.monitors.protocol_monitor_system import ProtMonitorSystemViewer
# from protocol.monitors.protocol_monitor_movie_gain import ProtMonitorMovieGainViewer

Is this agreeable?

       Roberto

**Comment by pconesa** [comment]
Well, I think the gain one, belongs more to Xmipp. I see it somewhere under Xmipp folder.

**Comment by rmarabini** [comment]
OK

**Comment by pconesa** [comment]
I'll take care of this!
