### ISSUE TITLE
MotionCor2 1.0.4

### ISSUE THREAD

**Issue by azazellochg** [I2PC/scipion#1393]
> MotionCor2 1.0.4 has been released. This version fixed the problem in version 1.0.2 where the program crashes when -DefectFile is enabled. Version 1.0.4 also improves the correction of bad pixels. This version can be downloaded from

 

http://msg.ucsf.edu/MotionCor2/MotionCor2-1.0.4.tar.gz

**Comment by delarosatrevin** [comment]
Yes, this should be relatively easy to update.

**Comment by pconesa** [comment]
Thanks @azazellochg , we will include it in this next release. We are about to generate the binaries as "beta" while we do some manual tests.
