### ISSUE TITLE
Scipion error loading protocols

### ISSUE THREAD

**Issue by majtner** [I2PC/scipion#1395]
I am executing some protocol, it fails, I can see it in Output log, so I close Scipion and try to fix the problem.
When I launch Scipion again, this protocol has still status "launched" (in Output log I still see it failed), so I can not edit it and launch again. Refresh in top right corner does not help. I need to click on protocol and choose "Stop", which will end with error (since the protocol is already not running) and after clicking on Refresh in top right corner, protocol is finally in "failed" status and I can edit it and execute again.

I also noticed that this is happening only with some types of error, typically when protocol is only in "launched" and the error appears before going to "running" status.

**Comment by pconesa** [comment]
@dmaluenda fix this in facilities....he can explain the solution. I think changes need to be pushed to devel.

**Comment by pconesa** [comment]
I've pushed changes to devel.
