### ISSUE TITLE
Support 4bit mrc

### ISSUE THREAD

**Issue by pconesa** [I2PC/scipion#1401]
From [scipion user list](https://sourceforge.net/p/scipion/mailman/message/36164680/)

**Comment by azazellochg** [comment]
this is so-called mode 101
specs: http://bio3d.colorado.edu/imod/betaDoc/mrc_format.txt

> For 4-bit data (mode 101), each byte contains a pair of pixels, and the first
> pixel (the one with lower coordinate) is in the lower 4 bits, while the second
> pixel is in the higher 4 bits.  This fill order is the same for little-endian
> and big-endian files.  Each line has int((nx + 1) / 2) bytes, with 4-bits of
> padding at the end of each line when nx is odd.

**Comment by pconesa** [comment]
As always, many thanks, @azazellochg. I've googled it and found the same link but wasn't sure.
