### ISSUE TITLE
RelionInitialModel test is failing

### ISSUE THREAD

**Issue by pconesa** [I2PC/scipion#1404]
I'm getting:
TypeError: Unrecognized type to create MDObject
00035:   Protocol failed: Unrecognized type to create MDObject

**Comment by pconesa** [comment]
I got more info: the actual problem is around rlnPhaseShift value being None?

00016:   XmippMdRow.writeToMd: Error writing value to metadata.
00017:                        label: rlnPhaseShift, value: None, type(value): <type 'NoneType'>

**Comment by azazellochg** [comment]
@pconesa my bad, fixed in facilities-fixes

**Comment by pconesa** [comment]
Excellent, @azazellochg , thanks!.
