### ISSUE TITLE
ShowJ do not load an .mrc properly

### ISSUE THREAD

**Issue by pconesa** [I2PC/scipion#142]
The file can be found here: https://drive.google.com/file/d/0B1G77GnEYRvMMC1HSjhhVENXV1k/view?usp=drive_web

To reproduce use: scipion viewer adv_001.mrc

It does not load the images properly. However using:
scipion viewer adv_001.mrc:mrcs it loads correct.

**Comment by pconesa** [comment]
native method getStatistics is failing. Roberto will deal with it.

**Comment by delarosatrevin** [comment]
@pconesa , the file link is not longer valid...this issues is closed? We need to remember that mrc is troublesome distinguishing between volumes and 2d stacks.

**Comment by delarosatrevin** [comment]
I checked with Roberto this issues and seems to be solved.
We tested with ADV volume of 780px of box size and was displayed correctly.
