### ISSUE TITLE
Problems about adding new protocol

### ISSUE THREAD

**Issue by phonchi** [I2PC/scipion#1424]
I just found this project and it seems great!

I have a problem with adding new protocol. I have tried to add protocol following the guide from [the wiki](https://github.com/I2PC/scipion/wiki/Creating-a-Protocol). 

For testing purpose, my simple protocol is listing as follows (where average.py is simply summing the mrcs files):

```
from os.path import exists, realpath, abspath

import pyworkflow.protocol.params as params
import pyworkflow.protocol.constants as cons
import pyworkflow.utils.path as pwutils
from pyworkflow.em.protocol import ProtAlignMovies, ProtProcessMovies


class ProtAverage(ProtAlignMovies):
    """ Wrapper to simple program
    """
    _label = 'average frame'
    CONVERT_TO_MRC = 'mrc'
    doSaveAveMic = True
    
    # --------------------------- DEFINE param functions -----------------------
    def _defineAlignmentParams(self, form):
        form.addParallelSection(threads=1, mpi=1)
    
    # --------------------------- STEPS functions ------------------------------
    def _processMovie(self, movie):
        try:
            self._createLink(movie)
            self._argsSummovie()

            params = {'movieFn': self._getMovieFn(movie)
                      }

            self.runJob("/home/aaa/scipion/software/em/stats328/average.py", self._args % params)
            print ("hello")
                
        except Exception as e:
            print("ERROR: Movie %s failed.\n"
                  "       Message: %s\n" % (movie.getFileName(), e))
    
    # --------------------------- INFO functions -------------------------------
    def _argsSummovie(self):
        # Avoid threads multiplication
        # self._program = 'export OMP_NUM_THREADS=%d; ' % self.numberOfThreads.get()
        # self._program = 'export OMP_NUM_THREADS=1; '
        self._args = """ << eof
%(movieFn)s
eof
"""

    def _validate(self):
        """ Should be overriden in subclasses to 
        return summary message for NORMAL EXECUTION. 
        """
        validateMsgs = [""]
        return validateMsgs
    # --------------------------- UTILS functions ------------------------------
    def _createOutputMovies(self):
        """ Returns True if an output set of movies will be generated.
        The most common case is to always generate output movies,
        either with alignment only or the binary aligned movie files.
        Subclasses can override this function to change this behavior.
        """
        return False
    
    def _storeSummary(self, movie):
        pass

    def _getMovieFn(self, movie):
        movieFn = movie.getFileName()
        if movieFn.endswith("mrcs"):
            return pwutils.replaceExt(movieFn, self.CONVERT_TO_MRC)
        else:
            return movieFn

    def _createLink(self, movie):
        movieFn = movie.getFileName()
        if movieFn.endswith("mrcs"):
            pwutils.createLink(movieFn, self._getMovieFn(movie))
```

The script name is `protocol_average.py` and I have placed the script into ~/scipion/pyworkflow/em/packages/stats328/

I also modify the ~/scipion/config/protocol.conf so that I can see my protocol in GUI as follows:

![problem_scipion](https://user-images.githubusercontent.com/11373055/34869613-68604512-f7c2-11e7-8107-5a01c8f7f043.png)

However, when I fill the input movie and execute nothing happen except there is an info window pop out.

In addition, there is no corresponding directory inside my project directory (Something like project/test/Runs/00001000_ProtAverage).

My questions are:

(1) Is there anything I missing in creating the protocol.
(2) Is there any way to debug in this kinds of scenario

Any suggestions will be appreciated, thanks in advance !!

**Comment by josuegbl** [comment]
Hi @phonchi and thank you for contribute to this project. Maybe the script name is different to the file that you are executing in self.runJob (average.py). Could you put here the message that appear in  info window pop out?

**Comment by phonchi** [comment]
Thanks for the quick reply!!

I have checked that the script did exists. It seems that the message shown in the pop-out window will be the message write in `validateMsgs`.

In addition, the 'average.py' is taken from the sphire project as follows:

```
#!/home/tlchen/EMAN2/bin/python

### This program will average a list of images or volumes passed in on the command-line
### average.py <vol1.mrc> <vol2.mrc> ...
### will produce average.hdf
### All inputs must have the same dimensions

from EMAN2 import *
from sys import argv

av=EMData(argv[1],0)
for i in argv[2:]:
        im=EMData(i,0)
        av.add(im)

av.mult(1.0/(len(argv)-1))
av.write_image("average.hdf",0)
```
I have checked it could take one or more mrcs/mrc file and works well in the command line.

**Comment by phonchi** [comment]
I just found that since I am using the EMAN2 's module, it may be conflicted with scipion's python module.

Should I change the related environment variable like the [example](https://github.com/I2PC/scipion/blob/master/pyworkflow/em/packages/eman2/eman2.py)?

**Comment by pconesa** [comment]
What happens if you return None in the _validate, or don't implement it?

**Comment by phonchi** [comment]
Thanks, it works!! If I return None or an empty list in the _validate method it will execute (the directory is also created) and only leave the EMAN2 problem. So the problem is that it will prevent the job from execution if the return list is non-empty (meaning that the input has some errors).

By the way, do you have any suggestions about including the EMAN2 library?

**Comment by pconesa** [comment]
Great! So what are you getting now? Any error message in the log/console?

**Comment by phonchi** [comment]
If I am using the #!/usr/bin/env python in the script (In my understanding, in this case, it will use  scipion's internal python interpreter), it can not find the EMAN2 modules.  Bu If I specify the python interpreter in the script (#!/home/aaa/EMAN2/bin/python)  it will show the following message:

```
Traceback (most recent call last):
  File "/home/aaa/scipion/software/em/stats328/average.py", line 8, in <module>
    from EMAN2 import *
  File "/home/taaa/EMAN2/lib/python2.7/site-packages/EMAN2.py", line 44, in <module>
    from EMAN2_cppwrap import *
  File "/home/aaa/EMAN2/lib/python2.7/site-packages/EMAN2_cppwrap.py", line 47, in <module>
    from libpyTypeConverter2 import *
ImportError: numpy.core.multiarray failed to import
```

My guess is that it is conflicted with the scipion's internal python interpreter. Should I change the related environment variable like the [example](https://github.com/I2PC/scipion/blob/master/pyworkflow/em/packages/eman2/eman2.py)? Or any other suggestion to call external python pakages that has its own dependnet package (and maybe different from the one in scipion)?

**Comment by delarosatrevin** [comment]
Hi @phonchi,

I think you guess is right, if you want to launch an EMAN2 process, you
should setup the environment such in those protocols.

The other issue that looks problematic is that you were returning a ['']
list in the validate method, which mean an error (with no message).
You should return instead an empty list [].

Hope this helps,
Best.

**Comment by phonchi** [comment]
Thanks for the help!! Now it executes without any problem!

**Comment by phonchi** [comment]
Just curious about if there is any way to add python modules to scipion's internal python packages. 

It seems like that we have to add python modules inside `scipion/install/script.py` using `env.addModule` and by default, it will download from `http://scipion.cnb.csic.es/downloads/scipion/software/` .  How do I add other modules from PyPI and how do I manage the dependency (Since there seems scipion's Python doesn't ship with pip)

Thanks in advance!

**Comment by pconesa** [comment]
Yes...depending on which branch are you in. In "devel" and in release-1.1.facilities (<- current 1.2.beta) you can install pip doing:

`scipion run scripts/get-pip.py`

Then you can use pip within scipion this way:
`scipion run pip list`
 or install things.

**Comment by pconesa** [comment]
if you are in master you must put the get-pip.py script somewhere and run the same command pointing to your get-pip.py script.

**Comment by phonchi** [comment]
I am in the master, and I put the get-pip.py in the scripts then run `scipion run scripts/get-pip.py`.

It will show the following errors:

```
pip is configured with locations that require TLS/SSL, however the ssl module in Python is not available.
Collecting pip
  Could not fetch URL https://pypi.python.org/simple/pip/: There was a problem confirming the ssl certificate: Can't connect to HTTPS URL because the SSL module is not available. - skipping
  Could not find a version that satisfies the requirement pip (from versions: )
No matching distribution found for pip
```

Any suggestion is appreciated, thanks!

**Comment by pconesa** [comment]
ummm,....which OS are you running....did you get any scipion installation error?

Google tells me [this](https://medium.com/@moreless/pip-complains-there-is-no-ssl-support-in-python-edbdce548852)

To trigger the compilation of scipion python, I've done this:
`rm -rf software/bin/python* software/lib/python2.7`
and then 
`scipion install -j 4`

Seems to work and make sense, but is the first time I think about this. If anyone can confirm this I'ld feel reassured, ;-)

**Comment by phonchi** [comment]
Thanks again for the reply. I am using Ubuntu 16.04, I do not face any problem since I am using the binaries.

I have tried the commands you provide, and now I am able to install pip. However, I faced the following error when I trying to open GUI:

```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/aaa/scipion/software/lib/python2.7/lib-tk/Tkinter.py", line 39, in <module>
    import _tkinter # If this fails your Python may not be configured for Tk
ImportError: No module named _tkinter
```

Any ideas?

**Comment by pconesa** [comment]
I wrongly supposed you were using the source code version or even getting the code from github....
How do you feel about "reinstaling" Scipion....I feel it would be faster than fixing this.

**Comment by phonchi** [comment]
Um~ you mean reinstalling from source instead of using the binaries?

**Comment by pconesa** [comment]
yep?....I do not understand what is wrong now, since tk should be already installed at software/lib/tk8.6

**Comment by phonchi** [comment]
Sure, I will try to install from source, thanks!

**Comment by phonchi** [comment]
I have built from source and now pip command is ok. (I am now in the master v1.1)

However, when I run the mix and match tutorial I encounter the issue describe [here](https://github.com/I2PC/scipion/issues/1040) .

How should I deal with this problem?

**Comment by phonchi** [comment]
It seems that it is not always failed when I restart it is ok now.

Anyway, this is not related to the original question.

Thanks again for all the help, and I will keep exploring this great project!

**Comment by pconesa** [comment]
Thanks, @phonchi , you know where to find us!
