### ISSUE TITLE
xmipp_correct_bfactor

### ISSUE THREAD

**Issue by carmensmp** [I2PC/scipion#1442]
could a protocol be created for running xmipp_correct_bfactor?

**Comment by Vilax** [comment]
Hi Carmen

you can perform the b-factor correction with the protocol resolution 3D. This protocol runs internally  xmipp_correct_bfactor.

Regards

Vilas

**Comment by pconesa** [comment]
can  we close this?

**Comment by carmensmp** [comment]
Yes

  -------------------------------------------------------------
  Carmen San Martín, Ph. D.
  Centro Nacional de Biotecnología (CNB-CSIC)
  Darwin, 3
  28049-Madrid (SPAIN)
  Email:  carmen@cnb.csic.es
  Phone:  34-91-5855450
  Fax:     34-91-5854506 <http://www.cnb.csic.es/>
  http://tinyurl.com/carmensanmartinlab
  https://sites.google.com/site/adenonet/
  ------------------------------------------------------------
