### ISSUE TITLE
copy pngs to imgShiftThumbs in ProtMonitorSummary instead of symbolic links?

### ISSUE THREAD

**Issue by andreanans** [I2PC/scipion#1443]
Hi,

I've just started testing the new version of the Monitor Summary on our system and it's working well. I noticed that the pngs for imgMicthumbs and imgPsdThumbs files are copied to the ProtMonitorSummary/extra/project folder but symbolic links are used for imgShiftThumbs. It would be very useful if the png files for imgShiftThumbs were also copied since we upload the scipion project directory to a different destination and the symbolic links are broken. Thanks!

**Comment by pconesa** [comment]
Great! How likely can you use rsync with the flag to follow links. At CNB
this is also done and work fine..basically save some little space.

**Comment by pconesa** [comment]
-L flag will do it

**Comment by andreanans** [comment]
Hi,

Thanks for the pointer. However wouldn’t rsync -L also copy the imported movies which we definitely wouldn’t want to do?

Andrea

**Comment by pconesa** [comment]
Hi,
>
> Thanks for the pointer. However wouldn’t rsync -L also copy the imported
> movies which we definitely wouldn’t want to do?
>
> Andrea
>
>
I was assuming you were copying only the HTML folder, there, there are only
thumbnails of the micrographs...are you copying the whole project?

If so, I believe there is also a way to exclude files in rsync:

https://askubuntu.com/questions/320458/how-to-exclude-multiple-directories-with-rsync

Does this help?

**Comment by andreanans** [comment]
We routinely copy the entire project folder. I will just manually copy the
pngs at the end of the pre-processing session as I do not want complicate
it further with rsync. Thank you for the helpful pointers.

Best

Andrea

**Comment by azazellochg** [comment]
I also agree that it is a bit strange to copy everything except shift plots.... can this be done as option in summary protocol? (either copy everything or create symlinks)

**Comment by andreanans** [comment]
Hello,

I found a solution to my problem and now Scipion copies the imgShift thumbnail to my monitor summary folder instead of creating a symbolic link. The file to edit is report_html.py in pyworkflow/em/protocol/monitors

I added this at the beginning of the file:

from shutil import copy

find the following line (it should be line 238)

pwutils.createAbsLink(self.thumbPaths[SHIFT_PATH][i], dstImgPath)
 
replace pwutils.createAbsLink with copy

Hope this helps,

Andrea

**Comment by pconesa** [comment]
Nice Andrea, that will copy the pngs....do you think that should be the
default and only behaviour....we are always trying to save space and might
become obsessive here. What others think?

**Comment by azazellochg** [comment]
Yes, I want copies.

**Comment by delarosatrevin** [comment]
We try (in most cases) to avoid data duplication. Nonetheless, the png's files are not what count most in the final project size (probably negligible)...and, on the other side, other pngs (or display images) are copied..and since this is a report, maybe it make sense to make copies to make it non-dependent on sym-links

**Comment by yaizar** [comment]
Ok, since this is a small fix and there's another bug in the summary because of eman's pluginization I'll add it to pluginization-fixes.
