### ISSUE TITLE
test new patch of motioncor2

### ISSUE THREAD

**Issue by pconesa** [I2PC/scipion#1444]
"We have released two compiled versions of MotionCor2_1.0.5, one for Cuda 8.0 and one for Cuda 9.1. This version fixed the bug in version 1.0.4 reported by some users. We really appreciate your contributions that help us continuously improve MotionCor2."

**Comment by azazellochg** [comment]
here we could add new params to GUI:  a third field for patch params (patch X Y Overlap) and dark reference correction

**Comment by delarosatrevin** [comment]
I have downloaded the version 1.0.5 of motioncor and it seems to work. I just created the same folder structure to follow our conventions. @pconesa should we add this facilities-devel? @azazellochg, someone around here also asked about the patch overlap argument, so we could add it in the same bag. ;)

**Comment by pconesa** [comment]
haven't add that parameter....

**Comment by pconesa** [comment]
Hi! Documentation say tha patch overlap is new  but we already have it from 1.0.1....is that rigth?

**Comment by azazellochg** [comment]
ehm, there is no patch overlap parameter in fixes/devel branch now. We only have patchX and patchY

**Comment by delarosatrevin** [comment]
I fixed a bug related to that option....I stupidly added a function isLatestVersion...(meaning 1.0.1 at that time) and then the option was not shown when 1.0.2 appeared. 

Fixed in commit 530a324550825340cfdab2b131d584692e99a79d
