### ISSUE TITLE
Optical flow missing in 1.2-beta?

### ISSUE THREAD

**Issue by JuhaHuiskonen** [I2PC/scipion#1448]
Hi, I installed 1.2-beta. we're running relion13 betagal tutorial.  However we noticed that movie alignment fails, and this is because xmipp_movie_optical_alignment_cpu program is not in the software/em/xmipp/bin folder.  Scipion did install without any errors

**Comment by delarosatrevin** [comment]
Hi @JuhaHuiskonen, can you check if the OpenCV option is set to True in the scipion/config/scipion.conf file? xmipp_movie_optical_alignment_cpu depends on OpenCV and if it False it will not be compiled. If it is False and you change it to True, you will need to launch the ./scipion install command again (hopefully only will install the missing part).

**Comment by JuhaHuiskonen** [comment]
you're right @delarosatrevin OpenCV installation hadn't worked so I had compiled with option --no-opencv. If I try to install it this is what happens:

[ 14%] Building CXX object modules/highgui/CMakeFiles/opencv_highgui.dir/src/grfmt_jpeg2000.cpp.o
In file included from /usr/include/jasper/jasper.h:77:0,
                 from /wrk/project_cryoem/apps/taito-gpu/scipion-1.2.beta/software/tmp/opencv-2.4.13/modules/highgui/src/grfmt_jpeg2000.cpp:58:
/usr/include/jasper/jas_math.h: In function âbool jas_safe_size_mul(size_t, size_t, size_t*)â:
/usr/include/jasper/jas_math.h:143:15: error: âSIZE_MAXâ was not declared in this scope
  if (x && y > SIZE_MAX / x) {
               ^
/usr/include/jasper/jas_math.h: In function âbool jas_safe_size_add(size_t, size_t, size_t*)â:
/usr/include/jasper/jas_math.h:170:10: error: âSIZE_MAXâ was not declared in this scope
  if (y > SIZE_MAX - x) {
          ^
make[2]: *** [modules/highgui/CMakeFiles/opencv_highgui.dir/src/grfmt_jpeg2000.cpp.o] Error 1
make[1]: *** [modules/highgui/CMakeFiles/opencv_highgui.dir/all] Error 2
make: *** [all] Error 2

**Comment by delarosatrevin** [comment]
Do you have OpenCV (and it devel ) libraries installed in your system? It is a huge library with many dependencies...so if you can install in the standard way, we could workaround the Scipion install script to use it instead of compiling from scratch. See the related issue #1445 .

**Comment by pconesa** [comment]
@JuhaHuiskonen , is this solved?

**Comment by JuhaHuiskonen** [comment]
yes. opencv compilation had failed

**Comment by pconesa** [comment]
Thanks!
