### ISSUE TITLE
html report

### ISSUE THREAD

**Issue by rmarabini** [I2PC/scipion#1451]
html report fails when non standard numbers are found. The following CTF values (see scipionbox:Offloaddata/carmen_kr5_cryp10_centrl2g) produce an error in html report. The offending line is

defocusU = 21250
defocusV = 21250
defocus_angle=-10282286687
ratio=1
reslution=inf <---------
fitQuality=0

My guess is that resolution=inf is not process properly.

Error returned by protocol: An Error hapend: float argument required not Nontype
Consequences: no html file is produced

**Comment by rmarabini** [comment]
I have been checking the file in which ctf_monitor  temporary store CTF ( "ctf_log.sqlite") and I see that instead of saving the new CTFs all ctfs are saved in each refresh. This is bad.

   Roberto

**Comment by rmarabini** [comment]
By the way, I understand that the version that handles resolution in CTF is in devel and not in release-1.1.facilities level although a cherry pick it to scipionbox scipion.

**Comment by pconesa** [comment]
Nope, facilities has the resolution in the CTF model if this is what you
are referring

**Comment by rmarabini** [comment]
I think I fixed this (I close the issue)
