### ISSUE TITLE
implement ctf estimation on movies with ctffind4

### ISSUE THREAD

**Issue by azazellochg** [I2PC/scipion#146]
CTFFIND4 allows to do this now on unaligned or aligned frame stacks. The input stack file has to have an .mrc extension (mrcs is currently not recognized by ctffind4).

I think this would be a beneficial enhancement for the ctf estimation protocol.

**Comment by delarosatrevin** [comment]
Have you use it with movies? What is your experience with this approach? 
I read in ctffind4 website that they recommend to use this if you do not trust in the movie alignment.
From which version this is available? There is any changes in the command line respect with 
the estimation for micrographs?

**Comment by azazellochg** [comment]
A while ago we were testing different schemes of ctf correction on several unsupported data sets from Falcon II. We have compared CTFs from unaligned/aligned (by motioncorr or unblur) stacks/sums and for us ctffind4 worked best on unaligned frames. Though I agree, this results will strongly depend on movie collection strategy (dose per frame etc.). 

I guess this option was always available for ctffind4..

There are 2 more input options that should be inserted after [this line](https://github.com/biocompwebs/scipion/blob/v1.0/pyworkflow/em/packages/grigoriefflab/protocol_ctffind.py#L252):
>Input is a movie (stack of frames)             [y]                                                                       
>Number of frames to average together           [1]

PS. Input movie file name should be .mrc and not .mrcs. But if all movies within scipion are recognized by .mrcs suffix, a simple symlink with mrc extension will work for ctffind4.
