### ISSUE TITLE
No-Dim when saving a SetOfParticles while streaming

### ISSUE THREAD

**Issue by JuhaHuiskonen** [I2PC/scipion#1465]
I am extracting (relion - particle extraction) in streaming mode. The output set of particles doesn't have a dimension (No-Dim), presumably as the number of particles is unknown.  However, if I open this set, and save a new set with all the particles that it contains, the new set still shows No-Dim.  Could this be changed so that it would show the correct dimensions? Then it would be possible to start e.g. 2D classification for those particles that are already available.

**Comment by pconesa** [comment]
Thanks Juha, Josue identified that just few days ago, I think is fixed,
maybe un facilities-fixes waiting to land on facilities branch.

**Comment by JuhaHuiskonen** [comment]
I am using 1.2 beta - is there any workaround in the meanwhile @pconesa?

**Comment by pconesa** [comment]
Not sure an easy one, let me talk to Josue and get back to you on Monday

**Comment by pconesa** [comment]
@JuhaHuiskonen , Is your installation done through git?
If it is urgent.....checkout:
git checkout  release-1.1.facilities-fixes
You might need to rerun the protocol. 

If not that urgent we plan to merge it to release-1.1.facilities this afternoon.

**Comment by JuhaHuiskonen** [comment]
No it's not from git - I downloaded the 1.2 beta release

**Comment by delarosatrevin** [comment]
Hi @JuhaHuiskonen 
I just wrote a simple script to fix (in case of No-dim) the dimensions of a give outputParticles. It is not our standard way to modify manually the database, but I think here it can be useful and avoid you to re-run the protocol.
You can find the script here:
https://github.com/I2PC/scipion-scripts/blob/master/particles_fixdim.py

Before running it, make a copy of the project.sqlite just in case.
And then run:
scipion python particles_fixdim.py ProjectName ProtId
Where ProjectName is the desired project and ProtId the protocol with the output to be fixed, make sure it has 'outputParticles'. 

The 1.2beta release is taken from the release-1.1.facilities branch, so in the long term it would be better for you to use git and stay updated.

**Comment by pconesa** [comment]
thanks @delarosatrevin

**Comment by pconesa** [comment]
Can we close this then?

**Comment by JuhaHuiskonen** [comment]
I tested it and it works @pconesa
