### ISSUE TITLE
xmipp reconstruct_fourier protocol does not use 'Extra paramters'  

### ISSUE THREAD

**Issue by 1aviervargas** [I2PC/scipion#1466]
I have try to correct CTF information with --useCTF but the command created is not using the flag --useCTF

![image](https://user-images.githubusercontent.com/12271201/36076482-a26612b2-0f2a-11e8-835c-9ca4fa29855e.png)

**Comment by dmaluenda** [comment]
I fix it in devel-fixes branch [commit: 315bca5309eb158962ed5dbcc9ac0a5af0312309].

**Comment by pconesa** [comment]
can we close this?
