### ISSUE TITLE
Error in convertInputStep in Relion

### ISSUE THREAD

**Issue by 1aviervargas** [I2PC/scipion#1467]
The .star created is incorrect. Only the first row has rlnVoltaje, rlnAmplitudeContrat, rlnSphericalAberration  different from zero. Big bug... there is no any test about this... really surprised... Devel branch

![image](https://user-images.githubusercontent.com/12271201/36076628-ba24633e-0f2c-11e8-84de-298c428f58ac.png)

**Comment by 1aviervargas** [comment]
No worries... I am seeing that maybe is a problem of the protocol that register in the database...

**Comment by pconesa** [comment]
Hi @1aviervargas , could you please elaborate a bit more. Have you seen this in a test. Is something coming from your development?

**Comment by 1aviervargas** [comment]
Sure... I have been doing tests and I think that now I can explain a little
bit more the problem and maybe the reasons.

I did the following test that is reproducible:

1) I run the test of enrich:

scipion test
tests.em.protocols.test_protocol_volume_homogenizer.TestVolumeHomogenizer

Everything went well. I checked that the particles .sqlite has ctf
information including voltage, magnification, shericalAberration....

2) From this particles I run Relion autorefine. The input_particles.star
created in the protocol folder has incorrect CTF values. (see imaged
attached).

Any idea...

Best regards
Javier


[image: Inline images 1]

**Comment by 1aviervargas** [comment]
Hi Pablo,

I think I fix my problem but this maybe is a potential problem for other
developers. In the homogeneizer protocol the createOutputStep was like this:

            fnDeformedParticles =
self._getExtraPath('deformed_particles.xmd')
            outputSetOfParticles = self._createSetOfParticles()
            readSetOfParticles(fnDeformedParticles, outputSetOfParticles)

outputSetOfParticles.copyInfo(inputParticles)
            self._defineOutputs(outputParticles=outputSetOfParticles)


I just changed to this and everything seems to work:

            fnDeformedParticles =
self._getExtraPath('deformed_particles.xmd')
            outputSetOfParticles = self._createSetOfParticles()
outputSetOfParticles.copyInfo(inputParticles)
            readSetOfParticles(fnDeformedParticles, outputSetOfParticles)

            self._defineOutputs(outputParticles=outputSetOfParticles)

Best
Javier

**Comment by pconesa** [comment]
So, you the 
` outputSetOfParticles.copyInfo(inputParticles)`
did the magic?

**Comment by 1aviervargas** [comment]
Just changing the order... first copy

**Comment by pconesa** [comment]
Can we close this then?

**Comment by 1aviervargas** [comment]
Hi Pablo,

Not sure about this... see my previous posts. In a protocol if you do
readSetOfParticles before copyInfo then you will find this problem in the
input.star, probably in more places as well...Maybe this is saying
something...

Best regards
Javier

**Comment by josuegbl** [comment]
@1aviervargas, I recomend you use copyItems  function instead of readSetOfParticles. readSetOfParticles does not transmit the info beyond xmipp labels, and your particles may have it (for instance, certain specific Relion Labels). There are several case of use of these function.
