### ISSUE TITLE
protocol xmip_preprocess particles

### ISSUE THREAD

**Issue by 1aviervargas** [I2PC/scipion#1468]
Normalization type seems not be OK. Selected "NewXmipp" actually used "Ramp". Branch devel

![image](https://user-images.githubusercontent.com/12271201/36077382-1fd2ca1c-0f38-11e8-98c2-acf0c449c1af.png)

**Comment by dmaluenda** [comment]
It was a bug. I fixed it in devel-fixes branch [commit: ea769b978abcd72f2556f2b34c3c1a9e34350e37].

Thank you Javier!!
