### ISSUE TITLE
Xmipp compile error

### ISSUE THREAD

**Issue by Sktewarybt1993** [I2PC/scipion#1472]
Hi 

I am trying to compile the Xmipp using the Scipion but I am getting some errors

Compiling Xmipp ...
install/scons.py 
Keeping existing file: /Applications/Software/scipion1.1/software/em/xmipp/xmipp.bashrc
Keeping existing file: /Applications/Software/scipion1.1/software/em/xmipp/xmipp.csh
Keeping existing file: /Applications/Software/scipion1.1/software/em/xmipp/xmipp.fish
scons: Reading SConscript files ...
Mkdir("/Applications/Software/scipion1.1/software/em/xmipp/java/build")
scons: done reading SConscript files.
scons: Building targets ...
scons: `software/lib/libXmippAlglib.so' is up to date.
scons: `software/lib/libXmippBilib.so' is up to date.
scons: `software/lib/libXmippCondor.so' is up to date.
scons: `software/lib/libXmippDelaunay.so' is up to date.
scons: `software/lib/libXmippSqliteExt.so' is up to date.
g++ -o software/em/xmipp/external/gtest/gtest-all.os -c -O3 -fPIC -Isoftware/em/xmipp/external -Isoftware/em/xmipp/libraries -Isoftware/include software/em/xmipp/external/gtest/gtest-all.cc
In file included from software/em/xmipp/external/gtest/gtest-all.cc:39:
software/em/xmipp/external/gtest/gtest.h:1561:13: fatal error: 'tr1/tuple' file not found
#   include <tr1/tuple>  // NOLINT
            ^~~~~~~~~~~
1 error generated.
scons: *** [software/em/xmipp/external/gtest/gtest-all.os] Error 1
scons: building terminated because of errors.

Please suggest what to do next.

**Comment by dmaluenda** [comment]
Hi, thanks for your comment.

Could be that you are trying to install it on Mac OsX?? So far, we only support Linux (Ubuntu, OpenSuSE, Fedora).

**Comment by pconesa** [comment]
I would say Scipion can run in other linux distros that the 3 above, like CentOS, Redhat,....but we haven't done the exercise of going through "all" of them.
