### ISSUE TITLE
openCV compile error (from #1464)

### ISSUE THREAD

**Issue by azazellochg** [I2PC/scipion#1473]
From @sktewary 
> Hi i am getting error while compiling the Scipion on my macbook.
> Please give suggestions to fix this.
> 
> Building opencv ...
> Skipping command: wget -nv -c -O software/tmp/opencv-2.4.13.tgz.part http://scipion.cnb.csic.es/downloads/scipion/software/external/opencv-2.4.13.tgz
> mv -v software/tmp/opencv-2.4.13.tgz.part software/tmp/opencv-2.4.13.tgz
> All targets exist.
> Skipping command: tar -xzf opencv-2.4.13.tgz
> All targets exist.
> Skipping command: cmake -DWITH_FFMPEG=OFF -DWITH_CUDA:BOOL=OFF -DCMAKE_INSTALL_PREFIX:PATH=/Users/sunil/CryoEM/scipion/software .
> All targets exist.
> cd software/tmp/opencv-2.4.13
> make -j 2 > /Users/sunil/CryoEM/scipion/software/log/opencv_make.log 2>&1
> cd software/tmp/opencv-2.4.13
> make install > /Users/sunil/CryoEM/scipion/software/log/opencv_make_install.log 2>&1
> Error: target 'software/lib/libopencv_core.dylib' not built (after running 'make install > /Users/sunil/CryoEM/scipion/software/log/opencv_make_install.log 2>&1')

**Comment by pconesa** [comment]
This is duplicated?

**Comment by azazellochg** [comment]
I guess this is similar to #1472 , since we don't support Macs at the moment
