### ISSUE TITLE
Re-running motioncorr on failed images from FAILED_all.txt file?

### ISSUE THREAD

**Issue by andreanans** [I2PC/scipion#1474]
It's great that Scipion now creates a list of movies where motioncorr failed (FAILED_all.txt). It would be very convenient if there was a quick way to create a subset containing the failed movies so we can run motioncorr on them again. Currently the only way is to manually create the subset from the imported movies.

**Comment by pconesa** [comment]
May be, this could be extended to all movie alignment protocols, to generate a set of failed movies?

**Comment by delarosatrevin** [comment]
I will propose not to create the set of failed movies by default, which maybe the user does not want it...but to easily allow the user to generate the set of FAILED (from the Analyze Results) and then do any further processing with it. 

Thanks for the feedback @andreanans

**Comment by azazellochg** [comment]
to be addressed here: https://github.com/scipion-em/scipion-em-motioncorr/pull/19
