### ISSUE TITLE
Investigate how to create a pip module for scipion plugins

### ISSUE THREAD

**Issue by ldelcano** [I2PC/scipion#1480]

**Comment by delarosatrevin** [comment]
And for Scipion itself... ;)

**Comment by ldelcano** [comment]
Created a test module for eman2, using yaiza's branch devel_pluginize_config.
It is uploaded to PyPI at https://pypi.python.org/pypi/test-scipion-eman-plugin and can be installed with 
pip install test-scipion-eman-plugin 
at the usual location or with
pip install --target $SCIPION_HOME/pyworkflow/em/packages test-scipion-eman-plugin

**Comment by ldelcano** [comment]
To discover modules at PyPI run for instance:
pip search scipion
test-scipion-eman-plugin (1.0.1)  - An Eman plugin for Scipion project
  INSTALLED: 1.0.1 (latest)

If Scipion is also a PyPI module then we could maybe use a different discovery plugins system (https://setuptools.readthedocs.io/en/latest/setuptools.html#dynamic-discovery-of-services-and-plugins)
