### ISSUE TITLE
Update labels in relion - mask creation protocol

### ISSUE THREAD

**Issue by delarosatrevin** [I2PC/scipion#1482]
Now the mask creation is a separated protocol in Relion...it is missing from Scipion.

![image](https://user-images.githubusercontent.com/8441688/36250809-2dce47cc-123f-11e8-8cf6-022edb479073.png)

@pconesa Should we add this to the release? or postpone it?

**Comment by josuegbl** [comment]
@delarosatrevin, are you proposing something like this:
![image](https://user-images.githubusercontent.com/12274357/36251548-e19b00c2-1241-11e8-8838-d622481d2897.png)
👅

**Comment by delarosatrevin** [comment]
Oopss! I'm having so many surprises these days of works already done!!!
Yes, I was talking about this. Nonetheless, the labels should be updated to 
be more close to the ones in Relion.

Thanks @josuegbl

**Comment by pconesa** [comment]
Let's leave it for the next one...this is a neverending story!

**Comment by delarosatrevin** [comment]
Solved in delarosatrevin/scipion@596933a
