### ISSUE TITLE
Update particle subtraction protocol from Relion 2.x

### ISSUE THREAD

**Issue by delarosatrevin** [I2PC/scipion#1483]
We have some differences with the particles subtraction protocol in Relion

![image](https://user-images.githubusercontent.com/8441688/36250875-7326148a-123f-11e8-9278-3f53b6c92264.png)

@pconesa , the same question...release 1.2 or not?

**Comment by pconesa** [comment]
Nope! ;-), unless it is very importatn and you want to doit.....I know the risk is almost 0 in changing a label.

**Comment by delarosatrevin** [comment]
Ok, let's postpone them...I will fix them here locally. ;)

**Comment by delarosatrevin** [comment]
I think our labels are fine (more consistent with our naming in Scipion) and easily inferred by users. The extra options are just a twisted way of Relion to switch image path in star files. We don't need this option since we have a more general subset mechanism.
