### ISSUE TITLE
Xmipp Particle Crop fails

### ISSUE THREAD

**Issue by pconesa** [I2PC/scipion#1494]
Cropping particles fail when converting CTF model to xmipp row.
It is failing because the ctf has a PhaseShift set to null. ShowJ change it to 0.000 but xmipp convert does not do that and fails:

> ERROR:  Protocol failed: float() argument must be a string or a number

**Comment by pconesa** [comment]
The issu here is....should the CTF have PhaseShift or not and if it should be None or 0?

**Comment by pconesa** [comment]
this is taking a different direction now...
Turns out that in the xmipp convert we are trying to convert the "_phaseShift" value that is coming with None. Actually, the fix is quite simple....remove the "_phaseShift" from the convert, since, at least in this release Xmipp does not use this value.

```
CTF_DICT = OrderedDict([
       ("_defocusU", xmipp.MDL_CTF_DEFOCUSU),
       ("_defocusV", xmipp.MDL_CTF_DEFOCUSV),
       ("_defocusAngle", xmipp.MDL_CTF_DEFOCUS_ANGLE),
       #("_phaseShift", xmipp.RLN_CTF_PHASESHIFT),
       ("_resolution", xmipp.MDL_CTF_CRIT_MAXFREQ),
       ("_fitQuality", xmipp.MDL_CTF_CRIT_FITTINGSCORE)
       ])

```

Looking at this we have discovered that relion's convert is ignoring this value.....

```
CTF_DICT = OrderedDict([
       ("_defocusU", md.RLN_CTF_DEFOCUSU),
       ("_defocusV", md.RLN_CTF_DEFOCUSV),
       ("_defocusAngle", md.RLN_CTF_DEFOCUS_ANGLE)
       ])
```
Therefore...values in the "_phaseShift" attribute of our CTFObject are not converted to relion metadata.

The questions are:

1.- Will ignore the _phaseShift in xmipp convert be correct?
2.- Shouldn't we convert this value in the case of relion? And if so...then
3.- Is it correct to assume that in our model a _phaseShift = None means no _phaseShift and therefore not convert it to Relion?

@delarosatrevin , @azazellochg , @rmarabini , @josuegbl ....feedback please?

**Comment by rmarabini** [comment]
I guess _phaseShift is related with volta phase plates. Am I correct? If
this is the case keep it for later use makes sense.


                  Roberto

**Comment by azazellochg** [comment]
I have added phase shift (so I am the one to blame :), but apparently missed how it is used/not used/converted in xmipp.  In relion convert there is conversion, so it is passed to relion. I have tried to keep the value 0.0 if it is not set (ctf protocols etc)
```
CTF_EXTRA_LABELS = [   
    ...
    md.RLN_CTF_PHASESHIFT,
```
The only place it is set to 0.0 by default in xmipp is [here](https://github.com/I2PC/scipion/blob/release-1.1.facilities-fixes/pyworkflow/em/packages/xmipp3/convert.py#L651)

**Comment by pconesa** [comment]
no worries @azazellochg , only people that do nothing, do not make mistakes!! ;-)

That md.RLN_CTF_PHASESHIFT, only works if the phaseshift is present as a extra param....comming from a relion CTF estimation , but if the ctf data is in our CTFModel as ctfModel._phaseShift  this is not taken into account.

**Comment by pconesa** [comment]
@azazellochg , do you know what is needed for relion....if there isn't  phaseShift......fiel should not be there or a phaseShift = 0.0 is valid?

**Comment by azazellochg** [comment]
@pconesa in relion rlnPhaseShift is not added to star files if it is None: [here](https://github.com/I2PC/scipion/blob/release-1.1.facilities-fixes/pyworkflow/em/packages/relion/protocol_base.py#L1201) It is also set to zero inside relion if it is absent, so it does not matter.

**Comment by azazellochg** [comment]
Also, I thought there is option in xmipp ctf estimation to look for phase shift, no?

**Comment by pconesa** [comment]
I think this might be in devel....yes there we need to consider the phaseShift but I'm now focused on the release

**Comment by azazellochg** [comment]
Right, in this case ignoring phaseShift in xmipp convert looks reasonable.
