### ISSUE TITLE
powerfit fails

### ISSUE THREAD

**Issue by mmmtnez** [I2PC/scipion#1498]
Has somebody changed powerfit package?. Now it has the line

        # Symmetry and non-rectangular boxes are not supported.
        error = (self.header['ispg'] != 1 or
                self.header['alpha'] != self.header['beta'] !=
                self.header['gamma'] != 90)

Since no MRC file has ispg set properly this is never satisfied and produces and error. Note that ispg is the crystallographic symmetry so for single particle should be  always P1 (even for symmetric samples) but no program fill the header properly. I think this "if" should be removed. We tried it and the program worked properly.

**Comment by pconesa** [comment]
@mmmtnez could you investigate this, please.

**Comment by mmmtnez** [comment]
Investigate what?

**Comment by pconesa** [comment]
Why the change? Or if you are sure about the fix, then fix it, please.

**Comment by pconesa** [comment]
Hi @mmmtnez , can I close this issue?

**Comment by pconesa** [comment]
Solved with a new tgz.
