### ISSUE TITLE
Problems doing scipion-subset intersection 

### ISSUE THREAD

**Issue by rsanchezgarc** [I2PC/scipion#1507]
I have done the intersection of a setOfParticles and a set OfCoordinates and the output setOfParticles was  nonsense, being particles of other intersection protocol run. I suppose that intersections of different type of objects may not be supported, but, in this case, some assertion should be done.

**Comment by pconesa** [comment]
Hi @rsanchezgarc , I've tried your case and is working fine. Code assumes this case and matching is done based only on the id, so, as long as the coordinate id matches the particle id, it should pass.

I'm closing this. Reopen it if you still see this happening and let me know more details.
