### ISSUE TITLE
MicName contains spaces

### ISSUE THREAD

**Issue by ldelcano** [I2PC/scipion#1522]
When importing a micrograph which name contains spaces they are removed from filename but not from micname. 
For some reason protocol RelionClassify2D tries to use micname and fails.
1. micname should be formed as last part of filename (no spaces, no duplicates).
2. Why is relion classify using micname to open an image?

**Comment by ldelcano** [comment]
ProtImportImages was modified to remove spaces from filename only for normal operation mode but not from streaming mode. Apparently Scipion workflow tolerates white spaces on filename, so focus on relion classify protocol and why is using micname instead of filename.

**Comment by ldelcano** [comment]
Error is on image.h from relion:
00035:   ERROR: 
00036:   Cannot read file 29kx.tif' It does not exist
00037:   File: /opt/scipion/software/em/relion-2.0.4/src/image.h line: 157

the star file created for relion contains spaces on  _rlnMicrographName, which is probably the problem.
# XMIPP_STAR_1 * 
# 
data_Particles
loop_
 _rlnEnabled
 _rlnCoordinateX
 _rlnCoordinateY
 _rlnMicrographName
 _rlnMicrographId
 _rlnImageId
 _rlnImageName
 _rlnDefocusU
 _rlnDefocusV
 _rlnDefocusAngle
 _rlnAmplitudeContrast
 _rlnSphericalAberration
 _rlnVoltage
 _rlnGroupName                                                                                                                                                                                  
1  2868.000000  1476.000000 '1C - 01 29kx.tif'                    1                    1 000001@Runs/000222_ProtRelionClassify2D/extra/1C-0129kx.mrcs  4006.243164  3718.075928   112.430509    
 0.100000     2.000000   200.000000 1

**Comment by ldelcano** [comment]
Comparing the particle star file created from Scipion with a particles.star created with Relion seems clear that _rlnMicrographName should point to the file existing under relion working dir (Runs extra on Scipion projects) and therefore should not have spaces (symlinks on Scipion are created without spaces). Change relion convert to solve this.

**Comment by ldelcano** [comment]
convertInputStep on relion extract particles is writing a 'good' _rlnMicrographName on input_micrographs.star ('extra/1C-0129kx.mrc') while convertInputStep on relion classify 2D is writing a 'bad' _rlnMicrographName on input_particles.star ('1C - 01 29kx.tif'). Is it because of the 'format conversion'?

**Comment by ldelcano** [comment]
@josuegbl , I am looking at this problem, do you, as Relion expert, have a clue if the problem is ours or is it Relion that does not like spaces on micrograph names?

**Comment by azazellochg** [comment]
@ldelcano I will look into this on the WE :)

**Comment by ldelcano** [comment]
@azazellochg if you need help reproducing it or a project where this happens let me know. 
The problem comes from the import micrographs, where the micName keep the spaces (while symliks pointing to mics do not)

**Comment by azazellochg** [comment]
@ldelcano thanks! I have actually discovered this bug today with another user :) os, I do have data to reproduce it.

**Comment by azazellochg** [comment]
Alright, so in relion classify convertInput, the following fucntion will insert the spaces:
```
    if coord.getMicName():
        coordRow.setValue(md.RLN_MICROGRAPH_NAME, str(coord.getMicName()))
```
While in relion extract: 
`imgRow.setValue(imgLabel, locationToRelion(index, filename))`, where imgLabel=RLN_MICROGRAPH_NAME and filename=img.getFileName() so there are no spaces introduced.
I guess as @ldelcano suggested, the solution would be to remove whitespaces from micName in both streaming and normal mode upon import.

**Comment by pconesa** [comment]
ok, I see your point, I was only surprised why extract can do it but not other relion protocols, taking into account that probably the one "critically uses" the micrograph is the one that copes with this case.
But for the sake of consistency/safety....I also understand  tackling this at the beginning.

We will remove spaces in the micName at import time. Also, what do you think if, just for safety reasons, we trim spaces the relion convert when micName is used...I'm thinking in projects already with this problem. (if any)

**Comment by delarosatrevin** [comment]
OK, this could be a double check. Just left a comment in the relion convert code why this is done despite the micName should not contain (after the change, of course) spaces.

**Comment by ldelcano** [comment]
We discuss here that in theory other problems with white spaces on paths could arise in other imports, specially if they have metadata (import coordinates, import cfts...) but we have decided not to work on this now since it is only a possibility that might never occur.
I therefore close this issue.

**Comment by azazellochg** [comment]
is it back? :)

**Comment by delarosatrevin** [comment]
What is the status of this issue?

**Comment by azazellochg** [comment]
I have no idea, I thought it was fixed.

**Comment by ldelcano** [comment]
It is closed. @azazellochg fixed the import to remove white spaces from micname and I modified relion convert on coordinates. There were some ideas about other possible problems that could appear in the future but we decided not to work on them.
