### ISSUE TITLE
CTF import from gCTF failed

### ISSUE THREAD

**Issue by haraQQiri** [I2PC/scipion#1530]
imported micrographs providing path and *.mrc
import CTF using *gctf.log files and gctf import type tries to read the label 'RES_LIMIT' as a float? import with auto as type fails to get .ctf files rendered and is also missing phase shift info from gctf log

00001:   RUNNING PROTOCOL -----------------
00002:             PID: 42619
00003:         Scipion: 1.2.beta (26-12-2017) Caligula
00004:      currentDir: 
00005:      workingDir: Runs/000106_ProtImportCTF
00006:         runMode: Restart
00007:             MPI: 1
00008:         threads: 1
00009:    Starting at step: 1
00010:    Running steps 
00011:   STARTED: importCTFStep, step 1
00012:     2018-03-13 16:47:48.461820
00013:   Matching files: 999
00014:   Traceback (most recent call last):
00015:     File "/opt/sbgrid/x86_64-linux/scipion/1.2.beta/pyworkflow/protocol/protocol.py", line 186, in run
00016:       self._run()
00017:     File "/opt/sbgrid/x86_64-linux/scipion/1.2.beta/pyworkflow/protocol/protocol.py", line 233, in _run
00018:       resultFiles = self._runFunc()
00019:     File "/opt/sbgrid/x86_64-linux/scipion/1.2.beta/pyworkflow/protocol/protocol.py", line 229, in _runFunc
00020:       return self._func(*self._args)
00021:     File "/opt/sbgrid/x86_64-linux/scipion/1.2.beta/pyworkflow/em/protocol/protocol_import/ctfs.py", line 167, in importCTFStep
00022:       ctf = getMicCTF(mic)
00023:     File "/opt/sbgrid/x86_64-linux/scipion/1.2.beta/pyworkflow/em/protocol/protocol_import/ctfs.py", line 158, in _getMicCTF
00024:       return ci.importCTF(mic, fileName)
00025:     File "/opt/sbgrid/x86_64-linux/scipion/1.2.beta/pyworkflow/em/packages/gctf/dataimport.py", line 43, in importCTF
00026:       readCtfModel(ctf, fileName, ctf4=False)
00027:     File "/opt/sbgrid/x86_64-linux/scipion/1.2.beta/pyworkflow/em/packages/gctf/convert.py", line 97, in readCtfModel
00028:       result = parseGctfOutput(filename)
00029:     File "/opt/sbgrid/x86_64-linux/scipion/1.2.beta/pyworkflow/em/packages/gctf/convert.py", line 80, in parseGctfOutput
00030:       result[5] = float(line.strip().split()[-2])
00031:   ValueError: could not convert string to float: RES_LIMIT
00032:   Protocol failed: could not convert string to float: RES_LIMIT
00033:   FAILED: importCTFStep, step 1
00034:     2018-03-13 16:47:48.558519
00035:   ------------------- PROTOCOL FAILED (DONE 1/1)

**Comment by pconesa** [comment]
Thanks @haraQQiri , could you provide some test files to reproduce it.

**Comment by azazellochg** [comment]
I confirm the bug in 1.1-facilities-devel branch. Surprisingly, I don't see the test for gctf import?

**Comment by pconesa** [comment]
Thanks @azazellochg.
Isn't the test that one under, em/packages/gctf/tests ?
We have moved almost all the test to its correspondent package.
Looking at the test, nothing is testing a CTF import using GCTF files but a normal scipion CTF import.

**Comment by azazellochg** [comment]
@delarosatrevin I found your commit https://github.com/I2PC/scipion/commit/b383e7672aa6bc3991f267bcd084f99b970739f1 where this was modified. Do you remember what was the problem then? 
Now escape characters are not removed from the line before fetching the value. I pushed a fix to fixes branch, please have a look.

**Comment by azazellochg** [comment]
We should also have a test for this import (with/without phase shift)

**Comment by haraQQiri** [comment]
here is a micrograph and gctf log i that were used as an import ​
 Archive.zip
<https://drive.google.com/file/d/1uHaQ0AuaQ45I2Gaj2H_UH0Z38bClVTaN/view?usp=drive_web>
​

**Comment by pconesa** [comment]
I'm trying this now, @haraQQiri files with @azazellochg changes....thanks to both.

**Comment by pconesa** [comment]
Looks good! 
![image](https://user-images.githubusercontent.com/785633/37448878-76fbc09c-2828-11e8-9e20-041f72ce02ca.png)
