### ISSUE TITLE
Micrograph parameters in 'relion - particles extraction' STAR files

### ISSUE THREAD

**Issue by JuhaHuiskonen** [I2PC/scipion#1535]
In the file input_micrographs.star written by this protocol, all the micrographs have the same values (rlnDefocusU, rlnDefocusV etc).  It seems these are copied from the first micrograph to the rest.  It would be nice to use the real values for all of them. In my case, I would have wanted to plot the defocus, phase shift etc.

**Comment by azazellochg** [comment]
@delarosatrevin @josuegbl Hi guys, I think [this](https://github.com/I2PC/scipion/blame/release-1.1.facilities-devel/pyworkflow/em/packages/relion/protocol_extract_particles.py#L564) is the problem here..

**Comment by delarosatrevin** [comment]
Thanks @JuhaHuiskonen! 

@azazellochg I think that you are right, this condition looks suspicious. I will take a look and fix it.

**Comment by JuhaHuiskonen** [comment]
Thanks @delarosatrevin. Is there currently any other way for extracting micrograph metadata for plotting?

**Comment by delarosatrevin** [comment]
You can visualize a SetOfCTF and plot the defocus values (or any other
value) from there.

**Comment by JuhaHuiskonen** [comment]
Cool! I had missed this feature. Very useful.

**Comment by pconesa** [comment]
Thank you all, I've cancelled the release yesterday. Actually it was
downloadable,but never announced
