### ISSUE TITLE
evaluate cisTEM

### ISSUE THREAD

**Issue by pconesa** [I2PC/scipion#1548]

**Comment by azazellochg** [comment]
End of the year / next year there will be a new release, we'll see if they detach gui from the actual jobs.

**Comment by pconesa** [comment]
@azazellochg, @cossorzano had the plan to give this to a student but till now our attempts were unsuccessful. May be we can work together on this. Thoughts? @cossorzano @azazellochg

**Comment by azazellochg** [comment]
If the student can read C++ then it's good. A lot of code has to be
reimplemented from cisTEM GUI into the protocols.

I have started with the simplest ones, but it gets more and more digging
into the code.

Best regards,
Grigory

--------------------------------------------------------------------------------
Grigory Sharov, Ph.D.

MRC Laboratory of Molecular Biology,
Francis Crick Avenue,
Cambridge Biomedical Campus,
Cambridge CB2 0QH, UK.
tel. +44 (0) 1223 267228 <+44%201223%20267228>
e-mail: gsharov@mrc-lmb.cam.ac.uk

**Comment by pconesa** [comment]
This is already happening.
