### ISSUE TITLE
update resmap 1.9

### ISSUE THREAD

**Issue by azazellochg** [I2PC/scipion#1557]
> We announce the release of a new version of our program for computing local
> resolution of 3D maps ResMap (v1.9) for single-particle
> cryo-EM (web: https://sourceforge.net/projects/resmap-latest/)  
> 
> * ResMap v1.9 has been updated to Python 3 with small changes to the GUI,
>   the command line and additional benchmarking as described in the manual. 
> 
> The package along with the manual can be downloaded from
> https://sourceforge.net/projects/resmap-latest/ . The precompiled binaries and 
> source code are available for both Linux and MacOsX. The source code
> runs under Windows 10 but may be unstable and is not fully supported in
> this release. 
> 
> ResMap-1.9 has been extensively tested for the environments described
> in the manual, but if you experience any problems or bugs please use
> the Wiki and discussion available on the Download website mentioned above.
> 
> The ResMap team:
> 
> Frederic Bonnet
> Hemant Tagare
> Frederick Sigworth

**Comment by pconesa** [comment]
Python 3!! ummm.

**Comment by azazellochg** [comment]
same as #1663
