### ISSUE TITLE
add gctf 1.18

### ISSUE THREAD

**Issue by azazellochg** [I2PC/scipion#1568]
https://www.mrc-lmb.cam.ac.uk/kzhang/Gctf/Gctf_v1.18/
this is a special version for phase plate data

**Comment by delarosatrevin** [comment]
v1.2.1???

**Comment by pconesa** [comment]
@azazellochg, does it require python changes?

**Comment by azazellochg** [comment]
moved to https://github.com/scipion-em/scipion-em-gctf/pull/1
