### ISSUE TITLE
em.data.test_data.TestImage - testOrigin FAILS

### ISSUE THREAD

**Issue by dmaluenda** [I2PC/scipion#1571]
`scipion test tests.em.data.test_data.TestImage` FAILS in devel branch since the mic under tests has not sampling rate.

The problem is in the function [_getDefaultOrigin()](https://github.com/I2PC/scipion/blob/daa413e7887bd6dad8481ee5db4d7c0311f1aa79/pyworkflow/em/data.py#L596), maybe it needs to assert if the Image have sampling rate and if not then do something.

Any idea? @mmmtnez

**Comment by dmaluenda** [comment]
Ok! So, the best option is to introduce a sampling rate to the micrograph by mic.setSamplingRate(1) in the test??

**Comment by josuegbl** [comment]
I dont know how works the test, but if it creates a new micrograph object, the sampling rate must be set. Check with @mmmtnez and @rmarabini all the details about this, please.
