### ISSUE TITLE
Crear MVs para curso Roberto Marabini

### ISSUE THREAD

**Issue by ldelcano** [I2PC/scipion#1573]
9 MVs durante 5 dias (23-27 abril)

**Comment by josuegbl** [comment]
@ldelcano, please write in English here cause is a public repository and all the collaborators are not Spanish speakers.

**Comment by delarosatrevin** [comment]
Just to add more wood to the fire ;) ... I would recommend to create a separate repository (scipion-cloud ?) for this kind of issues that are not entirely related to scipion development.
