### ISSUE TITLE
xmipp fails to calculate CTF

### ISSUE THREAD

**Issue by dzyla** [I2PC/scipion#1577]
Hello,

I have started using Scipion and I have problems at the very beginning - after images import I wanted to calculate the CTF using xmipp. The stdout is below. This happens for all my datasets and honestly I have no idea where to start troubleshooting. If any other information is needed I would be happy to provide. I hope there is easy fix for that.

Best,
Dawid

dataset: 329 single frame MRC files, 1.07 A/px, 

'[32mRUNNING PROTOCOL -----------------[0m
          PID: 35663
      Scipion: devel (2018-04-25) devel (devel 0e92e1d)
   currentDir: /localhome/dawid/ScipionUserData/projects/pSH2
   workingDir: Runs/000948_XmippProtCTFMicrographs
      runMode: Continue
          MPI: 1
      threads: 2
len(steps) 329 len(prevSteps) 0 
 Starting at step: 1
 Running steps 
[35mSTARTED[0m: _estimateCTF, step 1
  2018-04-28 15:23:32.879844
[32mxmipp_transform_downsample -i Runs/000512_ProtImportMicrographs/extra/FoilHole_24153502_Data_24155001_24155002_20180424_1529.mrc -o Runs/000948_XmippProtCTFMicrographs/tmp/FoilHole_24153502_Data_24155001_24155002_20180424_1529.mrc --step 1.401869 --method fourier[0m
Input File: Runs/000512_ProtImportMicrographs/extra/FoilHole_24153502_Data_24155001_24155002_20180424_1529.mrc
Output File: Runs/000948_XmippProtCTFMicrographs/tmp/FoilHole_24153502_Data_24155001_24155002_20180424_1529.mrc
[32mxmipp_ctf_estimate_from_micrograph --micrograph Runs/000948_XmippProtCTFMicrographs/tmp/FoilHole_24153502_Data_24155001_24155002_20180424_1529.mrc --oroot Runs/000948_XmippProtCTFMicrographs/extra/FoilHole_24153502_Data_24155001_24155002_20180424_1529/xmipp_ctf --sampling_rate 1.5 --defocusU 21250.000000 --defocus_range 18750.000000 --overlap 0.7 --acceleration1D --Q0 0.1 --min_freq 0.05 --ctfmodelSize 512 --max_freq 0.35 --kV 200.0 --Cs 2.0 --pieceDim 512 --fastDefocus --downSamplingPerformed 1.401869[0m
Computing models of each piece ...
0000/???? sec. ------------------------------------------------------------FileName = Runs/000948_XmippProtCTFMicrographs/extra/FoilHole_24153502_Data_24155001_24155002_20180424_1529/xmipp_ctf.psd 
Micrograph number: 1

     0/   0 sec. ............................................................
Adjusting CTF model to the PSD ...
1D acceleration
[32mxmipp_ctf_sort_psds -i Runs/000948_XmippProtCTFMicrographs/extra/FoilHole_24153502_Data_24155001_24155002_20180424_1529/xmipp_ctf.xmd[0m
Input File: Runs/000948_XmippProtCTFMicrographs/extra/FoilHole_24153502_Data_24155001_24155002_20180424_1529/xmipp_ctf.xmd
Filter w1:    0.02
Filter w2:    0.2
Filter decay: 0.02
Mask w1:      0.01
Mask w2:      0.45
0000/???? sec. ------------------------------------------------------------
   0/   0 sec. ............................................................
[32mxmipp_metadata_utilities -i Runs/000948_XmippProtCTFMicrographs/extra/FoilHole_24153502_Data_24155001_24155002_20180424_1529/xmipp_ctf.xmd --query select "ctfCritFirstZero<5 OR ctfCritMaxFreq>20 OR ctfCritfirstZeroRatio<0.9 OR ctfCritfirstZeroRatio>1.1 OR ctfCritFirstMinFirstZeroRatio>10 OR ctfCritCorr13<0 OR ctfCritCtfMargin<0 OR ctfCritNonAstigmaticValidty<0 OR ctfCritNonAstigmaticValidty>25 OR ctfBgGaussianSigmaU>50000 OR ctfBgGaussianSigmaU<1000 OR ctfCritIceness>1" -o Runs/000948_XmippProtCTFMicrographs/tmp/FoilHole_24153502_Data_24155001_24155002_20180424_1529.mrc_rejected.xmd[0m
[32mxmipp_transform_downsample -i Runs/000512_ProtImportMicrographs/extra/FoilHole_24153502_Data_24155001_24155002_20180424_1529.mrc -o Runs/000948_XmippProtCTFMicrographs/tmp/FoilHole_24153502_Data_24155001_24155002_20180424_1529.mrc --step 2.401869 --method fourier[0m
Input File: Runs/000512_ProtImportMicrographs/extra/FoilHole_24153502_Data_24155001_24155002_20180424_1529.mrc
Output File: Runs/000948_XmippProtCTFMicrographs/tmp/FoilHole_24153502_Data_24155001_24155002_20180424_1529.mrc
[32mxmipp_ctf_estimate_from_micrograph --micrograph Runs/000948_XmippProtCTFMicrographs/tmp/FoilHole_24153502_Data_24155001_24155002_20180424_1529.mrc --oroot Runs/000948_XmippProtCTFMicrographs/tmp/FoilHole_24153502_Data_24155001_24155002_20180424_1529.mrc_xmipp_ctf --sampling_rate 2.57 --defocusU 21250.000000 --defocus_range 18750.000000 --overlap 0.7 --acceleration1D --Q0 0.1 --min_freq 0.05 --ctfmodelSize 512 --max_freq 0.35 --kV 200.0 --Cs 2.0 --pieceDim 512 --fastDefocus --downSamplingPerformed 2.401869[0m
Computing models of each piece ...
0000/???? sec. ------------------------------------------------------------FileName = Runs/000948_XmippProtCTFMicrographs/tmp/FoilHole_24153502_Data_24155001_24155002_20180424_1529.mrc_xmipp_ctf.psd 
Micrograph number: 1

 0000/???? sec. ------------------------------------------------------------
   0/   0 sec. ............................................................
Adjusting CTF model to the PSD ...
1D acceleration
[32mxmipp_ctf_sort_psds -i Runs/000948_XmippProtCTFMicrographs/extra/FoilHole_24153502_Data_24155001_24155002_20180424_1529/xmipp_ctf.xmd[0m
Input File: Runs/000948_XmippProtCTFMicrographs/extra/FoilHole_24153502_Data_24155001_24155002_20180424_1529/xmipp_ctf.xmd
Filter w1:    0.02
Filter w2:    0.2
Filter decay: 0.02
Mask w1:      0.01
Mask w2:      0.45
0000/???? sec. ------------------------------------------------------------
   0/   0 sec. ............................................................
[32mxmipp_metadata_utilities -i Runs/000948_XmippProtCTFMicrographs/extra/FoilHole_24153502_Data_24155001_24155002_20180424_1529/xmipp_ctf.xmd --query select "ctfCritFirstZero<5 OR ctfCritMaxFreq>20 OR ctfCritfirstZeroRatio<0.9 OR ctfCritfirstZeroRatio>1.1 OR ctfCritFirstMinFirstZeroRatio>10 OR ctfCritCorr13<0 OR ctfCritCtfMargin<0 OR ctfCritNonAstigmaticValidty<0 OR ctfCritNonAstigmaticValidty>25 OR ctfBgGaussianSigmaU>50000 OR ctfBgGaussianSigmaU<1000 OR ctfCritIceness>1" -o Runs/000948_XmippProtCTFMicrographs/tmp/FoilHole_24153502_Data_24155001_24155002_20180424_1529.mrc_rejected.xmd[0m
[32mxmipp_transform_downsample -i Runs/000512_ProtImportMicrographs/extra/FoilHole_24153502_Data_24155001_24155002_20180424_1529.mrc -o Runs/000948_XmippProtCTFMicrographs/tmp/FoilHole_24153502_Data_24155001_24155002_20180424_1529.mrc --step 1.200935 --method fourier[0m
Input File: Runs/000512_ProtImportMicrographs/extra/FoilHole_24153502_Data_24155001_24155002_20180424_1529.mrc
Output File: Runs/000948_XmippProtCTFMicrographs/tmp/FoilHole_24153502_Data_24155001_24155002_20180424_1529.mrc
[32mxmipp_ctf_estimate_from_micrograph --micrograph Runs/000948_XmippProtCTFMicrographs/tmp/FoilHole_24153502_Data_24155001_24155002_20180424_1529.mrc --oroot Runs/000948_XmippProtCTFMicrographs/tmp/FoilHole_24153502_Data_24155001_24155002_20180424_1529.mrc_xmipp_ctf --sampling_rate 1.285 --defocusU 21250.000000 --defocus_range 18750.000000 --overlap 0.7 --acceleration1D --Q0 0.1 --min_freq 0.05 --ctfmodelSize 512 --max_freq 0.35 --kV 200.0 --Cs 2.0 --pieceDim 512 --fastDefocus --downSamplingPerformed 1.200935[0m
Computing models of each piece ...
0000/???? sec. ------------------------------------------------------------FileName = Runs/000948_XmippProtCTFMicrographs/tmp/FoilHole_24153502_Data_24155001_24155002_20180424_1529.mrc_xmipp_ctf.psd 
Micrograph number: 1

 
0000/???? sec. ------------------------------------------------------------
   0/   0 sec. ............................................................
Adjusting CTF model to the PSD ...
1D acceleration
[32mxmipp_ctf_sort_psds -i Runs/000948_XmippProtCTFMicrographs/extra/FoilHole_24153502_Data_24155001_24155002_20180424_1529/xmipp_ctf.xmd[0m
Input File: Runs/000948_XmippProtCTFMicrographs/extra/FoilHole_24153502_Data_24155001_24155002_20180424_1529/xmipp_ctf.xmd
Filter w1:    0.02
Filter w2:    0.2
Filter decay: 0.02
Mask w1:      0.01
Mask w2:      0.45
0000/???? sec. ------------------------------------------------------------
   0/   0 sec. ............................................................
[32mxmipp_metadata_utilities -i Runs/000948_XmippProtCTFMicrographs/extra/FoilHole_24153502_Data_24155001_24155002_20180424_1529/xmipp_ctf.xmd --query select "ctfCritFirstZero<5 OR ctfCritMaxFreq>20 OR ctfCritfirstZeroRatio<0.9 OR ctfCritfirstZeroRatio>1.1 OR ctfCritFirstMinFirstZeroRatio>10 OR ctfCritCorr13<0 OR ctfCritCtfMargin<0 OR ctfCritNonAstigmaticValidty<0 OR ctfCritNonAstigmaticValidty>25 OR ctfBgGaussianSigmaU>50000 OR ctfBgGaussianSigmaU<1000 OR ctfCritIceness>1" -o Runs/000948_XmippProtCTFMicrographs/tmp/FoilHole_24153502_Data_24155001_24155002_20180424_1529.mrc_rejected.xmd[0m
[35mFINISHED[0m: _estimateCTF, step 1
  2018-04-28 15:23:50.059744
[35mSTARTED[0m: _estimateCTF, step 2
  2018-04-28 15:23:50.104180
[32mxmipp_transform_downsample -i Runs/000512_ProtImportMicrographs/extra/FoilHole_24153506_Data_24155001_24155002_20180424_1531.mrc -o Runs/000948_XmippProtCTFMicrographs/tmp/FoilHole_24153506_Data_24155001_24155002_20180424_1531.mrc --step 1.401869 --method fourier[0m
Input File: Runs/000512_ProtImportMicrographs/extra/FoilHole_24153506_Data_24155001_24155002_20180424_1531.mrc
Output File: Runs/000948_XmippProtCTFMicrographs/tmp/FoilHole_24153506_Data_24155001_24155002_20180424_1531.mrc
Traceback (most recent call last):
  File "/localhome/dawid/Downloads/scipion/pyworkflow/protocol/protocol.py", line 186, in run
    self._run()
  File "/localhome/dawid/Downloads/scipion/pyworkflow/protocol/protocol.py", line 1114, in _run
    self._runSteps(startIndex)
  File "/localhome/dawid/Downloads/scipion/pyworkflow/protocol/protocol.py", line 985, in _runSteps
    self._stepsCheckSecs)
  File "/localhome/dawid/Downloads/scipion/pyworkflow/protocol/executor.py", line 220, in runSteps
    stepsCheckCallback()
  File "/localhome/dawid/Downloads/scipion/pyworkflow/em/protocol/protocol_micrographs.py", line 462, in _stepsCheck
    self._checkNewOutput()
  File "/localhome/dawid/Downloads/scipion/pyworkflow/em/protocol/protocol_micrographs.py", line 516, in _checkNewOutput
    newDoneUpdated = self._updateOutputCTFSet(newDone, streamMode)
  File "/localhome/dawid/Downloads/scipion/pyworkflow/em/protocol/protocol_micrographs.py", line 583, in _updateOutputCTFSet
    ctf = self._createCtfModel(mic)
  File "/localhome/dawid/Downloads/scipion/pyworkflow/em/packages/xmipp3/protocol_ctf_micrographs.py", line 472, in _createCtfModel
    ctfModel2 = readCTFModel(ctfParam, mic)
  File "/localhome/dawid/Downloads/scipion/pyworkflow/em/packages/xmipp3/convert.py", line 710, in readCTFModel
    return mdToCTFModel(md, mic)
  File "/localhome/dawid/Downloads/scipion/pyworkflow/em/packages/xmipp3/convert.py", line 698, in mdToCTFModel
    ctfObj = rowToCtfModel(ctfRow)
  File "/localhome/dawid/Downloads/scipion/pyworkflow/em/packages/xmipp3/convert.py", line 647, in rowToCtfModel
    extraLabels=CTF_EXTRA_LABELS)
  File "/localhome/dawid/Downloads/scipion/pyworkflow/em/packages/xmipp3/convert.py", line 276, in rowToObject
    getattr(obj, attr).set(value)
AttributeError: 'NoneType' object has no attribute 'set'
[32m------------------- PROTOCOL FAILED (DONE 1/329)[0m '

**Comment by pconesa** [comment]
Hi Dawid,
Unless you are willing to run the very latest developments from xmipp that
hasn't been "stablely" released, I would suggest you to use "master" branch
which was recently released. In any case this is a bug we have to look at
and fix, the sooner the better.

**Comment by dzyla** [comment]
Thank you for your reply. I have switched to master and indeed that problem is not occurring anymore.
