### ISSUE TITLE
Scipion 1.2 empty software/include/python2.7 directory

### ISSUE THREAD

**Issue by ckywong** [I2PC/scipion#1579]
Hello,

I am doing binary installation of Scipion 1.2 on CentOS 7 with scipion_v1.2_2018-04-02_linux64.tgz.  I get a few error messages about header files not found, e.g., pyconfig.h.  When I check the directory software/include/python2.7, it seems to be empty.  But the same directory in older versions (1.0.1 and 1.1) is not empty.  I just wonder if I missed something.  Could somebody please take a look at it?

Thanks a lot in advance.  Have a great day!

**Comment by pconesa** [comment]
Thanks, @ckywong. We'll review the bundle and let you know.

**Comment by ldelcano** [comment]
No, you did not do anything stupid. In fact we found that problem too after you mentioned it and reviewed the bundles. We are working on fixing it.
Cheers
Laura

**Comment by ldelcano** [comment]
We have updated the binaries to solve this problem. They now contain header files so cryoem should install ok. Please, download them again and let us now if you have any other problem.

**Comment by ckywong** [comment]
Thank you so much for your quick response.  I downloaded the new binary and was able to install all available packages.  Thanks again for the great work and have a wonderful day!
