### ISSUE TITLE
opencv compile error

### ISSUE THREAD

**Issue by naharrosp** [I2PC/scipion#1584]
Hi, I get the next error while installing scipion on Ubuntu 18.04 LTS
How can I solve it?
Thank you

--------------------

Building opencv ...
wget -nv -c -O software/tmp/opencv-2.4.13.tgz.part http://scipion.cnb.csic.es/downloads/scipion/software/external/opencv-2.4.13.tgz
2018-05-06 22:45:59 URL:http://scipion.cnb.csic.es/downloads/scipion/software/external/opencv-2.4.13.tgz [91817825/91817825] -> "software/tmp/opencv-2.4.13.tgz.part" [1]
mv -v software/tmp/opencv-2.4.13.tgz.part software/tmp/opencv-2.4.13.tgz
renamed 'software/tmp/opencv-2.4.13.tgz.part' -> 'software/tmp/opencv-2.4.13.tgz'
cd software/tmp
tar -xzf opencv-2.4.13.tgz
cd software/tmp/opencv-2.4.13
cmake -DWITH_FFMPEG=OFF -DWITH_CUDA:BOOL=OFF -DCMAKE_INSTALL_PREFIX:PATH=/home/naharrosp/Programs/scipion/software . > /home/naharrosp/Programs/scipion/software/log/opencv_cmake.log 2>&1
Error: target 'software/tmp/opencv-2.4.13/Makefile' not built (after running 'cmake -DWITH_FFMPEG=OFF -DWITH_CUDA:BOOL=OFF -DCMAKE_INSTALL_PREFIX:PATH=/home/naharrosp/Programs/scipion/software . > /home/naharrosp/Programs/scipion/software/log/opencv_cmake.log 2>&1')

**Comment by pconesa** [comment]
Hi, mean while we have a look to it add --no-opencv Param to "scipion
install" command to skip openCV installation. You'll not be able to use a
couple of xmipp GPU methods, but other than that, it is not critical to
skip it.

**Comment by naharrosp** [comment]
[log.txt](https://github.com/I2PC/scipion/files/2010987/log.txt)
[logCMakeError.txt](https://github.com/I2PC/scipion/files/2010988/logCMakeError.txt)
[logCMakeOutput.txt](https://github.com/I2PC/scipion/files/2010989/logCMakeOutput.txt)

Thank you for your help.

I also attach the logs recommended on the failed installation

**Comment by pconesa** [comment]
Yep, another user reported something similar regarding not finding video.h

**Comment by pconesa** [comment]
Hi @dmaluenda , this is related to openCV in ubuntu 18 and with xmipp...that is why I've assigned this to you.
