### ISSUE TITLE
Support to motioncor2 1.1.0

### ISSUE THREAD

**Issue by delarosatrevin** [I2PC/scipion#1586]
From ccpem list:

The newest version is available that can be downloaded at 

msg.ucsf.edu/em/software/index.html. 

The major improvement is its speed, maybe 5 to 6x speedup as opposed to 1.0.5. In addition, it is more robust. Try the new feature -InFmMotion that takes into account of frame motion blurring. My test based upon 20S proteasome shows a minor improvement of resolution. The FSC curve is also noticeably better.

**Comment by pconesa** [comment]
Binaries are on the server...: motioncor2-1.1.0.tgz

**Comment by delarosatrevin** [comment]
Fixed in #1637
