### ISSUE TITLE
Phase shift in ctffind does not work

### ISSUE THREAD

**Issue by JaviMota** [I2PC/scipion#1590]
I have found a problem with the volta phase plate using Ctffind. The label _phaseShift has been added for all ctf estimation protocols but when I run the Ctffind one it doesn't work. Another problem I have detected is with Xmipp ctf estimation the _phaseShift label is not working well, the CTFModel class has a condition in the _phaseShift label that it always return a None. Changing it to Float(kwargs.get('phaseShift', None)) it works. Nevertheless Ctffind doesn't work with any condition. It doesn't raise any error but it get stuck.

Regards.

**Comment by azazellochg** [comment]
Hi @JaviMota could you specify ctffind and scipion version? 4.1.10 and 1.2? What mic size do you have and which phase shift options you are using?

**Comment by azazellochg** [comment]
I think it does work, it's just very slow if you are using default step for phase shift. If you increase the step from 0.2 to 0.4 radians it runs much faster.
As for xmipp - it is not implemented yet unless you are using devel branch.

**Comment by pconesa** [comment]
I think he is using devel. Don't think this is happening in release-1.2.1

**Comment by JaviMota** [comment]
Hi, yes as Pablo says Im using devel. I have increased the step but it get stuck.  Something is wrong in the devel branch.

**Comment by pconesa** [comment]
@JaviMota is this fixed?
