### ISSUE TITLE
cryoem installation fails with scipion binaries

### ISSUE THREAD

**Issue by ldelcano** [I2PC/scipion#1592]
Cryoem is a python module that requires cython that requires python headers to compile. 
All c++ headers files were removed from binaries to make them lighter but we should leave headers on software/include/ folders just in case they are needed.

**Comment by delarosatrevin** [comment]
I think there is a bigger problem behind this..and not only for the cryoem package:

**We need to sepate the build from the install concepts!!!**

In one case, headers, development libraries and compilers are needed...in the other, just binaries (compiled code).

**Comment by pconesa** [comment]
That is true only for Xmipp, but for python modules, we should not remove the .h files, at some of them (like headers from numpy, that are needed for other python modules.

**Comment by delarosatrevin** [comment]
I'm not completely sure, but I strongly believe that .h files are only needed when compiling, not but install/execution.

**Comment by pconesa** [comment]
Yes, but numpy provides .h files under and some python modules (like in our case cryoem, that compiles against numpy headers need those headers)...technically this is installation and not execution, so you are right, but scipion, even if you are using binaries.....will need those .h...unless we provide "all packages, modeules" in the bundle.

**Comment by ldelcano** [comment]
I have created new binary bundles with all header files (*.h) except the one from xmipp that is used to check if xmipp should or not be compiled (binaries or sources), software/em/xmipp/libraries/data/args.h.
With these binaries cryoem install correctly on Ubuntu. On Centos there is a problem with gsl-devel library which is external to Scipion.

**Comment by ldelcano** [comment]
Uploaded to download page and replaced the other binaries.

**Comment by ckywong** [comment]
Hello, I think I am running into the missing header files issue with Scipion 1.2.1.  I downloaded the binary installer scipion_v1.2.1_2018-10-01_linux64.tgz and was able to install all included software except cryoem.  When building cython, there was an error message:

> gcc -fno-strict-aliasing -g -O2 -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -I/opt/apps/Scipion/1.2.1_2018-10-01/software/include -fPIC -I/opt/apps/Scipion/1.2.1_2018-10-01/software/include/python2.7 -c /opt/apps/Scipion/1.2.1_2018-10-01/software/tmp/Cython-0.22/Cython/Plex/Scanners.c -o build/temp.linux-x86_64-2.7/opt/apps/Scipion/1.2.1_2018-10-01/software/tmp/Cython-0.22/Cython/Plex/Scanners.o
> /opt/apps/Scipion/1.2.1_2018-10-01/software/tmp/Cython-0.22/Cython/Plex/Scanners.c:8:22: fatal error: pyconfig.h: No such file or directory
>  #include "pyconfig.h"
>                       ^
> compilation terminated.
> error: command 'gcc' failed with exit status 1

Could somebody please take a look at it?  Thanks a lot!
