### ISSUE TITLE
xmipp compilation with cuda enable fails

### ISSUE THREAD

**Issue by rmarabini** [I2PC/scipion#1596]
xmipp compilation with cuda enabled fails unless I execute first:

export PATH=$PATH:/usr/local/cuda-8.0/bin
export LD_LIBRARY_PATH=/usr/local/cuda-8.0/lib64

Should not xmipp use CUDA_LIB and CUDA_LIB by default? 
Is there a CUDA_LIB_XMIPP or similar?

In scipion.conf I have

CUDA_LIB = /usr/local/cuda-8.0/lib64
CUDA_BIN = /usr/local/cuda-8.0/bin

**Comment by pconesa** [comment]
I'm closing this issue. Feel free to reopen it if I'm wrong or missed something.
