### ISSUE TITLE
pop-up raised with msj:'NoneType' object has no attribute 'hasCondition' (v1.2)

### ISSUE THREAD

**Issue by josuegbl** [I2PC/scipion#1597]
this is happening with protocols that has been opened with a devel-related branch and when I try to open in v1.2 branch, the message 'NoneType' object has no attribute 'hasCondition'.

**Comment by pconesa** [comment]
Thanks @josuegbl ,I think we should try to aim for backward compatibility as much as we can but not invest too much in it...
I'm sure it has to be more specific...I've opened projects in devel and then those back to release 1.2 without any problems.

Can you give any more details: Is related to a specific protocol not in release 1.2 but new in devel....which attributte is trying to set.?

**Comment by josuegbl** [comment]
No, it is happening me with relion auto-refine protocol. In any case, if any protocol is not in certain branch, it should be shown as a LegacyProtocol. I could send you project.sqlite if you want.

**Comment by josuegbl** [comment]
a picture is worth more than 1000 words

![protocol_fail](https://user-images.githubusercontent.com/12274357/39875218-05e61ad2-543e-11e8-8cbf-da7fa0687850.png)

**Comment by azazellochg** [comment]
Could it be 'referenceAverages' PointerParam which is absent in 1.2 (master) and available only in 1.2.1/devel ?

**Comment by pconesa** [comment]
Yes, @josuegbl , please send me the sqlite to see what is going on.

**Comment by pconesa** [comment]
My guess is that the attributes are loaded from the DB but the "conditions" are defined in the form "load" and some attributes present in the condition are not present in the protocol.

**Comment by pconesa** [comment]
Josu.....could you confirm this is not happening in release-1.2.1? I guess must be only in master.

**Comment by josuegbl** [comment]
@pconesa you are right! This is happening on master branch.  release-1.2.1 works well.

**Comment by pconesa** [comment]
Thanks @josuegbl ....I think I've got it now. The thing is that I can push the changes to release-1.2.1...but this will not fix master, unless I push this to master.......was your case a "necesity" or more an improvement.

**Comment by pconesa** [comment]
And, yes @azazellochg , the problem was around "referenceAverages". Opening "new Data" with "old code" and finding that referenceAverages as an attribute, but nos define as a param...(the key here is that it was an "inputParam").
