### ISSUE TITLE
How to install tutorial data without directory permission?

### ISSUE THREAD

**Issue by gc435** [I2PC/scipion#1609]
I'm new to Scipion and am running the tutorial.  I use Scipion 1.2 from SBGrid.  I see that `scipion tutorial intro` downloads a sample dataset, but by default it tries putting this in the SBGrid directory, where I don't have write permission.  The Scipion docs seem to say I can download the dataset elsewhere by setting `SCIPION_HOME`, but setting this still results in attempting to save the dataset to the same folder I don't own.

Is there a workaround?

**Comment by pconesa** [comment]
Hi @gc435 , yes there is.

You need to:

1. Open your personal scipion config file: usually at $HOME/.config/scipion/scipion.conf
2. Add a line int the DIRS_LOCAL section with 
`SCIPION_TESTS=/the path /you/want/to/have/the/tests `

Something like this (note: 
![image](https://user-images.githubusercontent.com/785633/40321364-13b239b2-5d2f-11e8-9d31-f834f75dd2a6.png)

**Comment by pconesa** [comment]
I'm closing this issue. Feel free to reopen it if I'm wrong or missed something.
