### ISSUE TITLE
Bug selecting volumes

### ISSUE THREAD

**Issue by josuegbl** [I2PC/scipion#1619]
The following error raised when I have been selecting some volumes from a setOfVolumes:
00001:   RUNNING PROTOCOL -----------------
00002:        HostName: gauss.campus.mcgill.ca
00003:             PID: 6193
00004:         Scipion:  (2018-05-18)  (v1.2.1-devel 2a77053)
00005:      currentDir: /home/josuegbl/ScipionUserData/projects/Apoferritin
00006:      workingDir: Runs/001663_ProtUserSubSet
00007:         runMode: Continue
00008:             MPI: 1
00009:         threads: 1
00010:   len(steps) 1 len(prevSteps) 0 
00011:    Starting at step: 1
00012:    Running steps 
00013:   STARTED: createSetStep, step 1
00014:     2018-05-23 11:27:56.959105
00015:   Traceback (most recent call last):
00016:     File "/home/josuegbl/SOFTWARE/scipion/pyworkflow/protocol/protocol.py", line 186, in run
00017:       self._run()
00018:     File "/home/josuegbl/SOFTWARE/scipion/pyworkflow/protocol/protocol.py", line 233, in _run
00019:       resultFiles = self._runFunc()
00020:     File "/home/josuegbl/SOFTWARE/scipion/pyworkflow/protocol/protocol.py", line 229, in _runFunc
00021:       return self._func(*self._args)
00022:     File "/home/josuegbl/SOFTWARE/scipion/pyworkflow/em/protocol/protocol_batch.py", line 106, in createSetStep
00023:       otherObj = self.getProject().mapper.selectById(int(otherid))
00024:   TypeError: int() argument must be a string or a number, not 'NoneType'
00025:   Protocol failed: int() argument must be a string or a number, not 'NoneType'
00026:   FAILED: createSetStep, step 1
00027:     2018-05-23 11:27:56.961567
00028:   ------------------- PROTOCOL FAILED (DONE 1/1)

My branch comes from 1.2.1.

**Comment by pconesa** [comment]
Thanks @josuegbl , I guess this is not just selecting but also running and in this case the new "batch protocol" ?

**Comment by pconesa** [comment]
I might be wrong...this is creating a subset of volumes from "ShowJ"? Please....clarify?

**Comment by josuegbl** [comment]
Yes Pablo, this occurs when is creating a subset of volumes from showj.

**Comment by pconesa** [comment]
Thanks @josuegbl , I've tried here with one of my projects and it works...so I guess there must be a specific case...does it always happen to you?

**Comment by josuegbl** [comment]
Thank @pconesa, it is happening only with the output of the protocol volume selector I don't know why.

**Comment by pconesa** [comment]
Hey!, nice and shiny one. I like the logo!
![image](https://user-images.githubusercontent.com/785633/40639795-1e1eb7c4-6313-11e8-918c-a03d1d57a832.png)
May you want to overwrite the help?

Can you have a look to the volume id's in the set, are the filled...do they have any value?

If you don't see anything obvious...I might need your data to debug it....project.sqlite plus volumes.sqlite (from the shiny one) ;-)

**Comment by pconesa** [comment]
@josuegbl anything new here?

**Comment by josuegbl** [comment]
@pconesa, I did some changes (are in the PR), but I didn't test this bug. I hope test it before Monday. Ill tell you asap.

**Comment by pconesa** [comment]
How is this, @josuegbl ?

**Comment by josuegbl** [comment]
Is still there :). Now I haven't time to fix it, but I should do it by myself cause I think there is a problem with the volume selector protocol (I guess the SOV (I know, you love this naming concept, hahaha) is generated wrong as output of Volume selector protocol. )

**Comment by pconesa** [comment]
I'm closing this issue. Feel free to reopen it if I'm wrong or missed something. May be if it still remains, shouldn't it go to McGill repo?
