### ISSUE TITLE
Movie maxshift is not always closing stream

### ISSUE THREAD

**Issue by majtner** [I2PC/scipion#1628]
After Movie maxshift protocol is finished, sometimes _streamstate of output set is still 1 (open). I wrote sometimes because the behaviour is non-deterministic, sometimes is closed and sometimes open, typically alternating between closed and open when protocol is restarted.
@dmaluenda could you, please, look at it?

**Comment by dmaluenda** [comment]
I will look at that!!

Thanks Tomas!

**Comment by pconesa** [comment]
Is this fixed @dmaluenda ?

**Comment by dmaluenda** [comment]
Yes, sorry.
