### ISSUE TITLE
Max resolution histogram skewed if CTF estimation fails on a few images

### ISSUE THREAD

**Issue by andreanans** [I2PC/scipion#1629]
Hello,

We typically use the monitor summary to keep track of the max resolution estimated by CTFFind etc. After updating to the latest version of Scipion, I noticed that the histogram range becomes quite spread out if there are a few images on which ctffind failed. Max resolution estimate is sometimes is 700 angstroms and this completely throws off the plot. See the attached image. Is there a way to limit the range of the histogram? What we have to do now is edit the index.html file after the session.
Thanks

Andrea
![res_estimate](https://user-images.githubusercontent.com/17334897/40552038-86f38020-6036-11e8-93b4-036470aa9809.png)

**Comment by pconesa** [comment]
I was just trying it....this should work:
![image](https://user-images.githubusercontent.com/785633/40555968-24b84c0a-604b-11e8-8f5a-645d8673c070.png)

To restrinct xAxis to 20

**Comment by pconesa** [comment]
Just the last line!: max: 20 ...and the comma right before.

**Comment by pconesa** [comment]
We might do it here for everyone...what would be a "safe" maximum resolution for you?

**Comment by andreanans** [comment]
For us 20 would be safe. The majority of our images have a resolution estimate of 8 or lower. Thanks again, the change in code works well!

**Comment by pconesa** [comment]
I'm closing this issue. Feel free to reopen it if I'm wrong or missed something.s!.
