### ISSUE TITLE
TestSignificant is failing at buildbot

### ISSUE THREAD

**Issue by pconesa** [I2PC/scipion#1630]
00102:   xmipp_cuda_correlation -i_ref Runs/000233_XmippProtReconstructSignificant/tmp/iter002/gallery.doc -i_exp Runs/000233_XmippProtReconstructSignificant/extra/input_classes.xmd -o Runs/000233_XmippProtReconstructSignificant/extra/angles_iter002.xmd --significance 0.097500 --maxShift 10.000000
00103:   xmipp_cuda_correlation: error while loading shared libraries: libcudart.so.7.5: cannot open shared object file: No such file or directory

It seems related to xmipp and CUDA paths...not sure how it should go.

**Comment by pconesa** [comment]
@ajimoreno any idea about this.

**Comment by pconesa** [comment]
It is related to the use of LINKFLAGS. That has to have the path to CUDA libs....and is not using CUDA_LIB.

Maybe @cossorzano has already detected this in his "xmipp splitting" branch.

**Comment by pconesa** [comment]
For now, I'm setting this manually in buildbot.

**Comment by dmaluenda** [comment]
I think that all packages should take the path from the same env. var. CUDA_LIB.
