### ISSUE TITLE
gctf refine: make step per micrograph

### ISSUE THREAD

**Issue by azazellochg** [I2PC/scipion#1632]
From @pconesa : now refineCtfStep is one big step. We should spit it into one per mic so it could be run in parallel (maybe even on separate GPUs?)

**Comment by delarosatrevin** [comment]
Yes, that's a good idea...still will be good to have the possibility of grouping some of them.
Take a look at the 'batch' parameters that helps for that. It can be a balance between granularity and performance (grouping and processing many).
