### ISSUE TITLE
monores bug

### ISSUE THREAD

**Issue by josuegbl** [I2PC/scipion#1635]
executing monores in v1.2 related branch the following error was raised:

00026:   XMIPP_ERROR 1: Errors on command line parameters
00027:   Unrecognized parameter: --automatic
00028:   Unrecognized parameter: --step
00029:   
00030:   File: software/em/xmipp/libraries/data/argsparser.cpp line: 1036
00031:   For more info use --help

**Comment by josuegbl** [comment]
the command line and th error is :
 
00025:   xmipp_resolution_monogenic_signal  --vol Runs/006364_ProtRelionRefine3D/extra/relion_class001.mrc:mrc --mask Runs/006532_XmippProtMonoRes/extra/binarized_mask.vol --sampling_rate 1.500000 --automatic  --step 1.000000 --mask_out Runs/006532_XmippProtMonoRes/extra/output_Mask.vol -o Runs/006532_XmippProtMonoRes/extra/mgresolution.vol --volumeRadius 60.000000 --chimera_volume Runs/006532_XmippProtMonoRes/extra/MG_Chimera_resolution.vol --sym c1 --significance 0.950000 --md_outputdata Runs/006532_XmippProtMonoRes/extra/mask_data.xmd --filtered_volume 
00026:   XMIPP_ERROR 1: Errors on command line parameters
00027:   Unrecognized parameter: --automatic
00028:   Unrecognized parameter: --step
00029:   
00030:   File: software/em/xmipp/libraries/data/argsparser.cpp line: 1036

**Comment by Vilax** [comment]
Thanks Josue

I was not able to reproduce the error. I know it is a very silly issue but,... have you recompile xmipp after the git pull. I cannot find any other explanation. Alternatively if you don't mind to send me the map, I can try to fix the bug

Regards
Vilas

**Comment by josuegbl** [comment]
Thanks @Vilax, I followed your suggestions and it works again to me.
