### ISSUE TITLE
Import Coordinates Failed

### ISSUE THREAD

**Issue by phonchi** [I2PC/scipion#1644]
Dear developers:

I would like to import the precalculated coordinates from the tutorial as follows:

![image](https://user-images.githubusercontent.com/11373055/40970715-fc68244a-68ed-11e8-8e5e-9b603b8c4896.png)

However, when I execute the job, there seems nothing happen with the run log as follows:

![image](https://user-images.githubusercontent.com/11373055/40970907-8f530dd8-68ee-11e8-998f-b53f868794f4.png)

and there is no SetOfCoordinates created.

![image](https://user-images.githubusercontent.com/11373055/40970810-4a8449b0-68ee-11e8-81fe-e1942de7213c.png)

Is there any step that I am missing? (I am in the branch release-1.1.facilities-fixes)

Any suggestions will be appreciated, thanks in advance!

**Comment by azazellochg** [comment]
Hi @phonchi , the first thing that comes to mid is that your micrograph names do not match coordinate filenames

**Comment by delarosatrevin** [comment]
I would also recommend to switch to release-1.2.1 branch...that will be
soon a new small release.

**Comment by pconesa** [comment]
I'll have a look. Today @rsanchezgarc had a similar problem....I'll review this functionalty..Thanks @phonchi , @delarosatrevin and @azazellochg

**Comment by pconesa** [comment]
@phonchi I've tried to import from xmipp eman and relion....and so far from relion I've got a 2xsize set....I'm investigating this, but it would be interesting if you can send me the starfile and the sqlite of the project to have a look.

**Comment by pconesa** [comment]
My bad...I was pointing to import from a "Relion extract"/extra folder all the *.star...And there were coords.star and extract.star (which I'm guessing are the output, right?)

**Comment by pconesa** [comment]
@phonchi , I'm not able to reproduce this.....tests worked, and my manual test did too.

Are you stuck?

**Comment by phonchi** [comment]
As @azazellochg suggested, I found that my imported name of star files does not match the name of previously imported micrographs. After renaming it, the function works correctly!

Thanks again for all the help!
