### ISSUE TITLE
Gctf ctf local refinement...feddback

### ISSUE THREAD

**Issue by pconesa** [I2PC/scipion#1647]
One of our user here has used it. After 8 day it has failed in step 2nd which can't be resumed.
Firstime it died without info in the log, second....fails because a mic is not found....She was warned that se was using a non released code and that she was somehow "betatesting" this.

Runs/011216_ProtGctfRefine/tmp/GridSquare_9629623_Data_FoilHole_9633779_Data_9633547_9633548_20180410_1735-1901_aligned_mic/GridSquare_9629623_Data_FoilHole_9633779_Data_9633547_9633548_20180410_1735-1901_aligned_mic.mrc` > Runs/011216_ProtGctfRefine/tmp/GridSquare_9629623_Data_FoilHole_9633779_Data_9633547_9633548_20180410_1735-1901_aligned_mic/ctfEstimation.txt--do_validation 0 Runs/011216_ProtGctfRefine/tmp/GridSquare_9629623_Data_FoilHole_9633779_Data_9633547_9633548_20180410_1735-1901_aligned_mic/GridSquare_9629623_Data_FoilHole_9633779_Data_9633547_9633548_20180410_1735-1901_aligned_mic.mrc > Runs/011216_ProtGctfRefine/tmp/GridSquare_9629623_Data_FoilHole_9633779_Data_9633547_9633548_20180410_1735-1901_aligned_mic/ctfEstimation.txt--do_validation 0 Runs/011216_ProtGctfRefine/tmp/GridSquare_9629623_Data_FoilHole_9633779_Data_9633547_9633548_20180410_1735-1901_aligned_mic/GridSquare_9629623_Data_FoilHole_9633779_Data_9633547_9633548_20180410_1735-1901_aligned_mic.mrc > Runs/011216_ProtGctfRefine/tmp/GridSquare_9629623_Data_FoilHole_9633779_Data_9633547_9633548_20180410_1735-1901_aligned_mic/ctfEstimation.txt
00032:   2018-06-09 04:10:55,476 ERROR:  Protocol failed: [Errno 2] No such file or directory: 'Runs/011216_ProtGctfRefine/tmp/GridSquare_9629623_Data_FoilHole_9633779_Data_9633547_9633548_20180410_1735-1901_aligned_mic/GridSquare_9629623_Data_FoilHole_9633779_Data_9633547_9633548_20180410_1735-1901_aligned_mic.ctf'

And after this she tried to continue and got this:
0049:   2018-06-11 09:17:21,234 INFO:  STARTED: refineCtfStep, step 2
00050:   2018-06-11 09:17:21,234 INFO:    2018-06-11 09:17:21.234008
00051:   2018-06-11 09:17:21,287 ERROR:  Protocol failed: 'ProtGctfRefine' object has no attribute 'downFactor'

**Comment by azazellochg** [comment]
Thanks @pconesa I believe it can be addressed in #1632

**Comment by pconesa** [comment]
Then I close this one.
