### ISSUE TITLE
Changing Gautomatch version

### ISSUE THREAD

**Issue by calyip** [I2PC/scipion#1657]
Hi, 

I am wondering if it would be possible to change the default version of Gautomatch. When we set up Gautomatch run, it automatically uses the CUDA 7.5 version and leads to the following error (see below) as our machine only has CUDA 8.0 installed. 

Protocol failed: Command '/programs/scipion/software/em/Gautomatch-0.53/bin/Gautomatch-v0.53_sm_20_cu7.5_x86_64  Runs/000651_ProtGautomatch/extra/micrographs/FoilHole_11922852_Data_11923480_11923481_20180612_1536_Fractions_aligned_mic.mrc --T Runs/000651_ProtGautomatch/extra/references.mrcs  --apixM 1.75 --ang_step 5 --diameter 500 --lp 30 --hp 1000 --gid 0 --apixT 1.75 --dont_invertT --cc_cutoff 0.10' returned non-zero exit status 127

Thanks!

**Comment by pconesa** [comment]
Hi @calyip, you should be able to change the config file to point to the 8.0 version....unless there is no such version. I'll check when I have my laptop.

**Comment by pconesa** [comment]
There must be a 8.0 version...we have already done that in our devel branch.

**Comment by pconesa** [comment]
Are you administering a cluster...?

**Comment by calyip** [comment]
Yes, the 8.0 version is present in the installation. This is for a
workstation not a cluster.

I am new to Scipion and do not know how to properly change the configure
file for pointing specific programs.

Thanks!

**Comment by pconesa** [comment]
You should have a configuration file at:

<Home folder>/.config/scipion/scipion.conf

Open this file and change the value for the gautomatch program:

GAUTOMATCH = Gautomatch-v0.53_sm_20_cu8.0_x86_64

Save it and restart scipion.

**Comment by delarosatrevin** [comment]
Hi @calyip 
In Scipion, there are two main configuration files. One located in the installation folder, named config/scipion.conf. There you need to modify two variables related to CUDA:

CUDA_LIB = /usr/lib/x86_64-linux-gnu/
CUDA_BIN = /usr/bin

Modify that and point to the place in your system. This will define the general lib and bin for all programs that Scipion will executing during the data processing. But, if you need to define a specific CUDA version, you can do so in the "user config" file, located in: ~/.config/scipion/scipion.conf. There you can find configuration of the packages such as where they are (usually under software/em in the Scipion folder) and the libraries. For example, for Motioncor2:

MOTIONCOR2_BIN = MotionCor2_Cuda8.0_v1.0.5
MOTIONCOR2_CUDA_LIB = /usr/local/cuda-8.0/lib64
MOTIONCOR2_HOME = %(EM_ROOT)s/motioncor2-1.0.5

You can define the version, the CUDA paths and also the binary according to the CUDA version.

@pconesa I started answering and you message came in between, you are so fast!
