### ISSUE TITLE
requested feature by fjchichon: import movies

### ISSUE THREAD

**Issue by rmarabini** [I2PC/scipion#1669]
modify import movies so a set of directories may be provided instead of a single one. It would be interesting also to provide "exclude" directories. The reason of this request is that directories names are related to different  grids  and populate with a few movies  before deciding if this grid is interesting. Therefore, it will be interesting not to import all movies related with a session but those movies that have been obtained from a articular subset of grids.

**Comment by azazellochg** [comment]
why not making several imports and do join after? :)

**Comment by pconesa** [comment]
In streaming, then join should be streamified. This is related to #1702

**Comment by pconesa** [comment]
Black lists are allowed already. I think, combining this with manual folder links, same functionality could be achieved.
I'm closing this issue. Feel free to reopen it if I'm wrong or missed something.
