### ISSUE TITLE
ProtCreateStreamData input?

### ISSUE THREAD

**Issue by azazellochg** [I2PC/scipion#1671]
I don't understand how can I supply input for this protocol. How can I get objects like Movie or Micrograph imported in scipion ? I can only have SetOfMovies with 1 item.... Am I missing something?

**Comment by pconesa** [comment]
Hi @azazellochg , I missed this one. I think as it is now it will use a single movie and will copy it:
![image](https://user-images.githubusercontent.com/785633/42216058-c6eaa7dc-7ec0-11e8-9698-d1b72d55b606.png)

Initially was designed to simulate streaming in tests, thus it might not have all the desired options. It also has evolved recently after it being used in other tests.

**Comment by pconesa** [comment]
I see, for me is working selecting a SOM, that in my case it only has 1 movie...but in devel....I think in release-1.2.1 that option will only work programmatically.
