### ISSUE TITLE
Motioncor2 and gain

### ISSUE THREAD

**Issue by pconesa** [I2PC/scipion#1677]
Is not picking up the Gain, I think paths is being truncated and Gain never found.
Check if gain comes not in mrc (dm4)....then gain should be converted to mrc.

**Comment by pconesa** [comment]
Add test for this

**Comment by pconesa** [comment]
Update: Gain is picked up if it exists, so that part is working. Conversion is still needed.

**Comment by azazellochg** [comment]
future mc2 version will read dm4 gain directly ;)

**Comment by pconesa** [comment]
Solved at #1737
