### ISSUE TITLE
Gctf not performing well with phaseShift?

### ISSUE THREAD

**Issue by pconesa** [I2PC/scipion#1679]
From CNB facility......gctf seems not to estimate the ctf:
![image](https://user-images.githubusercontent.com/785633/42205846-cb104918-7ea5-11e8-9158-ee9652a557ff.png)

Any known bug ?
Release 1.2.1, gctf 1.06

**Comment by azazellochg** [comment]
Please could you send me the mic and full cmd line for both ctffind and gctf?

**Comment by pconesa** [comment]
I've managed to get something right tweaking params:
![image](https://user-images.githubusercontent.com/785633/42206357-277cb1d6-7ea7-11e8-962d-a05677f81110.png)

Does this seems correct?

**Comment by pconesa** [comment]
Sorry, quality might not be good enough to check, but here it seems to cath the rings. Differences from the previous run are:

![image](https://user-images.githubusercontent.com/785633/42206535-af3c9ea6-7ea7-11e8-8717-e5cf914162a8.png)

"Good" run on the right!

**Comment by pconesa** [comment]
To me, it seems relates to downsampling.

**Comment by azazellochg** [comment]
The PSD looks ok, you could open it and do Auto for brightness to see the
rings better. I usually dont do downsampling unless images are 8k

Best regards,
Grigory

--------------------------------------------------------------------------------
Grigory Sharov, Ph.D.

MRC Laboratory of Molecular Biology,
Francis Crick Avenue,
Cambridge Biomedical Campus,
Cambridge CB2 0QH, UK.
tel. +44 (0) 1223 267542 <javascript:void(0);>
e-mail: gsharov@mrc-lmb.cam.ac.uk

**Comment by pconesa** [comment]
![image](https://user-images.githubusercontent.com/785633/42211244-6a5acf0e-7eb3-11e8-95fa-c8832251bec8.png)
Thanks Gregory.
