### ISSUE TITLE
I can't create random subset of coordinates.

### ISSUE THREAD

**Issue by rsanchezgarc** [I2PC/scipion#1683]
I can create random subset of particles but not coordinates.

The reason is that 
 scipion/pyworkflow/em/protocol/protocol_sets.py: 417

    def createOutputStep(self):
        inputFullSet = self.inputFullSet.get()

        inputClassName = inputFullSet.getClassName()
        outputSetFunction = getattr(self, "_create%s" % inputClassName)
        outputSet = outputSetFunction()
        outputSet.copyInfo(inputFullSet)

Because _createSetOfCoordinates has at least one argument, contrary to _createSetOfParticles that has no one. See https://github.com/I2PC/scipion/blob/42bbe1845f0dfa8e070c461cd210b526e7572266/pyworkflow/em/protocol/protocol.py#L73

**Comment by azazellochg** [comment]
same problem for #609

**Comment by pconesa** [comment]
I'm closing this issue. Feel free to reopen it if I'm wrong or missed something. It's already working.
