### ISSUE TITLE
Create dinamically the protocols.conf

### ISSUE THREAD

**Issue by pconesa** [I2PC/scipion#1686]
Allow a way to add new plugins' protocols to the protocols.conf.

**Comment by pconesa** [comment]
Loading code is at loadProtocolsConf

**Comment by delarosatrevin** [comment]
@pconesa We had this at some point. But I guess there is not a good balance. In one hand, if you populate the protocols list automatically/dynamically, you can not control the order, which in some cases matters. On the other hand, I understand the need to put there new protocols. 

My suggestion will be to provide an easy API to allow plugins to insert items there in the protocol.conf. Then a problem could be that plugins could fight each other to put them first in the list. Or we only allow to add at the end of the give category list (first come first served).

**Comment by pconesa** [comment]
I vote for the last, first come first serve. My concern is about the ability to "edit the protocols.conf".....do our users really do it? Otherwise I'd simplify this and not have a custom .conf for this.

**Comment by delarosatrevin** [comment]
Yes, I think no one edit this file. Still maybe will be good to keep this flexibility. Maybe this goes in the general direction or more centralized config files and if and only if the user have a local copy, we use that one.

**Comment by delarosatrevin** [comment]
Uf, I haven't noticed the assignee! ;)

**Comment by azazellochg** [comment]
You must be joking, I always edit protocols.conf !!! And I requested a long time ago to have a custom per-user copy in ~/.config/scipion/protocols.conf ! :)

**Comment by pconesa** [comment]
Ok, if you use it...that's enough @azazellochg ;-). I wasn't joking, I just didn't know or forgot.
