### ISSUE TITLE
Testdata

### ISSUE THREAD

**Issue by geraets** [I2PC/scipion#1689]
Some of the test data sets can't be downloaded. For example, I can't download the betagal dataset. but I can download groel.

I did some digging, and although betagal appears in the download manifest at:
http://scipion.cnb.csic.es/downloads/scipion/data/tests/MANIFEST
there isn't a manifest at:
http://scipion.cnb.csic.es/downloads/scipion/data/tests/betagal/MANIFEST

Who is curating the manifests? Is betagal in the main manifest, but without files, just so users can continue to use local (already downloaded) versions? Why are the data no longer available?

I suppose this might change with pluginization... 

Many thanks,
James

**Comment by pconesa** [comment]
Dear @geraets our server is down due to a problem is our datacenter.....I'll post you once datasets are available.  Sorry.

**Comment by geraets** [comment]
OK, that would explain it!

Thanks

**Comment by pconesa** [comment]
Wait this can't explain it...I think betagal dataset is empty....

**Comment by pconesa** [comment]
Can't check now, server is down.

**Comment by pconesa** [comment]
None of the tests are using betagal dataset....I think this is used from a tutorial.

**Comment by geraets** [comment]
Perhaps it could be removed from the manifest then? Otherwise it appears as a option to download when running scipion testdata --list
