### ISSUE TITLE
Scipion v1.2 - ImportError: No module named numpy

### ISSUE THREAD

**Issue by eMKiso** [I2PC/scipion#1698]
Dear all,

I just compiled Scipion on a fresh Ubuntu 18.04 OS. I enabled CUDA and all the lines were green after running `./scipion configure`.
The compilation finished with no apparent issues.

When I try to start `./scipion` I get `ImportError: No module named numpy`(entire trace is attached).

Any ideas how to fix this?

[Numpy.txt](https://github.com/I2PC/scipion/files/2210353/Numpy.txt)

**Comment by pconesa** [comment]
What happens if you type:

./scipion install numpy

?

**Comment by eMKiso** [comment]
I tried `./scipion install numpy` and the compilation failed with this `ImportError: No module named PIL`.
Details are attached.[PIL.txt](https://github.com/I2PC/scipion/files/2213791/PIL.txt)

I gave up on this because I thought it could be an issue with the fact that I was compiling in some rather odd folder (not the home folder). When I compiled in the home folder I came across another error which is the topic of another  'issue' (will be posted soon).

**Comment by azazellochg** [comment]
It looks like the compilation was not successfull at all, since you are missing a lot of things...

**Comment by eMKiso** [comment]
Interesting, because as much as I rember now there was no error during the "first" compilation. For now I attribute this issue to folder permissions and ownership. After changing the compilation folder the issue disappeared. 
Consider this issue closed.
Thank you for your time!
