### ISSUE TITLE
Scipion v1.2 - opencv_cmake compile error

### ISSUE THREAD

**Issue by eMKiso** [I2PC/scipion#1699]
Hi,

I am trying to compile Scipion 1.2 on OS Ubuntu 18.04, CUDA 9.1 and Nvidia GTX 1080.
I get this error:
_cmake -DWITH_FFMPEG=OFF -DWITH_CUDA:BOOL=ON -DCMAKE_INSTALL_PREFIX:PATH=/home/shared/scipion/software . > /home/shared/scipion/software/log/opencv_cmake.log 2>&1
Error: target 'software/tmp/opencv-2.4.13/Makefile' not built (after running 'cmake -DWITH_FFMPEG=OFF -DWITH_CUDA:BOOL=ON -DCMAKE_INSTALL_PREFIX:PATH=/home/shared/scipion/software . > /home/shared/scipion/software/log/opencv_cmake.log 2>&1')_

and the compilation stops.
I also attached the output from the command line and two logs connected with opancv_cmake error.
[CMakeError.log](https://github.com/I2PC/scipion/files/2213830/CMakeError.log)
[CMakeOutput.log](https://github.com/I2PC/scipion/files/2213831/CMakeOutput.log)
[OpenCV_error.txt](https://github.com/I2PC/scipion/files/2213832/OpenCV_error.txt)

I tried running with `./scipion install -j 5 --no-opencv` and that finished just fine. If I understood correctly one needs OpenCV to use CUDA so that is why I hope we can figure this one out.

I had one previous issue if these two could be in any way connected.
[https://github.com/I2PC/scipion/issues/1698](url)

**Comment by azazellochg** [comment]
Hi @eMKiso , few notes here:

1. you should use './scipion install' and not 'scipion ./scipion install'
2. The opencv problem you have is described in https://github.com/I2PC/scipion/issues/1584
3. OpenCV, as far as I know is required only for Xmipp optical flow and not needed if you want to run other CUDA programs (mc2/gctf etc). So, --no-opencv flag is a right way to do it.

**Comment by eMKiso** [comment]
Hi @azazellochg, 
1.  The word scipion before `./scipion install` is just the name of the current folder. I use a flavour of zsh and it shows the name of the current folder.
2. OK so if I understand correctly it will be absent in the next release.
3. Great

Thank you for all the information!

**Comment by azazellochg** [comment]
Hi,
Oh, I was wrong then about the first point. As for opencv error, hopefully
it will be fixed in the next release.

Thanks for the feedback!

**Comment by pconesa** [comment]
In Ubuntu 18 we've found that scipion installation does not found: videoio.h
From your error.log:

> home/shared/scipion/software/tmp/opencv-2.4.13/CMakeFiles/CMakeTmp/CheckIncludeFile.c:1:10: fatal error: sys/videoio.h: No such file or directory  #include <sys/videoio.h>

We added a note in the documenteation for Ubuntu 18:
https://github.com/I2PC/scipion/wiki/How-to-Install-1.1-sources#step2-dependencies

Try:
`sudo apt-get install libreadline6-dev`
 And install again.
>

**Comment by pconesa** [comment]
To be honest, I can't remember if the previous line installs the videoio.h.

**Comment by eMKiso** [comment]
I'd say it doesn't.
I had `libreadline6-dev` install before attempting to compile scipion.

**Comment by eMKiso** [comment]
Unfortunately  I also figured out that we need opencv for `motioncor2`. 
`motioncor2` will not install without opencv if I am not mistaken.

**Comment by azazellochg** [comment]
it cant be...
```
ldd ~/soft/scipion/software/em/motioncor2-1.1.0/bin/MotionCor2_1.1.0-Cuda80 
        linux-vdso.so.1 =>  (0x00007fffd1e80000)
        libcufft.so.8.0 => /public/EM/CUDA/cuda-8.0/lib64/libcufft.so.8.0 (0x00007f591ebd4000)
        libcudart.so.8.0 => /public/EM/CUDA/cuda-8.0/lib64/libcudart.so.8.0 (0x00007f591e96e000)
        libcuda.so.1 => /lib64/libcuda.so.1 (0x00007f591ddce000)
        libtiff.so.5 => /lib64/libtiff.so.5 (0x00007f591db5a000)
        libpthread.so.0 => /lib64/libpthread.so.0 (0x00007f591d93e000)
        librt.so.1 => /lib64/librt.so.1 (0x00007f591d736000)
        libdl.so.2 => /lib64/libdl.so.2 (0x00007f591d532000)
        libstdc++.so.6 => /lib64/libstdc++.so.6 (0x00007f591d22b000)
        libm.so.6 => /lib64/libm.so.6 (0x00007f591cf29000)
        libc.so.6 => /lib64/libc.so.6 (0x00007f591cb5c000)
        libgcc_s.so.1 => /lib64/libgcc_s.so.1 (0x00007f591c946000)
        libnvidia-fatbinaryloader.so.390.67 => /lib64/libnvidia-fatbinaryloader.so.390.67 (0x00007f591c6fa000)
        libjbig.so.2.0 => /lib64/libjbig.so.2.0 (0x00007f591c4ee000)
        libjpeg.so.62 => /lib64/libjpeg.so.62 (0x00007f591c299000)
        libz.so.1 => /lib64/libz.so.1 (0x00007f591c083000)
        /lib64/ld-linux-x86-64.so.2 (0x00007f5927a22000)
```

**Comment by eMKiso** [comment]
You are correct, I had to use `--no-xmipp` when installing `motioncor2`.

**Comment by azazellochg** [comment]
@eMKiso , could you try the following:
```
cd software/tmp/opencv-2.4.13
cmake -DWITH_FFMPEG=OFF -DWITH_CUDA:BOOL=ON -DWITH_LIBV4L=ON -DWITH_V4L=OFF -DCMAKE_INSTALL_PREFIX:PATH=/home/shared/scipion/software . > /home/shared/scipion/software/log/opencv_cmake.log 2>&1
```
and see if opencv compiles successfully?
