### ISSUE TITLE
use regular expression in import to avoid importing certain files

### ISSUE THREAD

**Issue by rmarabini** [I2PC/scipion#1702]
I though this request was already an issue but I cannot find it.

Modify import movies so some directories can be skipped. Wildcards are not enought for this function but regular expressions will do the trick. 

A possible way to do this is to  get a list with all the files under a directory and then apply the regular expresion to the list.

I look to the import movie code and the relevnt methods seems to be in file base.py directory protocol_import.  See for example: getPattern. Unfortunately, I do not understand the code there. For example

        pattern = expandPattern(fullPattern.replace("$", ""))
        match = re.match('[^#]*(#+)[^#]*', pattern)

what are we doing in the second line and why we do need the first one?

**Comment by delarosatrevin** [comment]
HI @yaizar I completely agree with you that 4 options for this advanced parameters seems a bit too much. I think it would be good to investigate how would be the easiest way for users to take advantage of this feature. In my opinion, regex are a bit confusing, although just the batch one might be more familiar. 

One idea could be to have only an string where one can specify the type of blacklist:
e. g:
REGEX: (.*)GRID_....
DATE: >2019/01/12:HH:MM:SS (here the time format should be clear)
etc
This will allow to implement future cases later, if needed.

**Comment by azazellochg** [comment]
I would rather move this group to a separate tab after "Frames", looks like to many options on one screen..

**Comment by yaizar** [comment]
Well the idea is to not keep all the options :)

**Comment by yaizar** [comment]
OK I take it back, looks like at CNB they want them all. They say that the first option (blacklist a set) would probably be the most common but that there are many scenarios and the flexibility of the others would be appreciated.

**Comment by yaizar** [comment]
so when I was working on #1898 I realized we already had a blacklist that at least around here nobody seemed to be aware of, but its only for streaming
![image](https://user-images.githubusercontent.com/4609687/51384801-b1a6a200-1b1d-11e9-848e-22e62e9179de.png)
Should we keep this or remove?
Current blacklist implementation:

![image](https://user-images.githubusercontent.com/4609687/51384999-3e516000-1b1e-11e9-948e-11012a8ca145.png)


The **Blacklist File** (help message is for this param) is meant to contain regular expressions or file names, I personally don't like much the label I've put there but I can't think of an appropriate name... anyone has suggestions?

**Comment by yaizar** [comment]
Important to note that current blacklist works both in streaming and not streaming, previous one only for streaming.
