### ISSUE TITLE
labels stop working after a while

### ISSUE THREAD

**Issue by rmarabini** [I2PC/scipion#1703]
I have several projects in which I cannot add any further label. If I add a label everything seems to be OK, that is, protocol changes to a new color but if I exit scipion and restart it again the label is gone. If you check the settings.sqlite database, the old labrels are there but not the new labels :-(

**Comment by rmarabini** [comment]
I have exited many times the project. I do not recall each of them but at present, in that project, if a exit  through the menu the new lables are not added.

**Comment by pconesa** [comment]
Yes...recently we have discovered that if you exit through the menu they are never saved....what happens if you use the native "x" (close) button ?

**Comment by pconesa** [comment]
Is the code already in Devel? Was there a PR for the "exit" fix? @fonsecareyna82
