### ISSUE TITLE
relion - extract does not work when streaming

### ISSUE THREAD

**Issue by JuhaHuiskonen** [I2PC/scipion#1704]
I am running CTFfind4 and Xmipp autopicking in streaming mode. However, when I try to extract the particles using relion extract, it fails immediately. 

00033:     File "/gpfs2/well/strubi/juha/apps/scipion-1.2/pyworkflow/em/packages/relion/protocol_extract_particles.py", line 566, in _preprocessMicrographRow
00034:       img.setCTF(self.ctfDict[img.getMicName()])
00035:   AttributeError: 'ProtRelionExtractParticles' object has no attribute 'ctfDict'
00036:   Protocol failed: 'ProtRelionExtractParticles' object has no attribute 'ctfDict'

**Comment by azazellochg** [comment]
I think this was fixed in 1.2.1.... @delarosatrevin ?

**Comment by delarosatrevin** [comment]
What version of Scipion are you using? I will strongly recommend release-1.2.1, that will be the upcoming release soon. It has many bugfixes and features, most of them related to streaming.
