### ISSUE TITLE
Scipion (pluginized) fails when open projects.  PLEASE, URGENT!! 

### ISSUE THREAD

**Issue by josuegbl** [I2PC/scipion#1728]
The error below occurs when you install a new copy of scipion (plugin version) and try to execute ./scipion.

Scipion  (2018-08-17)  (devel-pluginization f07516d)

>>>>> python  /home/josuegbl/SOFTWARE/scipion-pluginization/pyworkflow/apps/pw_manager.py 
Xmipp binaries not found. Ghost active.....BOOOOOO!
  > See scipion install --list to install Xmipp. 
/home/josuegbl/SOFTWARE/scipion-pluginization/software/lib/python2.7/site-packages/matplotlib/font_manager.py:273: UserWarning: Matplotlib is building the font cache using fc-list. This may take a moment.
  warnings.warn('Matplotlib is building the font cache using fc-list. This may take a moment.')
Traceback (most recent call last):
  File "/home/josuegbl/SOFTWARE/scipion-pluginization/pyworkflow/apps/pw_manager.py", line 38, in <module>
    ProjectManagerWindow().show()
  File "/home/josuegbl/SOFTWARE/scipion-pluginization/pyworkflow/gui/project/project.py", line 365, in __init__
    ProjectBaseWindow.__init__(self, title, minsize=(750, 500), **kwargs)
  File "/home/josuegbl/SOFTWARE/scipion-pluginization/pyworkflow/gui/project/base.py", line 65, in __init__
    Window.createMainMenu(self, self.menuCfg)
  File "/home/josuegbl/SOFTWARE/scipion-pluginization/pyworkflow/gui/gui.py", line 376, in createMainMenu
    self._addMenuChilds(menu, menuConfig)
  File "/home/josuegbl/SOFTWARE/scipion-pluginization/pyworkflow/gui/gui.py", line 391, in _addMenuChilds
    self._addMenuChilds(submenu, sub)  # recursive filling
  File "/home/josuegbl/SOFTWARE/scipion-pluginization/pyworkflow/gui/gui.py", line 404, in _addMenuChilds
    image=self.getImage(sub.icon.get()),
  File "/home/josuegbl/SOFTWARE/scipion-pluginization/pyworkflow/gui/gui.py", line 371, in getImage
    maxheight=maxheight)
  File "/home/josuegbl/SOFTWARE/scipion-pluginization/pyworkflow/gui/gui.py", line 155, in getImage
    from PIL import Image
  File "/home/josuegbl/SOFTWARE/scipion-pluginization/software/lib/python2.7/site-packages/PIL/Image.py", line 61, in <module>
    from PIL import _imaging as core
ImportError: libtiff.so.3: cannot open shared object file: No such file or directory

**Comment by pconesa** [comment]
Hi @josuegbl, it seems scipion is not detecting xmipp. Check you have latest xmipp code and is compiled. I think this might help: https://github.com/I2PC/xmipp/wiki/Migrating-branches-from-nonPluginized-Scipion-to-the-new-Scipion-Xmipp-structure#xmipp-installation.  Then check the xmipp_home variable points to you xmipp build directory

**Comment by josuegbl** [comment]
Thanks @pconesa for answer me. There is a thing that I dont fully understand: If scipion is almost pluginized, why I need install xmipp to simply see my projects list? I supposed  that the idea of "xmipp ghost" was to open projects and (maybe) run some protocols, of course no xmipp-based such as eman or MC2, without the necessity to install xmipp. Thanks

**Comment by delarosatrevin** [comment]
Yes @josuegbl , this is the idea. Maybe we need to do some polishing about it.

**Comment by dmaluenda** [comment]
I think that this error is not for the ghost. The warning is triggered but the error seems to come from the pillow module and the tiff library..

Do you have installed scipion from 0 (after a git clone) or just checking out the devel-pluginization branch?

**Comment by josuegbl** [comment]
@dmaluenda. Yes I installed a fresh version of scipion (git clone) and I did checkout to devel-pluginization branch. After checkout, I executed "./scipion  install". I think there are some bugs in the code since once xmipp is not installed by default, several libs are not installed too. @dmaluenda, could you try reproduce this? Thanks.

**Comment by pconesa** [comment]
@josuegbl there is still one piece missing. Scipion should be able to load and discover the xmipp plugin and ask the xmipp plugin to install the binaries...This is now a manual process and is one of my priorities to  be able to complete xmipp installation through xmipp-plugin...Until then, you should install xmipp aside and tell scipion (XMIPP_HOME) where lates xmipp is.

**Comment by delarosatrevin** [comment]
There is something that is still not clear to me. Who is now responsible for installing Python and the required modules? scipion?, xmipp-plugin?, the user/developer?

**Comment by pconesa** [comment]
Scipion should install what is necessary, python, modules...some libraries have been moved to xmipp since they were exclusive to xmipp.  Now....although xmipp is needed for almost anything we can decide if:
1.-  scipion installation triggers xmipp plugin installation + binaries
2.- scipion suggest xmipp installation
3.- User manually do it.

I was aiming for 1.

**Comment by delarosatrevin** [comment]
I'm more in favor of 2. 

1 is more what we have now...and then the ugly --no-xmipp flag we need to use for other plugins.

**Comment by pconesa** [comment]
well I'm sure we can avoid the --no-xmipp if already present and go for 1. But it's also ok for me 2.

**Comment by josuegbl** [comment]
solution: add tiff lib as a dependency of pillow.

**Comment by dmaluenda** [comment]
The tiff lib was deleted during the cleaning of only-for-Xmipp libraries...

Thank you @josuegbl for detecting the bug!!

**Comment by dmaluenda** [comment]
In fact it was with `default=False` and nobody was depending on it. We have leaved as `default=False` but puting the dependency on Pillow (like jpeg).

This is done in devel-pluginization branch [ commit: 364fb2278dab145a4e0c1898a95eef71d633dbda]

**Comment by pconesa** [comment]
Can we close this?
