### ISSUE TITLE
label icons are not colored

### ISSUE THREAD

**Issue by azazellochg** [I2PC/scipion#1733]
When in standard view all labels are black circles:

![screenshot_20180818_231247](https://user-images.githubusercontent.com/6952870/44303593-66a11c80-a33c-11e8-8f9a-dc9b352dbd41.png)

When I toggle to label view, it's correct:
![screenshot_20180818_231303](https://user-images.githubusercontent.com/6952870/44303596-859fae80-a33c-11e8-98b9-b01d3b914abc.png)

Is it a bug or a feature?

**Comment by pconesa** [comment]
Well ..it was design that way. Think that a protocol migth have more than one label assigned ...but maybe, when by here is one label, most always, the circle could have that color.

**Comment by azazellochg** [comment]
Got it, thanks!
