### ISSUE TITLE
XmippProtExtractParticles is not closing the stream

### ISSUE THREAD

**Issue by majtner** [I2PC/scipion#1738]
When executed in streaming, _streamState=1 even after protocol is finished.

**Comment by pconesa** [comment]
I've fixed that in release 1.2.1. not sure if is already in devel.

**Comment by majtner** [comment]
I started from devel-pluginization and I do not have this line. I will test it tomorrow with this change.
Thank you!

**Comment by pconesa** [comment]
Ok, probably devel-pluginizacion needs a devel update.

**Comment by dmaluenda** [comment]
Yes, on Monday we shall sync all branches and repositories :p

**Comment by pconesa** [comment]
I'm closing this issue. Code is migrated and already in devel-pluginization. Feel free to reopen it if I'm wrong or missed something.
