### ISSUE TITLE
'gctf - CTF local refinement' fails with continue

### ISSUE THREAD

**Issue by JuhaHuiskonen** [I2PC/scipion#1748]
This job died for some reason. When I try to continue it, I get:

00076:     File "/gpfs2/well/strubi/juha/apps/scipion-1.2.1/pyworkflow/em/packages/gctf/protocol_gctf_refine.py", line 606, in _prepareCommand
00077:       sampling = self._getMicrographs().getSamplingRate() * self.downFactor
00078:   AttributeError: 'ProtGctfRefine' object has no attribute 'downFactor'
00079:   Protocol failed: 'ProtGctfRefine' object has no attribute 'downFactor'

**Comment by azazellochg** [comment]
Hi @JuhaHuiskonen , unfortunately it will take a while to fix this, since the protocol requires quite a lot of refactoring. Sorry about that.
