### ISSUE TITLE
Scipion don't run when ONE project is wrong

### ISSUE THREAD

**Issue by dmaluenda** [I2PC/scipion#1758]
Scipion get an error when in one project there is not a project.sqlite
![image](https://user-images.githubusercontent.com/30288932/45368048-ed1ae800-b5e2-11e8-9d4f-9cdf643a1863.png)

The raise is triggered adhoc
![image](https://user-images.githubusercontent.com/30288932/45368157-3c611880-b5e3-11e8-991a-ffdc97b03157.png)

May be getting just a warning it's enough to keep the functionality of the rest of the projects

**Comment by pconesa** [comment]
Is this....devel-pluginization?.....without xmipp?

**Comment by dmaluenda** [comment]
Yes, it is [devel-pluginization](https://github.com/I2PC/scipion/blob/a32ac0e884fce21909b374eab8746e06c315ef05/pyworkflow/project.py#L235) and without having xmipp installed (but I think that this is independent of xmipp installation).

**Comment by pconesa** [comment]
@delarosatrevin , I think you commented some useful lines temporary.....I guess they can be uncommented?
`
      for i, p in enumerate(self.manager.listProjects()):
            # try:
            project = self.manager.loadProject(p.getName(), chdir=False, loadAllConfig=False)
            # Add creation time to project info
            p.cTime = project.getCreationTime()
            # Add if it's a link
            p.isLink = project.isLink()
            # If it's a link, get the linked folder
            if p.isLink:
                p.linkedFolder = os.path.realpath(project.path)
            frame = self.createProjectLabel(parent, p, color=colors[i%2])
            frame.grid(row=r, column=0, padx=10, pady=5, sticky='new')
            r += 1
            # except Exception, ex:
            #     print "ERROR loading project: %s" % p.getName()
            #     print ex
`

**Comment by delarosatrevin** [comment]
Yes, I'm sorry for that...I wanted to see the actual error and probably I forgot to uncomment and was commited. Go ahead and revert that.
