### ISSUE TITLE
module' object has no attribute 'xmipp3'

### ISSUE THREAD

**Issue by vabrishami** [I2PC/scipion#1760]
I am now moving to scipion pluginized. So I installed Xmipp and compiled it. I have a seperate Sscipion for pluginization which is already in the devel-pluginization branch, updated and compiled. Then I made a link to xmipp build in software/em and another to scipion-em-xmipp in Software/lib/python2.7/site-packages/xmipp3. So I think everything is fine. But when I wanted to execute the code, this error raised up:

![image](https://user-images.githubusercontent.com/9831418/45408085-0029c880-b674-11e8-94de-546d22e7e6c8.png)

Do you have any idea?

**Comment by delarosatrevin** [comment]
Hi Vahid, take a look at the ~/.config/scipion/scipion.conf file and make sure you are not mixing it with the non-pluginazed version. XMIPP_HOME should be defined differently from one to another.

**Comment by dmaluenda** [comment]
Hi,

The xmipp software looks fine (except for the renaming of the 'import xmipp' to 'import xmippLib' claimed by the warrning, but not critical).

The error shown in the image suggests that some error is either in the <xmipp-plugin>/xmipp3/tests/__init__.py or <xmipp-plugin>/xmipp3/tests/test_protocols_mics.py (probaby this).

It seems a sintactic or importing error. Therefore, try to run 'scipion python <xmipp-plugin>/xmipp3/tests/test_protocols_mics.py' in order to run the test as a python script and get the traceback of the error.

In which branch is the xmipp plugin. Nowadays we recommend for the all xmipp repos (scipion-em-xmipp, xmipp, xmippCore and xmippViz) the devel branch [default], as we are fixing bugs.

Thanks!

**Comment by vabrishami** [comment]
Hi David,
Thanks for the clues. For the last comment, yes I am in the devel branch of all repos. However, for the first comment, I tried what you suggested, and it is the output:

Traceback (most recent call last):
  File "test_protocols_xmipp_mics.py", line 28, in <module>
    import unittest, sys
  File "/home/vahid/scipion_pluginized/software/lib/python2.7/unittest/__init__.py", line 64, in <module>
    from .main import TestProgram, main
  File "/home/vahid/scipion_pluginized/software/lib/python2.7/unittest/main.py", line 7, in <module>
    from . import loader, runner
  File "/home/vahid/scipion_pluginized/software/lib/python2.7/unittest/runner.py", line 7, in <module>
    from .signals import registerResult
  File "/home/vahid/scipion_pluginized/software/lib/python2.7/unittest/signals.py", line 2, in <module>
    import weakref
  File "/home/vahid/scipion_pluginized/software/lib/python2.7/weakref.py", line 14, in <module>
    from _weakref import (
ImportError: cannot import name _remove_dead_weakref

I think we use python 2.7.12; I read somewhere this problem wouldn't happen for python 2.714.

**Comment by delarosatrevin** [comment]
My guess here will be that you should use the same Python (or at least the same version) as the one that xmipp was compiled for, since we still have the binary dependencies for the libraries.

**Comment by vabrishami** [comment]
Can be since I am using system python to compile xmipp. Maybe I should use the one from Scipion? Anyway, the versions are exactly the same: 2.7.12.

**Comment by pconesa** [comment]
Not sure if it makes any difference but scipion version at devel is 2.7.14.

**Comment by vabrishami** [comment]
Yes, Pablo, it makes difference. You are right I will check it and let you know.

**Comment by vabrishami** [comment]
So this error raised:
from pyworkflow.em.headers import Ccp4Header
ImportError: No module named headers
There is nod header there, but convert_header?

**Comment by dmaluenda** [comment]
Seeing your reports, I guess that a 'git pull' is needed, at least in scipion but try it also for the xmipp to be sure. So,
```
cd <scipion-pluginized>
git pull
cd <xmipp-bundle>
./xmipp git pull
./xmipp
```

**Comment by vabrishami** [comment]
Thanks David. It works now properly. I did wrongly git pull.

**Comment by dmaluenda** [comment]
👍👍👍👍👍

Thanks to you!!
