### ISSUE TITLE
Can not add plugins

### ISSUE THREAD

**Issue by vabrishami** [I2PC/scipion#1765]
I compiled Scipion (scipion_pluginization) and also added xmipp as a plugin by first making a soft link to Xmipp plugin in Scipion python packages and then make a soft link to xmipp build folder. I did the same thing for Resmap.

scipion_pluginized/software/em/resmap-1.1.5s2 (soft link tobinaries)
scipion_pluginized/software/lib/python2.7/site-packages/resmap (link to plugin)
But after running Scipion, I can not still see Resmap protocols. I have a plugin myself which I can not embed in Scipion. So I thought to first try with Resmap to see if I can add it or not. 

P.S I have already executed ./scipion python scripts/inspect-plugins.py

**Comment by pconesa** [comment]
@vabrishami you have to link them to the python site-packages path
SCIPION_HOME/software/lib/python2.7/site-packages

Or add the PATH to the PYTHONPATH variable

I usually do this:
`export PYTHONPATH=$PYTHONPATH:/home/pablo/desarrollo/xmippBundle/src/scipion-em-xmipp/
`
But a link in python's site-packages should work too.
We'll review resmap to see if is already pluginized properly.

**Comment by vabrishami** [comment]
Yes, I did whatever you said. Yeah link for xmipp worked properly, but for resmap, No way :)

**Comment by pconesa** [comment]
checkout the other branch, for now: https://github.com/scipion-em/scipion-em-resmap/tree/newPluginStructure

**Comment by vabrishami** [comment]
Thanks! it works now properly. I really suffer from lacking a good documentation for developing plugins. So at the moment I just follow other plugins. Thanks again

**Comment by pconesa** [comment]
Sorry, @vabrishami . We are just starting with this new architecture. And probably now is good enough to improve the documentation a bit.
So far, the most up to date one should be here: 
https://github.com/I2PC/scipion/wiki/Creating-a-Plugin

Feel free to improve it
