### ISSUE TITLE
incomplete flags being passed during compilation of mpi4py

### ISSUE THREAD

**Issue by craigyk** [I2PC/scipion#177]
The compilation of the mpi4py Python module is not being passed the paths for the MPI installation.  Not sure if python setup.py is meant to use mpicc which is expected to add the correct paths and is not.  In any case, modifying the shell variables CPPFLAGS, LDFLAGS to add the include and lib paths for OpenMPI allowed mpi4py to finish compiling.

**Comment by delarosatrevin** [comment]
Thanks again for reporting us this problem. Did you got this issue with an OpenMPI installed in a non-standard location? We had never found this, maybe just luck. Anyway, I agree that will be better to pass the lib and include MPI path defined in scipion.conf. It should not be difficult to modify to pass it [here](https://github.com/biocompwebs/scipion/blob/4a0e757b1d098e98d0973b453671f07d4d4ca020/install/funcs.py#L478-L482)

**Comment by delarosatrevin** [comment]
I think this issue is related to #364 .
