### ISSUE TITLE
Show alert if chimera not installed

### ISSUE THREAD

**Issue by yaizar** [I2PC/scipion#1771]
When we don't have chimera installed, nothing happens after clicking the button. It would be good to show a message similar to when we don't have a package/plugin and we can't find the PACKAGE_HOME (Will also help directing the user to the config file in case the problem lays there)

**Comment by pconesa** [comment]
hehehehe, you said you new java, right ? @ldelcano

**Comment by pconesa** [comment]
This is not that easy....Java calls back Scipion like:
python pwworkflow/apps/ pw_chimera_client.py projector -input xxxxx

So java is only aware of SCIPION_HOME. but not aware of CHIMERA_HOME.

At least from java is hard to do. Maybe from chimera client.
