### ISSUE TITLE
Export workflow GUI issues

### ISSUE THREAD

**Issue by azazellochg** [I2PC/scipion#1778]
**Describe the bug**
Bug/feature request for export workflow GUI window.

**To Reproduce**
1. Select protocol boxes
2. Right click on Export
3. In appearing GUI you cannot sort files by name/size/date. Also you have to type the name into File field, bacause clicking on any file does not change the default 'workflow.json' name.

**Expected behavior**
1. Ability to sort files by name/size/date (as in Project -> Import workflow)
2. Filename field should change when you click/choose a file.

**Screenshots**
![screenshot_20180924_132102](https://user-images.githubusercontent.com/6952870/45951857-02d5d780-bffd-11e8-941d-fc3c781201bc.png)

**Desktop (please complete the following information):**
 - Version 1.2.1

**Comment by pconesa** [comment]
Thanks @azazellochg .
