### ISSUE TITLE
html report: protocol list is not sorted?

### ISSUE THREAD

**Issue by azazellochg** [I2PC/scipion#1779]
**Describe the bug**
Protocol list is not sorted by neither ID or creation date. I think it should be sorted as the tree in project GUI to follow the logic.

**Screenshots**
![screenshot_20180924_150452](https://user-images.githubusercontent.com/6952870/45956811-66670180-c00b-11e8-9012-0152cd2ed568.png)

**Desktop (please complete the following information):**
 - Version 1.2.1

**Comment by azazellochg** [comment]
Huh, actually yes @pconesa !

**Comment by pconesa** [comment]
Ok, at least it follows something! ;-)....the ID will not warranty the right order in few cases..and to follow the order in the tree.....well....not an easy thing. But also once you've added them, there is no way to reorder them...tricky!

**Comment by azazellochg** [comment]
okay, maybe it is not worth it, I should have just added protocol to monitor in a right order xD

**Comment by pconesa** [comment]
I was also thinking that!

**Comment by pconesa** [comment]
Can I close it then?
