### ISSUE TITLE
scipion install build fails when using GCC 5.3

### ISSUE THREAD

**Issue by craigyk** [I2PC/scipion#178]
I tried to install using GCC 5.3 and a couple of packages fail during compilation (lapack is the first).  I know this might be an upstream issue, but just thought you'd like to know.

**Comment by delarosatrevin** [comment]
Thanks  a lot  for let us know. We will check about this issue.
What other packages failed? Have you installed gcc 5.3 on your own or it comes 
with some new Linux distro?

**Comment by craigyk** [comment]
I compiled and installed from source.  The most recent pull of scipion I did seemed to compile without problem though.

**Comment by delarosatrevin** [comment]
Weird...since we have not changed nothing related to the installation script since the time that you reported that issue. Can we close this issue?
