### ISSUE TITLE
cryoem installation fails with scipion binary installer 1.2.1

### ISSUE THREAD

**Issue by ckywong** [I2PC/scipion#1788]
Hello, I think I am running into the missing header files issue with Scipion 1.2.1. I downloaded the binary installer scipion_v1.2.1_2018-10-01_linux64.tgz and was able to install all included software except cryoem. When building cython, there was an error message:

> gcc -fno-strict-aliasing -g -O2 -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -I/opt/apps/Scipion/1.2.1_2018-10-01/software/include -fPIC -I/opt/apps/Scipion/1.2.1_2018-10-01/software/include/python2.7 -c /opt/apps/Scipion/1.2.1_2018-10-01/software/tmp/Cython-0.22/Cython/Plex/Scanners.c -o build/temp.linux-x86_64-2.7/opt/apps/Scipion/1.2.1_2018-10-01/software/tmp/Cython-0.22/Cython/Plex/Scanners.o
> /opt/apps/Scipion/1.2.1_2018-10-01/software/tmp/Cython-0.22/Cython/Plex/Scanners.c:8:22: fatal error: pyconfig.h: No such file or directory
>  #include "pyconfig.h"
>                       ^
> compilation terminated.
> error: command 'gcc' failed with exit status 1

Could somebody please take a look at it? Thanks a lot!

**Comment by pconesa** [comment]
@ldelcano Could you please have a look at this?.
@ckywong Are you especially interested in that package....it is very rarely used. Optionally, you could try installing from sources, my guess is that there are some heders missing that the Binary bundle does not have.

**Comment by delarosatrevin** [comment]
I think a more general problem here is that we are still mixing installation with building...I would argue that when downloading the binaries, you are working in "installation mode"...and not building process should be involved. If you are compiling from sources, then all header/devel code should be ready to use and link (i.e.  "building mode" )

**Comment by ldelcano** [comment]
Yes, but cryoem is a module that compiles cython which requires header files from numpy whis is currently packed with Scipion binaries (without any source file). Solution is to provide those headers on scipion binaries or have a cython already compiled.

**Comment by ldelcano** [comment]
Not only numpy headers, also python headers

**Comment by ldelcano** [comment]
Generated new binaries. Ready to download on the web.
