### ISSUE TITLE
How to change CONDA_ROOT in scipion?

### ISSUE THREAD

**Issue by n1kt0** [I2PC/scipion#1791]
Hello,
As the subject line states i need to change the automatically deduced path for conda in scipion because it uses some conda from eman on the cluster where i don't have write permissions instead of my local installation?

Many thanks in advance.

**Comment by pconesa** [comment]
Is that an enviromental variable that eman reads?

**Comment by pconesa** [comment]
And....does this refer to V1.2.1?

**Comment by n1kt0** [comment]
yes, it does! I suspect it is taken from the deduced path from mpi_bindir as it is probably assembled together in a path variable.

**Comment by pconesa** [comment]
thanks @n1kt0 , I need help here, I'm not very familiar with how Eman runs
@azazellochg , @delarosatrevin ?

**Comment by n1kt0** [comment]
since mpiCC nor conda from eman is not on my path, I would like to know how the search for the binaries of scipion is done, perhaps there are some clues...

**Comment by pconesa** [comment]
We have a config file that scipion reads: https://github.com/I2PC/scipion/blob/master/config/templates/scipion.template#L26
For eman, by default, point to the path where eman 2.12 ends up, if eman is installed using:
`scipion install eman`

**Comment by pconesa** [comment]
This version is not compatible with latest eman version 2.2, is that what you want to use.

**Comment by n1kt0** [comment]
No, I would like to use my locally installed conda in my home folder and install eman via scipion but it choses our already installed EMAN which is the version 2.2.

**Comment by n1kt0** [comment]
That works, what you proposed. I ended up copying the config.template file and modifying the paths by myself instead of running `./scipion config` which deduced other paths.

**Comment by pconesa** [comment]
I'm closing this issue. Feel free to reopen it if I'm wrong or missed something.
