### ISSUE TITLE
Recursive error when try to import XmippViewer

### ISSUE THREAD

**Issue by dmaluenda** [I2PC/scipion#1797]
**Describe the bug**
When `from xmipp3.viewers import XmippViewer` is invoked a recursive import error is returned.

**To Reproduce**
I realized on that runing the inspect plugin for eman, so
1. Go to a pluginized version of Scipion with eman2 installed
2. run `./scipion python scripts/inspect-plugins.py eman2`
3. See the error in the viewers section

**Expected behavior**
We should manage this...

**Screenshots**
![](https://user-images.githubusercontent.com/30288932/46945877-5b394b80-d076-11e8-8202-d145941adf5a.png)

**Comment by rmarabini** [comment]
It sees that the wrapper is not finding the xmipp library.

Did you remember to link:

ln -s <xmipp_bundle>/src/scipion-em-xmipp/xmipp3 <pluginized-scipion>/software/lib/python2.7/site-packages/
and
ln -s <xmipp_bundle>/build <pluginized_scipion>/software/em/xmipp
---

P.S: It would be nice if xmipp installation script would perform these two actions

**Comment by delarosatrevin** [comment]
@rmarabini I don't think it is a good idea to link in python/site-packages or software/em/xmipp...I think it is better to handle this via the environment. I think linking/copying will prevent to use system or standard python in the future and more standard ways of installation. 

In my opinion, what would be really nice is that Xmipp is accesible as a Python package:
pip install xmipp

And also scipion and you can specify that scipion depends on xmipp. ;)

**Comment by azazellochg** [comment]
For eman2 viewer this was fixed in https://github.com/scipion-em/scipion-em-eman2/pull/9

**Comment by pconesa** [comment]
@dmaluenda , I'm closing this since it's not happening now.
