### ISSUE TITLE
spider-refinement protocol fails in the step1

### ISSUE THREAD

**Issue by mohsenkazemi** [I2PC/scipion#1801]
I have a set of particles to do 3D-refinement. I used spider protocol, but it fails in the first step (convertInputStep). Following is the log:

the log:

STARTED: convertInputStep, step 1
00013:     2018-10-18 09:14:26.761170
00014:   Traceback (most recent call last):
00015:     File "/home/mohsen/scipion/pyworkflow/protocol/protocol.py", line 190, in run
00016:     File "/home/mohsen/scipion/pyworkflow/protocol/protocol.py", line 237, in _run
00017:     File "/home/mohsen/scipion/pyworkflow/protocol/protocol.py", line 233, in _runFunc
00018:     File "/home/mohsen/scipion/pyworkflow/em/packages/spider/protocol/protocol_projmatch.py", line 162, in convertInputStep
00019:     File "/home/mohsen/scipion/pyworkflow/em/packages/spider/protocol/protocol_projmatch.py", line 256, in _writeGroupFiles
00020:     File "/home/mohsen/scipion/pyworkflow/em/packages/spider/protocol/protocol_projmatch.py", line 379, in addParticle
00021:     File "/home/mohsen/scipion/pyworkflow/em/convert.py", line 178, in convert
00022:   XmippError: Image::openFile cannot open: Runs/006202_ProtImportParticles/extra/FoilHole_28459060_Data_28451961_28451962_20180629_0057-19401_288_0.stk
00023:   Protocol failed: Image::openFile cannot open: Runs/006202_ProtImportParticles/extra/FoilHole_28459060_Data_28451961_28451962_20180629_0057-19401_288_0.stk
00024:   FAILED: convertInputStep, step 1

The point is that using "scipion show" I can see the particles. Even, in the input form of the spider-refinement protocol, I can see the particles well!

I am using scipion v1.2.1 (ubuntu 16).

**Comment by pconesa** [comment]
Thanks @mohsenkazemi

**Comment by pconesa** [comment]
@azazellochg @delarosatrevin any hint?

**Comment by azazellochg** [comment]
I'll have a look this week-end

**Comment by mohsenkazemi** [comment]
@azazellochg let me know if you think I have to share the input particles with you...

**Comment by azazellochg** [comment]
@mohsenkazemi could you export ctf from this particles and send it to me? I don't have any ctf for spider stacks around...

**Comment by azazellochg** [comment]
oh, wait, stk is not spider format.. I can find particles with ctf!

**Comment by azazellochg** [comment]
@mohsenkazemi I couldn't reproduce this error using the similar filenames as yours. Convert input works:
![screenshot_20181018_214223](https://user-images.githubusercontent.com/6952870/47182980-cefd8180-d31e-11e8-8b72-3d26aaf26fa4.png)

**Comment by mohsenkazemi** [comment]
@azazellochg , could you do a test with attached dataset? The point is that, using this dataset, I can perform refinement with highres, proj-matching and relion!
[007939_ProtImportParticles.tar.gz](https://github.com/I2PC/scipion/files/2493631/007939_ProtImportParticles.tar.gz)

**Comment by azazellochg** [comment]
The attached archive has only symlinks to non-existing files

**Comment by mohsenkazemi** [comment]
Yes! you are right...I attached the wrong folder...Anyway, apparently, there should be a problem from my side (either my scipion installation! or the dataset) as you can run spider smoothly. So, I will close this issue.
Thanks

**Comment by azazellochg** [comment]
@mohsenkazemi Let me know if you figure it out!
