### ISSUE TITLE
methods fail when article has no keywords

### ISSUE THREAD

**Issue by azazellochg** [I2PC/scipion#1804]
**Describe the bug**
Methods tab fails to display references when there are no keywords in bibtex reference

**To Reproduce**
1. Find a bibtex.py with @article that does not have keywords in the dict
2. Open a project with the protocol referencing this citation
3. See error:
`Could not load all methods:local variable 'label' referenced before assignment`

**Expected behavior**
It should work irrespectively of the presence of keywords.

**Desktop (please complete the following information):**
 - Devel-pluginization branch

**Comment by azazellochg** [comment]
cannot reproduce anymore after pluginisation completed.

**Comment by azazellochg** [comment]
I was finally able, to find the root of the issue: every line inside @article{} should end with a comma. I had a few bibtex ending with:
```
...
author = "Grant, T. and Grigorieff, N."
}
```

This will stop bibtex from parsing the authors. Overall this issue is coming from bibtex package, not scipion.

**Comment by delarosatrevin** [comment]
Thanks @azazellochg ! Anyway, we should be protected, so a failure parsing the bibtex should not bring everything down. ;)
