### ISSUE TITLE
test with grep fails weirdly

### ISSUE THREAD

**Issue by pconesa** [I2PC/scipion#1811]
In an empty scipion installation:

If I do scipion test it works fine, some test cannot be loaded due to absence of  plugins in workflow tests.

But if I do:

>>>>> python  scripts/run_tests.py --show --grep TestProtocolExe
Running tests....
 > xmipp3 plugin not found. No module named xmipp3.convert
   Called by /home/pablo/desarrollo/scipion/pyworkflow/tests/em/protocols/test_protocols_ctf_monitor.py, line 35
   See 'scipion installp --help' to install it.

Line 35 at test_protocols_ctf_monitor.py is this one:

ProtCTFFind = importFromPlugin('grigoriefflab.protocols', 'ProtCTFFind', doRaise=True)

**Comment by pconesa** [comment]
I need to clarify that I had one plugin...grigorieflab. That might explain why.

**Comment by dmaluenda** [comment]
Ok. But this doesn't explain the missmatch between the error message and the adressed line...
