### ISSUE TITLE
add goCTF software

### ISSUE THREAD

**Issue by azazellochg** [I2PC/scipion#1812]
Should be easy to add this new CTF estimation program. Options are essentially the same as for ctffind4.

paper: https://www.biorxiv.org/content/early/2018/09/25/426189
program binary: https://sites.google.com/umich.edu/min-su-ph-d/home

**Comment by azazellochg** [comment]
Below is an example of _go.star file. As long as you star file contains _rlnCoordinateX, _rlnCoordinateY, _rlnDefocusU, _rlnDefocusV, it should run.
The rest are not important to goCTF. Also, _rlnDefocusU, _rlnDefocusV will remain the same value, thus _rlnDefocusAngle doesn’t do anything.

```
data_

loop_ 
_rlnMicrographName #1 
_rlnCoordinateX #2 
_rlnCoordinateY #3 
_rlnImageName #4 
_rlnDefocusU #5 
_rlnDefocusV #6 
_rlnDefocusAngle #7 
_rlnVoltage #8 
_rlnSphericalAberration #9 
_rlnAmplitudeContrast #10 
_rlnMagnification #11 
_rlnDetectorPixelSize #12 
_rlnCtfFigureOfMerit #13 
_rlnAnglePsi #14 
_rlnAutopickFigureOfMerit #15 
_rlnClassNumber #16 
18aug31a_002_00067gr_00016sq_00002hl_00002en-a.mrc  3055.000000   305.000000 000001@Particles/18aug31a_002_00067gr_00016sq_00002hl_00002en-a_particles_s3.mrcs 29389.769531 30483.869141    80.000000   300.000000     2.700000     0.070000 4950
5.000000    15.000000     0.039430   135.000000     1.542709            1 
18aug31a_002_00067gr_00016sq_00002hl_00002en-a.mrc  1090.000000   358.000000 000002@Particles/18aug31a_002_00067gr_00016sq_00002hl_00002en-a_particles_s3.mrcs 29389.769531 30483.869141    80.000000   300.000000     2.700000     0.070000 4950
5.000000    15.000000     0.039430   205.000000     0.640324
```

**Comment by azazellochg** [comment]
[goctf-1.1.0-linux-64.tar.gz](https://github.com/I2PC/scipion/files/3805238/goctf-1.1.0-linux-64.tar.gz)

**Comment by pconesa** [comment]
Should I add it to the server?

**Comment by azazellochg** [comment]
If you want to, I do not have time to make this plugin.

**Comment by pconesa** [comment]
Ok, I was asking because you've assigned it to yourself.

**Comment by pconesa** [comment]
How popular is goCTF? Does it worth the effort?

**Comment by azazellochg** [comment]
I don't think it has any popularity. There is no release since last year and I haven't seen any papers using it.

**Comment by pconesa** [comment]
Ok, I'm closing this. I'll reopen if we need something for a student. Thanks @azazellochg
