### ISSUE TITLE
deprecate motioncorr/dosefgpu?

### ISSUE THREAD

**Issue by azazellochg** [I2PC/scipion#1813]
Motioncorr (v2.1) was last released 5 years ago. Are there people still using it? Is it used/asked by people at workshops @pconesa @delarosatrevin @cossorzano ? I suggest we can retire it and clean up a bit the current movie alignment protocol.

**Comment by delarosatrevin** [comment]
I totally agreed that we should deprecate it in the plugin.

**Comment by joshua4289** [comment]
Also the developer of the old method recommended new motioncor in a CCPEM discussion

**Comment by azazellochg** [comment]
okay then! https://github.com/scipion-em/scipion-em-motioncorr/pull/5
