### ISSUE TITLE
Bsoft viewer is now the default volume viewer and chimera doest't open from the icon

### ISSUE THREAD

**Issue by dmaluenda** [I2PC/scipion#1850]
**Describe the bug**
From viewers refactorization, the default viewer for volumes becomes the Bsoft viewer. Additionally, when the Scipion viewer is chosen by right-click on a volumeObject, chimera doesn't open by clicking at the icon at top-right.

**To Reproduce**
1. Select a protocol with a volume as main output (i.e. Reconstract significance) 
2. Click on Analyze Results icon
3. See the Bsoft viewer opened with the outputVolume  **<- First issue!**
4. Close the Bsoft viewer
5. Right-click on the outputVolume
6. Select "Open with DataViewer"
7. Click on chimera icon at top-right
8. See that nothing happen, even no error in terminal  **<- Second issue**

**Desktop:**
 Version 2.0 Diocletian

**Comment by pconesa** [comment]
I have a fix for "Second issue"
