### ISSUE TITLE
gain reference information for movies is lost upon creating movie subset

### ISSUE THREAD

**Issue by andreanans** [I2PC/scipion#1852]
Hi,

I noticed that when you create a movie subset the gain reference associated with the movies is lost and you need to specify it as an additional parameter in motioncorr2.

**Comment by delarosatrevin** [comment]
Thanks @andreanans ! We will take a look at this. The gain reference information should definitively be carried on by the new subset of movies.

**Comment by pconesa** [comment]
Yep, @andreanans which version are you using?

**Comment by andreanans** [comment]
I'm using 1.2.1 (2018-10-01) Claudio

**Comment by pconesa** [comment]
I've did a quick check on Claudio (v1.2.1). It worked for me:

`
00020:   /home/pablo/desarrollo/scipion_alt/software/em/motioncor2-1.1.0/bin/MotionCor2_1.1.0-Cuda80  -InMrc "qbeta.mrc" -OutMrc "../../extra/qbeta_aligned_mic.mrc" -kV 300.0 -Trunc 0 -FmDose 0.0 -OutStack 0 -InitDose 0.0 -PixSize 1.0 -Tol 0.5 -Group 1 -Patch 5 5 -Throw 0 -LogFile ../../extra/micrograph_000001_ -FtBin 1.0 -MaskCent 0 0 -MaskSize 1 1 -Gain "/data/mario_dm4/20180212_1446_A023_G006_H489_D001_1.mrc"  -Dark "/data/mario_dm4/20180212_1446_A023_G006_H489_D001_1.mrc" -Gpu 0
`

**Comment by andreanans** [comment]
This was from a movie subset? Very strange! I can try re-installing I suppose?

**Comment by pconesa** [comment]
ummm, wait....I was going to ask if you've done something before.....a sub set?

**Comment by andreanans** [comment]
Exactly. I selected 10 movies from the import job to create a movie subset. When I run motioncor2 the gain information is not used.

**Comment by pconesa** [comment]
That's it, @andreanans , the subset is loosing the gain info...it shouldn't. Many thank for re porting it. We need to fix this.

**Comment by pconesa** [comment]
@andreanans , Is this is blocking you? How critical is this for you? Can't offer now a workaround other than sending a file back and forth to fix it...

**Comment by andreanans** [comment]
Hi,

It's not a huge deal but I will a have to revisit the past datasets to see if they were affected by the bug. I'm sure other people would need to check as well..

**Comment by delarosatrevin** [comment]
@pconesa I think the fix will not be that complicated. 
@andreanans we can also write some script to "patch" wrong subset with the correct gain and dark images if needed. This can be useful for already existing subsets and subsequent processing.

We can get back to you by next week.
