### ISSUE TITLE
Remove last image in a stack causes showj to have outOfBound indexes

### ISSUE THREAD

**Issue by cossorzano** [I2PC/scipion#187]

**Comment by delarosatrevin** [comment]
This issue happens if you visualize directly a xmd file, for example:

scipion show input_particles.xmd

And then try to remove the last row from the table.

**Comment by pconesa** [comment]
Checked in branch v1.0. with TestXmippWorkflow project. File Runs/000250_XmippProtExtractParticles/images.xmd and also with one of the stk files in extra folder. It has worked fine. Any concrete file to test with?

**Comment by delarosatrevin** [comment]
Fixed with the help of @airenzp , removed the selection after removing rows
