### ISSUE TITLE
Menu Project -> Notes

### ISSUE THREAD

**Issue by azazellochg** [I2PC/scipion#1875]
Scipion notes - not documented, default edit program should be the same as for displaying/editing conf files (Configuration->XX in project list window). Also I get an error when clicking on it:
![screenshot_20190106_132420](https://user-images.githubusercontent.com/6952870/50736584-6c01e500-11bf-11e9-9c05-60ebba440d0a.png)
Does it not create the new file automatically?

**Comment by JorMaister** [comment]
Hi Gregory, 
Now the first time the Notes submenu is clicked in a project, the file is automatically generated, and it will contain a few lines that explain what is it and how to manage its behavior via the conf file, like choosing the program that will open it from Scipion. The result can be observed below.
 
![image](https://user-images.githubusercontent.com/54907551/72063338-e507b100-32d9-11ea-9aad-9fd573361bfa.png)

On the other hand, I wasn't able to reproduce the error shown in the image above. Can you tell me in detail the actions carried out that resulted in that error?
