### ISSUE TITLE
Model building protocols in SPA view

### ISSUE THREAD

**Issue by azazellochg** [I2PC/scipion#1882]
Model building protocols should not be in SPA list.

**Comment by mmmtnez** [comment]
I agree with you, but sometimes I do not know... Look at this article:

http://www.jbc.org/content/early/2019/02/25/jbc.REV118.005602

https://www.ncbi.nlm.nih.gov/pmc/articles/PMC6442032/figure/F1/

**Comment by azazellochg** [comment]
So, then sample purificatino will also be in Scipion? Come on..

**Comment by mmmtnez** [comment]
You're right, but purifying "single particles" could be the first step in the "single particle analysis". Think about it. Maybe we have to adopt other less ambiguous names to delimit the type of tools included in each branch of Scipion.

**Comment by azazellochg** [comment]
Alright, I will remove it myself from my fork.

**Comment by pconesa** [comment]
may be now that are few they could be there....but at some point, model building protocols should have it's own view, otherwise SPA will become huge!! (already it is huge)

**Comment by delarosatrevin** [comment]
I agree with @azazellochg that we should not have these protocols in SPA...they can have their own view...and this is saved when you are working in a project...so if you are working on model building and change to its view...next time it will be the default in this project. 

We have also started with tomo...so it should also have a separated view...as @pconesa mentioned, SPA view is already quite crowded. 

To go a step further...I would propose to have even the basic data model for model building in a separate plugin, to avoid changes to it...to affect the scipion (or pyworkflow) core.

**Comment by pconesa** [comment]
@mmmtnez will create a model building view.

**Comment by mmmtnez** [comment]
Follows a list with the protocols that make sense to move to a model building view. Those protocols that end with "*" make sense to keep them in both places spa and model building

IMPORT
   volume *
  more -  atomic structure *
  more - sequence
  more - export to EMDB *

TOOLS - CALCULATORS
    chimera operate *
    chimera restore session *
    atomStructUtils operator *
   phenix superpose pdbs *

Model Building
   move all. The only protocol that may make sense to keep in SPA is 3d bionotes but I am not sure

**Comment by pconesa** [comment]
This is done.
