### ISSUE TITLE
All wizards improvements

### ISSUE THREAD

**Issue by azazellochg** [I2PC/scipion#1883]
- All wizards: enable scrolling values with mouse wheel, it is very difficult to adjust to a correct number. Especially annoying are the tiny arrows that are twice smaller than my mouse cursor!!!!!!!!!!!
![screenshot_20190106_141739](https://user-images.githubusercontent.com/6952870/50737158-50e6a380-11c6-11e9-960c-a2c93c05d45c.png)

- Also, for all frequencies wizards show values both in Angstrom and freq units (0.01-0.5 range). No 0.0 min values should be allowed. Same for radius wizards etc.: display both px and Angstroms.

**Comment by JorMaister** [comment]
Hi @azazellochg,

I've been checking this issue and all the Spinboxes (GUI component with the tiny arrows) were replaced by scales (valued-scroll bars). Also, the low range value was updated from 0 to 0.01, as you requested. 
![image](https://user-images.githubusercontent.com/54907551/72429205-b08b6d80-378f-11ea-9b48-262ac6b81b90.png)
![image](https://user-images.githubusercontent.com/54907551/72429433-3ad3d180-3790-11ea-9e55-9e9e17379b57.png)
The question is about displaying both values in pixels and angstroms in the radius filter. Should it be another scale component, being both synchronized?

**Comment by azazellochg** [comment]
Hi @JorMaister , I'm going to buy you a beer for doing this!
I think both px and Ang can be on the same scroll bar - like it's done for frequencies. Would I be able to use themouse scroll wheel for these?

**Comment by JorMaister** [comment]
Hi @azazellochg, unfortunately, that beer doesn't belong to me, I found that done when I was checking this issue xD. I'll check if it is possible to make that bars controlled also with the scroll wheel and I'll represent the radius filter the same as the frequency filter.

**Comment by JorMaister** [comment]
Hi @azazellochg, I've been working on the wizards. Most of them can be controlled now with both sliders and mousewheel. The layout has also been updated. I think there is one wizard missing in terms of mousewheel event, but I'll update it.

**Comment by azazellochg** [comment]
Hi Jorge,

That's awesome! Thank you for this great job to ma make scipion more user
friendly. I'll check it out when I can
