### ISSUE TITLE
Import images: repeated calls to _validateImages

### ISSUE THREAD

**Issue by yaizar** [I2PC/scipion#1903]
It seems that in import protocols, we iterate over all the images that match the pattern a couple times before launching the import protocol in the function [_validateImages](https://github.com/I2PC/scipion/blob/master/pyworkflow/em/protocol/protocol_import/images.py#L333). Sometimes we've heard from users that imports take some time to start, so it could be because of this (we're validating the whole list of images twice). Maybe iterating the whole list for the validate is a bit excessive? maybe each image could be validated individually at the import time, not before, and when pressing "execute" we could validate only the form params? 

There's other validate instances where we only do it in the first one, like [this _validate](https://github.com/I2PC/scipion/blob/master/pyworkflow/em/protocol/protocol_import/micrographs.py#L230)

**Comment by delarosatrevin** [comment]
Yep...this has been reported from many users over here, where import takes a long time, more than expected. This is noticeably slow when the raw movies are in external hard-drives. I think validating the first one should be good enough.

**Comment by pconesa** [comment]
@delarosatrevin and @azazellochg , we will then validate only the first one. We could also test what happens if the pattern matches, accidentally, a problematic file (something that causes an exception)....I think in this case it should report it but continue, do you agree?

**Comment by delarosatrevin** [comment]
Yes, I guess it will be better to fail one (or some) steps but in normal cases, the validation will be quicker and so the import in general.

**Comment by yaizar** [comment]
ok, that means no reporting on problematic file as Pablo said, just letting the exception happen when it happens

**Comment by delarosatrevin** [comment]
Hum...I'm not sure...
Usually in the streaming processing, the motioncor is kind of the bottleneck...so, adding an extra validation of the file for each step, could add more time to the execution. So, maybe it is better to just let it fail (as in other conditions) and then report the failures in general.

**Comment by yaizar** [comment]
Yeah I agree with that. Just wanted to clarify because your suggestion and @pconesa 's seemed contradicting. That's the behavior I've implemented as of now (just check first file and break, no further checks on file by file basis).

**Comment by pconesa** [comment]
I'm ok with this.
