### ISSUE TITLE
Messages when an error occur during import from plugin

### ISSUE THREAD

**Issue by dmaluenda** [I2PC/scipion#1907]
When something is imported from a plugin and this importing fails, Scipion prints, either: 
* `<pluginName> plugin not found. See 'scipion installp --help' to install it.` ([when that plugin is not found](https://github.com/I2PC/scipion/blob/63cc93d4adcf9e537e0d4120950df72dc17560db/pyworkflow/utils/utils.py#L739)) 

or 

* `Error when importing from *****. See 'scipion installp --help', it can be a versions compatibility issue.` ([when any error is gotten even existing that plugin](https://github.com/I2PC/scipion/blob/63cc93d4adcf9e537e0d4120950df72dc17560db/pyworkflow/utils/utils.py#L744))

Maybe we should review that messages before the release, on the one hand, by addressing the user to the plugins installer, and on the other hand, by clarifying a bit the 'it can be a versions compatibility issue'. Any idea?

**Comment by yaizar** [comment]
Yup, I agree, I think  there's a try/catch somewhere that's not letting the real error message pass, I'll try to take a look

**Comment by dmaluenda** [comment]
I think that the function is right. I mean the message it self.

**Comment by yaizar** [comment]
changed in 2e9706b
