### ISSUE TITLE
Spefific viewer is not launched if protocol inherits from a target of DataViewer.

### ISSUE THREAD

**Issue by dmaluenda** [I2PC/scipion#1915]
**Describe the bug**
If a plugin define a specific viewer for a certain protocol (via target) and, at the same time, this protocol inherits from a protocolClass defined as a target for the DataViewer, that specific viewer is ignored when 'Analyze result' is clicked.

The reason is because `pyworkflow/em/__init__.py.findViewers()` (lines from 78 to 89) returns a list where the DataViewer is always first. And then, that first item is used to visualize the data.

**To Reproduce**
1. Open a project which contains a Xmipp**Auto**Picking.
2. Select the  XmippAutoPicking protocol and click 'Analyze result'.
3. See the 'State' column with all micrographs set as 'Manual'.
4. Close the project
-------------------
5. Edit `pyworkflow/em/__init__.py.findViewers()` (lines from 78 to 89) including the following lines before the return (**solution suggested till a more flexible and elegant solution is implemented**)
```
pyworkflow/em/__init__.py:

    .../...
    
89:    from pyworkflow.em.viewers import DataViewer
90:    if len(viewers)>1 and isinstance(viewers[0], DataViewer):
91:        viewers = reversed(viewers)
```
6. Repeat 1. and 2.
7. See the 'State' column with different states corresponding to the trainning process and Xmipp Staff.

**Expected behavior**
If a specific viewer is found, ignore the general one. (under my point of view)

**Additional**
In the case described above it is not a big deal, but we are finishing a protocol which is also inheriting from ProtocolAutoPicking base class and we have design a specific viewer **whose behavior is completely different from the general one** (in fact, the general one doesn't make sense...)

**Comment by delarosatrevin** [comment]
Hi @dmaluenda , in one of the refactors recently done, I tried to separate the DataView logic, and how its name indicates, we should keep it for output data, not protocols. I agree that if there is a more specific viewer...it should be used.  And regarding the default viewers, I think there is a related issue, and the solution will be to allow some sort of default configuration, where user could customize which one is the default.

**Comment by dmaluenda** [comment]
Hi @delarosatrevin, I totally agree with the procedure with the default configuration but it will not be immediately implemented (hopefully not so), thus I suggest this to get the more specific viewer.

Just to clarify, DataViewer has [the ImportProtocol and the ParticlePicking](https://github.com/I2PC/scipion/blob/7452ed793464c084ece29fd71af017d713ab3aee/pyworkflow/em/viewers/viewers_data.py#L53) as targets. The first to [show the gain file if it exists](https://github.com/I2PC/scipion/blob/7452ed793464c084ece29fd71af017d713ab3aee/pyworkflow/em/viewers/viewers_data.py#L213) and the second to [show just the last picking if more than one is done](https://github.com/I2PC/scipion/blob/7452ed793464c084ece29fd71af017d713ab3aee/pyworkflow/em/viewers/viewers_data.py#L209).

That's two are the unique cases where the DataViewer is attached to a Protocol. For that reason I considered that is not the same issue than those to be solved with the default configuration.

**Comment by delarosatrevin** [comment]
Hum...I think we could remove both cases from DataViewer
* ImportProtocol: the gain image is associated with the SetOfMovies, so it is a property of the output data, not the protocol itself
* ParticlePicking: the default behaviour could be if a protocol has not specific viewer...and many outputs...just show the last one.

Apart from that, I agree that the more specific viewer should be used, but your solution does not address this. It just take the last viewer ignoring the DataViewer...imagine if there are more than one viewer you will be in the same situation. I think the configuration approach could be better and I'm not sure if @fonsecareyna82 was going to try something before the release. Anyway, you could try to implement a more general solution where the viewers discovered for a given Object, are sorted by the more specific ones to the more general...and use the first one.

**Comment by pconesa** [comment]
Yaiza has started this task about specifying. Default viewer in case there
are more than one.

**Comment by yaizar** [comment]
Yes this is being dealt with as part of #1850. Not removing anything from data viewer, should I? 

What we're doing is having a variable in the config file where we can set a preferred viewer like:

```
VIEWERS={"Volume":"bsoft.viewers.bsoft_viewers.BsoftViewer",
         "SetOfVolumes": "bsoft.viewers.bsoft_viewers.BsoftViewer",
         "XmippParticlePickingAutomatic" :"xmipp3.viewers.viewer.XmippViewer"}

```
Then this preferred viewer will be used first.

**Comment by delarosatrevin** [comment]
Looks good! Can it be a list? ("Data": ["viewer1", "viewer2"])
Maybe we could remove these two protocols from DataViewer for consistency, but I it is not a priority.
