### ISSUE TITLE
NFS and scipion

### ISSUE THREAD

**Issue by rmarabini** [I2PC/scipion#1917]
BUG reported by Jaime Martin Benito.

version= scipion_plugin

When executing a protocol using scipion and NFS (data in hilbert)  if the protocol  fails (or if it is stopped) a hidden file called .fuse.XXXXXX remains  in the "Log" directory. This file makes scipion fail if you try to start or delete de protocol. It seems that scipion cannot delete the fuse file and therefore the Log directory cannot be removed.

**Comment by pconesa** [comment]
I talked to Jaime....and looked at the problem. Seems that NFS wasn't behaving. Although good to know I think this issues are out of Scope of what scipion can do. We are simply deleting the run folder, if we can't trust that operation we are doomed!.

I' closing it.
