### ISSUE TITLE
Error when running Eman2 - initial model in Scipion

### ISSUE THREAD

**Issue by phongnq94** [I2PC/scipion#1923]
**Describe the bug**
Error when running Eman2 - initial model in Scipion. 

**To Reproduce**
1. Go to 'protocol SPA'
2. Click on '3D'
3. Scroll down to 'Initial volume'
4. Click on 'eman2 - initial model'
5. Execute and See program stop running in step 2 of 3

**Expected behavior*
Eman2 - initial model will finish

**Screenshots**

**Desktop (please complete the following information):**
 - OS: ubuntu 3.19.0 - 80 -generic
 

**run.stdout output**
00001:   RUNNING PROTOCOL -----------------
00002:         Scipion: v1.0.0
00003:      currentDir: /home/phong/ScipionUserData/projects/Pol3IN1_glu_SECB1_NS
00004:      workingDir: Runs/003211_EmanProtInitModel
00005:         runMode: Continue
00006:             MPI: 1
00007:         threads: 32
00008:   len(steps) 3 len(prevSteps) 0
00009:    Starting at step: 1
00010:    Running steps 
00011:   STARTED: createStackImgsStep, step 1
00012:     2019-02-12 13:00:48.025734
00013:   FINISHED: createStackImgsStep, step 1
00014:     2019-02-12 13:00:48.949155
00015:   STARTED: createInitialModelStep, step 2
00016:     2019-02-12 13:00:49.059494
00017:   /home/eva/scipion/software/em/eman2.12/Python/bin/python /home/eva/scipion/software/em/eman2.12/bin/e2initialmodel.py   --input=../representatives.stk iter=8 --sym=c1 --tries=10 --parallel=thread:32
00018:   /bin/sh: /home/eva/scipion/software/em/eman2.12/Python/bin/python: No existe el archivo o el directorio
00019:   Traceback (most recent call last):
00020:     File "/home/eva/scipion/pyworkflow/protocol/protocol.py", line 167, in run
00021:       self._run()
00022:     File "/home/eva/scipion/pyworkflow/protocol/protocol.py", line 211, in _run
00023:       resultFiles = self._runFunc()
00024:     File "/home/eva/scipion/pyworkflow/protocol/protocol.py", line 207, in _runFunc
00025:       return self._func(*self._args)
00026:     File "/home/eva/scipion/pyworkflow/em/packages/eman2/protocol_initialmodel.py", line 127, in createInitialModelStep
00027:       self.runJob(program, args, cwd=self._getExtraPath())
00028:     File "/home/eva/scipion/pyworkflow/protocol/protocol.py", line 960, in runJob
00029:       self._stepsExecutor.runJob(self._log, program, arguments, **kwargs)
00030:     File "/home/eva/scipion/pyworkflow/protocol/executor.py", line 56, in runJob
00031:       env=env, cwd=cwd)
00032:     File "/home/eva/scipion/pyworkflow/utils/process.py", line 51, in runJob
00033:       return runCommand(command, env, cwd)
00034:     File "/home/eva/scipion/pyworkflow/utils/process.py", line 65, in runCommand
00035:       check_call(command, shell=True, stdout=sys.stdout, stderr=sys.stderr, env=env, cwd=cwd)
00036:     File "/home/eva/scipion/software/lib/python2.7/subprocess.py", line 540, in check_call
00037:       raise CalledProcessError(retcode, cmd)
00038:   CalledProcessError: Command '/home/eva/scipion/software/em/eman2.12/Python/bin/python /home/eva/scipion/software/em/eman2.12/bin/e2initialmodel.py   --input=../representatives.stk iter=8 --sym=c1 --tries=10 --parallel=thread:32' returned non-zero exit status 127
00039:   Protocol failed: Command '/home/eva/scipion/software/em/eman2.12/Python/bin/python /home/eva/scipion/software/em/eman2.12/bin/e2initialmodel.py   --input=../representatives.stk iter=8 --sym=c1 --tries=10 --parallel=thread:32' returned non-zero exit status 127
00040:   FAILED: createInitialModelStep, step 2
00041:     2019-02-12 13:00:49.116244
00042:   Cleaning temporarly files....
00043:   ------------------- PROTOCOL FAILED (DONE 2/3)
00044:   RUNNING PROTOCOL -----------------
00045:         Scipion: v1.0.0
00046:      currentDir: /home/phong/ScipionUserData/projects/Pol3IN1_glu_SECB1_NS
00047:      workingDir: Runs/003211_EmanProtInitModel
00048:         runMode: Continue
00049:             MPI: 1
00050:         threads: 16
00051:   len(steps) 3 len(prevSteps) 3
00052:    Starting at step: 2
00053:    Running steps 
00054:   STARTED: createInitialModelStep, step 2
00055:     2019-02-12 13:01:52.592569
00056:   /home/eva/scipion/software/em/eman2.12/Python/bin/python /home/eva/scipion/software/em/eman2.12/bin/e2initialmodel.py   --input=../representatives.stk iter=8 --sym=c1 --tries=10 --parallel=thread:16
00057:   /bin/sh: /home/eva/scipion/software/em/eman2.12/Python/bin/python: No existe el archivo o el directorio
00058:   Traceback (most recent call last):
00059:     File "/home/eva/scipion/pyworkflow/protocol/protocol.py", line 167, in run
00060:       self._run()
00061:     File "/home/eva/scipion/pyworkflow/protocol/protocol.py", line 211, in _run
00062:       resultFiles = self._runFunc()
00063:     File "/home/eva/scipion/pyworkflow/protocol/protocol.py", line 207, in _runFunc
00064:       return self._func(*self._args)
00065:     File "/home/eva/scipion/pyworkflow/em/packages/eman2/protocol_initialmodel.py", line 127, in createInitialModelStep
00066:       self.runJob(program, args, cwd=self._getExtraPath())
00067:     File "/home/eva/scipion/pyworkflow/protocol/protocol.py", line 960, in runJob
00068:       self._stepsExecutor.runJob(self._log, program, arguments, **kwargs)
00069:     File "/home/eva/scipion/pyworkflow/protocol/executor.py", line 56, in runJob
00070:       env=env, cwd=cwd)
00071:     File "/home/eva/scipion/pyworkflow/utils/process.py", line 51, in runJob
00072:       return runCommand(command, env, cwd)
00073:     File "/home/eva/scipion/pyworkflow/utils/process.py", line 65, in runCommand
00074:       check_call(command, shell=True, stdout=sys.stdout, stderr=sys.stderr, env=env, cwd=cwd)
00075:     File "/home/eva/scipion/software/lib/python2.7/subprocess.py", line 540, in check_call
00076:       raise CalledProcessError(retcode, cmd)
00077:   CalledProcessError: Command '/home/eva/scipion/software/em/eman2.12/Python/bin/python /home/eva/scipion/software/em/eman2.12/bin/e2initialmodel.py   --input=../representatives.stk iter=8 --sym=c1 --tries=10 --parallel=thread:16' returned non-zero exit status 127
00078:   Protocol failed: Command '/home/eva/scipion/software/em/eman2.12/Python/bin/python /home/eva/scipion/software/em/eman2.12/bin/e2initialmodel.py   --input=../representatives.stk iter=8 --sym=c1 --tries=10 --parallel=thread:16' returned non-zero exit status 127
00079:   FAILED: createInitialModelStep, step 2
00080:     2019-02-12 13:01:52.807270
00081:   Cleaning temporarly files....
00082:   ------------------- PROTOCOL FAILED (DONE 2/3)
00083:   RUNNING PROTOCOL -----------------
00084:         Scipion: v1.0.0
00085:      currentDir: /home/phong/ScipionUserData/projects/Pol3IN1_glu_SECB1_NS
00086:      workingDir: Runs/003211_EmanProtInitModel
00087:         runMode: Continue
00088:             MPI: 1
00089:         threads: 1
00090:   len(steps) 3 len(prevSteps) 3
00091:    Starting at step: 2
00092:    Running steps 
00093:   STARTED: createInitialModelStep, step 2
00094:     2019-02-12 13:02:02.889858
00095:   /home/eva/scipion/software/em/eman2.12/Python/bin/python /home/eva/scipion/software/em/eman2.12/bin/e2initialmodel.py   --input=../representatives.stk iter=8 --sym=c1 --tries=10
00096:   /bin/sh: /home/eva/scipion/software/em/eman2.12/Python/bin/python: No existe el archivo o el directorio
00097:   Traceback (most recent call last):
00098:     File "/home/eva/scipion/pyworkflow/protocol/protocol.py", line 167, in run
00099:       self._run()
00100:     File "/home/eva/scipion/pyworkflow/protocol/protocol.py", line 211, in _run
00101:       resultFiles = self._runFunc()
00102:     File "/home/eva/scipion/pyworkflow/protocol/protocol.py", line 207, in _runFunc
00103:       return self._func(*self._args)
00104:     File "/home/eva/scipion/pyworkflow/em/packages/eman2/protocol_initialmodel.py", line 127, in createInitialModelStep
00105:       self.runJob(program, args, cwd=self._getExtraPath())
00106:     File "/home/eva/scipion/pyworkflow/protocol/protocol.py", line 960, in runJob
00107:       self._stepsExecutor.runJob(self._log, program, arguments, **kwargs)
00108:     File "/home/eva/scipion/pyworkflow/protocol/executor.py", line 56, in runJob
00109:       env=env, cwd=cwd)
00110:     File "/home/eva/scipion/pyworkflow/utils/process.py", line 51, in runJob
00111:       return runCommand(command, env, cwd)
00112:     File "/home/eva/scipion/pyworkflow/utils/process.py", line 65, in runCommand
00113:       check_call(command, shell=True, stdout=sys.stdout, stderr=sys.stderr, env=env, cwd=cwd)
00114:     File "/home/eva/scipion/software/lib/python2.7/subprocess.py", line 540, in check_call
00115:       raise CalledProcessError(retcode, cmd)
00116:   CalledProcessError: Command '/home/eva/scipion/software/em/eman2.12/Python/bin/python /home/eva/scipion/software/em/eman2.12/bin/e2initialmodel.py   --input=../representatives.stk iter=8 --sym=c1 --tries=10' returned non-zero exit status 127
00117:   Protocol failed: Command '/home/eva/scipion/software/em/eman2.12/Python/bin/python /home/eva/scipion/software/em/eman2.12/bin/e2initialmodel.py   --input=../representatives.stk iter=8 --sym=c1 --tries=10' returned non-zero exit status 127
00118:   FAILED: createInitialModelStep, step 2
00119:     2019-02-12 13:02:02.992332
00120:   Cleaning temporarly files....
00121:   ------------------- PROTOCOL FAILED (DONE 2/3)

**Comment by joshua4289** [comment]
: No existe el archivo o el directorio

File doesn't exist?

**Comment by phongnq94** [comment]
@joshua4289 Yes you are right. There is no file in that directory. So I need to change the directory that Scipion will use right? Do you know where is the ¨createInitialModelStep¨ file?

**Comment by joshua4289** [comment]
Hi

The file doesn't exist error is for the python of Eman check that eman2
package is correctly installed in scipion . then check your scipion config
file

/home/eva/scipion/software/em/eman2.12/Python/bin/python should launch
eman's python

Sincerely
Josh

**Comment by azazellochg** [comment]
Hi, EMAN 2.12 should have python in EMAN2DIR/Python/bin/python, otherwise it was not installed properly. Does  /home/eva/scipion/software/em/eman2.12 folder exist?

**Comment by phongnq94** [comment]
Hi @azazellochg. No that folder is not exist. But I have installed Eman2 in the other folder manually. Can we change the way Scipion reach the eman2?

**Comment by phongnq94** [comment]
@joshua4289 As I have checked there is no eman2 was installed in ¨eva¨ account. That why I have installed it in my account. So now I want to change the way Scipion reach the eman2 from /home/eva/scipion/software/em/eman2.12/Python/bin/python to home/phong/eman2.ee/bin/python . But I still don´t know how to do that.

**Comment by azazellochg** [comment]
@phongnq94 there are two way to point scipion to your eman installation folder:

1. create a symbolic link /home/eva/scipion/software/em/eman2.12 pointing to the real installation folder
2. put the path to the folder into ~/.config/scipion/scipion.conf in EMAN2DIR variable.

**Comment by phongnq94** [comment]
Thank you @azazellochg
