### ISSUE TITLE
creating volume subset fails when xmipp viewer is in table mode

### ISSUE THREAD

**Issue by azazellochg** [I2PC/scipion#1936]
**Describe the bug**
Red Volume button is gray when displaying volumes in a table mode, when you press it, the create set fails 

**To Reproduce**
1. Go to Analyze results of e.g., relion refine protocol
2. Click on show both half maps
3. Switch viewer from slices view to middle slice / table view
4. Click Volume button
5. See error:

```
00015:   Traceback (most recent call last):
00016:     File "/lmb/home/gsharov/soft/scipion2/pyworkflow/protocol/protocol.py", line 186, in run
00017:       self._run()
00018:     File "/lmb/home/gsharov/soft/scipion2/pyworkflow/protocol/protocol.py", line 237, in _run
00019:       resultFiles = self._runFunc()
00020:     File "/lmb/home/gsharov/soft/scipion2/pyworkflow/protocol/protocol.py", line 233, in _runFunc
00021:       return self._func(*self._args)
00022:     File "/lmb/home/gsharov/soft/scipion2/pyworkflow/em/protocol/protocol_batch.py", line 109, in createSetStep
00023:       otherObj = self.getProject().mapper.selectById(int(otherid))
00024:   TypeError: int() argument must be a string or a number, not 'NoneType'
00025:   Protocol failed: int() argument must be a string or a number, not 'NoneType'
00026:   FAILED: createSetStep, step 1
```

**Expected behavior**
Is saving volumes not supposed to be available from table mode? Why?

**Screenshots**
![screenshot_20190224_183327](https://user-images.githubusercontent.com/6952870/53303544-68a3e500-3863-11e9-82eb-76d310a5d399.png)

**Desktop (please complete the following information):**
 - Version 2.0.0 , relion plugin any branch

**Comment by pconesa** [comment]
Thanks @azazellochg will have a look.

**Comment by pconesa** [comment]
Weird that is grey

**Comment by azazellochg** [comment]
@pconesa it actually might be still red, my remote connection quality is not the best :)

**Comment by pconesa** [comment]
I've seen the gray color too. But so far, tested from a import and subset worked. Going for the specific case.

**Comment by azazellochg** [comment]
it works only if the viewer is in "slice" mode but then you can display/save only one volume at a time

**Comment by pconesa** [comment]
I can understand the need of using the halves in the project, it gives you other options....but creating a "subset" from a protocol, that does not output any of that content.....isn't it confusing? (I'm now seeing this from a traceability /reproducibility point of view). @delarosatrevin, @azazellochg ?

**Comment by delarosatrevin** [comment]
@pconesa, when you visualize results (usually sets) from most of the protocols, you are able to create subsets. This is properly tracked with the 'user-subset' protocol.

I think that the issue here that @azazellochg is reporting, is that the viewer is behaving differently if in slice view (where the subset seems to work) from the list view (where the subset is not working and it should as well)

**Comment by pconesa** [comment]
thank you @delarosatrevin for clarifying, I actually got it. Was just raising a concert about what a subset is, and seeing it from a reproducibility point of view.

**Comment by azazellochg** [comment]
@pconesa thank you for fixing this, but I have another comment: 

- could we make the Volumes button red in TABLE mode?
- should we disable Volume button in GALLERY mode? Because only the slices of a single volume are shown at a time and you can't save just some slices :)

**Comment by pconesa** [comment]
I'll try.
