### ISSUE TITLE
relion postprocess.star file missing info

### ISSUE THREAD

**Issue by andreanans** [I2PC/scipion#1945]
Hi,

I noticed that the postprocess.star files generated by relion are missing the following:

_rlnUnfilteredMapHalf1
_rlnUnfilteredMapHalf2
_rlnMaskName

It would be super helpful to include these lines so that the file has the same format as postprocess.star files that are generated by the standalone version of Relion.

I'm using 1.2.1 (Claudio, 2018-10-01).

**Comment by azazellochg** [comment]
Hi @andreanans . I checked and relion-2.1 does not generate these columns. Scipion-1.2.1 does not support relion3 unless you are using @delarosatrevin version. The columns are available in relion-3.0 only and will work in next scipion version (2.0) due to release soon.
