### ISSUE TITLE
installing plugins from interface fails if ssh port if not vailable

### ISSUE THREAD

**Issue by rmarabini** [I2PC/scipion#1952]
Plugin installation through scipion plugin interface fails if the computer cannot connect through ssh with the outside world. 

Some institutions only allow http/https connections with the internet and ssh is filtered. I suggest to replace rsync by wget (or even better try both) as a way to transfer files. In this way computers behind a firewall that filter ssh connections will be easier to install.

    Roberto

**Comment by dmaluenda** [comment]
Right! If no internet connection also fails. I added a print message to telling why, but maybe it's not enough...

**Comment by pconesa** [comment]
Thanks Roberto, we are not using rsync, as far as I know in the plugin manager. A few days ago , @yaizar replaced wget by curl, but not sure if this is what you had.

What is the error?

**Comment by yaizar** [comment]
This seemed to be a xmipp thing but looks like its not happening anymore - at least not from the plugin manager - xmipp does use rsync when installing manually if I'm right? If anything that's what should be reviewed but for manual installation I think it's ok to leave like it is.

Anyway, closing!
