### ISSUE TITLE
relion reconstruct broken

### ISSUE THREAD

**Issue by JuhaHuiskonen** [I2PC/scipion#1957]
Hi @delarosatrevin 

Protocol 'relion - reconstruct' does not start anymore. It fails with error:

00017: File "...pyworkflow/em/packages/relion/protocol_reconstruct.py", line 129, in _insertReconstructStep
00018:       if self.numberOfTheads > 1 and isVersion2():
00019:   AttributeError: 'ProtRelionReconstruct' object has no attribute 'numberOfTheads'

I am using 1.2.1.facilities (sdevel relion3 53459999)

**Comment by delarosatrevin** [comment]
Hi @JuhaHuiskonen, thanks for reporting it. 

I have fixed! It was a stupid type that caused the bug, I'm really sorry for the inconveniences.

Please update you branch to sdevel_relion3 and make sure you have updated to the last commit. It should display something like the following:
```
> scipion version

Scipion v1.2.2-rc (2019-03-24) Constantino (sdevel-relion3 5967690)

 > git log -1
commit 5967690e5b016fde4de6133378433973df1cad1b
Author: Jose Miguel de la Rosa Trevin <delarosatrevin@gmail.com>
Date:   Sun Mar 24 16:48:58 2019 +0100

    Fixed protcol_reconstruct typo in numberOfThreads (causing a bug)
```

Please note that threads are not available for this protocol in Relion3, so you should use MPI.
