### ISSUE TITLE
Add phase shift plot as reported by gCTF to htmlreport

### ISSUE THREAD

**Issue by rmarabini** [I2PC/scipion#1963]
This is a feature request form the people at the microscope:

Add another plot to html_report. Containing the phase shift computed by gCTF when the phase plate is used.

**Comment by azazellochg** [comment]
there is already a plot of phase shift in time series

**Comment by pconesa** [comment]
We have added a time series plot with phaseshift, defocus and
resolution...how is that gctf plot?

**Comment by azazellochg** [comment]
Gctf does not produce any plots itself, which plot do you mean?

**Comment by rmarabini** [comment]
I see, so may be this request is already covered. @pconesa, let us look to
the last version of the report next Monday.
