### ISSUE TITLE
Why the data Model changed???

### ISSUE THREAD

**Issue by josuegbl** [I2PC/scipion#1967]
This is my formal complain 😈 about the change in the data model. pdbFile was renamed to AtomStruct and this change caused a lot of problems in our case. I guess the changes were did it by @rmarabini, so SHAME ON YOU! Please, be extremely careful with these kind of changes....

**Comment by pconesa** [comment]
It was renamed but old pdbobject should still work. Not sure if additionally, there's been an actual model change. Could you describe the issue, please!

**Comment by rmarabini** [comment]
Hi,

    As far As I know  the class pdbFile is still available with no decrease
in functionality (in fact now is much more robust).
Since pdbFile is a rather confusing name (pdb is a file format) we have
created the class atomStruct
 (that stands from atomic structure) that handles both cif and Pdb files.
pdbFile is now a dummy class
that inherits from atomStruct.

  After introducing this modification we execute all PDB related tests with
no problem but if you
have encountered one let us know and we will try to fix it. I have being
fighting with PDB fils these
two years and the current implementation of atomStruct is far superior than
the old pdbFile, with the
former implementation we could not feed several files downloaded from EMDB
to the ccp4 software.

    Roberto

**Comment by josuegbl** [comment]
@pconesa, one of our students was working with nma in scipion 1.2. After an error (in the protocols), we changed to scipion 2.0 and the outputs produced some protocols before as pdbFile were not found by the new version of the protocols (nma related) because they are especting, now, an AtomStruct object as input. So, for this change, we need to re-do several weeks of work. As far as I know, we were going to discuss the changes in the data model.

**Comment by azazellochg** [comment]
@josuegbl to be fair, a change in first digit of scipion version assumes breaking api.

**Comment by pconesa** [comment]
Well, there where some errors in the plugins where some Params where still
looking for pdbfiles. I think all of them are where fixed, probably a
plugin update or just a message in slack or here would have solve your
issue, or if it was earlier than when we identified the problem, it could
have help to fix it earlier.

Ah, and even we called next version 2.0 compatibility is not broken and
pdbfile outputs should show up and been able to be chosen.

@josuegbl, next time:
Let us know what is the problem earlier, we might have a solution or you
might have found a bug.
And also, before, making any assumptions,or even complaints, try to clarify
the situation ;-).

**Comment by josuegbl** [comment]
@pconesa, the solution isn't as simple as "plugin update" cause you (not you, the team, I mean, @rmarabini) changed the model without any consultation (I thought we have a deal about model changes) or even think the consequences about that. This was my complain, just that.... and yes, the compatibility (at least in xmipp) is broken. I didn't any assumption, I just saw data model has changed.... this is a fact, not a guess. btw, I opened this "issue complain" 10 minutes after I knew the model was changed so I don't understand what "Let us know what is the problem earlier" means in your "recommendations". I don't have a time machine....
Unfortunately, we have a lot of work, pressure and no time, so I try to solve locally all the problems that students found cause they can't stop their work.
@azazellochg, yes you are (usually) right 😄, my bad for not take this into account 😢

**Comment by pconesa** [comment]
@josuegbl :
I misunderstood, I thought you already spent 2 weeks redoing the work, but if I'm right you are just at the beginning. So I still think there is no reason for a compatibility break.

Please, describe the error and we will found out why compatibility is broken. Why do you say the compatibility is broken?

**Comment by pconesa** [comment]
Hi @josuegbl , we have just tried this behaviour doing:
1.- scipion.1.2 - Importing a pdb (this should generate an old pdbFile output)
2.- Open scipion 2.0 and use a protocol that inputs (AtomStruct) 

It sees the "old" pdb" output ....are we missing anything?

**Comment by pconesa** [comment]
![image](https://user-images.githubusercontent.com/785633/56495351-ccf6c400-64f5-11e9-877d-0caff1cc349e.png)

**Comment by pconesa** [comment]
I'm closing this issue. Feel free to reopen it if I'm wrong or missed something.
