### ISSUE TITLE
PSD generation (using Xmipp programs) is very very SLOW

### ISSUE THREAD

**Issue by delarosatrevin** [I2PC/scipion#1972]
This issue have been reported (I'm not sure if we already have an entry for it) by @azazellochg  many times. 

I just opened an issue in the Xmipp repo here: https://github.com/I2PC/xmipp/issues/132

I think this issue is a killing one for really keeping-up with the data processing. So, I don't recommend to use the 'Compute PSD before/after' option right now, if you don't want to generate an excessive overhead.

**Comment by azazellochg** [comment]
Fixed in xmipp.
