### ISSUE TITLE
Configuration -> Variables improvements in plugin manager

### ISSUE THREAD

**Issue by azazellochg** [I2PC/scipion#1974]
Configuration -> Variables is very handy! But maybe sort that list alphabetically? And use printf to format the list like a table, so that it can be easily readable?

**Comment by pconesa** [comment]
It is already sorted, I tried to printf them but the font is not monospaced therefore printf does not do we want.

I tried this:
![image](https://user-images.githubusercontent.com/785633/72004112-053c5f00-324b-11ea-93b6-d42812639e85.png)

It can be copy and pasted, so at least it can be used to be pasted in the config.
