### ISSUE TITLE
Convert PDB to SAXS curve not working

### ISSUE THREAD

**Issue by Sacha83** [I2PC/scipion#1975]
Hello, I successfully generated pseudoatoms for a 3D volume using Xmipp3 - convert to pseudoatoms (1.5 vox radius). I'm following the initial model validation tutorial and the next step is to use Atsas - convert PDB to SAXS curve. I gave the psuedoatom pdb as the only input and the protocol fails. Below is the run.out. I see on the crysol page that the arguments need - instead of /. 

00012:   STARTED: crysolWrapper, step 1
00013:     2019-05-10 10:09:13.785293
00014:   crysol pseudoatoms.pdb  /lm 18 /sm 0.300000 /ns 256 
00015:    error: unable to read input file: /lm
00016:   Traceback (most recent call last):
00017:     File "/data/sbgrid/programs/x86_64-linux/scipion/1.2.1/pyworkflow/protocol/protocol.py", line 190, in run
00018:       self._run()
00019:     File "/data/sbgrid/programs/x86_64-linux/scipion/1.2.1/pyworkflow/protocol/protocol.py", line 237, in _run
00020:       resultFiles = self._runFunc()
00021:     File "/data/sbgrid/programs/x86_64-linux/scipion/1.2.1/pyworkflow/protocol/protocol.py", line 233, in _runFunc
00022:       return self._func(*self._args)
00023:     File "/data/sbgrid/programs/x86_64-linux/scipion/1.2.1/pyworkflow/em/packages/atsas/protocol_pdb_to_saxs.py", line 97, in crysolWrapper
00024:       self.otherCrysol))
00025:     File "/data/sbgrid/programs/x86_64-linux/scipion/1.2.1/pyworkflow/protocol/protocol.py", line 1174, in runJob
00026:       self._stepsExecutor.runJob(self._log, program, arguments, **kwargs)
00027:     File "/data/sbgrid/programs/x86_64-linux/scipion/1.2.1/pyworkflow/protocol/executor.py", line 61, in runJob
00028:       env=env, cwd=cwd, gpuList=self.getGpuList())
00029:     File "/data/sbgrid/programs/x86_64-linux/scipion/1.2.1/pyworkflow/utils/process.py", line 52, in runJob
00030:       return runCommand(command, env, cwd)
00031:     File "/data/sbgrid/programs/x86_64-linux/scipion/1.2.1/pyworkflow/utils/process.py", line 67, in runCommand
00032:       env=env, cwd=cwd)
00033:     File "/data/sbgrid/programs/x86_64-linux/scipion/1.2.1/software/lib/python2.7/subprocess.py", line 186, in check_call
00034:       raise CalledProcessError(retcode, cmd)
00035:   CalledProcessError: Command 'crysol pseudoatoms.pdb  /lm 18 /sm 0.300000 /ns 256 ' returned non-zero exit status 1
00036:   Protocol failed: Command 'crysol pseudoatoms.pdb  /lm 18 /sm 0.300000 /ns 256 ' returned non-zero exit status 1
00037:   FAILED: crysolWrapper, step 1
00038:     2019-05-10 10:09:14.446552
00039:   ------------------- PROTOCOL FAILED (DONE 1/1)

**Comment by pconesa** [comment]
I've checked and code has exactly \
https://github.com/I2PC/scipion/blob/master/pyworkflow/em/packages/atsas/protocol_pdb_to_saxs.py

Now, either this never worked, or there is a crysol version that accepted
that format

**Comment by azazellochg** [comment]
I've updated recently atsas  plugin to support ATSAS 3.0.1 and the crysol protocol works
