### ISSUE TITLE
import particles from scipion doesnt work

### ISSUE THREAD

**Issue by josuegbl** [I2PC/scipion#1976]
**Describe the bug**
Im working in a project and I wanted to import a set of particles using aour sqlite file, and the protocols fails as follows: 

File 'Runs/002857_ProtImportParticles/logs/run.stdout' doesn't existFile 'Runs/002857_ProtImportParticles/logs/run.stdout' doesn't exist00001:   RUNNING PROTOCOL -----------------
00002:        HostName: cajal
00003:             PID: 38352
00004:         Scipion: v2.0 (2019-04-12) Diocletian (release-2.0.0 50b3aea)
00005:      currentDir: /data/josuegbl/ScipionUserData/projects/44S_TestBank
00006:      workingDir: Runs/002857_ProtImportParticles
00007:         runMode: Restart
00008:             MPI: 1
00009:         threads: 1
00010:    Starting at step: 1
00011:    Running steps 
00012:   STARTED: importParticlesStep, step 1
00013:     2019-05-15 15:12:06.108666
00014:   referenceFile: /data/josuegbl/ScipionUserData/projects/44S_R3C_high_salt_05_24_2017_Krios/Runs/003049_ProtUserSubSet/subset.sqlite
00015:   checking: Traceback (most recent call last):
00016:     File "/usr/local/scipion/2.0-devel/scipion/pyworkflow/protocol/protocol.py", line 186, in run
00017:       self._run()
00018:     File "/usr/local/scipion/2.0-devel/scipion/pyworkflow/protocol/protocol.py", line 237, in _run
00019:       resultFiles = self._runFunc()
00020:     File "/usr/local/scipion/2.0-devel/scipion/pyworkflow/protocol/protocol.py", line 233, in _runFunc
00021:       return self._func(*self._args)
00022:     File "/usr/local/scipion/2.0-devel/scipion/pyworkflow/em/protocol/protocol_import/particles.py", line 208, in importParticlesStep
00023:       ci.importParticles()
00024:     File "/usr/local/scipion/2.0-devel/scipion/pyworkflow/em/protocol/protocol_import/dataimport.py", line 71, in importParticles
00025:       self._findImagesPath(inputSet)
00026:     File "/usr/local/scipion/2.0-devel/scipion/pyworkflow/em/protocol/protocol_import/dataimport.py", line 94, in _findImagesPath
00027:       self._imgPath = findRootFrom(self._sqliteFile, img.getFileName())
00028:     File "/usr/local/scipion/2.0-devel/scipion/pyworkflow/utils/path.py", line 82, in findRootFrom
00029:       print "checking: ", os.path.join(absPath, searchFile)
00030:     File "/usr/local/scipion/2.0-devel/scipion/software/lib/python2.7/posixpath.py", line 68, in join
00031:       if b.startswith('/'):
00032:   AttributeError: 'NoneType' object has no attribute 'startswith'
00033:   Protocol failed: 'NoneType' object has no attribute 'startswith'
00034:   FAILED: importParticlesStep, step 1
00035:     2019-05-15 15:12:06.201969
00036:   *** Last status is failed 

Particles are there, sqlite exists... and works in the old project.

**Comment by pconesa** [comment]
Thanks Josie, what are the paths inside the sqlite?

**Comment by pconesa** [comment]
@josuegbl , import particle test is working.....
does it work for you there ( I can see you are not updated, but I do not think it will make a difference, but I'd run the test just in case.)

Optionally....could you share the sqlite with us?

**Comment by pconesa** [comment]
I'm closing this issue. Feel free to reopen it if I'm wrong or missed something.
