### ISSUE TITLE
Duplicated protocol label

### ISSUE THREAD

**Issue by azazellochg** [I2PC/scipion#1983]
**Describe the bug**
The following should not be allowed

**To Reproduce**
Copy a protocol and change the name to the same as the original

**Screenshots**
![Screenshot_20190523_201843](https://user-images.githubusercontent.com/6952870/58280250-19088300-7d98-11e9-996c-340457ec84f1.png)

**Desktop (please complete the following information):**
 - Version 2.0.0

**Comment by delarosatrevin** [comment]
I think there is not much to do here. Labels can be set freely by the user...so we should not impose any restriction...I think users should name protocol runs in a meaningful way.

**Comment by azazellochg** [comment]
oh, I thought this label is in the db... alright then.

Best regards,
Grigory

--------------------------------------------------------------------------------
Grigory Sharov, Ph.D.

MRC Laboratory of Molecular Biology,
Francis Crick Avenue,
Cambridge Biomedical Campus,
Cambridge CB2 0QH, UK.
tel. +44 (0) 1223 267542 <+44%201223%20267542>
e-mail: gsharov@mrc-lmb.cam.ac.uk
