### ISSUE TITLE
Plugin can not be found

### ISSUE THREAD

**Issue by vabrishami** [I2PC/scipion#1984]
I am developing a plugin, and I wanted to test it. So based on the instructions, I clone it from the repo and used the Scipion command to install it in devel mode. It finished successfully, but I can't see the protocols in Scipion. 

**To Reproduce**

./scipion installp -p XXX/scipion-em-localrec --devel

and this is the output from Scipion

>>>>> python  YYY/scipion_pluginized/pyworkflow/install/install-plugin.py ./scipion installp -p XXX/scipion-em-localrec --devel
Building scipion-em-localrec ...
YYY/scipion_pluginized/software/bin/python 
YYY/scipion_pluginized/software/lib/python2.7/site-packages/pip install -e 
XXX/scipion-em-localrec
DEPRECATION: Python 2.7 will reach the end of its life on January 1st, 2020. Please upgrade your Python as Python 2.7 won't be maintained after that date. A future version of pip will drop support for Python 2.7.
Obtaining file:///XXX/scipion-em-localrec
Installing collected packages: scipion-em-localrec
  Running setup.py develop for scipion-em-localrec
Successfully installed scipion-em-localrec

**Comment by pconesa** [comment]
There is a script, inspect_plugin that might help to diagnose the problem

https://github.com/I2PC/scipion/blob/master/pyworkflow/install/inspect-plugins.py

Try to run it. If don't get any hint, let us know...which branch are you working with? Devel? Is it updated in GitHub?

**Comment by vabrishami** [comment]
Hi Pablo,

Thanks for your reply. Could you please also correct it in the plugin instructions? Since it is said the inspect-plugins is in the scripts while we do not have this folder anymore. Additionally, in the instructions, it is said to uninstall a package we should type scipion installp while it should be uninstallp. Anyway, I found the problem. It was because I included a protocol while the python code was not there. Thanks!

**Comment by pconesa** [comment]
Thanks @vabrishami , I'll update the docs.
