### ISSUE TITLE
ProtAlignMovies protocols access outputMicrographs without checking if are generated

### ISSUE THREAD

**Issue by delarosatrevin** [I2PC/scipion#1985]
**Describe the bug**
In the ProtAlignMovies base class, the property outputMicrographs is being access without checking that this output should be produced. Indeed, there is a method for that, _createOutputMicrographs, that if return False, means no output micrographs are generated. 

This issue has been detected in the Relion motioncor protocol where it is possible to generate DW micrographs only: 

https://github.com/scipion-em/scipion-em-relion/issues/62

**Comment by azazellochg** [comment]
https://github.com/scipion-em/scipion-em/commit/da38ef4d2b5052637809a1d8cdc2cc17a0b36e52
