### ISSUE TITLE
Search in the run.stdout and run.log gets broken

### ISSUE THREAD

**Issue by DStrelak** [I2PC/scipion#1988]
**Describe the bug**
One running a protocol, both run.stdout and run.log get filled by the log text.
While searching for a string literal using the Search field, random text (instead of the searched literal) gets highlighted.

**To Reproduce**
It seems to happen randomly,  but more often if you switch between the tabs and / or change the literal and or refresh the windows (using the double circular arrow button).

**Expected behavior**
The search should always find (and highlight) the searched string, if present

**Screenshots**
![image](https://user-images.githubusercontent.com/28389367/58620550-9c116800-82c7-11e9-8847-bd8d577a00c7.png)

**Desktop (please complete the following information):**
4.15.0-50-generic #54-Ubuntu SMP Mon May 6 18:46:08 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux (Ubuntu 18.04.2)
Scipion commit 93872702eeb4e40ef267e6a2db889503eb1ebfc1

**Comment by pconesa** [comment]
Fixed here: https://github.com/I2PC/scipion/pull/2033
