### ISSUE TITLE
Output the reason why a ctf has not been created

### ISSUE THREAD

**Issue by pconesa** [I2PC/scipion#1993]
If there is an error parsing ctf output we are just saying:
"Missing CTF?: Couldn't update CTF set with mic: %s" % micFn

It would be better to know more about the reason why.

**Comment by azazellochg** [comment]
@pconesa The only reason I can see that CTF estimation failed, no?

**Comment by pconesa** [comment]
I mean what is the actual parsing problem.

**Comment by azazellochg** [comment]
I don't get it :) There is nothing to parse, hence parsing problem.

**Comment by pconesa** [comment]
Ok, I should have reported more detailed this issue.....what I remember is that there was a file to parse, but for some reason, the parsing failed. Since I cannot reproduce this and give more details, I'll close it and will reopen if I hit it again.
