### ISSUE TITLE
Motioncor2 outputs .mrc, DW.mrc and DWS.mrc ?

### ISSUE THREAD

**Issue by andreanans** [I2PC/scipion#1994]
Hi, 

I finally started testing v 2.0 (2019-04-23). I noticed that an extra .mrc file is written out when running motioncor2: there is the expected *.mrc and *DW.mrc but now an extra file called *DWS.mrc. Is this the intended behaviour? We're trying to save as much disk space as possible so it would be good to know if I can somehow disable the generation of this additional image. Thanks and sorry if I've missed something obvious!

EDIT- it looks like it's something to do with the motioncor2 executable. The version downloaded through scipion plugin manager is writing out this extra mrc. I will just change the version. Sorry!

EDIT2- This is a new behaviour of Motioncor2. It automatically outputs a third image sum of dose-weighted frames whose accumulated doses are within 3 to 35 e/A2. To disable this option you must indicate -SumRange 0 0.

Best

Andrea

**Comment by azazellochg** [comment]
@andreanans thank you for debugging! I will add this option to the next plugin version and activate it by default
