### ISSUE TITLE
tmp directory in ctfffind job generates >100 GB

### ISSUE THREAD

**Issue by andreanans** [I2PC/scipion#1996]
I noticed in scipion 2.0 that when you run a ctffind job on a few thousand micrographs, the tmp directory accumulates hundreds of GB and doesn't get cleared, even after the job finishes. I don't remember this being the case in 1.2 so has something changed? Thanks

**Comment by delarosatrevin** [comment]
Hi @andreanans, thanks for your feedback!
Have you checked the "Batch size" option? If will use a value N greater than 0, it means that N micrographs will be processed in the same step. A folder in tmp folder is created for each "batch" and it should be deleted after done and values stored. 

Regarding this issue, my guess is that the default value is 0 (that we should maybe review and discuss it) and then all micrographs will be processed before any temporary files are deleted. 

Can you check this and maybe run with 10 o 20 as batch size?

**Comment by andreanans** [comment]
Hi,

I was using batch size 10 actually but still the directories were not deleted at all. Even after waiting for the entire process to complete it did not clean any directories. I'll try 20 and see what happens..

**Comment by delarosatrevin** [comment]
Hum..then it should not make a difference 10 or 20. The folder for each batch should be deleted. I think you don't need to relaunch again for now. I will check the code and get back to you.

**Comment by pconesa** [comment]
Just in case, there's variable , by default not active, that will prevent the tmp cleaning process: SCIPION_DEBUG_NOCLEAN. You probably don't know about it, and this might not be your case, but is worth checking.

Could you please, post the output of:

scipion run printenv

**Comment by andreanans** [comment]
Hi, just checked the environment and there is no variable for SCIPION_DEBUG_NOCLEAN.

**Comment by pconesa** [comment]
Thanks!

**Comment by delarosatrevin** [comment]
Hi @andreanans 
I have checked the code of ctffind4 and gct protocols...and the temporary folder for batch processing was not being cleaned up. Still, I believe that the tmp folder get clean after the protocol is finished. Anyway, it does not make sense to keep temporary files eating disk space unnecessary.

I'm not sure how it was different to 1.2, but I just fixed this issue for these two programs. How did you installed Scipion 2.0? Can you try the devel branch of these plugins? If not, you will need to wait a while until we make small patch release for these plugins. 

If you need any help updating help just let us know, I will be happy to help you with that.

**Comment by andreanans** [comment]
Hi, I installed from source but I'm happy to test the devel branch as well. I'll let you know how it goes. Thanks for looking into this!

**Comment by delarosatrevin** [comment]
Hi, Now with the plugins structure...you can use the stable version of Scipion and the devel branch of the fixed plugins only. Anyway, we probably will make a patch release soon.

**Comment by andreanans** [comment]
Hi, I tried installing some of the devel versions of the plugin but I'm running into permissions issues (I think?) I tried this command: git clone git@github.com:scipion-em/scipion-em-ctffind4.git and I get this error message: Permission denied (publickey). fatal: could not read from remote repository. Please make sure you have the correct access rights and the repository exists. I was following the instructions on this page: https://scipion-em.github.io/docs/release-2.0.0/docs/scipion-modes/install-plugins-command-line

Please let me know if I've done something wrong. Thanks!

**Comment by delarosatrevin** [comment]
Hi @andreanans ...thanks a lot for trying this out and compiling from source code. I feel that it is not as easy as it should be right now.

First, there is not ctffind4 plugin right now...this protocol is inside the grigoriefflab plugin.
Second, the url in that documentation page is a bit misleading...since it will only work for developers with access to that repository. You can use something like this:

```
git clone https://github.com/scipion-em/scipion-em-grigoriefflab.git
```

You can replace the same prefix for other links (i.e https:// instead of git@)

**Comment by andreanans** [comment]
Great! I've installed the devel version of the grigorieff lab and gctf plugins. Will let you know how it goes today. Cheers

**Comment by andreanans** [comment]
Just an update- ctffind is clearing the tmp directory after the completion of each batch so the devel version is working as it did in 1.2. Thanks so much!

**Comment by pconesa** [comment]
Thank you all.

**Comment by delarosatrevin** [comment]
Thanks for the update @andreanans!
