### ISSUE TITLE
protocols.template does not contain protocols necessary for model building

### ISSUE THREAD

**Issue by mmmtnez** [I2PC/scipion#2004]
scipion/pyworkflow/templates/protocols.template from branch release-2.0.0 was not updated for certain model building protocols, although respective tests were running in buildbot. This is the case of protocol "ProtImportSequence" and "ProtExportEMDB" in the Imports section. Additionally, "ProtImportPdb" shows the obsolete text "import PDB" and not the updated "import atomic structure". 
Can we have a way to test that protocols that are running in tests  also have their updates names in the template to avoid this problem in the future? Our tutorial indicates clearly the location in the Scipion menu of these protocols to edit them, and users are not going to find them there.

**Comment by pconesa** [comment]
Devel has this fixed already. As for production, we will add the missing ones in chimera plugin.

**Comment by pconesa** [comment]
@mmmtnez this was addressed in #2003 , right?
