### ISSUE TITLE
eman2.3: can not plot tilt validation result

### ISSUE THREAD

**Issue by liz18** [I2PC/scipion#2010]
I installed EMAN2.3, and ran a tilt validation project. However, when clicked "plot tilt validation", it said as following:

Couldn't load tp from DB, not showing polar plot
Couldn't open contour plot
Traceback (most recent call last):
  File "/usr/local/EMAN2/bin/e2tiltvalidate.py", line 591, in <module>
    main()
  File "/usr/local/EMAN2/bin/e2tiltvalidate.py", line 110, in main
    display_validation_plots(options.path, options.radcut, options.planethres, plotdatalabels=options.datalabels, color=options.datalabelscolor, plotzaxiscolor=options.colorzaxis)
  File "/usr/local/EMAN2/bin/e2tiltvalidate.py", line 490, in display_validation_plots
    plot = EMValidationPlot()
UnboundLocalError: local variable 'EMValidationPlot' referenced before assignment

besides this, all the other program ran normally. What could be the problem? How should I resolve it?

Thanks in advance.

**Comment by azazellochg** [comment]
Hi @liz18 , this is a bug in eman2.3 that you can find in eman mailing list. You can use Display tilt geometry plot instead - it will open the same plot using Scipion.

**Comment by liz18** [comment]
@azazellochg Thanks for your advice. I tried to use scipion to import the tilt pairs, however, it seems that there's no RCT module in scipion V2.0 as previous version. The "Display tilt geometry plot" you mentioned is a command run in terminal or a module in scipion v2.0?

**Comment by azazellochg** [comment]
@liz18 I'm a bit lost. Are you running tilt validation protocol in scipion? There are two buttons in Analyze results there to make the same plot - one with Scipion, one with EMAN. As for RCT menu, it's still in the View list, but maybe not complete. All protocols are still there.

**Comment by liz18** [comment]
@azazellochg Thanks!
