### ISSUE TITLE
Preserve tmp folder for failing protocols

### ISSUE THREAD

**Issue by DStrelak** [I2PC/scipion#2016]
**Is your feature request related to a problem? Please describe.**
While debugging / testing protocols, it happens that something goes wrong. Since the _tmp_ folder is deleted every time, it is hard to reproduce the issue.

**Describe the solution you'd like**
Ideally, _tmp_ folder should be preserved till the moment the protocol successfully finishes (for streamed protocols, this can be e.g. checked at the end of each iteration). Only once the protocol finishes properly, _tmp_ folder can be safely deleted.

**Describe alternatives you've considered**
I know I can export SCIPION_DEBUG_NOCLEAN=1. However, I don't consider this to be a alternative option, as I have to do it a priory of the protocol failure. If it fails after several hours of computation, it takes a lot of time to debug.

**Comment by azazellochg** [comment]
I think this is done already in pw/protocol/protocol.py:
```
        elif not self.isFailed():
            self.info('Cleaning temp folder....')
            self.cleanTmp()
```
