### ISSUE TITLE
Batch protocols do not finish when left items are lower than batch size

### ISSUE THREAD

**Issue by pconesa** [I2PC/scipion#2023]
**Describe the bug**
For gctf, cftfind and may be others, and processing in streaming, they fail without processing the remaining micrographs that are less than the batch size.

Number: mics --> 7995
Batch size --> 100
Processed mics --> 7900
95 are left out.

**Expected behavior**
Process those 95 once found input set is closed, or after a "while"?? (how to do this, not sure)

**Desktop (please complete the following information):**
 - Version: 2.0

**Comment by azazellochg** [comment]
I'm running version 2.0. Streaming.
Import, then motioncor2 (2 gpus, 3 threads), then ctffind4 with batches of 10 on 10 threads.
Number: mics --> 538
Batch size --> 10
Processed mics --> 538

**Comment by pconesa** [comment]
..and worked for you.

**Comment by azazellochg** [comment]
Yes

**Comment by pconesa** [comment]
I can close it and reopen in case a see this again. Thanks @azazellochg
