### ISSUE TITLE
particles.star from relion export particles not compatible with pyem

### ISSUE THREAD

**Issue by andreanans** [I2PC/scipion#2024]
Hi,

I noticed that the star file written out by 'relion export particles' is incompatible with the pyem scripts. I have to pass the star file through relion_star_handler to produce a star file in the correct format. 

We often run this command:
csparc2star.py --copy-micrograph-coordinates particles.star particles_selected.cs final_particles.star

and get the following error:

  File "pandas/_libs/parsers.pyx", line 545, in pandas._libs.parsers.TextReader.__cinit__
pandas.errors.EmptyDataError: No columns to parse from file

I think it's something to do with the delimiter but I have no clue how to fix it other than running relion_star_handler and removing a column to reformat the file. 

Any ideas?

**Comment by pconesa** [comment]
Hi @andreanans , if you are running Scipion 2.0, we have released a plugin to send jobs to cryosparc:

2D classification, ab-initio, and refinement (uniform and non-uniform)....

All of them import the particles into cryosparc so you can:
1.- use those methods and stay in scipion fot further processing.
2.- If you want other jobs not yet implemented.....you can kick off one of them and you will have a workspace with the particles in cryosparc.

Probably we can add a "export to cs" to export particles, volumes ....as we are already doing now, but this is not done yet.

**Comment by delarosatrevin** [comment]
Pablo, in any case would be good to take a look a this incompatibility
issue.

**Comment by andreanans** [comment]
Hi guys,

Thanks very much for the comments. I'll be sure to test the new plugin.

Just to clarify, we're having issues when going **back** to Scipion from cryosparc. As you probably know, some metadata is not preserved in those .cs files from cryosparc. If we want to generate a star file containing the original micrograph coordinates (for particle re-extraction) we must source our original star file from Scipion using the --copy-micrograph-coordinates flag. For some reason the scripts cannot read this star file unless I run it through relion_star_handler. 

Another side note, in previous versions of scipion  (1.1 or 1.2?) when you ran a particle extraction job it wrote out a star file automatically. This star file works fine with the script so I wonder if you could compare the two different files and see if the delimiter has changed somehow?

I hope this makes sense!!

**Comment by pconesa** [comment]
@delarosatrevin sure, I was just trying to give a workaround (if possible), but yes, something to look at.

@andreanans thanks for the tip....

I wish I could transfer this to scipion-em-relion repo.

**Comment by pconesa** [comment]
Added to relion repo.
