### ISSUE TITLE
motioncorr does not write out FAILED_all.txt file anymore

### ISSUE THREAD

**Issue by andreanans** [I2PC/scipion#2030]
Hi,

I noticed that the FAILED_all.txt file is not written out anymore during motion correction. This was very useful for identifying movies that failed to align. Is there anyway to get this back? in 2.0?

Edit: I compared protocol_align_movies.py in 1.21 and 2.0 and all the code that generates the FAILED_all.txt list is missing from 2.0. I suppose I can try copying the relevant code to get this working again but is it at all possible to add back the functionality in the future? Thank you!

**Comment by pconesa** [comment]
Hi @andreanans , could you post this at the motioncor plugin repo, I'd transfer it, but github does not allow to do this across organizations, and it's better if you remain as the author.

https://github.com/scipion-em/scipion-em-motioncorr/issues

**Comment by pconesa** [comment]
please

**Comment by pconesa** [comment]
Added here --> https://github.com/scipion-em/scipion-em-motioncorr/issues/16

**Comment by azazellochg** [comment]
@pconesa why this is motioncorr issue? This code was in protocol_align_movies.py so this is scipion issue
