### ISSUE TITLE
ProtUserSubset + new objects comming from plugins....

### ISSUE THREAD

**Issue by pconesa** [I2PC/scipion#2036]
We have actually a case now with tomography objects that can be shown in SHowJ, but subsets cannot be created since the ProtUserSubset is not aware of tomography objects and cannot create subsets.

This has to be considered in the "modularization" of Scipion core.

**Comment by delarosatrevin** [comment]
Yes, I think we need to think/discuss about this. Now the types from where subsets can be created are hard-coded in the Showj Java code.

**Comment by pconesa** [comment]
This is resolved through the static  Set.create method
