### ISSUE TITLE
Motioncorr problem in streaming mode

### ISSUE THREAD

**Issue by vabrishami** [I2PC/scipion#2037]
**Describe the bug**

In streaming mode, Motioncorr (2-1.2.6) reads one out of 20 movies from _import movies_ protocol and for example for 100 movies produces 5 or 6 aligned micrographs. In Scipion 1.2 Motioncorr (_motioncor2-1.0.5_) it works fine and processes all the movies.

**To Reproduce**

1. Make a project.
2. Add import movies and _Motioncorr_ protocols.
3. Run and schedule the protocols.

**Expected behavior**

_Motioncorr_ should process all the movies of the _import movies_ protocol.

**System**

 - OS: Centos 7
 - Scipion 2.0

**Comment by pconesa** [comment]
Thanks @vabrishami , just to clarify:

"Reads one out of 20" means it fails for 19?

**Comment by azazellochg** [comment]
can we see the log files please?

**Comment by vabrishami** [comment]
@pconesa It seems there’s no error since there’s nothing in the log about error.

**Comment by vabrishami** [comment]
@azazellochg I will send it tomorrow since I am out. Thanks

**Comment by vabrishami** [comment]
Hello guys,

It was a memory problem on GPU because of wrong projection of threads on GPU. Now it works perfectly.
