### ISSUE TITLE
CreateOutputStep's Movie align protocols bug

### ISSUE THREAD

**Issue by dmaluenda** [I2PC/scipion#2053]
**Describe the bug**
CreateOutputStep's Movie align protocols fails if doseWeithing is applaied and also saveMovies and saveUnWeithedMics are False.

**To Reproduce**
1. Import movies providing some dose per frame value
2. Run motioncor disabling the 'Save unWeithed micrographs' (in order to save disk).
3. See how all run as expected until the last step
4. See the error in the last step due to outputMicrographs doesn't exist.

**Error source**
https://github.com/I2PC/scipion/blob/d1a60f69960d1079bbbecde5bf3f5f4017b36927/pyworkflow/em/protocol/protocol_align_movies.py#L110_L114

**How to fix**
My proposal is to watch any output 
```
# validate that we have some output movies
for outName, out in self.iterOutputAttributes():
    output = out
    break

...

    self.warning(yellowStr("WARNING - Failed to align %d movies."
                           % (len(self.listOfMovies) - output.getSize())))
```

**Comment by azazellochg** [comment]
Fixed in https://github.com/scipion-em/scipion-em/commit/da38ef4d2b5052637809a1d8cdc2cc17a0b36e52 for scipion 3.0
