### ISSUE TITLE
particles shifted when picking with 'sphire - cryolo picking' from K3 micrographs

### ISSUE THREAD

**Issue by JuhaHuiskonen** [I2PC/scipion#2054]
When picking particles from K3 micrographs (rectangular shape) the particles are shifted towards the top right corner. As the installation works fine with Falcon III micrographs (square shape), I suspect it has to do with the rectangular shape.  I am not sure if this is a bug in cryolo or in Scipion coordinate conversions.

**Comment by pconesa** [comment]
Thanks @JuhaHuiskonen , we experienced that , and if I remember correctly, the shift was coming from entering a non multiple of 32 in the input size.

We also added some code to convert the parameter to the closest multiple of 32, and as a consequence, throsten added this in his documentation page:

#02 input_size: This is the size to which the input is rescaled before passed through the network (it is NOT the size of your micrograph!). In the example given here it would be 768×768. The input could either be the whole micrograph or a patch (in case you use the patchmode). The input size have to be a multiple of 32.



Either:
1.- you do not have the latest plugin
2.- The latest plugin does not have what I'm saying it has (our bad)
3.- You are right and Cryolo does not work nicely with non square images.

@JuhaHuiskonen , can you check that the input size is multiple of 32?

I'll check with Thorsten.

**Comment by JuhaHuiskonen** [comment]
Hi @pconesa.  The input size is the Scipion default = 1024. Number of patches = 1.

**Comment by pconesa** [comment]
Great! then, that eliminates #1 and #2, or at least that is not the issue.

**Comment by delarosatrevin** [comment]
@JuhaHuiskonen what version of the plugin are you using?

@pconesa the symptom of going to the top right corner could also be a bug while parsing the coordinates from EMAN convention, that we bring to the center, could you check this?

**Comment by JuhaHuiskonen** [comment]
@delarosatrevin our plugin version is 1.2.8

**Comment by pconesa** [comment]
@JuhaHuiskonen ....is the shift progressively increasing? or is it constant?

Could you please post a screenshot?

**Comment by JuhaHuiskonen** [comment]
@pconesa  It's a constant.   If I extract the particles, each particle is shifted towards the top right corner.

**Comment by pconesa** [comment]
Thanks, @JuhaHuiskonen, could you post a screen capture of the output, for now.

**Comment by thorstenwagner** [comment]
The problem seems to be on the crYOLO side. It seems to be a problem, when you apply a model which was trained with square anchor sizes on non-square images. I've to dig deeper into that problem next week.

Quick workaround, pick 5 micrographs, train (or maybe just refine) a model and it will work.

**Comment by pconesa** [comment]
Many thanks @thorstenwagner !

**Comment by thorstenwagner** [comment]
Thank you @JuhaHuiskonen  and @pconesa  for making me aware of that problem!

**Comment by thorstenwagner** [comment]
@JuhaHuiskonen  and @pconesa 

The problem should be fixed. Here is release candidate:
https://pypi.org/project/cryolo/1.5.4rc2/

Could you give it a try?

**Comment by pconesa** [comment]
Thanks @thorstenwagner , we are going to update the plugin and test the new version. @JuhaHuiskonen I'll let you know when we release the plugin

**Comment by JuhaHuiskonen** [comment]
We updated the binary and it seems to have solved the problem.

**Comment by pconesa** [comment]
I guess a : 
`pip install cryolo==1.5.4rc3`
solved it?

**Comment by vabrishami** [comment]
@pconesa It should work, but we had a number of errors. So I followed the download instructions in Cryolo page (without touching plugin) to install it again, and it did work.
