### ISSUE TITLE
'scipion - join sets' fails when joining large sets of coordinates

### ISSUE THREAD

**Issue by JuhaHuiskonen** [I2PC/scipion#2061]
I am trying to join two sets of coordinates (from CrYOLO runs that complete ok) with 1M and 2.8M coordinates.  This fails with the following error:

00001:   RUNNING PROTOCOL -----------------
00002:        HostName: puhti-login1.bullx
00003:             PID: 151118
00004:         Scipion: v2.0 (2019-04-23) Diocletian
00005:      currentDir: /scratch/project_2001566/ScipionUserData/projects/JK_em20223-30
00006:      workingDir: Runs/005526_ProtUnionSet
00007:         runMode: Continue
00008:             MPI: 1
00009:         threads: 1
00010:   len(steps) 1 len(prevSteps) 0 
00011:    Starting at step: 1
00012:    Running steps 
00013:   STARTED: createOutputStep, step 1
00014:     2019-10-27 16:12:34.015138
00015:   Traceback (most recent call last):
00016:     File "/projappl/project_2001566/apps/scipion/2.0/pyworkflow/protocol/protocol.py", line 186, in run
00017:       self._run()
00018:     File "/projappl/project_2001566/apps/scipion/2.0/pyworkflow/protocol/protocol.py", line 237, in _run
00019:       resultFiles = self._runFunc()
00020:     File "/projappl/project_2001566/apps/scipion/2.0/pyworkflow/protocol/protocol.py", line 233, in _runFunc
00021:       return self._func(*self._args)
00022:     File "/projappl/project_2001566/apps/scipion/2.0/pyworkflow/em/protocol/protocol_sets.py", line 138, in createOutputStep
00023:       outputSet = getattr(self, "_create%s" % set1.getClassName())()
00024:   TypeError: _createSetOfCoordinates() takes at least 2 arguments (1 given)
00025:   Protocol failed: _createSetOfCoordinates() takes at least 2 arguments (1 given)
00026:   FAILED: createOutputStep, step 1
00027:     2019-10-27 16:12:34.057002
00028:   *** Last status is failed 
00029:   ------------------- PROTOCOL FAILED (DONE 1/1)

Our Scipion version is 2.0

**Comment by pconesa** [comment]
Hi @JuhaHuiskonen , thanks for reporting the issue. 
We have already fixed it in our devel branch, but it might not be a good idea to switch to it for production work.

the changes are here: https://github.com/I2PC/scipion/commit/e9381a5823d19398e75d9a5d80ce53c5dd8e3ec0#diff-6f8bea850795c9016fc4a7754c247bfc

1.- Either make the same change to your local file
2.- Do the extraction first and then join particles.

**Comment by JuhaHuiskonen** [comment]
Hi @pconesa, thanks.  I am having a similar issue with 'scipion - split sets' and sets of coordinates. Is this likely to be related or should I open another ticket?

**Comment by JuhaHuiskonen** [comment]
@pconesa, thanks this worked!

**Comment by pconesa** [comment]
I'm closing this issue. Feel free to reopen it if I'm wrong or missed something.
