### ISSUE TITLE
'relion - post-processing' protocol does not update calibrated pixel size

### ISSUE THREAD

**Issue by JuhaHuiskonen** [I2PC/scipion#2068]
A calibrated pixel size can be given to this protocol.  However this value is not reflected in the outputVolume.

**Comment by delarosatrevin** [comment]
So, the output volume should have the calibrated pixel size?

**Comment by JuhaHuiskonen** [comment]
yes, that would make sense, both in Scipion metadata and the header of the map file written out.

**Comment by delarosatrevin** [comment]
I have fixed this in the following commit: https://github.com/scipion-em/scipion-em-relion/commit/773f982c2fb769427a58aa086a95b9b6ab775a2f

It will be released in the next scipion-em-relion pluglin version. 

I updated the output pixel size in the Scipion metadata. I also
checked that the mrc volume has the correct value (using mrcfile library).
