### ISSUE TITLE
relion-3D multi-body fails in the last step 'createOutputStep'

### ISSUE THREAD

**Issue by mohsenkazemi** [I2PC/scipion#2070]
relion-3D multi-body fails in the last step and is not providing output. The error is:

Traceback (most recent call last):
00772:     File "/share/apps/scipion/pyworkflow/protocol/protocol.py", line 186, in run
00773:       self._run()
00774:     File "/share/apps/scipion/pyworkflow/protocol/protocol.py", line 237, in _run
00775:       resultFiles = self._runFunc()
00776:     File "/share/apps/scipion/pyworkflow/protocol/protocol.py", line 233, in _runFunc
00777:       return self._func(*self._args)
00778:     File "/share/apps/scipion/software/lib/python2.7/site-packages/relion/protocols/protocol_multibody.py", line 242, in createOutputStep
00779:       volume.setFileName(self._getFileName('outputVolume'))
00780:     File "/share/apps/scipion/pyworkflow/protocol/protocol.py", line 841, in _getFileName
00781:       return self.__filenamesDict[key] % kwargs
00782:   KeyError: 'outputVolume'

**Comment by azazellochg** [comment]
Thank you @mohsenkazemi , that's a known bug we hope to fix soon. https://github.com/scipion-em/scipion-em-relion/issues/113
