### ISSUE TITLE
2D classification failure 

### ISSUE THREAD

**Issue by PatriciaGD** [I2PC/scipion#2079]
Hi, 

When I tried to run a 2D classification using Xmpp3 or Relion it always fail. I get these error messages: 

00020:   2020-05-12 08:33:39,725 ERROR:  Protocol failed: Command 'mpirun -np 2  `which xmipp_mpi_classify_CL2D` -i Runs/002332_XmippProtCL2D/tmp/input_particles.xmd --odir Runs/002332_XmippProtCL2D/extra --oroot level --nref 50 --iter 25  --distance correlation --classicalMultiref --nref0 4' returned non-zero exit status 1

or

00093:   Protocol failed: Command 'mpirun -np 8  `which relion_refine_mpi` --gpu  --tau2_fudge 2 --scale  --dont_combine_weights_via_disc  --iter 25 --norm  --psi_step 10.0 --ctf  --offset_range 5.0 --oversampling 1 --pool 3 --scratch_dir /scratch/tmp-pg --o Runs/001440_ProtRelionClassify2D/extra/relion --i Runs/001440_ProtRelionClassify2D/input_particles.star --particle_diameter 304.5 --K 20 --ctf_phase_flipped  --flatten_solvent  --zero_mask  --offset_step 2.0 --angpix 1.05  --j 1' returned non-zero exit status 1

I have tried downscaling the particles and also using different amounts of MPIs but it keeps falling. I am using Scipion v2.0 (2019-04-23) Diocletian. 

Many thanks in advance! 

Best regards, 
Patricia Gil

**Comment by azazellochg** [comment]
Hello @PatriciaGD  let's start from basic checks. Could you please run 'scipion run mpirun -np 3 hostname' command and post the output here?

**Comment by PatriciaGD** [comment]
Hi, 
This is all I got:  
Sorry!  You were supposed to get help about:
    opal_init:startup:internal-failure
But I couldn't open the help file:
    /usr/lib64/openmpi-2.0.1/share/openmpi/help-opal-runtime.txt: No such file or directory.  Sorry!

Many thanks for the quick answer! 
Patricia Gil

**Comment by azazellochg** [comment]
OK, so mpi is not configured properly for scipion. Could you please verify that all MPI* vars are set properly in the configuration file, as described here: https://scipion-em.github.io/docs/docs/scipion-modes/scipion-configuration.html

Also you could run 'mpirun -np 3 hostname' outside of scipion to make sure your system mpi works.

**Comment by PatriciaGD** [comment]
It doesn´t run: command not found
I can imagine that the problem is the system mpi configuration. What could be the solution?
I can´t install anything myself but I can report the problem to the IT technician. 
Also, I am working on another server via ssh.

**Comment by azazellochg** [comment]
Yes, since there can be many different options, I would consult the IT
person responsible for the server on how to use mpi.

**Comment by PatriciaGD** [comment]
Ok, many thanks for your help.
