### ISSUE TITLE
Check bug in reading images in threads from reconstruct_fourier

### ISSUE THREAD

**Issue by cossorzano** [I2PC/scipion#217]

**Comment by juannavascalvente** [comment]
If the reconstruct fourier is executed using more than 1 thread then the results are not correct because of race conditions. The algorithm must be executed using 1 thread or using MPI.

It is necessary to remove the --thr parameter to avoid the execution of the algorithm using more than 1 thread.

**Comment by delarosatrevin** [comment]
Is this fixed?

**Comment by juannavascalvente** [comment]
This bug is not yet fixed. The solution to this bug is to remove the input parameter that sets the number of threads. This algorithm must not be executed using threads because there are race conditions. The only way to execute it is using MPI or a single thread.

**Comment by delarosatrevin** [comment]
Reconstruct fourier currently does not support threads.
