### ISSUE TITLE
Implement Bsoft viewer for images

### ISSUE THREAD

**Issue by ldelcano** [I2PC/scipion#24]
Bshow needs a star file with a specific format (see attached file).
Image file needs to be a stack (either a spider stack or a mrc stack).
If dealing with individual images we need a block per micrograph (image).
Create a bsoft.convert to create the required star file

It is not that bshow requires a star file to open the image.
Bshow can open spider or mrc stacks and single img files but if we want to open many imgs they cannot be opened together on a single viewer (like xmipp does), we need to create a stack or a star file.

Xmipp metadata_sql module does not accept metadata labels with a 'dot' in the middle.
Jose Miguel suggest maybe method label2Str should be changed to return the string already with quotes.

**Comment by ldelcano** [comment]
Bosft viewer already appear for volumes, check if it is possible (and make sense) to use it for images too.

**Comment by azazellochg** [comment]
Assuming nobody is using Bsoft, it will be deprecated as plugin. Feel free to re-open if you think otherwise
