### ISSUE TITLE
Form download

### ISSUE THREAD

**Issue by rmarabini** [I2PC/scipion#252]
when downloading scipion you get the following message:

The download of scipion_v1.0.0_2016-01-21_linux64-em-packages.tgz will start now. If it doesn't, click on this link

The link is there (in the word link) but no change in color or style give you anu hint

**Comment by pconesa** [comment]
Better? 
![image](https://cloud.githubusercontent.com/assets/785633/12550222/92832e04-c362-11e5-8194-9a8fe4b54268.png)
