### ISSUE TITLE
Error in scipion.conf if there is a previous installation

### ISSUE THREAD

**Issue by juannavascalvente** [I2PC/scipion#267]
If there is a previous installation of scipion, when trying to execute ./scipion config there is an error. The output provided is:

Section PACKAGES exists in the template but not in the configuration file.

It is necessary to remove scipion.conf file in the home folder and then it works. It does not work either when executing ./scipion config --overwrite.

**Comment by pconesa** [comment]
I'm not getting any error, but an output highlighting  differences between the template and the actual config file. I guess the idea is to append the sections where missing copying them from the template.

**Comment by pconesa** [comment]
solved at #723
