### ISSUE TITLE
tools-> set-->subset

### ISSUE THREAD

**Issue by mohsenkazemi** [I2PC/scipion#274]
parameter set operation does not make sense here
@rmarabini

**Comment by delarosatrevin** [comment]
@rmarabini , why do you think the *set operation* parameter does not make sense there?

This protocol create a subsets of elements from set A, taking either the intersection or the difference respect with set B.

**Comment by rmarabini** [comment]
we were using subset-> make random subset. There is no B set in this case.

**Comment by delarosatrevin** [comment]
You are right...I added the condition to this parameter. So now, when you select to use 'random subset',
the other set and the set operation disappears.

I added the modification in the Pull Request #275 , assigned to @cossorzano , 
@rmarabini maybe you can take a look at the changes and approve the merge into v1.0.
