### ISSUE TITLE
Pick filaments

### ISSUE THREAD

**Issue by cossorzano** [I2PC/scipion#293]

**Comment by delarosatrevin** [comment]
Some options to pick filaments in Scipion are:
1) Implement that feature in Xmipp particle picker
2) Add a protocol for the e2helixboxer.py Eman program.

**Comment by pconesa** [comment]
Add an filament/"linear" mode. We need a "distance" (d) in pixels to represent how close or not are the particles from each other.

The the user clicks once  at any point (origin) to start the linear picking.
a line would be nice to be painted from the origin to the mouse pointer
to finish the user must click somewhere (end) else and particles are created from origin to end separated "d" pixel from each other.

**Comment by pconesa** [comment]
I'm leaving this as Pick filaments and will create another for the protocol.

**Comment by pconesa** [comment]
relates to #475

**Comment by pconesa** [comment]
Samples:
![image](https://cloud.githubusercontent.com/assets/785633/16414519/541d4708-3d38-11e6-9c56-31e0d7e5b960.png)

New cursors:
Linear picking cursor:
![image](https://cloud.githubusercontent.com/assets/785633/16414551/8f89999a-3d38-11e6-8959-64db0d4ed0a9.png)
Eraser cursor:
![image](https://cloud.githubusercontent.com/assets/785633/16414562/9afd727e-3d38-11e6-831a-c533d6620755.png)
Normal picking cursor:
![image](https://cloud.githubusercontent.com/assets/785633/16414583/b9048eb0-3d38-11e6-9472-b220e6db5e81.png)

**Comment by pconesa** [comment]
A better image:
![image](https://cloud.githubusercontent.com/assets/785633/16800379/52579784-48f5-11e6-9de7-03a8a916c99c.png)
