### ISSUE TITLE
Import Set of Volumes

### ISSUE THREAD

**Issue by cossorzano** [I2PC/scipion#297]
It should use the filename as the default label for each one of the items

**Comment by ldelcano** [comment]
There are two options: 
1. Modify import_volumes protocol to set label to filename when creating the output.
Also find all protocols that create SetOfVolumes as output and set label as filename (to overwrite a possible old value if it is copied from input volumes).
2. See how the Object selector works and if it could be possible to set label equal to filename for SetOfVolumes there. This option is not possible cause Object selector works on a completely generic way, with a generic tree provider that is agnostic on the type of object.

**Comment by ldelcano** [comment]
Option 1 does not work since the name shown on the Object selector for items does not corresponds to the label.

**Comment by ldelcano** [comment]
Modified SubclassesTreeProvider._getPointerLabel function to return label for an item set if it exists (if not return the 'item #id' as before). The only question is that currently the label shown is not the object label but the string returned by function 'getObjectLabel', which is a string representation of the object and is never empty. Decide which one we want to show.

**Comment by ldelcano** [comment]
Final solution:
- Object selector: For items on a set show 'ItemX - label (if there is label)'.
- For Align Volumes output volumes: Set label as 'Protocol origin - outputVolume - X'.
