### ISSUE TITLE
Resmap wizard does not load

### ISSUE THREAD

**Issue by pconesa** [I2PC/scipion#305]
If you go to fcv example project and try to run the resmap wizzard it will fail

**Comment by pconesa** [comment]
I've restarted and now it works...memory issues?. Also there were some jobs running, and maybe affecting the webserver?.

**Comment by pconesa** [comment]
I've found a suspicous line at matplotlib_image.py forcing 'TkAgg'

import matplotlib
matplotlib.use('TkAgg')

There are 4 places where we are doing this..is this necessary. Can we rely on the config file instead?

@delarosatrevin

**Comment by pconesa** [comment]
It seems that launching a result resmap result (slices), breaks the wizzard, does it make any sense? @delarosatrevin

**Comment by delarosatrevin** [comment]
It does not make any sense....anyway we should removed those line. We should check the history to see if this was cleaned up in the past or the bug was re-introduced.

**Comment by pconesa** [comment]
I know, but it happens. Now I've found we are using os.cwd at Resmap_wizzard.py/getPlotResMap

results = _beforePreWhitening(protocol, os.getcwd())

Therefore, going to "scipion home" in the web and generating volume1.map there!!

Getting closer!

**Comment by pconesa** [comment]
There's something mixing things up! (histogram + resmap wizzard together.).
![image](https://cloud.githubusercontent.com/assets/785633/13313241/c1136778-db9c-11e5-80b0-70050578fc8d.png)

**Comment by pconesa** [comment]
fixed closing the plots when not used anymore.
