### ISSUE TITLE
xmipp extract particle fails if background radius > particle half-size

### ISSUE THREAD

**Issue by azazellochg** [I2PC/scipion#316]
If I select micrograph source: other, downsample 4, box size 128px, preprocess: background radius 200px, the protocol obviously crashes in the middle of the run due to radius bigger than particle size:

> 00154:   XMIPP_ERROR 2:  Incorrect argument received
> 00155:   Given radius is larger than half the output size
> 00156:   File: software/em/xmipp/libraries/data/normalize.cpp line: 638

I suggest to implement a check of this radius upon protocol validation.

Ps. error also exists if I select micrographs source: same as picking.

**Comment by delarosatrevin** [comment]
Sure, a validation should be added to check this. If you click on the wizard, it proposed a reasonable box size base on the sampling of micrographs, original box size and the downsampling factor.

**Comment by azazellochg** [comment]
@delarosatrevin , yes, the wizard for particle box size works fine.

**Comment by delarosatrevin** [comment]
Validation added in 07af721af8fe
