### ISSUE TITLE
java error upon displaying CTF profile

### ISSUE THREAD

**Issue by azazellochg** [I2PC/scipion#318]
I have imported \*.txt files from ctffind4 as CTFs, in Analyze results I can see power spectra fit and all the results (defocuses, max res etc), but if I click on 'Show CTF profile' for any PSD: 
I get **java.lang.NullPointerException** window and **Unsupported format or not found** string in the console..

**Comment by delarosatrevin** [comment]
Could you make a tar file with 3 result folder and send to us? Just to try to reproduce the same error with an smaller case.

**Comment by azazellochg** [comment]
@delarosatrevin , I have sent you the files. In addition, I should say that there is no option "Display CTF fitting" in the menu, though I have *_avrot.txt files for graph plotting, when importing CTFs.

**Comment by azazellochg** [comment]
@delarosatrevin 
Maybe this can help: I have discovered that when I click Analyze results of the ctffind4 protocol, the command is the following. It has _Display ctf fitting_ line etc.:

```bash
java -Xmx2g -d64 -Djava.library.path=/home/igbmc/gsharov/soft/scipion_gpu/scipion/software/em/xmipp/lib -Dplugins.dir=/home/igbmc/gsharov/soft/scipion_gpu/scipion/software/em/xmipp/external/imagej/plugins -cp /usr/lib/jvm/java-1.6.0-openjdk-1.6.0.0.x86_64/lib/*:/home/igbmc/gsharov/soft/scipion_gpu/scipion/software/em/xmipp/external/imagej/*:/home/igbmc/gsharov/soft/scipion_gpu/scipion/software/em/xmipp/java/lib/* xmipp.viewer.scipion.ScipionViewer -i Runs/000835_ProtCTFFind/ctfs.sqlite --render _psdFile --object_commands 'Display Ctf Fitting' --zoom 50 --visible id enabled comment _psdFile _defocusU _defocusV _defocusAngle _defocusRatio _ctffind4_ctfResolution _micObj._filename --mode metadata --order id enabled comment _psdFile _defocusU _defocusV _defocusAngle _defocusRatio _ctffind4_ctfResolution _micObj._filename --scipion 49722 896
```

However, when I click on Analyze results of the ctf import protocol, the command is:

```bash
java -Xmx2g -d64 -Djava.library.path=/home/igbmc/gsharov/soft/scipion_gpu/scipion/software/em/xmipp/lib -Dplugins.dir=/home/igbmc/gsharov/soft/scipion_gpu/scipion/software/em/xmipp/external/imagej/plugins -cp /usr/lib/jvm/java-1.6.0-openjdk-1.6.0.0.x86_64/lib/*:/home/igbmc/gsharov/soft/scipion_gpu/scipion/software/em/xmipp/external/imagej/*:/home/igbmc/gsharov/soft/scipion_gpu/scipion/software/em/xmipp/java/lib/* xmipp.viewer.scipion.ScipionViewer -i Runs/000799_ProtImportCTF/ctfs.sqlite --visible id enabled label _psdFile _xmipp_enhanced_psd _xmipp_ctfmodel_quadrant _xmipp_ctfmodel_halfplane _defocusU _defocusV _defocusAngle _defocusRatio _xmipp_ctfCritFirstZero _xmipp_ctfCritCorr13 _xmipp_ctfCritFitting _xmipp_ctfCritNonAstigmaticValidity _xmipp_ctfCritCtfMargin _xmipp_ctfCritMaxFreq _micObj._filename --zoom 50 --mode metadata --render _psdFile _xmipp_enhanced_psd _xmipp_ctfmodel_quadrant _xmipp_ctfmodel_halfplane --order id enabled label _psdFile _xmipp_enhanced_psd _xmipp_ctfmodel_quadrant _xmipp_ctfmodel_halfplane _defocusU _defocusV _defocusAngle _defocusRatio _xmipp_ctfCritFirstZero _xmipp_ctfCritCorr13 _xmipp_ctfCritFitting _xmipp_ctfCritNonAstigmaticValidity _xmipp_ctfCritCtfMargin _xmipp_ctfCritMaxFreq _micObj._filename --scipion 49722 901
```

It has no line _Display Ctf fitting_ and has many xmipp-related parameters, though I explicitly selected import from grigorieff in the import protocol.

**Comment by delarosatrevin** [comment]
Yes, this could be the reason of the problem...we need to take a look.

**Comment by azazellochg** [comment]
I think the problem is that by default, for any SetOfCTF, xmipp viewer is launched with "xmipp-related" ctf params: [here](https://github.com/I2PC/scipion/blob/master/pyworkflow/em/packages/xmipp3/viewer.py#L262).
So, we need somehow to check if, for example, CTFModel contains _ctffind4_crossCorrelation and then add OBJCMDS command (to Display Ctf fitting).
The same if CTFModel contains, e.g. _xmipp_enhanced_psd and then use default xmipp viewParams.

**Comment by delarosatrevin** [comment]
If think that is more related to missing the "Display ctf fitting" part. Certainly the xmipp-related labels are useless in this case, but there are harmless as well.

**Comment by azazellochg** [comment]
@delarosatrevin , you are right. Meanwhile, I believe I found the bug. 
[Here](https://github.com/I2PC/scipion/blob/v1.0/pyworkflow/em/packages/grigoriefflab/dataimport.py#L56), when psd file is imported from ctffind, it will have a name _blabla.ctf:mrc_ - it will be recognized/visible in metadata display, but CTF profile wont work. If I rename psd files to mrc (or manually edit psd filenames in ctfs.sqlite and rename psd files accordingly) and remove ":mrc" suffix, the problem is gone and the plot works.

**Comment by delarosatrevin** [comment]
Great! Thanks one more time for the help! Sometimes it is harder to find the bug that fix it.
I think this one can be easily be fixed. I will let you know.
