### ISSUE TITLE
error installing package...

### ISSUE THREAD

**Issue by rmarabini** [I2PC/scipion#319]
When trying to execute install relion

                   roberto@clark-cinco:/usr/local/ScipionStable/scipion# ./scipion install relion-1.4

I get the error: gzip: stdin: unexpected end of file (see issue end for details)
I imagine that this is because scipionwiki.cnb.csic.es is down.

I would suggest:

if the problem is that  scipionwiki.cnb.csic.es is down the user should get a more descriptive error message: "server xxxx is down please try again later". Since I have suffered this error many times, scipionwiki.cnb.csic does not seem to be  a reliable server. My suggestion would be to move the tared files to  github

------------------------
Scipion v1.0.0 (2016-02-15) Augusto

Building relion-1.4 ...
wget -nv -c -O software/em/relion-1.4.tgz.part http://scipionwiki.cnb.csic.es/files/scipion/software/em/relion-1.4.tgz
mv -v software/em/relion-1.4.tgz.part software/em/relion-1.4.tgz
`software/em/relion-1.4.tgz.part' -> `software/em/relion-1.4.tgz'
cd software/em
tar -xzf relion-1.4.tgz

gzip: stdin: unexpected end of file
tar: Child returned status 1
tar: Error is not recoverable: exiting now
Error: target 'software/em/relion-1.4' not built (after running 'tar -xzf relion-1.4.tgz')

root@clark-cinco:/usr/local/ScipionStable/scipion# ls -lrt software/em/relion-1.4.tgz
-rw-r--r-- 1 root staff 0 Feb 17 09:43 software/em/relion-1.4.tgz

**Comment by delarosatrevin** [comment]
You have a wrong configuration file....with a WRONG value of SCIPION_URL pointing to out-of-date 
 http://scipionwiki.cnb.csic.es/files/scipion

You should remove (or backup) the scipion/config/scipion.conf and generated again by ./scipion config. The right value should be:

SCIPION_URL = http://scipion.cnb.csic.es/downloads/scipion
