### ISSUE TITLE
Running remote, still uses ssh to localhost

### ISSUE THREAD

**Issue by andreanans** [I2PC/scipion#329]
Hello,

I modified my hosts.conf file to include other multi-CPU machines. However, when I try to run jobs on them remotely, scipion still uses 'ssh localhost etc etc' instead of 'ssh machinename etc etc'. I've deleted the section of hosts.conf that references localhost to try to force it to use the remote machine but it still uses localhost. Is there something else I need to do or is this a bug?

Thanks,

Andrea

**Comment by delarosatrevin** [comment]
Hi Andrea, 

Unfortunately, the distributed execution over different machines is not fully operational yet. We are working on it and we plan to release it soon (the first official v1.0.0 release will be announced next week) in another version. 

Would you be interested in test a beta-version of this feature? (when we have it)
Thanks for the feedback, this is important for us to know about users need.

**Comment by andreanans** [comment]
I'm happy to test anything you have. I managed to get it working on our cluster after changing ###PBS -q default to #PBS -q mpi in hosts.conf. For now we will just ssh into head node and open scipion there.

Thanks!

Andrea

**Comment by delarosatrevin** [comment]
Great! Don't hesitate to contact us to report a bug or suggest a new feature.
Then I will close this issue and keep you updated about the progress of remote computing over several hosts.
