### ISSUE TITLE
misleading message when re-run picking protocols

### ISSUE THREAD

**Issue by azazellochg** [I2PC/scipion#330]
I have run picking protocol (e.g., gEMpicker) twice: first time 289 ptcls were picked first time and 321 in a second run. When I click **Analyze results**, this message appears:

> It seems that you have edited this SetOfCoordinates before.
> Do you wish to load the changes?
> 
>  Note: If you choose **No**, the original coordinates will be loaded
>  and previous changes will be lost.

- second sentence does not make sense to me: what are "previous" changes - old or new coord set?
- If I click **No** - new ptcls (321) are loaded, if I click **Yes** - 289 old particles are loaded

I think the idea (in the first sentence) was that if you click **Yes** you will get new coordinates and if you click **No** - new coords are lost and old ones are loaded. I suggest to:

- [x] invert the behavior of the program, so upon clicking **Yes** you get new picked data.
- [ ] rephrase 2nd sentence to: Note: If you choose **No**, the original coordinates will be loaded
and latest changes will be lost.
- [ ]  also, after choosing the answer once, the window should not appear again, since any answer will not work anymore (I checked it)

**Comment by delarosatrevin** [comment]
I agree that this message is misleading. Actually, it is not related to the run of the picking but to the 'Analyze Result'. Let me try to explain the rationale behind.
When you hit 'Analyze Result' the coordinates are converted to Xmipp format in temporary folder(tmp). 
Then if you hit again, if the tmp exists, the misleading question is asked. The point here is that you could have picked in the tmp folder and have not generated coordinates, so if we clean up the tmp you could loose your picked particles. 

Anyway, I think the message is not helpful at all, so I have removed it. And I will open a new issue to warning if you picking in the tmp folder that you save your changes.
