### ISSUE TITLE
Warn if the user picks in the Tmp folder of the written coordinates

### ISSUE THREAD

**Issue by delarosatrevin** [I2PC/scipion#331]
This issue is related to #330 , before we used a misleading question to load an existing tmp directory (which, by the way, did not took into account the time of modification of the set of coordinates).

I more clear solution could be warn the user when picking in a tmp directory and leaving without saving changes.

**Comment by pconesa** [comment]
Add a parameter to warn that the user will loose the changes (if there are changes to be lost) before closing the picker.
