### ISSUE TITLE
Bug upon deleting multiple SetOfCoordinates after picking

### ISSUE THREAD

**Issue by azazellochg** [I2PC/scipion#333]
Here is the situation:
![picking2](https://cloud.githubusercontent.com/assets/6952870/13204837/ef5910d0-d8d9-11e5-8c81-f86ca298a8fc.png)

1. I have picked some particles via xmipp manual/supervised and then manually added/removed some particles in Xmipp picking GUI (few times), thereby creating several output SetOfCoordinates (outputCoordinates, outputCoordinates2, outputCoordinates3). If I right-click on one of them and choose Delete, the uncomplete message appears (see the image). However, the coordinates are indeed deleted.
![picking1](https://cloud.githubusercontent.com/assets/6952870/13204839/01af006e-d8da-11e5-83af-81ecb60df89d.png)

2. Another thing If I delete outputCoordinates (the original one), even if there are new outputCoordinates2/3, I can't display results anymore since `'XmippProtParticlePicking' object has no attribute 'outputCoordinates'`

**Comment by delarosatrevin** [comment]
@azazellochg , this should be easy to fix, thanks for the feedback.

**Comment by azazellochg** [comment]
Fix confirmed.
