### ISSUE TITLE
spider classify kmeans: number of classes is not displayed and not passed by protocol

### ISSUE THREAD

**Issue by azazellochg** [I2PC/scipion#338]
The problem is that the [number of classes](https://github.com/I2PC/scipion/blob/v1.0/pyworkflow/em/packages/spider/protocol/protocol_classify_kmeans.py#L49) goes after [mpi params](https://github.com/I2PC/scipion/blob/v1.0/pyworkflow/em/packages/spider/protocol/protocol_classify_base.py#L84) from the base protocol, so it does not appear in GUI

Update: the protocol does not work with number of classes other than 4. This number is hard-coded in kmeans script and does not seem to be updated from the protocol input.

**Comment by delarosatrevin** [comment]
We fixed this bug in cb3c0f2e3c661cdb11bf822fc9ae2fc2e7950773, the problem was the order of defineParams. 

Additionally, we also fixed a problem parsing the Spider script lines of the form: x = value.
