### ISSUE TITLE
xmipp3 tilt pairs picking: incorrect summary

### ISSUE THREAD

**Issue by azazellochg** [I2PC/scipion#343]
If user has created several outputCoordinatesTiltPair, the summary of the protocol is not correct: number of particles, size and last picked mic does not change and have the values from the first output.  

Here is the picture:
![summary_rct](https://cloud.githubusercontent.com/assets/6952870/13294184/13beb5a6-db23-11e5-9162-a285dabec2b3.png)

**Comment by delarosatrevin** [comment]
@Vilax , can you take a look at this?

**Comment by Vilax** [comment]
Thanks in advance for reporting this bug.

It has been fixed.

Vilax

**Comment by delarosatrevin** [comment]
@azazellochg , This was also fixed in v1.0, together with other related issues with picking, deleting and summary...let us know if you can try it.

**Comment by azazellochg** [comment]
Fix confirmed.
