### ISSUE TITLE
eraser size in xmipp picking GUI

### ISSUE THREAD

**Issue by azazellochg** [I2PC/scipion#345]
This is more of a feature request: I could not find a way to erase bigger "areas" with bad particles using the default eraser. Maybe smth similar to e2boxer eraser could be implemented (it is a circle with adjustable radius)? 
Btw, I guess after erasing these areas are available again for autopickers? The last one would be difficult to do for all picking protocols, however maybe there is a way? :)

**Comment by delarosatrevin** [comment]
Thanks for the feedback. We should further discuss about this.

**Comment by delarosatrevin** [comment]
@pconesa Added some shortcuts to enlarge/shrink the eraser area. 
Maybe we should highlight this area or allow to set the numeric value.

**Comment by azazellochg** [comment]
Hm, I have tried them but didn't notice much difference. Maybe showing a circle around the eraser image (to highlight which area is going to be erased) would be nice? 
![resmap2](https://cloud.githubusercontent.com/assets/6952870/17512963/b08bb020-5e2a-11e6-84f3-4cb1686ea257.png
)
Using shortcuts might be fine, though I still advocate for eman2-style eraser (circle radius can be adjusted by a slider)

**Comment by pconesa** [comment]
So be it! ;-) Nice example image by the way.

**Comment by pconesa** [comment]
We are making some room for the eraser size... will look something like this:

## Normal picking mode
![pickingredesign](https://cloud.githubusercontent.com/assets/785633/17550773/fe8d8e2a-5ef6-11e6-8aa2-176ea4ddb94c.png)

## Linear mode
![pickinglredesign](https://cloud.githubusercontent.com/assets/785633/17550775/fe8f65b0-5ef6-11e6-8a51-5ec0a3d04107.png)

## Erase mode
![pickingeredesign](https://cloud.githubusercontent.com/assets/785633/17550774/fe8e619c-5ef6-11e6-973f-ffd5c437d5d6.png)

**Comment by azazellochg** [comment]
@pconesa Looks cool! May I ask unrelated question: what does Save button do? Does it save modifications of SetOfCoordinates (e.g. displaying results of auto-picking and adding/removing some particles) for a certain micrograph?

**Comment by delarosatrevin** [comment]
@azazellochg , The save button save the state of the current micrograph after adding/removing particles. This is just for calm down users, since it is saved automatically when you change from one micrograph to another.

**Comment by pconesa** [comment]
Implemented.
