### ISSUE TITLE
importing files from thalos

### ISSUE THREAD

**Issue by rmarabini** [I2PC/scipion#367]
I was investigating the Thalos output. In Seems that five files are created for each acquisition:

   1) micrograph thumbnail (jpg format)
   2) mrc file with movies and  xml file with acquisition information
   3) mrc file with average microraphs and  xml file with acquisition information

It would be nice to modify the import protocol so the xml files would be  used to fill metadata. In particular it would be interesting to store the electron dose and nominal defocus.

Data is available at josue@finlay:

**Comment by delarosatrevin** [comment]
Rather than modifying the import protocol (we can end-up with a Christmas tree if we add parameters and metadata from each microscope), I would propose to create an script particular for the Thalos that feed the information into the import protocol. Anyway we should discuss further about this.

**Comment by rmarabini** [comment]
Hi Jose Miguel,

  As you say it does not make sense to include a protocol for any
conceivable microscope in the standard Scipion distribution. Nevertheless,
I think we will need to add a couple of variables to the model so movies
may be  stored with their electron dose and  nominal defocus.

Regarding how to import the Thalos data I think the best way is to
allow the import protocol to call a script (tailored to the microscope)
that parse the data. I do not know if this is what you suggested.
As you said we may further discuss this when you are back.

   Roberto
