### ISSUE TITLE
ML2D alignment information is missing

### ISSUE THREAD

**Issue by rmarabini** [I2PC/scipion#375]
- classify with ml2d
- click analyze results
- in show select a class and save the corresponding images creating a new scipion object
- display result. Apply geometry is disabled :-(
- edit sqlite file and set alignment=2D
- apply alignment
- compute avg. The resulting average is wrong :-(

**Comment by delarosatrevin** [comment]
I think readSetOfClasses is out of date, but there is a bug anyway. Maybe we should move forward and use the classifyItems approach in this protocol.

**Comment by josuegbl** [comment]
it seems is fixed... I executed the test of ML2D and the results seems OK. I close the issue.

**Comment by delarosatrevin** [comment]
So @josuegbl and @cossorzano,  Do we let the readSetOfClasses and change to classifyItems (including CL2D) for v1.1.0 ??

**Comment by cossorzano** [comment]
If classifyItems is the new way, we would have to go for it. However, I 
would need some help to make the changes

**Comment by delarosatrevin** [comment]
@cossorzano , @josuegbl (or myself after coming back) can help you with that. We need to decide if we consider it important for 1.0.1, or can wait until 1.1.0

**Comment by cossorzano** [comment]
In principle, I would say it can wait for 1.1.0

**Comment by josuegbl** [comment]
I'm agree with @cossorzano . 1.1.0 is a good option.

**Comment by delarosatrevin** [comment]
Okay! I will open a new issue for v1.1.0, just to remember about this.
