### ISSUE TITLE
Delete from multiple selection

### ISSUE THREAD

**Issue by cossorzano** [I2PC/scipion#382]
1) Run Multiple FSCs with several volumes selected
2) Copy the protocol
3) Delete some of the volumes from the selection and run the copy
Poblem: The copied protocol runs on the same volumes as the original protocol

**Comment by delarosatrevin** [comment]
The GUI seems to be working properly when removing the input objects. The problem seems to be when storing the protocol with the new input list, the old one is still in the db.

**Comment by delarosatrevin** [comment]
Fixed in 78e0dfa81eba7. Related to issue #465
