### ISSUE TITLE
input stack looks weird when running frealign job

### ISSUE THREAD

**Issue by andreanans** [I2PC/scipion#419]
Hello,

It seems like the input mrc stack that is created for the frealign job has strange densities. I have to quick run alterheader (from IMOD) and use the mmm command so that the densities appear normal and so the frealign results appear reasonable. Could someone please check this?

Thanks
Andrea

**Comment by delarosatrevin** [comment]
Dear Andrea,

Thanks for the feedback. Could you be more precise about what means by 'weird' and 'normal'. Have you check the densities values (min, max, avg) with some program or just by visual inspection? Can you provide more information about the image format before being converted to mrc for frealign?

Bests

**Comment by andreanans** [comment]
Hello,

Sorry for the delay. The input stack of particles were extracted in scipion using Xmipp extract particles function. When I run frealign, a new input stack called particles.mrc appears in Runs/007055_ProtFrealign/tmp. If i open this stack in imod, it looks quite pixelated with mostly dark pixels. The particle is not visible at all. When I run header, the values for min max and mean density are all zero. If I run alterheader on this stack followed by the mmm option (fix min max mean), the header now lists density values and the particles appear to have a normal density distribution. I have to do this to the stack for frealign to properly do the projection matching. Otherwise, the final volume looks like a bunch of noise. I hope this helps.

**Comment by andreanans** [comment]
Hello,

I just ran the TestMixedBPV and I noticed the same thing happens to the initial particle stack that is created. This is found in the tmp directory right before the first iteration begins and is named particles.mrc. Again, there is no intensity information in the header and when viewed in IMOD the volume appears very pixelated. The projection matching still proceeds, however I found that the particles were better centered if I quick ran alterheader mmm on the input stack as soon as the particles.mrc was created. I checked the frealign tutorial datasets and the input stacks do not have that type of appearance and the header contains intensity information. The tmp folder is cleared after the first iteration is complete.

![zap000](https://cloud.githubusercontent.com/assets/17334897/15318087/52d20632-1c1c-11e6-90af-6371cae69619.jpg)
![zap001](https://cloud.githubusercontent.com/assets/17334897/15318093/560c3142-1c1c-11e6-9217-b947f08342e2.jpg)

 I'm attaching images of the stack before and after fixing the header. I hope this

**Comment by josuegbl** [comment]
Hello @andreanans:
I ran  the TestMixedBPV, as you did, to understand the problem. To generate the stack we use Xmipp, but it doesn't write any information in the header. As IMOD expect the information of the statistics  (mix, max, mean, etc) of the stack (IMOD interpret as a volume) and it is not stored, it is not able to show the particles correctly. Anyway, I ran the command  alterheader mmm to write the header. After that I checked the statistics of the images and both stacks are the same, as expected. Besides, I ran five iterations of frealign with each stack. The shifts, angles and score are slightly different. I ran another frealign with the particles without the info in the header. Doing the same comparison with the particles without any info header, the result was the same: there are minor differences in the shifts, angles and score. In 3 cases the resolution was the same. In conclusion, I believe that the statistical information inserted in the header only matters to show the stack in IMOD, but not for processing with frealign, at least for this set. I could do more tests with a more realistic set of particles, but it takes time. In the future we could put the information in the header when the set are converting. Thanks very much for your feedback. If you have any question or find something wrong, please don’t hesitate to tell us.
Josue.

**Comment by andreanans** [comment]
Great, I really appreciate you looking into this. I'm happy to provide my stack of particles that I was having trouble with in the future.

Cheers
Andrea

**Comment by delarosatrevin** [comment]
Thanks @andreanans, we will close this issue then. We can reopen it if we find any problem. 
We will be happy to test with the stack of particles that you were having trouble, so let us know a way were we can get the files. Could you also provide the workflow (text .json file) in order to reproduce exactly your steps? You can select some boxes in the workflow and go to Project -> Export Workflow and save the .json fie.
