### ISSUE TITLE
xmipp pythoninterface test

### ISSUE THREAD

**Issue by rmarabini** [I2PC/scipion#420]
batch_test_pythoninterface.py does not produce a test (or I do not know where to look for it)

**Comment by delarosatrevin** [comment]
Solved in eab93af9f3baa1f32f56d092e915c12ed15fa314.
Now it can be executed by:
scipion test tests.em.programs.test_pythoninferface_xmipp

**Comment by delarosatrevin** [comment]
Also included in v1.0 in commit 433a163454e06caeb090605088fb04af95dd67ad
