### ISSUE TITLE
web & desktop: movie aligment (with gpu) fails in production

### ISSUE THREAD

**Issue by pconesa** [I2PC/scipion#430]
Log says:

02353: xmipp_movie_optical_alignment_gpu -i movie_000001.mrcs:mrcs -o Falcon_2014_07_16-16_32_43_0_aligned.mrc --winSize 150 --groupSize 1 --nst 0 --ned 0 
02354: xmipp_movie_optical_alignment_gpu: Symbol `_ZN3MDL11emptyHeaderE' has different size in shared object, consider re-linking 
02355: *** Error in `xmipp_movie_optical_alignment_gpu': free(): invalid pointer: 0x00007ffc32026678 ***

**Comment by pconesa** [comment]
I've  run scipion install, and still fails.

**Comment by pconesa** [comment]
It also fails on Scipion desktop (nolan: scipion-web/web-master branch).
I unassign myself from this task

**Comment by pconesa** [comment]
umm! It seems it's the type of protocol: I was using the mixed one (moitioncorr+optical flow). Only motion corr seems to work.

**Comment by pconesa** [comment]
only optical flow also worked.

**Comment by delarosatrevin** [comment]
Check this issues with @josuegbl.

**Comment by pconesa** [comment]
Migrated to web repo.
