### ISSUE TITLE
Add more "colorModes" and a menu to select them

### ISSUE THREAD

**Issue by pconesa** [I2PC/scipion#433]
Add:
menu to switch from one mode to the others.
- age mode (almost done but range must go from oldest to newest, apply a logarithmic scale and scale from 0 to 255.).
- Size mode?
- Duration mode?

A scale might be useful since final colors will be relative to the items in the project.

**Comment by azazellochg** [comment]
When I click Toggle color mode, there are normal one, age and labels, right? I can distinguish the last two. Could this be shown somewhere on the project window (top right?)

**Comment by pconesa** [comment]
You mean like, indicating which mode is active, right?...age mode is still behaving weird.

**Comment by azazellochg** [comment]
@pconesa ye, this is what I meant. I did find on release notes that older protocols are more blue-ish, but an indication would be great.

**Comment by azazellochg** [comment]
Same as #1874
