### ISSUE TITLE
frealign continue

### ISSUE THREAD

**Issue by rmarabini** [I2PC/scipion#438]
when running continue frealign you get the following error about the sampling rate 

RUNNING PROTOCOL -----------------
00002:         Scipion: v1.0.1
00003:      currentDir: /mnt/big2/roberto/ScipionUserData/projects/3d_analysis
00004:      workingDir: Runs/002007_ProtFrealign
00005:         runMode: Continue
00006:             MPI: 4
00007:         threads: 4
00008:   Traceback (most recent call last):
00009:     File "/mnt/big2/scipion/pyworkflow/protocol/protocol.py", line 167, in run
00010:       self._run()
00011:     File "/mnt/big2/scipion/pyworkflow/protocol/protocol.py", line 930, in _run
00012:       self._insertAllSteps() # Define steps for execute later
00013:     File "/mnt/big2/scipion/pyworkflow/em/packages/grigoriefflab/protocol_frealign_base.py", line 483, in _insertAllSteps
00014:       self._insertItersSteps()
00015:     File "/mnt/big2/scipion/pyworkflow/em/packages/grigoriefflab/protocol_frealign_base.py", line 511, in _insertItersSteps
00016:       paramsDic = self._getParamsIteration(iterN)
00017:     File "/mnt/big2/scipion/pyworkflow/em/packages/grigoriefflab/protocol_frealign_base.py", line 794, in _getParamsIteration
00018:       'sampling3DR': imgSet.getSamplingRate()
00019:   AttributeError: 'NoneType' object has no attribute 'getSamplingRate'
00020:   Cleaning temporarly files....
00021:   ------------------- PROTOCOL FAILED (DONE 0/0)

**Comment by josuegbl** [comment]
There were two bugs related with frealign continue:
- _getInputParticlesPointer method fails in continue mode. Frealign not has input particles if continue is active.
- In the definition of Relations, the way to get the input particles pointer was fixed.
