### ISSUE TITLE
Share GPU for Scipion-box

### ISSUE THREAD

**Issue by delarosatrevin** [I2PC/scipion#441]
I have found this issue in Appion repository that could be interesting for us:

http://emg.nysbc.org/redmine/issues/4149

**Comment by azazellochg** [comment]
Assuming that mc2 and relion_refine now have memory limiting option, do we still need to consider this?

**Comment by pconesa** [comment]
I'm closing this issue. Feel free to reopen it if I'm wrong or missed something.
