### ISSUE TITLE
Consider some updates in the Protocols Menu

### ISSUE THREAD

**Issue by delarosatrevin** [I2PC/scipion#446]
In the left panel with the protocols menu, some changes we might consider:
- Include new protocols coming from the Scipion-Box branch (several more alignments), maybe create a section for Movie Alignment...and add Monitor under Tools (group 'calculators' under a sub-menu)
- Maybe create a sub-menu only for tools of Scipion-Box
- Maybe have a view of All Protocols? (Maybe automatically generated? Sort alphabetically?
- Change order of Classify and Refine under 3D section

**Comment by pconesa** [comment]
I've added all missing protocols to a "new" section.  We should go through it and decide on placement withing SPA tree  view or whatever.
