### ISSUE TITLE
Showj: Crash when saving into a directory without write permissions

### ISSUE THREAD

**Issue by delarosatrevin** [I2PC/scipion#452]
It should show an error in this case, but not crash.

**Comment by pconesa** [comment]
SupervisedPicker is done, but while testing the same scenario in the TiltPair picker:

When saving tilted picked particles we are using: xmiip MetaData binding this way:

mdT.write(getParticlesBlock(file))


"file" is write protected, so it is not saved, but the MetaData.write() method doesn't thow any exception or complains about this. Is there a way to check the last Error or something similar? @delarosatrevin

**Comment by delarosatrevin** [comment]
@pconesa , Could you put the validation in Java just before calling the binding function? Sometimes exceptions generated in the binding code are difficult to track. In that way we will have more control close to Java.

**Comment by pconesa** [comment]
@delarosatrevin , I've done it that way, thanks. 

Jose, there are 3 "Pickers" java classes: Supervised, TiltPair and Extract. This last one is use from a gallery under some conditions, when clicking on File>"Open colored particles". I have it disabled and it seems only will be enable when the metadata contains all these labels?:

MDLabel.MDL_MICROGRAPH, MDLabel.MDL_XCOOR, MDLabel.MDL_YCOOR, MDLabel.MDL_ENABLED

All these constants have numeric values: 182, 324,  328, 147.

Haven't test this picker. @josuegbl doesn't know anything about it, and I'm wondering if this is a legacy stuff not used anymore?

**Comment by delarosatrevin** [comment]
You are right, it is kind of legacy from Xmipp. So, I would say not to worry much about it right now. If the other two are working properly we can move on. Anyway, do not delete the code related to this 'Extract' picker, just in case we can re-use the idea later.
