### ISSUE TITLE
Uploading a dataset, ocassionally uploads files to the root folder.

### ISSUE THREAD

**Issue by pconesa** [I2PC/scipion#454]
We have found data sets files belonging to 3 different datasets (pvalidation, SymVirus, and basic_image_processing) in the server (server:../data/tests/).

I can't tell you how to reproduce this behaviour, since it happens rarely. but has happened at least 3 times.

**Comment by azazellochg** [comment]
uploading is not available for mortal users, no?

**Comment by pconesa** [comment]
No, is not open to everyone, but datasets can be hosted anywhere where and wget can reach.
