### ISSUE TITLE
Scipion install problem: Source `software/em/xmipp/external/imagej.tgz' not found

### ISSUE THREAD

**Issue by mcianfrocco** [I2PC/scipion#458]
Hello,

I'm trying to install scipion on a single workstation (CentOS 7), and I get the following error during installation: 

<pre>Install file: "software/em/xmipp/lib/libXmippJNI.so" as "software/lib/libXmippJNI.so"
scons: *** [software/em/xmipp/external/imagej/ij.jar] Source `software/em/xmipp/external/imagej.tgz' not found, needed by target `software/em/xmipp/external/imagej/ij.jar'.
scons: building terminated because of errors.</pre>

I'm uncertain as to what this error is related to - it seems that it can't find imagej.tgz within the xmipp installation folder. 

I can see that this file exists (`software/em/xmipp/external/imagej/ij.jar`), but this file does not exist (`software/em/xmipp/external/imagej.tgz`). 

Am I missing an ImageJ dependency? Or?

Thank you for your help!
Mike

**Comment by delarosatrevin** [comment]
Dear Michael,
Have you installed the binary version?
If this is the case, Xmipp and Relion are already installed by default.
Make sure to use the --no-xmipp option when you install another EM package.
For example:
./scipion install spider --no-xmipp

Check more detail in the How to Install wiki page.

Hope this helps
Jose Migue

On Wednesday, June 1, 2016, Michael A. Cianfrocco <notifications@github.com>
wrote:
> Hello,
>
> I'm trying to install scipion on a single workstation (CentOS 7), and I
get the following error during installation:
>
> Install file: "software/em/xmipp/lib/libXmippJNI.so" as
"software/lib/libXmippJNI.so"
> scons: *** [software/em/xmipp/external/imagej/ij.jar] Source
`software/em/xmipp/external/imagej.tgz' not found, needed by target
`software/em/xmipp/external/imagej/ij.jar'.
> scons: building terminated because of errors.
>
> I'm uncertain as to what this error is related to - it seems that it
can't find imagej.tgz within the xmipp installation folder.
>
> I can see that this file exists
(software/em/xmipp/external/imagej/ij.jar), but this file does not exist
(software/em/xmipp/external/imagej.tgz).
>
> Am I missing an ImageJ dependency? Or?
>
> Thank you for your help!
> Mike
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub, or mute the thread.<
https://ci4.googleusercontent.com/proxy/NVlmu_T_jFviOOf9mlXxImzvX0aBiSGxwSZWfwluCANr_4ZKiacvAJnKAPzthaKILHVnSpmMxl69voY1kbL3uyOm2KKQb7BqT7w7Yhk7SKQ2ouXK3l7ylLkvllRZADqCZi1hK_Btq2Aub7j5ZFrMGMO_uTYwgg=s0-d-e1-ft#https://github.com/notifications/beacon/AIDPWBefvRw-uvO-BkTfilGDyiSc-EOhks5qHcE3gaJpZM4Irycl.gif
>

**Comment by mcianfrocco** [comment]
Ah - yes! You're right, they were the binaries, and I didn't realize that xmipp and relion came pre-installed in the binary download. Thanks!
