### ISSUE TITLE
Importing coordinates into tilt pair picking

### ISSUE THREAD

**Issue by mcianfrocco** [I2PC/scipion#459]
Hello,

I've been going through the RCT tutorial and I have a question related to particle importing. I see how to import a single set of coordinates (File -> Import Coordinates from files), but I'd like to import all of the coordinates at once. 

I see input option File -> Import Coordinates, but I'm not sure how to specify the inputs. 

It asks for: 

<pre>Source:
Prefix:
Suffix:</pre>

Could you explain what these would be for the input test data provided? I tried: 

<pre>Source: scipion/data/tests/rct/positions
Prefix: F_rct_u_
Suffix: .pos</pre>

But it says "Unable to detect format". 

Is this possible to do?

**Comment by mcianfrocco** [comment]
I now see that you just need to leave the prefix and suffix fields empty and it will import! 

Sorry for all of the questions today :)

**Comment by delarosatrevin** [comment]
You are welcome. Anyway we need to figure out a way to make more intuitive
the Import all, with the Prefix and Suffix. It is not very clear, you are
not the first one to get confused with that.
