### ISSUE TITLE
xmipp_image_operate issues with input stacks

### ISSUE THREAD

**Issue by rmarabini** [I2PC/scipion#466]
xmipp_operate test fails. Investigating I have found that  when the input are two stacks (test 6)

```
  ( ~/Scipion/scipion_devel/scipion  xmipp_image_operate "-i" "input/projectionsBacteriorhodopsin.stk" "--minus" "input/projectionsBacteriorhodopsin.stk" "-o" "tmpLink/xmipp_image_operate_06/diff.stk")
```

 we get the following error

XMIPP_ERROR 48:  Incorrect MultidimArray size.
Array_by_array: different shapes (-)
File: software/em/xmipp/libraries/data/multidim_array.h line: 3858

further investigation reveled that the program is trying to operate using the first image from the first stack and the whole stack from the second stack

even further investigation revealed that the variable isvalue is set to true. If I force isvalue to be False then the program fails because the iterator md2Iterator is always returning zero.

**Comment by juannavascalvente** [comment]
This failure has been detected when executing the same tests in DEVEL and v1.0 branches. It fails in DEVEL but not in v1.0. The failed tests are:

tests.em.programs.test_programs_xmipp.ImageOperateMpi
tests.em.programs.test_programs_xmipp.ImageOperate

**Comment by rmarabini** [comment]
Hola,

   La diferencia entre image_operate.cpp en ambas versiones es:

nuevo

   if (md2.isMetadataFile)

viejo

    if (md2.size() > 1)

git blame dice:

a26d124d (josuegbl                      2016-04-19 08:27:44 +0200 481)
        if (md2.isMetadataFile)

así que le podemos colgar el muerto a Josue ya que no ejecutó los tests de
xmipp despues de realizar el cambio

              Roberto

P.S: el test es

*   scipion test tests.em.programs.test_programs_xmipp.ImageOperate*



On Thu, Jun 9, 2016 at 11:26 AM, juannavascalvente <notifications@github.com

**Comment by josuegbl** [comment]
Git never lies.... but, this line was wrote by another person (presumably @cossorzano).... Nevertheless, I assume my fault and will try to fix it :) (with help, of course)

**Comment by delarosatrevin** [comment]
I agree with @josuegbl in this case, I think I remember it. I think @cossorzano and @joton were around.

**Comment by joton** [comment]
Güel, sins llu bigan spiquin spanis an den muvd tu inglis ail llus bouz of dem.

Dis chein in  "image_operate.cpp" doun bai @cossorzano guos tu solf som baj ai can not rimemba. Dearfor, de guil in not pasin de tes is jin. "Que le corten la cabeza!!!!"

**Comment by cossorzano** [comment]
It seems to have magically been solved. 

scipion  xmipp_image_operate "-i" "data/tests/xmipp_programs/input/projectionsBacteriorhodopsin.stk" "--minus" "data/tests/xmipp_programs/input/projectionsBacteriorhodopsin.stk" "-o" diff.stk

gives the correct answer.
