### ISSUE TITLE
reading star files

### ISSUE THREAD

**Issue by rmarabini** [I2PC/scipion#472]
when reading a star file (from relion). The command

   scipion show file.star

fails if the first line is "data_XXXX"

If we edit the file and we add a blank line (or a comment) at the beginning of the file then 

  scipion show file.star

works

**Comment by delarosatrevin** [comment]
This issue have been fixed here: https://github.com/delarosatrevin/scipion/pull/44
Still this need to be merged and also ported to xmippCore.

**Comment by pconesa** [comment]
You have removed all BSOFT labels.....were they all useless?

**Comment by delarosatrevin** [comment]
Yes, I think they are useless now, nonetheless not strictly necessary to remove. Below some points in favor of removing them:
1) Try to avoid the increasing number of labels (it increase the number of memory used by each Row...and I'm not sure if in some cases we are loading many rows)
2) Bsoft is not that much used anyway and there are not many protocols
3) Most of bsoft labels were string, so we can read them now with the flexible approach.

Still, removing the Bsoft labels is unrelated to this fix, that was related to expecting '\n' always before the 'data_'  block in star files.
