### ISSUE TITLE
ShowJ: Sorting by a column takes a long time. (Evaluate, .sqlite, .xmd)

### ISSUE THREAD

**Issue by pconesa** [I2PC/scipion#479]

**Comment by pconesa** [comment]
@delarosatrevin, I'm trying with a 100.000 particles set and sorting is not bad (around a second)....How much is "long time"? Do I need more particles?

**Comment by delarosatrevin** [comment]
@pconesa , Have you tried both sqlite and xmd files? Could you also think a kind of (non-intrusive) feedback after the sort option?
