### ISSUE TITLE
Any way to change the Relion MPI setup?

### ISSUE THREAD

**Issue by andreanans** [I2PC/scipion#486]
Hi, 

We would like to add the --bind-to-none option after mpirun when running relion. Is there a way to adjust the Relion MPI setup so this command is always used?

Also, I noticed that the entry for MPI's is equal to the number of nodes used for running relion on a cluster. Outside of scipion, we typically run relion with as many MPIs as there are CPUs per node. The newest version of relion (1.4) let's you specify the minimum number of dedicated cores per node, which is different to the threads entry. The threads option (--j) is only used when we have memory intensive datasets. It may be helpful to be to specify the total number of MPIs and the minimum dedicated CPUs in the relion launch panel of scipion, along with a separate entry for nodes requested. This is how we run relion in standalone on our cluster.

```
#!/bin/tcsh
#PBS -r n
#PBS -V
#PBS -q mpi
#PBS -l nodes=XXXnodesXXX:ppn=XXXdedicatedXXX 
#PBS -e XXXerrfileXXX
#PBS -o XXXoutfileXXX
#PBS -A Relion 
#PBS -S /bin/tcsh

# Environment
source ~/.cshrc

cd $PBS_O_WORKDIR

mpiexec --map-by node -bind-to none -n XXXmpinodesXXX  XXXcommandXXX --dont_combine_weights_via_disc
```

Thanks
Andrea

**Comment by delarosatrevin** [comment]
Hi Andrea, 

Sorry for the late response. I slightly modified your comment to escape the script part as markdown syntax like it.

About your question, have you looked in the following wiki page?
https://github.com/I2PC/scipion/wiki/Host-Configuration

There you can find the details about how to customize the MPI command and other setup for some queue systems (e.g., PBS in your case) through a script template the will be filled with MPI and threads specified in the GUI. 

Let me know if you need any help customizing it for your system or do you have any other suggestion.

Bests,
Jose Miguel.

**Comment by andreanans** [comment]
Hi there,

Yes, we have set up a host file that works for our cluster. The problem is the interface with relion. In standalone, relion 'threads' is usually set to 1 with MPIs set to 128 or 256. However, if I set relion MPIs in scipion to 256, it assumes I mean 256 nodes and the job doesn't run. I'm just wondering if there's a way for to make number of MPIs not equal to number of nodes requested? Currently we launch from scipion, kill the job and copy the mpirun command into our own cluster script with the correct number of nodes and MPIs.  

Best,

Andrea

**Comment by delarosatrevin** [comment]
Hi, 

Can you post your current configuration of host.conf for your cluster?
You can modify the PARALLEL_COMMAND with something like this?

PARALLEL_COMMAND = mpiexec --map-by node -bind-to none -n %_(JOB_NODES)d

But in your queue configuration (SUBMIT_TEMPLATE variable) you are not forced 
to use that MPI as the number of nodes. You could even a queue related variable
such as QUEUE_NODES that you can use in the template.

Indeed, take a look into the specific example for Torque-PBS, which  use a different value for MPI jobs and the number of requested nodes.
https://github.com/I2PC/scipion/wiki/Host-Configuration#example-for-torque-pbs

Please don't hesitate to ask, we would be happy helping to allow to launch Relion (or other) jobs with the optimal configuration from Scipion without the need to stop it and go to the command line.

Bests,
Jose Miguel.

**Comment by andreanans** [comment]
Hi Jose Miguel,

Thanks so much for that example. It is quite helpful. Here is our hosts file. If you could advise on what I need to add in order to separate MPI and nodes requested, that would be most helpful! 
Thanks,
Andrea

[localhost]
PARALLEL_COMMAND = mpirun -np %_(JOB_NODES)d -bynode %_(COMMAND)s
NAME = PBS/TORQUE
MANDATORY = False
SUBMIT_COMMAND = qsub %_(JOB_SCRIPT)s
SUBMIT_TEMPLATE = #!/bin/bash
    ### Inherit all current environment variables
    #PBS -r n
    #PBS -V
    ### Job name
    #PBS -N %_(JOB_NAME)s
    ### Queue name
    #PBS -q mpi
    ### Standard output and standard error messages
    #PBS -k eo
    ### Specify the number of nodes and thread (ppn) for your job.
    #PBS -l nodes=%_(JOB_NODES)d:ppn=%_(JOB_THREADS)d
    ### Tell PBS the anticipated run-time for your job, where walltime=HH:MM:SS
    ###PBS -l walltime=%_(JOB_HOURS)d:00:00
    # Use as working dir the path where qsub was launched
    WORKDIR=$PBS_O_WORKDIR
    #################################
    ### Set environment varible to know running mode is non interactive
    export XMIPP_IN_QUEUE=1
    ### Switch to the working directory;
    cd $WORKDIR
    # Make a copy of PBS_NODEFILE
    cp $PBS_NODEFILE %_(JOB_NODEFILE)s
    # Calculate the number of processors allocated to this run.
    NPROCS=`wc -l < $PBS_NODEFILE`
    # Calculate the number of nodes allocated.
    NNODES=`uniq $PBS_NODEFILE | wc -l`
    ### Display the job context
    echo Running on host `hostname`
    echo Time is `date`
    echo Working directory is `pwd`
    echo Using ${NPROCS} processors across ${NNODES} nodes
    echo PBS_NODEFILE:
    cat $PBS_NODEFILE
    #################################
    %_(JOB_COMMAND)s
CANCEL_COMMAND = qdel %_(JOB_ID)s
CHECK_COMMAND = qstat %_(JOB_ID)s
QUEUES = { "mpi": {} }

**Comment by delarosatrevin** [comment]
Hi Andrea,

Based on your previous comments, I think you can replace the PARALLEL_COMMAND with
PARALLEL_COMMAND = mpiexec --map-by node -bind-to none -n %_(JOB_NODES)d

Moreover, you could replace the line in your template:
#PBS -l nodes=%(JOB_NODES)d:ppn=%(JOB_THREADS)d
by
#PBS -l nodes=%_(JOB_REAL_NODES)s:ppn=%_(CPUS_PER_NODE)s

This two variables will be the number of nodes and the cores per node, that does not need to match with MPI and threads in Relion. 

You still need to replace the line:
QUEUES = { "mpi": {} }
by
QUEUES = { "mpi": [ ["JOB_HOURS", "120", "Time (hours)", "Select the expected job time"], ["JOB_REAL_NODES", "1", "Nodes", "How many nodes the job needs"], ["CPUS_PER_NODE", "8", "CPUs", "How many CPUs/node to use"]] }

With these changes, each time user submit a job through the Scipion GUI, a new dialog will appears and he/she can select the values for nodes and cores, that will be put into the job script.

Let me know if it worked out with these modifications.

**Comment by andreanans** [comment]
Thanks very much. I've created an updated script with your recommendations. Unfortunately, the head node of our cluster just froze up so I will have to post an update tomorrow.

Cheers,
Andrea

**Comment by andreanans** [comment]
Dear Jose Miguel,

Your suggestion for editing the hosts.conf script worked perfectly. We now have control over the number of nodes and CPUs for our jobs. I hope other people find this useful. Thanks again for your help. It is much appreciated!!

Cheers,

Andrea

**Comment by delarosatrevin** [comment]
Good to hear that it worked!
