### ISSUE TITLE
spider -capca fails and status is shown as finished

### ISSUE THREAD

**Issue by pconesa** [I2PC/scipion#488]
I'm getting an error, it might be me doing some stupid things. The case is that the status after executing it and failing shows finished.

![image](https://cloud.githubusercontent.com/assets/785633/16301058/8630cd4e-3943-11e6-9bd4-a863a17dca31.png)

**Comment by azazellochg** [comment]
Apparently, if any error is encountered in Spider batch mode, the runTemplate function --> ... --> subprocess.check_call() will still return 0. Should we check Spider log file after runTemplate or runScript?

**Comment by delarosatrevin** [comment]
Is always the log file consistent with the report about failure or success? Another idea could be to simply check output files that should be produced. The problem with this one is that is specific for each run.

**Comment by azazellochg** [comment]
Same error message is produced if Spider script fails:
```
*** FATAL ERROR ENCOUNTERED IN BATCH MODE
```

**Comment by delarosatrevin** [comment]
Ok, then I think you idea or modifying the runScript function is the more general way to go.
We could check if this message is found in the log and raise an Exception that will make 
the process fail.

**Comment by azazellochg** [comment]
fixed in 263c092
