### ISSUE TITLE
spider filter wizard always shows low and high frecuency form params

### ISSUE THREAD

**Issue by ldelcano** [I2PC/scipion#492]
Regardless of having chosen low band or high band filters the wizard always show both on the form.

**Comment by azazellochg** [comment]
Spider uses both frequencies irrespectively of the filter mode: low or high pass (details are [here](http://spider.wadsworth.org/spider_doc/spider/docs/man/fq.html)).  Nevertheless I found few mistakes that I will fix.

**Comment by azazellochg** [comment]
Fixed in 6986b6a
