### ISSUE TITLE
Install new version of Buildbot (0.9.7)

### ISSUE THREAD

**Issue by delarosatrevin** [I2PC/scipion#494]
It seems that some new functionality is in the newer versions.

**Comment by juannavascalvente** [comment]
The new version has been successfully installed. The new functionality supplied by this version is being added.

**Comment by azazellochg** [comment]
Is it supposed to be here: http://scipion.cnb.csic.es/buildbot/ ? or it's not yet open to public?

**Comment by delarosatrevin** [comment]
@azazellochg, It is supposed to be there...can you see it? I open it and seems that now there is a configuration problem. Our idea is to let is open to be accessed from outside.

**Comment by azazellochg** [comment]
@delarosatrevin , yeah, it looks misconfigured. If I go to console view and select any build, I see just empty pages.

**Comment by delarosatrevin** [comment]
@juannavascalvente , can you take a look on it?

**Comment by azazellochg** [comment]
PS. "about" page says Buildbot version: 0.9.0rc1
