### ISSUE TITLE
Use Buildbot Dynamic builders for running tests

### ISSUE THREAD

**Issue by delarosatrevin** [I2PC/scipion#495]
This will automatize the processing of adding new tests without configuration changes.

**Comment by delarosatrevin** [comment]
Depends on #494

**Comment by juannavascalvente** [comment]
The new buildbot release has been installed and now the dynamic builders can been added to the buildbot. Some dynamic builders have been configured and the dynamic builds work.

**Comment by juannavascalvente** [comment]
The dynamic builders must be configured to select the test depending on their label. This issue now depends on #497 that will classify the tests.
