### ISSUE TITLE
Update to pass all test in BuildBot

### ISSUE THREAD

**Issue by delarosatrevin** [I2PC/scipion#497]
We need this to schedule each group of tests in a reasonable way.

**Comment by juannavascalvente** [comment]
An initial scheme of the test has been decided. Next step is to label the tests to classify them and so they can be dynamically executed in buildbot in separated builders.

**Comment by pconesa** [comment]
Things I've found:

need mag_distortion and it does not install

scipion test tests.em.protocols.test_protocols_ctf_monitor.TestCtfStream fails:
AttributeError: 'ProtMonitorCTF' object has no attribute 'dataBase'
@rmarabini any ideas?
