### ISSUE TITLE
Bug when selecting a subset of particles from a class

### ISSUE THREAD

**Issue by delarosatrevin** [I2PC/scipion#498]
Open any SetOfClasses (2D or 3D), open the images assigned to some class. Then select (not disable/enable) some of then and create a new SetOfParticles. The output should contains only the selected ones and now it have all the images assigned to this class.

**Comment by pconesa** [comment]
hmmm! The code, when there is a parent, in this case theSetOfClasses, is ignoring the selection and writing all in the tmp sqlite. One way could be not loosing the selection.
