### ISSUE TITLE
eman2 check not working on zsh default shell

### ISSUE THREAD

**Issue by WolfgangLugmayr** [I2PC/scipion#506]
$ ./scipion install eman2.12

Scipion v1.0.1 (2016-06-30) Augusto

Building eman2.12 ...
  Skipping command: wget -nv -c -O software/em/eman2.12.linux64.tgz.part http://scipion.cnb.csic.es/downloads/scipion/software/em/eman2.12.linux64.tgz
mv -v software/em/eman2.12.linux64.tgz.part software/em/eman2.12.linux64.tgz                                                                                                           
  All targets exist.
  Skipping command: tar -xzf eman2.12.linux64.tgz
  All targets exist.
cd software/em/eman2.12.linux64
./eman2-installer
export LC_CTYPE=en_US.utf8
export LC_ALL=en_US.utf8
Please add the following line to the end of your /home/lugmayr/.zshrc :
source /sw/scipion/git/software/em/eman2.12.linux64/eman2.zshrc
Error: target 'software/em/eman2.12.linux64/eman2.bashrc' not built (after running './eman2-installer')

WORKAROUND 
copy the eman2.zshrc to eman2.bashrc and rerun the installation

**Comment by azazellochg** [comment]
@WolfgangLugmayr thanks for reporting this!
@delarosatrevin the bug is [here](https://github.com/I2PC/scipion/blob/master/install/script.py#L382). We could check environ['SHELL'] in install script and adjust the command accordingly.
