### ISSUE TITLE
xmipp align with cl2d 

### ISSUE THREAD

**Issue by JoyceJWW** [I2PC/scipion#507]
I am having issues with the xmipp3 -align with cl2d feature. I imported particles picked with another program, filtered them, and want to align them. However when I try align with cl2d the job fails and I have this output:

00012:   FINISHED: convertInputStep, step 1
00013:     2016-07-05 13:15:15.740130
00014:   STARTED: runJob, step 2
00015:     2016-07-05 13:15:15.764980
00016:   xmipp_classify_CL2D -i Runs/000432_XmippProtCL2DAlign/extra/images.xmd --odir Runs/000432_XmippProtCL2DAlign/extra --nref 1 --iter 10 --maxShift 10 --nref0 1
00017:   /bin/sh: xmipp_classify_CL2D: command not found
00018:   Traceback (most recent call last):
00019:     File "/home/jjwwong/scipion/pyworkflow/protocol/protocol.py", line 167, in run
00020:       self._run()
00021:     File "/home/jjwwong/scipion/pyworkflow/protocol/protocol.py", line 211, in _run
00022:       resultFiles = self._runFunc()
00023:     File "/home/jjwwong/scipion/pyworkflow/protocol/protocol.py", line 207, in _runFunc
00024:       return self._func(*self._args)
00025:     File "/home/jjwwong/scipion/pyworkflow/protocol/protocol.py", line 960, in runJob
00026:       self._stepsExecutor.runJob(self._log, program, arguments, **kwargs)
00027:     File "/home/jjwwong/scipion/pyworkflow/protocol/executor.py", line 56, in runJob
00028:       env=env, cwd=cwd)
00029:     File "/home/jjwwong/scipion/pyworkflow/utils/process.py", line 51, in runJob
00030:       return runCommand(command, env, cwd)
00031:     File "/home/jjwwong/scipion/pyworkflow/utils/process.py", line 65, in runCommand
00032:       check_call(command, shell=True, stdout=sys.stdout, stderr=sys.stderr, env=env, cwd=cwd)
00033:     File "/home/jjwwong/scipion/software/lib/python2.7/subprocess.py", line 540, in check_call
00034:       raise CalledProcessError(retcode, cmd)
00035:   CalledProcessError: Command 'xmipp_classify_CL2D -i Runs/000432_XmippProtCL2DAlign/extra/images.xmd --odir Runs/000432_XmippProtCL2DAlign/extra --nref 1 --iter 10 --maxShift 10 --nref0 1' returned non-zero exit status 127
00036:   Protocol failed: Command 'xmipp_classify_CL2D -i Runs/000432_XmippProtCL2DAlign/extra/images.xmd --odir Runs/000432_XmippProtCL2DAlign/extra --nref 1 --iter 10 --maxShift 10 --nref0 1' returned non-zero exit status 127
00037:   FAILED: runJob, step 2

what I do not understand is when it says xmipp_classify_CL2D: command not found because I was able to run other xmipp processes within scipion and it seemed to work, e.g. create 2d mask and filter particles, so it seemed like scipion was able to access the xmipp installation that came with the package. For example, the output from the xmipp filter particles job that was used to generate the particles I put into align with cl2d was

00013:   2016-07-05 12:50:44,893 INFO:  FINISHED: convertInputStep, step 1
00014:   2016-07-05 12:50:44,894 INFO:    2016-07-05 12:50:44.873641
00015:   2016-07-05 12:50:44,895 INFO:  STARTED: filterStep, step 2
00016:   2016-07-05 12:50:44,895 INFO:    2016-07-05 12:50:44.894969
00017:   2016-07-05 12:50:44,907 INFO:  xmipp_transform_filter -i Runs/000256_XmippProtFilterParticles/tmp/input_particles.xmd --fourier  band_pass 0.071333 0.214000 0.042800  -o Runs/000256_XmippProtFilterParticles/extra/output_images.stk --save_metadata_stack Runs/000256_XmippProtFilterParticles/extra/output_images.xmd --keep_input_columns
00018:   2016-07-05 12:53:23,309 INFO:  FINISHED: filterStep, step 2
00019:   2016-07-05 12:53:23,309 INFO:    2016-07-05 12:53:23.287314

Did I miss something?

**Comment by delarosatrevin** [comment]
Hi,  I think the problem here is that you should use a value for MPI greater than 1. In this case, the xmipp_classify_CL2D program only exists in the MPI version (xmipp_mpi_classify_CL2D). We could include a validation for that, so when you try to launch the protocol it warns about this nuisance. In the meantime, set the number of MPI 2 or more. 

Thanks for your feedback.

**Comment by azazellochg** [comment]
Fixed in 5ca0681

**Comment by hamidrezah** [comment]
Hi,

I have similar issue. The version of my openmpi is not compatible with the scipion so I decided to set MPI to 0 but then the program cannot find xmipp_classify_CL2D because only the mpi version is available when you install scipion binaries. Could you please tell me how I can fix this?

Thanks

**Comment by pconesa** [comment]
Hi @hamidrezah, as @delarosatrevin there is only and MPI version of CL2D. you must set a value of MPI greater than 1.
