### ISSUE TITLE
scipion ctf assign protocol

### ISSUE THREAD

**Issue by azazellochg** [I2PC/scipion#509]
I probably don't understand how this protocol works. In the version 1.0, I selected a set of mics and ctfs as input, and it produced only a SetOfMics, that does not contain CTF information..

**Comment by delarosatrevin** [comment]
Hi @azazellochg, 
Remember that SetOfMicrographs does not contains CTF information per row, instead they could be related to a CTF estimation. So assigning a SetOfCTF for a SetOfMics, will create a new estimation.
For example, imaging that for SetOfMic1 you have estimated CTF with ctffind4 and gctf.
Then you have SetOfMic1 related to two different CTF estimation. And if you assign is like adding a new relation.

This is not the case of SetOfParticles, where the CTF information is stored per particle. If you want to use a different CTF values, you should go to extract and select another estimation (among the available for the SetOfMics). 

I know it is a bit confusing, maybe we should create a How To entry in the wiki with this information.

**Comment by azazellochg** [comment]
Hi @delarosatrevin 
Okay, I think it's clear now, this protocol is basically adding a new relation between mics and ctf. And it is not visible until I extract particles, where I can select one of the related ctfs, right?

**Comment by delarosatrevin** [comment]
That's it.

**Comment by azazellochg** [comment]
Thanks, I guess I will close it for now.
