### ISSUE TITLE
SetOfCtfs is not created upon selecting a subset from SetOfCtfs

### ISSUE THREAD

**Issue by azazellochg** [I2PC/scipion#510]
I think this issue was raised before but I cant find it anymore. 
The problem is when I analyze results of CTF estimation and select a subset, click on +Micrographs, only a SetOfMics is created that does not show any CTF info anymore (I know that this SetOfMics has relation to input SetOfCtfs). This means I can select mics with good CTF only once after CTF estimation and this is really annoying. 

I usually select micrographs with good CTF, creating a new subset. But I would like to split the data into defocus groups for picking (e.g., pick mics with high defocus first). The problem is that subset of good mics have no more CTF info displayed. 

I've tried the following workaround: use _scipion - create subset_ by intersecting a full CTF set with good SetOfMics, and it produces a new SetOfCtfs, however the latter one can't be used later for a micrograph subset  selection (error - no SetOfMics associated was found). **UPDATE**: _I guess I could assign this new ctfset to good mics and use it further._

So, my overall request would be to create both SetOfCtfs and SetOfMics upon selecting mics with good CTF (in Analyze results for ctffind4, for example)

**Comment by delarosatrevin** [comment]
You are totally right and this request is completely reasonable. We had (back in time) also the option to create also SetOfCTFs button, but after some discussion was removed. I guess that creating both, as you suggest is a good approach. I think we should fix the subset problem, but anyway the subset workaround is annoying for following this methology.

**Comment by josuegbl** [comment]
@azazellochg, you can use ctf -assign to select the micrographs that belongs to your SetOfCTFs. In any case, I'm agree with @delarosatrevin.

**Comment by azazellochg** [comment]
@josuegbl ctf assign does not seem to work for me (see attached image). The workflow was: import mics and ctfs, select good ctf1 (produced outputMics), assign ctf (input is good ctf1 mics + full setof CTFs). Last step fails.

![error1](https://cloud.githubusercontent.com/assets/6952870/16913666/67edfebc-4cec-11e6-9bc3-2908a93f7fe0.png)

**Comment by josuegbl** [comment]
@azazellochg ctf assign has not been tested in scipion-box branch. I fixed the error, at least no fail for me. Just update.

**Comment by josuegbl** [comment]
Thank you very much for you feedback

**Comment by azazellochg** [comment]
@josuegbl thanks! you are right, I should have checked this in 1.0.1 branch.

**Comment by azazellochg** [comment]
So, I came back to 1.0.1 branch and I don't know how to extract particles.
To reproduce:

1. I have imported 2 sets of mics
2. I have imported CTFs for each set of mics
3. I have created a subset from each set of ctfs.
4. i joined output mics from step3.
5. i have imported coordinates for the set from step4
6. i cant extract particles since there is no ctf set for input mics (from step4)

I tried to join ctfs from step2 (a) and assign them (b) for mics from step4, then use new mics after assignment (other set option) in extraction (6). There is still NO associated set of ctfs for these mics. 
Please see the pic below. I removed irrelevant links.
![error](https://cloud.githubusercontent.com/assets/6952870/16981524/334ac2f0-4e6b-11e6-883d-3ac1bcc7cea2.png)

**Comment by azazellochg** [comment]
@delarosatrevin I have started to look into this and would like to ask you whether this [line ](https://github.com/I2PC/scipion/blob/devel/pyworkflow/em/protocol/protocol_batch.py#L104) is ever reached? I cant remember anywhere creating subset of ctf from ctfs

**Comment by delarosatrevin** [comment]
This is related to your original request. In showj GUI in Java we had a button to create a subset of ctfs...and this probably ends in this part of the python code. I think the best option is what you proposed, when creating the subset of micrographs, we can also create the subset of ctfs associated.

**Comment by azazellochg** [comment]
Fixed in 75fb437, however we should recheck this after closing #565
