### ISSUE TITLE
Delete key in seaching box

### ISSUE THREAD

**Issue by Vilax** [I2PC/scipion#511]
When you want to delete the text in the search box using the delete key, the selected protocol is attempted to be deleted

![issue](https://cloud.githubusercontent.com/assets/12271438/16649619/08c2a768-443a-11e6-94eb-5d10eebfcfdf.png)

Regards

Vilas

**Comment by delarosatrevin** [comment]
@pconesa , The fix of this bug introduced another one: when clicking the DELETE action from the toolbar (or from the context menu) if the canvas did not have the focus, the action does nothing. I have fixed that in 879f13674d0d, now the key DEL event is bound to another function, which check the widget with the focus, but does not interfere with the other ways to delete protocol boxes.
