### ISSUE TITLE
make psd computation in movie alignment protocol optional

### ISSUE THREAD

**Issue by azazellochg** [I2PC/scipion#512]
I've just launched movie alignment protocol with motioncorr+optical flow and I see that xmipp psd calculation (which is a part of the protocol) takes ~30 sec per movie (for both unaligned and aligned sum). As far as I understand this step is done only for visualization of results. I would suggest to make it optional to save time for preprocessing. I think plots with frame shifts are more informative and anyway CTF estimation is done in a later step.

```
01099:   xmipp_ctf_estimate_from_micrograph --micrograph uncorrectedmic.mrc --oroot uncorrectedpsd --dont_estimate_ctf --pieceDim 400 --overlap 0.7
01100:   Computing models of each piece ...
01101:   0000/???? sec. Micrograph number: 1
01102:     16/  16 sec. 
01103:      0/   0 sec. . 
01104:   xmipp_ctf_estimate_from_micrograph --micrograph FoilHole_16033574_Data_16034884_16034885_20160616_1320_frames_aligned.mrc --oroot correctedpsd --dont_estimate_ctf --pieceDim 400 --overlap 0.7
01105:   Computing models of each piece ...
01106:   0000/???? sec. Micrograph number: 1
01107:     14/  14 sec. 
01108:      0/   0 sec. 
01109:   erasing.....movieFolder:  Runs/000059_ProtMovieAlignment/tmp/movie_000008
```

**Comment by delarosatrevin** [comment]
Totally agree @azazellochg , This is not even computing the CTF, but just the PSD image to show both before and after alignment. But of course it is something that we can switch off for save processing time.

**Comment by delarosatrevin** [comment]
@azazellochg I have make the PSD computation optional, now there is a boolean parameter to skip this (True by default). Nevertheless, I have modify the OF program to write the initial average micrograph (in commit 1b0f249f55b13), so now computing the PSD option should go much faster. Please give me your feedback when you can test this.

**Comment by azazellochg** [comment]
@delarosatrevin  thanks! I checked it, the only thing is if I disable PSD computation, the first column (plotCart) is rendered in enormous size (50 is default)
![de1](https://cloud.githubusercontent.com/assets/6952870/18387883/6e92d24c-769f-11e6-96dc-539dc133430b.png)

**Comment by delarosatrevin** [comment]
Ok, we could handle this in the viewer.
