### ISSUE TITLE
Specify libQT path for different versions of eman2?

### ISSUE THREAD

**Issue by andreanans** [I2PC/scipion#516]
Hi,

In Scipion, we have to use eman2.11 instead of 2.12 as most of our workstations have libQT version that are only compatible with 2.11. However, my workstation operating system is slightly more recent and my version of libQT can only work with eman 2.12. Outside of scipion, I can run 2.11 only if I specify an older QTDIR path. Is there anyway I can ask scipion to use a specific QTDIR path when running eman2.11? I tried setting QTDIR in scipion.conf and the template.conf but that hasn't worked. 

P.S I should mention the error I get when running scipion e2boxer.py image.mrc

Cannot mix incompatible Qt library (version 0x40805) with this library (version 0x40804

Thank you,

Andrea

**Comment by azazellochg** [comment]
Hi @andreanans , this error is well known.
Just remove the Qt that comes with EMAN2 from extlib/lib, e.g. - rm -rf EMAN2/extlib/lib/libQt*

**Comment by andreanans** [comment]
Yes I now feel silly as I remember reading about this error. Thank you for reminding me.

Andrea

**Comment by azazellochg** [comment]
no problem :+1:
