### ISSUE TITLE
Scipion viewer has a problem with unknown columns in a Relion STAR file

### ISSUE THREAD

**Issue by JuhaHuiskonen** [I2PC/scipion#519]
I tried to open a STAR file in scipion viewer. I get:

WARNING Ignoring unknown column: rlnImageOriginalName
....
XmippError: Do not know how to handles this type. 

If I still double click the file and try opening it, I get error:

Couldn't open file: ...
Error: XMIPP_ERROR 2: Incorrect argument received

It would be great if the viewer just ignored unknown columns.

**Comment by delarosatrevin** [comment]
Can you post the star file (or just the first few lines, which I guess will trigger the same error)
that raised this error?

**Comment by JuhaHuiskonen** [comment]
Attached 

[particles.star.txt](https://github.com/I2PC/scipion/files/360143/particles.star.txt)

**Comment by delarosatrevin** [comment]
I was unable to reproduce the problem.
In what version of Scipion (or branch) are you having this issue?. 
I fixed this problem in the following commit 22a34b9309db.
And it seems to be included in master (current v1.0.1) and in the devel branch (also in devel-localized-reconstruction)

**Comment by JuhaHuiskonen** [comment]
My bad I was using an earlier version, it does work in the current
