### ISSUE TITLE
adding environment for the packages more than once.

### ISSUE THREAD

**Issue by josuegbl** [I2PC/scipion#527]
This problem has seen in a Relion execution after a localized reconstruction. Now we ( @rmarabini  and me ) added few lines (see below), in relion convert, to avoid this.

relPath = join(os.environ['RELION_HOME'], 'bin')
if not relPath in environ['PATH']:

**Comment by azazellochg** [comment]
Commit: https://github.com/I2PC/scipion/commit/09c17c29474b78e0bf09c2e9e06e20e6f29e6a6c
Now: https://github.com/scipion-em/scipion-em-relion/blob/master/relion/__init__.py#L54
I don't think this is relevant anymore. @pconesa ?

**Comment by pconesa** [comment]
Seems to be fixed, rigth?
