### ISSUE TITLE
join sets gui freezing when browsing for set of ctfs

### ISSUE THREAD

**Issue by azazellochg** [I2PC/scipion#529]
In version 1.0.1 when I launch scipion-join sets protocol, select input type CTFs and click browse button it freezes for ~1min before showing available ctfs. I think the reason is that it looks not only for SetOfCTF, but also for CTFModel (as displayed in the window title)

![error2](https://cloud.githubusercontent.com/assets/6952870/17051795/bcc21df4-4ffa-11e6-84c0-abdaab2d7c10.png)

**Comment by delarosatrevin** [comment]
Yep, that could be the reason, we will check that.

**Comment by azazellochg** [comment]
Indeed, e.g. in ctf assign protocol, where it browses only for SetOfCTF it is quick as usual.

**Comment by pconesa** [comment]
I know this is old but I'm trying to fix this. My projects seem to behave quite well and, although still searching for CTFModels, the browsing window loads fast.

Is there any special condition when this happens....lots of CTF protocols?... Having CTFModels as output?

To @delarosatrevin or @azazellochg

**Comment by pconesa** [comment]
We have tried with:
A.) A small project (20 boxes) with 6 protocols outputting over 20K ctfs. 
tried in a project with 181 protocols, but in this case one ctf protocol.

In both cases, loading time seems acceptable, but in case A took 4-5 secs.
