### ISSUE TITLE
sort objects by creation date in browse window

### ISSUE THREAD

**Issue by azazellochg** [I2PC/scipion#530]
In version 1.0.1:
I think it would be nice if the objects in browse window were sorted by creation date (creation column) by default with a possibility to sort by name (object column). Otherwise it becomes difficult to find something if I have >30 different sets

![error3](https://cloud.githubusercontent.com/assets/6952870/17052676/d0a62cc6-4ffe-11e6-9738-459333083260.png)

**Comment by delarosatrevin** [comment]
Yes, we have talk about this feature before...and I agree that will improve the way to find objects where the list is large. We will look at it, but the Tkinter widgets are kind of hand-made, so some simple task takes some effort.
