### ISSUE TITLE
CL2D classes do not have sampling rate

### ISSUE THREAD

**Issue by cossorzano** [I2PC/scipion#533]

**Comment by delarosatrevin** [comment]
I think this issue will be solved when addressing #471, since the classifyItems function should take care of these details.

**Comment by delarosatrevin** [comment]
@josuegbl , Do you already fixed this?

**Comment by josuegbl** [comment]
this issue is in progress

**Comment by delarosatrevin** [comment]
Fixed here: 78ba38c997baa54fbf8fdc70d72081727fc7e7c6, branch #655
