### ISSUE TITLE
2D classification not running (problem with openmpi in scipion)

### ISSUE THREAD

**Issue by sayanbhakta** [I2PC/scipion#535]
While I am running 2D classification with any of the available packages, I am getting following error. Please help. I suspect it to be related to openmpi library issue. But I am not sure how to fix this. Please help.

00001:   RUNNING PROTOCOL -----------------
00002:         Scipion: v1.0.1
00003:      currentDir: /home/sayan/trf_scipion/trf
00004:      workingDir: Runs/000973_ProtRelionClassify2D
00005:         runMode: Continue
00006:             MPI: 3
00007:         threads: 24
00008:   len(steps) 3 len(prevSteps) 0
00009:    Starting at step: 1
00010:    Running steps 
00011:   STARTED: convertInputStep, step 1
00012:     2016-07-23 14:01:26.301908
00013:   Converting set from 'Runs/000570_XmippProtExtractParticles/particles.sqlite' into 'Runs/000973_ProtRelionClassify2D/input_particles.star'
00014:   FINISHED: convertInputStep, step 1
00015:     2016-07-23 14:02:03.971671
00016:   STARTED: runRelionStep, step 2
00017:     2016-07-23 14:02:04.112142
00018:   mpirun -np 3 -bynode  `which relion_refine_mpi` --tau2_fudge 2 --scale  --iter 25 --norm  --memory_per_thread 2 --ctf  --offset_range 5.0 --oversampling 1 --o Runs/000973_ProtRelionClassify2D/extra/relion --i Runs/000973_ProtRelionClassify2D/input_particles.star --particle_diameter 338.0 --K 300 --psi_step 10.0 --ctf_phase_flipped  --flatten_solvent  --zero_mask  --offset_step 2.0 --angpix 1.69  --j 24
00019:   --------------------------------------------------------------------------
00020:   It looks like opal_init failed for some reason; your parallel process is
00021:   likely to abort.  There are many reasons that a parallel process can
00022:   fail during opal_init; some of which are due to configuration or
00023:   environment problems.  This failure appears to be an internal failure;
00024:   here's some additional information (which may only be relevant to an
00025:   Open MPI developer):
00026:   
00027:     opal_shmem_base_select failed
00028:     --> Returned value -1 instead of OPAL_SUCCESS
00029:   --------------------------------------------------------------------------
00030:   Traceback (most recent call last):
00031:     File "/data/scipion/pyworkflow/protocol/protocol.py", line 167, in run
00032:       self._run()
00033:     File "/data/scipion/pyworkflow/protocol/protocol.py", line 211, in _run
00034:       resultFiles = self._runFunc()
00035:     File "/data/scipion/pyworkflow/protocol/protocol.py", line 207, in _runFunc
00036:       return self._func(*self._args)
00037:     File "/data/scipion/pyworkflow/em/packages/relion/protocol_base.py", line 602, in runRelionStep
00038:       self.runJob(self._getProgram(), params)
00039:     File "/data/scipion/pyworkflow/protocol/protocol.py", line 960, in runJob
00040:       self._stepsExecutor.runJob(self._log, program, arguments, **kwargs)
00041:     File "/data/scipion/pyworkflow/protocol/executor.py", line 56, in runJob
00042:       env=env, cwd=cwd)
00043:     File "/data/scipion/pyworkflow/utils/process.py", line 51, in runJob
00044:       return runCommand(command, env, cwd)
00045:     File "/data/scipion/pyworkflow/utils/process.py", line 65, in runCommand
00046:       check_call(command, shell=True, stdout=sys.stdout, stderr=sys.stderr, env=env, cwd=cwd)
00047:     File "/data/scipion/software/lib/python2.7/subprocess.py", line 540, in check_call
00048:       raise CalledProcessError(retcode, cmd)
00049:   CalledProcessError: Command 'mpirun -np 3 -bynode  `which relion_refine_mpi` --tau2_fudge 2 --scale  --iter 25 --norm  --memory_per_thread 2 --ctf  --offset_range 5.0 --oversampling 1 --o Runs/000973_ProtRelionClassify2D/extra/relion --i Runs/000973_ProtRelionClassify2D/input_particles.star --particle_diameter 338.0 --K 300 --psi_step 10.0 --ctf_phase_flipped  --flatten_solvent  --zero_mask  --offset_step 2.0 --angpix 1.69  --j 24' returned non-zero exit status 1
00050:   Protocol failed: Command 'mpirun -np 3 -bynode  `which relion_refine_mpi` --tau2_fudge 2 --scale  --iter 25 --norm  --memory_per_thread 2 --ctf  --offset_range 5.0 --oversampling 1 --o Runs/000973_ProtRelionClassify2D/extra/relion --i Runs/000973_ProtRelionClassify2D/input_particles.star --particle_diameter 338.0 --K 300 --psi_step 10.0 --ctf_phase_flipped  --flatten_solvent  --zero_mask  --offset_step 2.0 --angpix 1.69  --j 24' returned non-zero exit status 1
00051:   FAILED: runRelionStep, step 2
00052:     2016-07-23 14:02:04.243185
00053:   Cleaning temporarly files....
00054:   ------------------- PROTOCOL FAILED (DONE 2/3)

**Comment by delarosatrevin** [comment]
Hi, it seems that there is a problem between the MPI library that was used during compilation and the one that is being used during execution.
Did you properly set the MPI variables here: https://github.com/I2PC/scipion/wiki/Scipion-Configuration ? Are you using a different MPI local installation rather than the system-wide MPI?

I was struggling once to compile Relion (inside and outside of Scipion) and the problem was that I had my own compiled version of OpenMPI that was different than the one in the system. 

We only build from sources Xmipp and Relion (both use MPI). Can you test if you can launch a Xmipp-MPI program? (for example cl2d-align )

**Comment by sayanbhakta** [comment]
Xmipp mpi program was also not running

**Comment by sayanbhakta** [comment]
when I ran Xmipp classification, I got following error...

_00001:   RUNNING PROTOCOL -----------------
00002:         Scipion: v1.0.1
00003:      currentDir: /home/sayan/trf_scipion/trf
00004:      workingDir: Runs/001031_XmippProtCL2D
00005:         runMode: Continue
00006:             MPI: 24
00007:         threads: 1
00008:   len(steps) 13 len(prevSteps) 0
00009:    Starting at step: 1
00010:    Running steps 
00011:   STARTED: convertInputStep, step 1
00012:     2016-07-24 19:48:38.792721
00013:   FINISHED: convertInputStep, step 1
00014:     2016-07-24 19:49:32.667655
00015:   STARTED: runJob, step 2
00016:     2016-07-24 19:49:32.820608
00017:   mpirun -np 24 -bynode  `which xmipp_mpi_classify_CL2D` -i Runs/001031_XmippProtCL2D/extra/images.xmd --odir Runs/001031_XmippProtCL2D/extra --oroot level --nref 600 --iter 10  --distance correlation --classicalMultiref --nref0 4
00018:   --------------------------------------------------------------------------
00019:   It looks like opal_init failed for some reason; your parallel process is
00020:   likely to abort.  There are many reasons that a parallel process can
00021:   fail during opal_init; some of which are due to configuration or
00022:   environment problems.  This failure appears to be an internal failure;
00023:   here's some additional information (which may only be relevant to an
00024:   Open MPI developer):
00025:   
00026:     opal_shmem_base_select failed
00027:     --> Returned value -1 instead of OPAL_SUCCESS
00028:   --------------------------------------------------------------------------
00029:   Traceback (most recent call last):
00030:     File "/data/scipion/pyworkflow/protocol/protocol.py", line 167, in run
00031:       self._run()
00032:     File "/data/scipion/pyworkflow/protocol/protocol.py", line 211, in _run
00033:       resultFiles = self._runFunc()
00034:     File "/data/scipion/pyworkflow/protocol/protocol.py", line 207, in _runFunc
00035:       return self._func(*self._args)
00036:     File "/data/scipion/pyworkflow/protocol/protocol.py", line 960, in runJob
00037:       self._stepsExecutor.runJob(self._log, program, arguments, **kwargs)
00038:     File "/data/scipion/pyworkflow/protocol/executor.py", line 56, in runJob
00039:       env=env, cwd=cwd)
00040:     File "/data/scipion/pyworkflow/utils/process.py", line 51, in runJob
00041:       return runCommand(command, env, cwd)
00042:     File "/data/scipion/pyworkflow/utils/process.py", line 65, in runCommand
00043:       check_call(command, shell=True, stdout=sys.stdout, stderr=sys.stderr, env=env, cwd=cwd)
00044:     File "/data/scipion/software/lib/python2.7/subprocess.py", line 540, in check_call
00045:       raise CalledProcessError(retcode, cmd)
00046:   CalledProcessError: Command 'mpirun -np 24 -bynode  `which xmipp_mpi_classify_CL2D` -i Runs/001031_XmippProtCL2D/extra/images.xmd --odir Runs/001031_XmippProtCL2D/extra --oroot level --nref 600 --iter 10  --distance correlation --classicalMultiref --nref0 4' returned non-zero exit status 1
00047:   Protocol failed: Command 'mpirun -np 24 -bynode  `which xmipp_mpi_classify_CL2D` -i Runs/001031_XmippProtCL2D/extra/images.xmd --odir Runs/001031_XmippProtCL2D/extra --oroot level --nref 600 --iter 10  --distance correlation --classicalMultiref --nref0 4' returned non-zero exit status 1
00048:   FAILED: runJob, step 2
00049:     2016-07-24 19:49:32.999279
00050:   Cleaning temporarly files....
00051:   ------------------- PROTOCOL FAILED (DONE 2/13)_


**I edited the scipion.conf file as follows....**

_[REMOTE]
SCIPION_URL = http://scipion.cnb.csic.es/downloads/scipion
SCIPION_URL_TESTDATA = %(SCIPION_URL)s/data/tests
SCIPION_URL_SOFTWARE = %(SCIPION_URL)s/software

[DIRS_GLOBAL]
SCIPION_SOFTWARE = software
SCIPION_TESTS = data/tests

[BUILD]
LINKERFORPROGRAMS = g++
CXXFLAGS = 
GTEST = False
MPI_LINKERFORPROGRAMS = mpiCC
REMOTE_MESA_LIB = /services/guacamole/usr/mesa/lib/
MPI_LIB = mpi
MPI_BINDIR = /usr/lib/openmpi/bin/
JNI_CPPPATH = %(JAVA_HOME)s/include:%(JAVA_HOME)s/include/linux
OPENCV = True
MPI_CC = mpicc
CUDA = True
JAVA_HOME = /usr/lib/jvm/java-1.7.0-openjdk-1.7.0.101.x86_64
MATLAB = False
JAVA_BINDIR = %(JAVA_HOME)s/bin
CC = gcc
JAR = %(JAVA_BINDIR)s/jar
MPI_CXX = mpiCC
DEBUG = False
MPI_LIBDIR = /usr/lib/openmpi/lib/
JAVAC = %(JAVA_BINDIR)s/javac
CXX = g++
LINKFLAGS = 
CCFLAGS = -std=c99
MATLAB_DIR = /usr/local/MATLAB/R2011a
MPI_INCLUDE = /usr/include/openmpi-i386_


please suggest me way to get rid of the problem.

**Comment by sayanbhakta** [comment]
I ran ./scipion config again after editing the scipion.conf file as stated before. Then I ran ./scipion install -j 24 to identify which openmpi it is using. I got the following result

```
[root@localhost scipion]# ./scipion install -j 24

Scipion v1.0.1 (2016-06-30) Augusto

Building fftw3 ...
  All targets exist, skipping.
Done (0.00 seconds)
Building fftw3f ...
  All targets exist, skipping.
Done (0.00 seconds)
Building tcl ...
  All targets exist, skipping.
Done (0.00 seconds)
Building tk ...
  All targets exist, skipping.
Done (0.00 seconds)
Building zlib ...
  All targets exist, skipping.
Done (0.00 seconds)
Building jpeg ...
  All targets exist, skipping.
Done (0.00 seconds)
Building png ...
  All targets exist, skipping.
Done (0.00 seconds)
Building tiff ...
  All targets exist, skipping.
Done (0.00 seconds)
Building sqlite3 ...
  All targets exist, skipping.
Done (0.00 seconds)
Building hdf5 ...
  All targets exist, skipping.
Done (0.00 seconds)
Building python ...
  All targets exist, skipping.
Done (0.00 seconds)
Building opencv ...
  All targets exist, skipping.
Done (0.00 seconds)
Building setuptools ...
  All targets exist, skipping.
Done (0.00 seconds)
Building scons ...
  All targets exist, skipping.
Done (0.00 seconds)
Building lapack ...
  All targets exist, skipping.
Done (0.00 seconds)
Building numpy ...
  All targets exist, skipping.
Done (0.00 seconds)
Building six ...
  All targets exist, skipping.
Done (0.00 seconds)
Building dateutil ...
  All targets exist, skipping.
Done (0.00 seconds)
Building pyparsing ...
  All targets exist, skipping.
Done (0.00 seconds)
Building matplotlib ...
  All targets exist, skipping.
Done (0.00 seconds)
Building psutil ...
  All targets exist, skipping.
Done (0.00 seconds)
Building mpi4py ...
  All targets exist, skipping.
Done (0.00 seconds)
Building scipy ...
  All targets exist, skipping.
Done (0.00 seconds)
Building bibtexparser ...
  All targets exist, skipping.
Done (0.00 seconds)
Building django ...
  All targets exist, skipping.
Done (0.00 seconds)
Building Pillow ...
  All targets exist, skipping.
Done (0.00 seconds)
Compiling Xmipp ...
install/scons.py -j 24
Keeping existing file: /data/scipion/software/em/xmipp/xmipp.bashrc
Keeping existing file: /data/scipion/software/em/xmipp/xmipp.csh
Keeping existing file: /data/scipion/software/em/xmipp/xmipp.fish
scons: Reading SConscript files ...
Mkdir("/data/scipion/software/em/xmipp/java/build")
scons: done reading SConscript files.
scons: Building targets ...
scons: `software/lib/libXmippAlglib.so' is up to date.
scons: `software/lib/libXmippBilib.so' is up to date.
scons: `software/lib/libXmippCondor.so' is up to date.
scons: `software/lib/libXmippDelaunay.so' is up to date.
scons: `software/lib/libXmippSqliteExt.so' is up to date.
scons: `software/lib/libXmippGtest.so' is up to date.
scons: `software/lib/libXmippData.so' is up to date.
scons: `software/lib/libXmippClassif.so' is up to date.
scons: `software/lib/libXmippDimred.so' is up to date.
scons: `software/lib/libXmippRecons.so' is up to date.
scons: `software/lib/libXmippInterface.so' is up to date.
mpiCC -o software/em/xmipp/lib/libXmippParallel.so -shared software/em/xmipp/libraries/parallel/mpi_angular_projection_matching.os software/em/xmipp/libraries/parallel/mpi_validation_nontilt.os software/em/xmipp/libraries/parallel/mpi_classify_CL2D_core_analysis.os software/em/xmipp/libraries/parallel/mpi_performance_test.os software/em/xmipp/libraries/parallel/mpi_reconstruct_wbp.os software/em/xmipp/libraries/parallel/xmipp_mpi.os software/em/xmipp/libraries/parallel/mpi_angular_class_average.os software/em/xmipp/libraries/parallel/mpi_ml_align2d.os software/em/xmipp/libraries/parallel/mpi_reconstruct_significant.os software/em/xmipp/libraries/parallel/mpi_reconstruct_art.os software/em/xmipp/libraries/parallel/mpi_classify_FTTRI.os software/em/xmipp/libraries/parallel/mpi_image_rotational_pca.os software/em/xmipp/libraries/parallel/mpi_reconstruct_fourier.os software/em/xmipp/libraries/parallel/mpi_project_XR.os software/em/xmipp/libraries/parallel/mpi_reconstruct_admm.os -Lsoftware/em/xmipp/lib -Lsoftware/lib -L/usr/lib/openmpi/lib -lpthread -lfftw3_threads -lXmippData -lXmippClassif -lXmippRecons -lXmippBilib -lmpi
scons: *** [software/em/xmipp/external/imagej/ij.jar] Source `software/em/xmipp/external/imagej.tgz' not found, needed by target `software/em/xmipp/external/imagej/ij.jar'.
/usr/bin/ld: skipping incompatible /usr/lib/openmpi/lib/libmpi.so when searching for -lmpi
/usr/bin/ld: skipping incompatible /usr/lib/openmpi/lib/libmpi.so when searching for -lmpi
/usr/bin/ld: cannot find -lmpi
collect2: ld returned 1 exit status
scons: *** [software/em/xmipp/lib/libXmippParallel.so] Error 1
scons: building terminated because of errors.
```

So I suspect that the openmpi path I gave in the config file is not compatible with the required openmpi by xmipp or relion. can you please suggest me which openmpi should be compatible? Waiting for your suggestion.

**Comment by sayanbhakta** [comment]
I found out I have multiple openmpi in my system. I changed the scipion.conf file with another openmpi as follows.
```
[REMOTE]
SCIPION_URL = http://scipion.cnb.csic.es/downloads/scipion
SCIPION_URL_TESTDATA = %(SCIPION_URL)s/data/tests
SCIPION_URL_SOFTWARE = %(SCIPION_URL)s/software

[DIRS_GLOBAL]
SCIPION_SOFTWARE = software
SCIPION_TESTS = data/tests

[BUILD]
LINKERFORPROGRAMS = g++
CXXFLAGS = 
GTEST = False
MPI_LINKERFORPROGRAMS = mpiCC
REMOTE_MESA_LIB = /services/guacamole/usr/mesa/lib/
MPI_LIB = mpi
MPI_BINDIR = /usr/lib64/openmpi-1.10/bin/
JNI_CPPPATH = %(JAVA_HOME)s/include:%(JAVA_HOME)s/include/linux
OPENCV = True
MPI_CC = mpicc
CUDA = True
JAVA_HOME = /usr/lib/jvm/java-1.7.0-openjdk-1.7.0.101.x86_64
MATLAB = False
JAVA_BINDIR = %(JAVA_HOME)s/bin
CC = gcc
JAR = %(JAVA_BINDIR)s/jar
MPI_CXX = mpiCC
DEBUG = False
MPI_LIBDIR = /usr/lib64/openmpi-1.10/lib/
JAVAC = %(JAVA_BINDIR)s/javac
CXX = g++
LINKFLAGS = 
CCFLAGS = -std=c99
MATLAB_DIR = /usr/local/MATLAB/R2011a
MPI_INCLUDE = /usr/include/openmpi-1.10-x86_64

```
Then I ran ./scipion install -j 24 and got the following result

```
[sayan@localhost scipion]$ ./scipion install -j 24

Scipion v1.0.1 (2016-06-30) Augusto

Building fftw3 ...
  All targets exist, skipping.
Done (0.00 seconds)
Building fftw3f ...
  All targets exist, skipping.
Done (0.00 seconds)
Building tcl ...
  All targets exist, skipping.
Done (0.00 seconds)
Building tk ...
  All targets exist, skipping.
Done (0.00 seconds)
Building zlib ...
  All targets exist, skipping.
Done (0.00 seconds)
Building jpeg ...
  All targets exist, skipping.
Done (0.00 seconds)
Building png ...
  All targets exist, skipping.
Done (0.00 seconds)
Building tiff ...
  All targets exist, skipping.
Done (0.00 seconds)
Building sqlite3 ...
  All targets exist, skipping.
Done (0.00 seconds)
Building hdf5 ...
  All targets exist, skipping.
Done (0.00 seconds)
Building python ...
  All targets exist, skipping.
Done (0.00 seconds)
Building opencv ...
  All targets exist, skipping.
Done (0.00 seconds)
Building setuptools ...
  All targets exist, skipping.
Done (0.00 seconds)
Building scons ...
  All targets exist, skipping.
Done (0.00 seconds)
Building lapack ...
  All targets exist, skipping.
Done (0.00 seconds)
Building numpy ...
  All targets exist, skipping.
Done (0.00 seconds)
Building six ...
  All targets exist, skipping.
Done (0.00 seconds)
Building dateutil ...
  All targets exist, skipping.
Done (0.00 seconds)
Building pyparsing ...
  All targets exist, skipping.
Done (0.00 seconds)
Building matplotlib ...
  All targets exist, skipping.
Done (0.00 seconds)
Building psutil ...
  All targets exist, skipping.
Done (0.00 seconds)
Building mpi4py ...
  All targets exist, skipping.
Done (0.00 seconds)
Building scipy ...
  All targets exist, skipping.
Done (0.00 seconds)
Building bibtexparser ...
  All targets exist, skipping.
Done (0.00 seconds)
Building django ...
  All targets exist, skipping.
Done (0.00 seconds)
Building Pillow ...
  All targets exist, skipping.
Done (0.00 seconds)
Compiling Xmipp ...
install/scons.py -j 24
Keeping existing file: /data/scipion/software/em/xmipp/xmipp.bashrc
Keeping existing file: /data/scipion/software/em/xmipp/xmipp.csh
Keeping existing file: /data/scipion/software/em/xmipp/xmipp.fish
scons: Reading SConscript files ...
Mkdir("/data/scipion/software/em/xmipp/java/build")
scons: done reading SConscript files.
scons: Building targets ...
scons: `software/lib/libXmippAlglib.so' is up to date.
scons: `software/lib/libXmippBilib.so' is up to date.
scons: `software/lib/libXmippCondor.so' is up to date.
scons: `software/lib/libXmippDelaunay.so' is up to date.
scons: `software/lib/libXmippSqliteExt.so' is up to date.
scons: `software/lib/libXmippGtest.so' is up to date.
scons: `software/lib/libXmippData.so' is up to date.
scons: `software/lib/libXmippClassif.so' is up to date.
scons: `software/lib/libXmippDimred.so' is up to date.
scons: `software/lib/libXmippRecons.so' is up to date.
scons: `software/lib/libXmippInterface.so' is up to date.
scons: `software/lib/libXmippParallel.so' is up to date.
scons: `software/lib/xmipp.so' is up to date.
scons: `software/lib/libXmippJNI.so' is up to date.
scons: *** [software/em/xmipp/external/imagej/ij.jar] Source `software/em/xmipp/external/imagej.tgz' not found, needed by target `software/em/xmipp/external/imagej/ij.jar'.
scons: building terminated because of errors.
```
I suppose the previous incompatible openmpi problem is gone. But still when I ran the cl2d with xmipp or 2d classification in relion, I get the same error as opal_init failed for some reason. please help.

**Comment by delarosatrevin** [comment]
Hi, 
From the log I think it is still not compiling properly. There is another error with imagej.tgz not found. Have you download the precompiled binaries or the source code? I would suggest to start from scratch (either download the source tar file or from git) and install scipion with the new configuration of MPI you have set.

**Comment by sayanbhakta** [comment]
After reinstalling freshly, I am finally able to run the 2D classification. But it works only when I am keeping the thread 24 and mpi 1 (relion). But in case of xmipp cl2d, I can't put the mpi as 1. and if I give mpi more than 1, xmipp cl2d is not running. For your kind information, I am working on a 24 core (with hyperthreading) single processor machine. Is it not possible to run the program with mpi in my machine?

**Comment by sayanbhakta** [comment]
Finally I am able to solve the problem. I created a .bashrc file (as my shell is b shell) with the following lines. When I am running the program, I source that .bashrc file.
```
export SCIPION_ROOT=/data/scipion
alias s=$SCIPION_ROOT/scipion
export LD_LIBRARY_PATH=/usr/lib64/openmpi-1.10/lib/:$LD_LIBRARY_PATH
export MPIHOME=/usr/lib64/openmpi-1.10
export MPIBIN=$MPIHOME/bin
```
Thanks for your response.

**Comment by delarosatrevin** [comment]
Great! Thanks for letting us know. I will close this issue, do not hesitate to contact us if you have any other trouble.
