### ISSUE TITLE
eman2 - initial model: results viewer improvements

### ISSUE THREAD

**Issue by azazellochg** [I2PC/scipion#546]
Can be improved by displaying not just volumes, but [also](http://blake.bcm.edu/emanwiki/EMAN2/Programs/e2initialmodel#Results) reprojections+class-averages file, final reprojections file and initial model file. All this files are produced by the protocol and are in _extra/initial_model_ folder.

**Comment by delarosatrevin** [comment]
After updating, you should have the following:

![image](https://cloud.githubusercontent.com/assets/8441688/17486270/824f2de4-5d90-11e6-935b-bb352bf37a61.png)

**Comment by azazellochg** [comment]
@delarosatrevin Great, looks perfect!
