### ISSUE TITLE
problems compiling opencv-2.4.9 with cuda>=6.5

### ISSUE THREAD

**Issue by azazellochg** [I2PC/scipion#553]
We had a major system upgrade on our machines and I had to recompile Scipion from scratch. Among other things, CUDA was updated to 7.5. During Scipion re-install, opencv-2.4.9 failed to compile:
`Error: target 'software/lib/libopencv_core.so' not built`

Log file showed that:

```
[ 9%] Building NVCC (Device) object modules/core/CMakeFiles/cuda_compile.dir/src/cuda/cuda_compile_generated_gpu_mat.cu.o
/usr/include/string.h: In function ‘void* __mempcpy_inline(void, const void, size_t)’:
/usr/include/string.h:652:42: error: ‘memcpy’ was not declared in this scope
return (char *) memcpy (__dest, __src, __n) + __n;
^
CMake Error at cuda_compile_generated_gpu_mat.cu.o.cmake:264 (message):
Error generating file
/home/mag/opencv/build_opencv_master/modules/core/CMakeFiles/cuda_compile.dir/src/cuda/./cuda_compile_generated_gpu_mat.cu.o
```

After some googling I have found the solution. There are two bugs in [opencv](https://github.com/opencv/opencv) that were fixed in [July 2014](https://github.com/opencv/opencv/pull/2975/files) and [May 2016](https://github.com/guysoft/opencv/commit/0a48b9ae776a03e1c4f09e7e3cd0e1c21f3ca75c). 

Also, I had to specify the GPU card microarchitecture before running make command: in my case, _Kepler_ for K40 card:

`cmake -DCUDA_GENERATION=Kepler -DWITH_CUDA:BOOL=ON -DCMAKE_INSTALL_PREFIX:PATH=/path/to/scipion/software . > /path/to/scipion/software/log/opencv_cmake.log 2>&1`

I am thinking whether it is better to update opencv tarball (cons: it will differ from official 2.4.9 release, also I didn't test the fixes with old CUDA) or I could add a troubleshooting page in the wiki.

**Comment by delarosatrevin** [comment]
Yes, OpenCV and CUDA have always been troublesome. Are these fixes in an official released version of OpenCV? We could consider updating the version. Another way could be to required that OpenCV (and devel) should be installed system-wide and do not try to install in Scipion. The only program in Xmipp that uses OpenCV is the Optical Flow.

@azazellochg, Thanks for the feedback, in the meantime I agree that is a good idea to create the Troubleshooting page in the wiki.

**Comment by azazellochg** [comment]
@delarosatrevin,  first bug is fixed in 2.4.13 however the second is fixed only in master branch (not released yet)

**Comment by cossorzano** [comment]
I have upgraded our opencv version to 2.4.13 and compiled with cuda 7.5. I did not get any compilation error. Grigory, could I close the issue?

**Comment by azazellochg** [comment]
@cossorzano sure thing.
