### ISSUE TITLE
import particles: relion star file requires optimiser file

### ISSUE THREAD

**Issue by azazellochg** [I2PC/scipion#564]
When I try to import relion_data.star particles file after finished 3d refinement I get an [exception](https://github.com/I2PC/scipion/blob/master/pyworkflow/em/packages/relion/dataimport.py#L192): 

> Exception: Protocol.run: Validation errors:
> Missing required optimiser star file: /home/sharov/soft/scipion/data/tests/relion_tutorial/import/refine3d/extra/relion_optimiser.star

I understand that this is required when importing star file from a certain iteration, but after completed 3d refinement in relion optimiser file is not produced.

**Comment by delarosatrevin** [comment]
I will check that. Regarding the test for the protocol sort, we have already some data-sets that import relion data. I'm not sure if we can cover all cases with these.

**Comment by azazellochg** [comment]
@delarosatrevin , I have almost finished writing the test for sort protocol, relion_tutorial test data covers most of it, but I have added few files

**Comment by delarosatrevin** [comment]
Ok, great!

**Comment by delarosatrevin** [comment]
Send the test when you have it, so I could test my changes. I will probably need to update a little bit of the tests.
