### ISSUE TITLE
ctf output step is broken in devel

### ISSUE THREAD

**Issue by azazellochg** [I2PC/scipion#565]
It looks like after merging scipion-box into devel (4d261dd) gctf is not producing output anymore:
```
FINISHED: _estimateCTF, step 1
```
After this the process is hanging indefinitely, i.e. createOutput step is not even starting.

**Comment by delarosatrevin** [comment]
Yep, I think I broken the output trying to get Gctf working in streaming. I will fix it.

**Comment by azazellochg** [comment]
ctffind also has problems with output, looks like ctfrelation is not defined for the outputctfs. In devel I can't create a subset of mics from resulting CTFs.

**Comment by delarosatrevin** [comment]
Ok, I will look it.
