### ISSUE TITLE
ProtImportMicrographsTiltPairs does not set micName

### ISSUE THREAD

**Issue by azazellochg** [I2PC/scipion#569]
ProtImportMicrographsTiltPairs does not set micName in the output set

**Comment by delarosatrevin** [comment]
I think this is a bug, since the micName is very important for join (when micId can be messed up).

**Comment by azazellochg** [comment]
indeed, it should be set somewhere around [here](https://github.com/I2PC/scipion/blob/devel/pyworkflow/em/protocol/protocol_tiltpairs.py#L132)

**Comment by azazellochg** [comment]
@delarosatrevin could you explain why pwutils.commonPath() is used to fill micName (for usual mics) and not just os.path.basename()?
Does it mean that if I import files "dir1/dir2/img1.mrc" and "dir1/dir3/img1.mrc", their micNames will be "dir2/img1.mrc" and "dir3/img1.mrc", so the collision if using simple basenames is avoided?

**Comment by delarosatrevin** [comment]
Yes, that is the reason, to avoid collapse if the basename is the same. Remember the micName should be unique, it is a kind of string identifier to be used when numeric ids are scrambled by joins.
