### ISSUE TITLE
Run protocols in debug_mode directly from the form 

### ISSUE THREAD

**Issue by 1aviervargas** [I2PC/scipion#580]

**Comment by azazellochg** [comment]
I don't think this is useful for users, we already have the SCIPION_DEBUG var. Also, the right-click context menu of the protocols is already crowded, we have to be careful when adding options there.

**Comment by pconesa** [comment]
We have come up with an idea. Having a "hidden" shortcut or click combination to set SCIPION_DEBUG var to true. From there all features that obey to SCIPION_DEBUG should become active.
Related to #1878

**Comment by delarosatrevin** [comment]
Adding options, hidden or not, is more to maintain. I don't think this have
such a priority.
