### ISSUE TITLE
Grigorieff movies alignment test protocols does not run...

### ISSUE THREAD

**Issue by josuegbl** [I2PC/scipion#586]
There exist an error with the following exit:
>>>>> python  /home/josue/workspace/scipion/pyworkflow/apps/pw_protocol_run.py "/home/josue/ScipionUserData/projects/TestUnblur" "Runs/000280_ProtUnblur/logs/run.db" "280"
** Running command: 'python /home/josue/workspace/scipion/scipion runprotocol pw_protocol_run.py "/home/josue/ScipionUserData/projects/TestUnblur" "Runs/000354_ProtUnblur/logs/run.db" 354'

Scipion devel-fixes (2016-09-12) db290fd

>>>>> python  /home/josue/workspace/scipion/pyworkflow/apps/pw_protocol_run.py "/home/josue/ScipionUserData/projects/TestUnblur" "Runs/000354_ProtUnblur/logs/run.db" "354"
Error trying to update protocol: (jobId=25650)
 ERROR: foreign key constraint failed, tries=0
Error trying to update protocol: (jobId=None)
 ERROR: foreign key constraint failed, tries=1
Error trying to update protocol: (jobId=None)
 ERROR: foreign key constraint failed, tries=2
Error trying to update protocol: (jobId=None)
 ERROR: foreign key constraint failed, tries=3
Traceback (most recent call last):
  File "/home/josue/workspace/scipion/pyworkflow/project.py", line 425, in _updateProtocol
    protocol.copy(prot2, copyId=False)
  File "/home/josue/workspace/scipion/pyworkflow/protocol/protocol.py", line 905, in copy
    rParentExt, rChildExt)
  File "/home/josue/workspace/scipion/pyworkflow/mapper/sqlite.py", line 366, in insertRelationData
    parentExtended, childExtended)
  File "/home/josue/workspace/scipion/pyworkflow/mapper/sqlite.py", line 472, in insertRelation
    object_parent_extended, object_child_extended))
IntegrityError: foreign key constraint failed

>>> ERROR running protocol unblur2
    FAILED with error: foreign key constraint failed

[   FAILED ] TestUnblur.test_movies

**Comment by azazellochg** [comment]
same error in devel, for both unblur and summovie

**Comment by azazellochg** [comment]
fixed in #601
