### ISSUE TITLE
Wrong convertion of 2D Alignment in Xmipp (when flip)

### ISSUE THREAD

**Issue by delarosatrevin** [I2PC/scipion#587]
When there are classes with a lot of flipped particles, Xmipp 2D classification protocols (e.g., ML2D, CL2D) output are not properly converted to Scipion trasformation matrix.

**Comment by cossorzano** [comment]
It seems to be only in the ML2D side

**Comment by cossorzano** [comment]
Let's leave it as a known bug of ML2D
