### ISSUE TITLE
Xmipp particle picking is not working

### ISSUE THREAD

**Issue by 1aviervargas** [I2PC/scipion#589]

**Comment by azazellochg** [comment]
Another issue is that if I do manual picking (step 1) few times, producing several outputCoordinates, then in step2 I can select only outputCoordinates as input and not outputCoordinates2, outputCoordinates3 etc.

**Comment by pconesa** [comment]
There were some Java 7 syntax and Javi had Java 6, which should be supported. I've changed syntax to be Java 6 compatible.

**Comment by pconesa** [comment]
@azazellochg , I'll create a new issue, good point.. As you said...."another issue is ..." (;-)).
