### ISSUE TITLE
relion viewer does not show rlnChangesOptimalClasses for classify 3d protocol

### ISSUE THREAD

**Issue by azazellochg** [I2PC/scipion#598]
The button "Changes in offsets, angles, classes" opens iterations_changes_xmipp.xmd file, but there is no column "rlnChangesOptimalClasses". In the case of 2D classification the column is present.

![de7](https://cloud.githubusercontent.com/assets/6952870/19112679/854017fe-8b06-11e6-95ba-94050233fc85.png)

**Comment by delarosatrevin** [comment]
Is it for 2D or 3D?

**Comment by azazellochg** [comment]
only for 3d classification.

**Comment by azazellochg** [comment]
[here](https://github.com/I2PC/scipion/blob/devel/pyworkflow/em/packages/relion/protocol_classify3d.py#L49) md.RLN_OPTIMISER_CHANGES_OPTIMAL_CLASSES is missing

**Comment by delarosatrevin** [comment]
Thanks @azazellochg !
