### ISSUE TITLE
volume_homogenizer breaks devel compilation if no opencv

### ISSUE THREAD

**Issue by azazellochg** [I2PC/scipion#600]
@mohsenkazemi 
There are few issues with this new protocol, that was recently merged to devel. Both are in **scipion_sconscript** file:

- [here](https://github.com/I2PC/scipion/blob/devel/software/em/xmipp/scipion_sconscript#L60) opencvLibs should be set by default to  `[]` (if no opencv)
- [libopencv_calib3d](https://github.com/I2PC/scipion/blob/devel/software/em/xmipp/scipion_sconscript#L194) should be moved to opencvLibs list
- [this](https://github.com/I2PC/scipion/blob/devel/software/em/xmipp/scipion_sconscript#L710) has no effect, since scipion anyway tries to compile it due to [that](https://github.com/I2PC/scipion/blob/devel/software/em/xmipp/scipion_sconscript#L191). I guess this program should be moved completely from `software/em/xmipp/libraries/reconstruction` and `software/em/xmipp/libraries/parallel/mpi_volume_homogenizer` folders to `software/em/xmipp/applications/programs/volume_homogenizer`.

**Comment by delarosatrevin** [comment]
@azazellochg , Thanks a lot for catching up this issue!. You are right in every point you mentioned. We should move the program to the proper place and then keep the OpenCV dependency only to this program, not to the whole 'XmippRecons' base library.

**Comment by azazellochg** [comment]
Solved in #603
