### ISSUE TITLE
Scipion (v-1.0) thread parallel processing

### ISSUE THREAD

**Issue by rmarabini** [I2PC/scipion#611]
When I execute movie_alignment with 64 threads Scipion does not keep all threads working all the time but waits until the first 64 works finished before launching the next 64.

Follows the output of the command
"while sleep 10; do date ;ps -ef | grep xmipp | wc; done"
that prints the number of xmipp processes (note that the maximum is 127 becouse some xmipp programs internally call another xmipp programs "Oh tempora, Oh mores!")

In order to summarize the file. The computer is running at top capacity until 16:54, then the number of processses go down to 1 at 17:05 and back to full capacity at 17:18

[pp.txt](https://github.com/I2PC/scipion/files/553768/pp.txt)

**Comment by pconesa** [comment]
Does this help?
![image](https://cloud.githubusercontent.com/assets/785633/19735859/8b5fdb6c-9bad-11e6-9e19-0c6da66aa19d.png)

**Comment by pconesa** [comment]
Can this be closed? @rmarabini

**Comment by rmarabini** [comment]
yes it can,

   Roberto
