### ISSUE TITLE
Flag new protocols/obsolete ones

### ISSUE THREAD

**Issue by pconesa** [I2PC/scipion#614]
Figure out a way to flag new protocols as new and obsolete ones too

**Comment by azazellochg** [comment]
This seems to be implemented (for new ones), but it's not documented anywhere. Is it done in protocols.conf files? @pconesa

**Comment by pconesa** [comment]
This is done, through the use of protocolclass._lastUpdateVersion static attribute.

The base protocol class has this:
    @classmethod
    def isNew(cls):
        version = cls.getLastUpdateVersion()
        return version not in pw.OLD_VERSIONS

With pligunization, the version of the core might be static, but if , as a plugin, you want to fine tune this just implement the isNew method in your class base on your own criteria.
