### ISSUE TITLE
backward compatibility for removed (legacy) protocols

### ISSUE THREAD

**Issue by rmarabini** [I2PC/scipion#616]
1) Execute protocol in stable version
2) open project with developer version, removed protocol appear as legacy :-)
3) open project with stable version. All those protocols open in developer version that has disappear in developer version still appear as legacy :-(. Protocols not opened in developer version, even if they are legacy in developer version, can be open without problems.

**Comment by pconesa** [comment]
@rmarabini ...ummm, I created a new local protocol in Master, and "moved" to devel. Y opened it and moved back to master...it opens....maybe I need to trigger the save somehow.

**Comment by pconesa** [comment]
@rmarabini , if I update the comment, it saves it as legacy, Got it!.
