### ISSUE TITLE
parallel ctf

### ISSUE THREAD

**Issue by rmarabini** [I2PC/scipion#621]
scipion_devel
protocol: ctffind

 An average cttfind determination takes around 30 sec. Therefore if you run the protocol with 30 CPUs ideally you should be able to solve a CTF each 1 second. Unfortunately, when run in parallel, the protocol star a new step each 4-5 sec therefore, there is no way to run 30 ctffinds in parallel because the workflow engine only starts a new execution each 4-5 seconds. (In practice there is no way to run more than 17 cttfinds in parallel)

**Comment by delarosatrevin** [comment]
Yes, this is one issue that I have recently found with some "working"
program that just waste cpu cycles for a given amount of seconds. If the
working time is less than those 4~5 secs, then you can not have more than
one. I was testing because your report and also some report from Coss.

**Comment by azazellochg** [comment]
Actually, I have a related question.
ctffind3 and ctffind4.0.x support both mpi and threading. Right now in devel branch ctffind3_mp.exe is never used, NCPUS is never set by a protocol; for ctffind4 OMP_NUM_THREADS=1 always. And mpi is switched off in GUI form.py. ctffind4.1.x supports only mpi, but it's not in devel (yet)

Do I understand correctly that at the moment scipion itself implements threading for ctffind (hence the use of ctffind3.exe and not ctffind3_mp.exe)?

**Comment by pconesa** [comment]
And this one?....can this be closed?
