### ISSUE TITLE
problem compilin opencv

### ISSUE THREAD

**Issue by rmarabini** [I2PC/scipion#626]
version scipion_devel
when compiling (new) scipion download I got errors like:

opencv-2.4.9/modules/highgui/src/ffmpeg_codecs.hpp:146:7: error: ‘CODEC_ID_MSMPEG4V3’ was not declared in this scope
     { CODEC_ID_MSMPEG4V3, MKTAG('A', 'P', '4', '1') },

Solution:

FFMPEG is deprecated, and most likely not installed on your  Distro
   build with the WITH_FFMPEG=OFF Flag.

more details in post: http://stackoverflow.com/questions/29397965/unable-to-make-opencv-2-4-9-ubuntu-14-10

Exact cmake command used: 

cmake -DWITH_FFMPEG=OFF -DWITH_CUDA:BOOL=OFF -DCMAKE_INSTALL_PREFIX:PATH=/usr/local/ScipionDevel/scipion/software .

**Comment by cossorzano** [comment]
I have added this flag to the installation script -DWITH_FFMPEG=OFF. Now it should not break.
