### ISSUE TITLE
protocol sparx gaussian picker

### ISSUE THREAD

**Issue by rmarabini** [I2PC/scipion#634]
The protocol should check if eman is installed and return and error if it is not.

**Comment by azazellochg** [comment]
@rmarabini I can't reproduce this. There [is](https://github.com/I2PC/scipion/blob/devel/pyworkflow/em/packages/eman2/protocol_autopick.py#L103) a check for eman2.

**Comment by rmarabini** [comment]
You are right. I cannot reproduce it either. I close the issue
