### ISSUE TITLE
xmipp auto picking

### ISSUE THREAD

**Issue by rmarabini** [I2PC/scipion#635]
press analyze
correct selected particles
press create new set of coordinates
a new file coordinates2.sqlite is created but no new Scipion object is added

**Comment by rmarabini** [comment]
After restarting scipion the second data set is there ;-)

**Comment by pconesa** [comment]
Did you try to refresh before restarting?

**Comment by pconesa** [comment]
This works.
I'm closing this issue. Feel free to reopen it if I'm wrong or missed something.
