### ISSUE TITLE
Implement protocol search within the graph

### ISSUE THREAD

**Issue by pconesa** [I2PC/scipion#642]
When you have a huge project it is almost impossible to locate a protocol in the "tree view". You can go to the data view and sort the table, but searching dialog will help.

**Comment by pconesa** [comment]
Duplicated #1508

**Comment by carmensmp** [comment]
If both this and #1508 are closed, does it mean the issue has been solved? Is there already a way to search within the tree?

**Comment by azazellochg** [comment]
Hi @carmensmp , #1508 is not closed :)
