### ISSUE TITLE
set operations fail (in scipion devel) if a subset was created using scipion v1.0

### ISSUE THREAD

**Issue by rmarabini** [I2PC/scipion#651]
scipion devel.
when any set protocol is used I get the error

x,y,z = self._firstDim
Valuerr: too many values to unpack

It may be relevant than the project was started using scipion v1.0.

@delarosatrevin did we fix a very similar issue? Is the fix available in devel?

**Comment by azazellochg** [comment]
how relevant is this now, ~3 years later?

**Comment by pconesa** [comment]
I'm closing this, thanks @azazellochg
