### ISSUE TITLE
Xmipp CTF protocol does not produce the right output

### ISSUE THREAD

**Issue by cossorzano** [I2PC/scipion#674]
The Xmipp metadata looks OK, but the sqlite does not take any of the data in the metadata

**Comment by pconesa** [comment]
I'm confused.....I've run Xmipp ctf estimation and I'm getting values in all _xmipp fields...Am I missing anything?

![image](https://cloud.githubusercontent.com/assets/785633/20792669/55b55b2c-b7c3-11e6-8597-ff995851a9f3.png)

**Comment by pconesa** [comment]
False alarm!
