### ISSUE TITLE
Guide to request a personal certificate for EGI FedCloud

### ISSUE THREAD

**Issue by grgsipos** [I2PC/scipion#675]
Hi,

On this page the user is directed to the IRISgrid CA to obtain a personal certificate: https://github.com/I2PC/scipion/wiki/Scipion-on-the-EGI-Federated-Cloud. 

One actually needs to obtain a certificate from the national IGTF Certificate Authority (CA). The national CA can be found on this website: https://www.igtf.net/

Regards,
Gergely

**Comment by ldelcano** [comment]
Wiki page updated, thanks Gergely.
