### ISSUE TITLE
scipion install --help does not work just after configuring

### ISSUE THREAD

**Issue by cossorzano** [I2PC/scipion#693]
1) Clone the repository
2) ./scipion config
3) ./scipion install --help

You get

Scipion v1.0.1 (2016-06-30) Augusto

Usage: ./scipion install [<target>] [--no-scipy] [--no-opencv] [--show]

Installs Scipion. Also used to install only part of it, as specified
in the <target>, or to add extra em packages to Scipion.

Arguments:
  <target>      a library, a python module, an em package or a xmipp file
   -j N         where N is the number of processors to use during installation
  --help        show this help message
  --show        just show what would be done, without actually installing
  --no-opencv   do not install opencv (big) or anything that depends on it
  --no-scipy    do not install scipy or anything that depends on it
  --no-xmipp    use this option only after a successful compilation of Xmipp
                to save some time when installing other packages 

Available packages (*: seems already installed)
Error: [Errno 2] No such file or directory: 'software/lib/python2.7/site-packages'

**Comment by azazellochg** [comment]
works in 2.0
