### ISSUE TITLE
R2.0: Add local resolution protocol

### ISSUE THREAD

**Issue by pconesa** [I2PC/scipion#694]
There is a local resolution protocol in Relion that would be nice to have in the future.

**Comment by azazellochg** [comment]
@ldelcano @pconesa I have added it in az-relion2.1 branch

**Comment by pconesa** [comment]
Excellent, thanks @azazellochg. I guess this could go with the next minor release, right?

**Comment by azazellochg** [comment]
@pconesa I am now checking if everything works with relion-2.1, so it should be ready for 1.1.1, yes

**Comment by delarosatrevin** [comment]
@azazellochg One question, what is the base branch that you used for R2.1 branch?

**Comment by azazellochg** [comment]
@delarosatrevin it is based now on release-1.1, I guess I will merge from 1.1.1

**Comment by delarosatrevin** [comment]
Great! I think this will be a really nice feature for release...it is start becoming no so 'minor' ;)
