### ISSUE TITLE
copy relion 3D classify.

### ISSUE THREAD

**Issue by rmarabini** [I2PC/scipion#702]
launch one relion 3D classify with 3 classes (we will call it protA in the following)
launch a continuation of protA (we will call it protA2 in the following)
copy protA (we will call this protB in the following) and modify the number of classes to 4
copy protA2 to continue protB  (we will call this protB2 in the following) 

prot B has 4 classes, but protB2 according to scipion summary has only 3 (although relion runs correctly with 4). Analyze results shows only 3 classes unless you specify that you want to see classes 1-4

**Comment by pconesa** [comment]
How often a user will do this?

**Comment by rmarabini** [comment]
Not very often but more than once in a human lifespan (by the way, the lowest life expectancy country is Chad at just 49.44 years)

**Comment by azazellochg** [comment]
"not a bug" (c) Lennart Poettering.
