### ISSUE TITLE
resmap using relion two half unfil maps

### ISSUE THREAD

**Issue by rmarabini** [I2PC/scipion#704]
1. cannot directly use relion refine 3D protocol unfil maps (one has to manually import them)
2. crashes without error message

(resmap runs without problem with the final map from the same relion run in single map mode)

**Comment by azazellochg** [comment]
given that now all refinement  protocols produce a volume with  halfmaps property and import volumes also allows to import a vol with half maps, we might consider modifying resmap protocol to only accept single volume and fetch associated halfmaps. Thoughts? @pconesa ?

**Comment by pconesa** [comment]
Makes sense, I'll check this with the rest.
