### ISSUE TITLE
SUPPORT: import movies from individual frames is not working

### ISSUE THREAD

**Issue by azazellochg** [I2PC/scipion#705]
I have been trying to import movie frames and create movie stacks at the same time using scipion, but each time it failed after importing with this message :

Traceback (most recent call last):
  File "/dls_sw/apps/scipion/devel/scipion/pyworkflow/protocol/protocol.py", line 182, in run
    self._run()
  File "/dls_sw/apps/scipion/devel/scipion/pyworkflow/protocol/protocol.py", line 234, in _run
    raise Exception('Missing filePaths: ' + ' '.join(missingFiles))
Exception: Missing filePaths:

Does this mean there is an error in the script for this? But I have previously done this without error. Kindly please enlighten me.

Many thanks,
Weng

-------------------------------------------------------------------------
I can't reproduce the error, however whether I set "import from individual frames" to Yes or No it doesn't make any movie stacks, importing simply individual files. I also dont understand what should I use as the pattern in this case.

**Comment by pconesa** [comment]
Thanks @azazellochg. ;-) I'll try to help too.

**Comment by pconesa** [comment]
On the 13th of december I?ve sent this:
Dear Weng, sorry for the late reply.


The code shown in the log hasn't changed recently, so I would say it might be a special case with the data provided.


Could you please send the complete log. Also a screenshot of import protocol with the parameters might be useful.


Cheers, Pablo


Scipion team.

No reply yet.

**Comment by pconesa** [comment]
Today:
Dear Weng...are you still getting that error or blocked?

All the best, Pablo.

**Comment by pconesa** [comment]
it turns out that: 

He... " was running the movie import and stacking without streaming, thinking that streaming is only used when data/movies are being generated concurrently with the in-line processing. I managed to get the stacking running once I switched to streaming mode."

So he found a workaround, but there is a bug.
