### ISSUE TITLE
project -> export tree graph

### ISSUE THREAD

**Issue by rmarabini** [I2PC/scipion#708]
When executed ()  it produces the following errors:

>>>>> python  /home/roberto/Scipion/scipion_devel/pyworkflow/apps/pw_manager.py 
ERROR loading project: Runs
Project database not found in '/home/roberto/ScipionUserData/projects/Runs/project.sqlite'
ERROR loading project: Uploads
Project database not found in '/home/roberto/ScipionUserData/projects/Uploads/project.sqlite'
ERROR loading project: Tmp
Project database not found in '/home/roberto/ScipionUserData/projects/Tmp/project.sqlite'
ERROR loading project: .config
Project database not found in '/home/roberto/ScipionUserData/projects/.config/project.sqlite'
ERROR loading project: Logs
Project database not found in '/home/roberto/ScipionUserData/projects/Logs/project.sqlite'
PROJECT: Warning, protocol view 'None' not found.
         Using 'Protocols SPA' instead.

**Comment by pconesa** [comment]
False alarm!
