### ISSUE TITLE
Motioncorr use cuda7.5

### ISSUE THREAD

**Issue by pconesa** [I2PC/scipion#732]
install motioncorr (2.1) with cuda 7.5. Now is looking for cuda 5.0 and since relion and motioncor2 uses 7.5 make sense to use same cuda version.

**Comment by pconesa** [comment]
motioncorr test compiled with cuda 7.5 renders different shifts!! (same in 2 different machines( ubuntu and suse).

AssertionError: Alignment SHIFTS must be ([0.0, 0.3646, 0.2604], [0.0, -0.1354, -0.3958]) (<type 'tuple'>) and it is ([0.0, 0.3333, 0.2292], [0.0, -0.2187, -0.4688]) (<type 'tuple'>)

**Comment by azazellochg** [comment]
devel (2017-01-02) d5e31d0
motioncorr2.1 compiled (from src) with cuda 7.5, passes all 3 tests.

> Linux microgpu2 4.4.0-31-generic #50-Ubuntu SMP Wed Jul 13 00:07:12 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux

**Comment by pconesa** [comment]
Hi @azazellochg ! Did you compile yourself or used the already cuda version in our repository:
`scipion install morioncorr 2.1.cuda.7.5`

**Comment by azazellochg** [comment]
Hi @pconesa ! I think I downloaded it first from your repo (motioncorr2.1, not motioncorr2.1.cuda.7.5), then I saw it was compiled for cuda 5.5, so I recompiled it myself with 7.5.
