### ISSUE TITLE
devel_version file

### ISSUE THREAD

**Issue by azazellochg** [I2PC/scipion#733]
When scipion is installed system-wide, normally user has no writing permissions for installation folder (/usr/local/*). It's a bit annoying when with every scipion command I get:
```
/bin/sh: 1: cannot create .devel_version: Permission denied
/bin/sh: 1: cannot create .devel_version: Permission denied
```
Could we make a check to avoid writing this file when there is no access?

**Comment by pconesa** [comment]
Now it's done without writing any file.
