### ISSUE TITLE
running tests

### ISSUE THREAD

**Issue by rmarabini** [I2PC/scipion#750]
I have tried to run the tests described in URL

   https://github.com/I2PC/scipion/wiki/Running-Tests#xmipp-workflow

Most of them fail. For example:

deimos:/usr/local/scipion # ./scipion tests em.data.test_convert_xmipp

Scipion  devel (2017-01-02) d5e31d0

>>>>> python  scripts/run_tests.py em.data.test_convert_xmipp
Running tests....
Cannot find test em.data.test_convert_xmipp -- skipping
error:  'module' object has no attribute 'test_convert_xmipp'

[==========] run 0 tests (0.000 secs)
[  PASSED  ] 0 tests

What is the status of the tests?

**Comment by azazellochg** [comment]
we got buildbot for this now :)
