### ISSUE TITLE
Test ctffind with MPI

### ISSUE THREAD

**Issue by pconesa** [I2PC/scipion#758]
Check openMPI version 1.6

**Comment by ldelcano** [comment]
I tried ctffind4-4.0.15 with openmpi 1.6 and it worked with 6 MPI (betagal project).
Then I updated my OS from Ubuntu 14 to 16 and openmpi to 1.10 and:
ctffind4-4..0.15 with 6 MPI or threads works
ctffind4-4.1.5 with 6 MPI do not work but with threads works
xmipp ctf estimation with 6 MPI or threads work

**Comment by pconesa** [comment]
I thinks I've found something, @rmarabini suspicions were right:

ctffind returns 255 as exit status.

pablo@newton:~/ScipionUserData/projects/mpi$ /home/pablo/desarrollo/scipion/software/em/ctffind4-4.1.5/ctffind


        **   Welcome to Ctffind   **

            Version : 4.1.5
           Compiled : Sep  9 2016
               Mode : Interactive

Input image file name [input.mrc]                  : Runs/000066_ProtCTFFind/tmp/008.mrcs           

Error: File does not exist, please provide an existing file!

Input image file name [input.mrc]                  : Runs/000066_ProtCTFFind/tmp/008.mrc
Output diagnostic image file name
[diagnostic_output.mrc]                            : Runs/000066_ProtCTFFind/tmp/008_ctfestimation.mrc
Pixel size [1.0]                                   : 1.34
Acceleration voltage [300.0]                       : 200
Spherical aberration [2.70]                        : 2
Amplitude contrast [0.07]                          : 0.1
Size of amplitude spectrum to compute [512]        : 256
Minimum resolution [30.0]                          : 26.8
Maximum resolution [5.0]                           : 3.82
Minimum defocus [5000.0]                           : 2500
Maximum defocus [50000.0]                          : 40000
Defocus search step [500.0]                        : 500
Do you know what astigmatism is present? [no]      : no
Slower, more exhaustive search? [no]               : 
Use a restraint on astigmatism? [yes]              : 
Expected (tolerated) astigmatism [200.0]           : 100
Find additional phase shift? [no]                  : 
Do you want to set expert options? [no]            : yes
Resample micrograph if pixel size too small? [yes] : yes

Summary information for file Runs/000066_ProtCTFFind/tmp/008.mrc
Number of columns, rows, sections: 1024, 1024, 1
MRC data mode: 2
Bit depth: 32
Pixel size: 1.000 1.000 1.000
Bytes in symmetry header: 0
Label 1 : 
Label 2 : 
Label 3 : 
Label 4 : 
Label 5 : 
Label 6 : 
Label 7 : 
Label 8 : 
Label 9 : 
Label 10 : 

Working on micrograph 1 of 1
Estimated defocus values        : 14137.42 , 14030.68 Angstroms
Estimated azimuth of astigmatism: 90.00 degrees
Score                           : -0.05517
Pixel size for fitting          : 1.403 Angstroms
Thon rings with good fit up to  : 13.8 Angstroms
CTF aliasing apparent from      : 6.8 Angstroms
Warning: CTF aliasing occurred within your CTF fitting range. Consider computing a larger spectrum (current size = 256).

Summary of results                          : Runs/000066_ProtCTFFind/tmp/008_ctfestimation.txt
Diagnostic images                           : Runs/000066_ProtCTFFind/tmp/008_ctfestimation.mrc
Detailed results, including 1D fit profiles : Runs/000066_ProtCTFFind/tmp/008_ctfestimation_avrot.txt
Use this command to plot 1D fit profiles    : ctffind_plot_results.sh Runs/000066_ProtCTFFind/tmp/008_ctfestimation_avrot.txt


pablo@newton:~/ScipionUserData/projects/mpi$ echo $?
255
