### ISSUE TITLE
SUPPORT:about RCT-Can I generate a tilted particle set according to an untilted class set?

### ISSUE THREAD

**Issue by pconesa** [I2PC/scipion#762]
From scipion users:

Dear colleagues，

When I did RCT with scipion, I found that it could only generate volumes according to the classified untilted sets (like what you only need to import in the " Random Conical Tilt" menu are the tilt_pairs and Good_classes files ). Since after viewing those volumes, I need to merge a few classes to generate a better volume which may come from the same conformation. Then, what should I do to extract and merge those tilted particles from corresponding classes? (as you know, the classes were generated from untilted particles.) 

Hope I described my question clearly.

**Comment by cossorzano** [comment]
Dear Liz,

as you indicate, the RCT protocol is only capable of reconstructing volumes from individual untilted classes. To merge them, you may use any subtomogram averaging protocol. Currently in Scipion the only one fully available (there are some other in development) is cltomo (do CTRL-F to locate it). The number of classes would be 1 in your case.

Kind regards, Carlos Oscar

**Comment by pconesa** [comment]
@cossorzano this issue was added by me to keep track of it, but the user used scipion-users@lists.sourceforge.net.

Better reply to the list!! ;-)
