### ISSUE TITLE
SUPPORT: auto-refinement for 2D

### ISSUE THREAD

**Issue by pconesa** [I2PC/scipion#763]
From user list: 

Dear colleagues,

? --> auto-refinement for 2D

We work a lot with negative staining samples doing classification (in relion 2D) and getting 2D projection average classes.

It might be possible to improve 2D results doing auto-refinement step (for 2D).

If yes how can we do that?

I tried to use dataset and created 2D mrc (vol) file as a reference but the program ended up with some errors.

 

Dear colleagues do you have any ideas about that possibility ?

**Comment by pconesa** [comment]
Reviewing support....what's the status of this?

**Comment by josuegbl** [comment]
refinement for 2D has not sense.... you should close this issue
