### ISSUE TITLE
scipion show histograms

### ISSUE THREAD

**Issue by rmarabini** [I2PC/scipion#768]
1) Compute CTFs with ctffind
2) Analyze the result and plot the histogram for maximum resolution
3) If, as often happends, any of the resolution is equal to infinity the histogram does not make sense
---------  

Proposed solution: filter the values equal to inf when plotting/calculating-histogram

-------
Other: attached file with infinite values
[ctfs.sqliteOLD.zip](https://github.com/I2PC/scipion/files/704565/ctfs.sqliteOLD.zip)

**Comment by pconesa** [comment]
fixed here https://github.com/scipion-em/scipion-em/pull/23/commits/8f8502708209d03522d395a57a4a054b975ac622
