### ISSUE TITLE
xmipp_test_metadata fails

### ISSUE THREAD

**Issue by pconesa** [I2PC/scipion#770]
[  FAILED  ] 1 test, listed below:
[  FAILED  ] MetadataTest.CopyColumn

**Comment by pconesa** [comment]
@cossorzano , Could you please help with this? I don't think is related to the changes in the branch we've reviewed today (devel_coss), but I was running the tests and found that.

**Comment by cossorzano** [comment]
For me it is working in release-1.1, can we see the machine where it fails?

**Comment by cossorzano** [comment]
It was a compiler issue already solved
