### ISSUE TITLE
Improve the model for Movies and Frames

### ISSUE THREAD

**Issue by rmarabini** [I2PC/scipion#78]
It would be interesting:

1) think how to handle frames in scipion
2) store frame shift (for unblur program and yifan)

**Comment by azazellochg** [comment]
May I reopen this? I have checked alignment_shifts for output movies:

- correlation alignment: all shifts in output SetOfMovies are 0
- motioncorr/motioncor2: shifts are ok
- optical flow: all shifts are 0
- unblur: no shifts are written to output movies - no values

**Comment by delarosatrevin** [comment]
Have selected to write the aligned movies? If yes is it normal that shift are 0, since the alignment have been applied. But all should be the same. For OF, since the shift are not global, it only can outputs Micrographs or Movies with the correction applied (so 0 shifts)

**Comment by azazellochg** [comment]
Ah, I see. So if aligned movie is produced by the program then all shifts should be 0 and if not then output movies = input ones with non-zero shifts?

**Comment by delarosatrevin** [comment]
Yes, that is the idea. Just to keep the shifts (similar to 2D alignment in classification) as much as possible to avoid data duplication and then generate the metadata of shifted movied when necessary.

**Comment by azazellochg** [comment]
@delarosatrevin all protocol except unblur work as expected. Unblur has no option "save movie" so it is supposed to clone input one and assign shifts. However no shift values are present in outputMovies. I will look into this.

**Comment by azazellochg** [comment]
fixed in  5efa73a
