### ISSUE TITLE
xmipp commands and MPI

### ISSUE THREAD

**Issue by pconesa** [I2PC/scipion#794]
From email:
Have another issue with xmipp distributed with scipion-v1.0.1, and I failed to find a documentation on this topic.  When I run commands with mpi, like xmipp_mpi_run, it says

Sorry! You were supposed to get help about:

Opal_init:startup:internal-failure

But I couldn’t open the help file:

/software/lib/Linux-x86-64/openmpi-1.6.5-build3/share/openmpi/help-opal-runtime.txt: No such file or directory.

 

I have configured scipion.conf to point to openmpi directories before scipion installation.  After the install, openmpi directories in xmipp.cfg are also edited.  I could not find a documentation with Scipion about how to successfully compile xmipp.  Could you advise or forward my message to someone who may know?

 

Thank you, and I appreciate your input.

**Comment by azazellochg** [comment]
Xmipp works with mpi from cmdline irrespective of whether xmipp.cfg is edited or not:
```
mpirun -np 4 software/em/xmipp/bin/xmipp_mpi_angular_project_library -i  ~/test/relion/run_class001.mrc -o proj.stk --sym d2 --sampling_rate 1
```
Is xmipp.cfg is still used for something?

**Comment by delarosatrevin** [comment]
I'm not completely sure...but I think xmipp.cfg is not longer used.
