### ISSUE TITLE
Problem with particle picking in Scipion

### ISSUE THREAD

**Issue by pconesa** [I2PC/scipion#795]
My name is Luigi De Colibus and I’m Post Doc at the Division of Structural Biology of Oxford University.
I’m writing you because I’m trying to run automated particle picking  programs  on my micrographs  trough SCIPION.
Surprisingly, despite the fact my virus particle is very big and evident on the micrographs, neither Xmipp particle picking program nor Boxer in EMAN2 is able to pick correctly the particles after providing the reference.
I guess my settings could be wrong and trying different values has not helped so far.

It would be great if you could point me in the right direction.
I can send you one of my micrographs if you need to do a test run.

Thanks a lot in advance for your help!

Best Regards

Reply to: luigi   at  strubi.ox.ac.uk

**Comment by azazellochg** [comment]
This has nothing to do with scipion, no?

**Comment by pconesa** [comment]
Nope, I think once I tried to certralize all support "issues" in github.
