### ISSUE TITLE
Add motioncor2 new release..

### ISSUE THREAD

**Issue by pconesa** [I2PC/scipion#797]
Dear Colleagues,

The new version of MotionCor2 has been released on our website

http://msg.ucsf.edu/em/software/index.html

This version has implemented the following new functions in addition to bug fixing.

1. Correction of anisotropic magnification. This correction is integrated with the correction of local motion. There is no extra real-space interpolation as a result.
2. Archiving input movie stacks of 8 bits per pixel into MRC files with 4 bits per pixel.
3. Allow stacks to be aligned to user specified frames. 

This version is compiled with CUDA 8. For your convenience, the last version of MotionCor2 is still kept on our website.

Thank you all for your interests and feedbacks.

Best
Shawn

**Comment by delarosatrevin** [comment]
Thanks @azazellochg I just remembered that @pconesa added the issue, but I could not find it. I will close #908

**Comment by delarosatrevin** [comment]
@azazellochg Let me know if I can help you with this one. Please open the branch from release-1.1 and if there are not much changes we can try it to push it into the release.

**Comment by pconesa** [comment]
@azazellochg, many thanks for your offering. Just to be clear, when I added this issue, and until now, I never thought that this was "kind of" your thing. It was just something we want to have, but didn't find time.
Please never feel that the "ball is in your court" or any similar thing. All the best, Pablo.

**Comment by azazellochg** [comment]
@pconesa  no worries, I did plan to update it quite a while ago anyway :) also this is a small change
