### ISSUE TITLE
SUPPORT: wiener filter and relion

### ISSUE THREAD

**Issue by pconesa** [I2PC/scipion#798]
From Dmitry (user list):

1. Wienner filter + CTF envelope correction --> relion 2D error 
(normalisation).

I did the CTF correction of the particle using Wiener filter script + 
correct for the CTF envelope I had a problem running the corrected 
particles in relion 2D alignment (in the settings of relion I selected “NO” 
for the CTF correction).

The error:

Error: it appears that these images have not been normalized to an average 
background value of 0 and a stddev value of 1

Then I tried relion - preprocessing tool
Outcome: finished but in the log:
WARNING! Stddev on image …… 
Xmipp_ProtCTFCorrectedWiener2D/corrected_ctf_particles.stk is zero! 
Skipping normalisation

Tried Xmipp - preprocessing tool
Outcome - finished no error.

But again - when you run relion 2D alignment you getting the same error.

Why?

2. Particle picking.

Probably very basic question but it is still not a routine for me.

Now I’m collecting the data on Titan Krios and one of the outcome is the 
binned jpg file where you can see your particles nicely.
Do we have the similar tool in the SCIPION that will allow us to initially 
bin the images, pick the particles and then interpolate the coordinates on 
unbinned images?
(Normally I don't really use the binning).

Is that what we can do using the CTF estimation script?
If so how and when can/should we unbin the dataset?

**Comment by pconesa** [comment]
@josuegbl are you able to reply dmitry?

**Comment by azazellochg** [comment]
1. use relion preprocess to normalize particles. Even better to do CTF correction in relion
2. yes.
