### ISSUE TITLE
Buildbot: release11_Protocol_Tests tests.em.protocols.test_protocols_system_monitor

### ISSUE THREAD

**Issue by pconesa** [I2PC/scipion#805]
fix this in buildbot

**Comment by ldelcano** [comment]
Missing library stress-ng. Pablo to install.

**Comment by delarosatrevin** [comment]
Library stress-ng ??

**Comment by ldelcano** [comment]
apt-cache search stress-ng
stress-ng - tool to load and stress a computer

**Comment by delarosatrevin** [comment]
Maybe the test can warn about the missing tool...but I think we should keep
its installation out of Scipion.

**Comment by ldelcano** [comment]
Sure, and the test is warning, I have installed it directly on the machine :)
