### ISSUE TITLE
Buildbot:   tests.em.protocols.test_protocols_motioncor2

### ISSUE THREAD

**Issue by pconesa** [I2PC/scipion#811]
at protocol tests

**Comment by ldelcano** [comment]
Folder software/em/motioncorr-2.1 does not exist (it is motioncorr_v2.1.cuda.7.5).
Modify scipion.conf name (Pablo is working on this).

**Comment by ldelcano** [comment]
Package motioncorr2 is not installed. Pablo will add it.
