### ISSUE TITLE
Buildbot:  tests.em.protocols.test_protocols_mixed_movies.TestMixedMovies

### ISSUE THREAD

**Issue by pconesa** [I2PC/scipion#812]
at protocol tests

**Comment by ldelcano** [comment]
The comparison between output images from the two OF runs fails.
COSS suggests to use cubic interpolation instead of linear, but images are still not good enough to be considered equal.

**Comment by cossorzano** [comment]
To the best I can test, both paths give the same result (up to some interpolation errors that have an SNR of -50dB). In the process, we have discovered a couple of errors.
