### ISSUE TITLE
Streaming for particle pickers

### ISSUE THREAD

**Issue by JuhaHuiskonen** [I2PC/scipion#820]
Feature request - please add streaming for particle pickers

**Comment by delarosatrevin** [comment]
Thanks for the feedback @JuhaHuiskonen , this is really important for us to assign priorities among several tasks.

**Comment by delarosatrevin** [comment]
Now we have picking in streaming! in branch release-1.1.facilities-stream-picking, that soon will be merged into release-1.1.facilities-devel (which will be the next release)
