### ISSUE TITLE
Correct spelling of QUEUES_DEFAULT on wiki

### ISSUE THREAD

**Issue by bedroge** [I2PC/scipion#821]
I was looking for a way to add our SLURM GPU partition to the hosts.conf file and make Scipion (1.1) request a GPU (only for this partition) using SLURM's --gres=gpu:N option. On the following page of the wiki I found that you can use an additional option to set the default number of GPUs for all partitions/queues to 0, which is really helpful:

https://github.com/I2PC/scipion/wiki/Host-Configuration

However, it firsts states that the name of the option is QUEUES_DEFAULTS, while the next sentence says QUEUE_DEFAULTS. I tried both, but they did not work for me. Looking in the source code revealed that it should be QUEUES_DEFAULT instead, which indeed works fine.

**Comment by delarosatrevin** [comment]
Thanks a lot for the feedback @bedroge !!! I just fixed the wiki to be consistent with the variable used in the code.
