### ISSUE TITLE
mag_distortion install fails

### ISSUE THREAD

**Issue by azazellochg** [I2PC/scipion#826]
> Building mag_distortion-1.0.1 ...
>   Skipping command: wget -nv -c -O software/em/mag_distortion_v1.0.1.tgz.part http://scipion.cnb.csic.es/downloads/scipion/software/em/mag_distortion_v1.0.1.tgz
> mv -v software/em/mag_distortion_v1.0.1.tgz.part software/em/mag_distortion_v1.0.1.tgz
>   All targets exist.
> cd software/em
> tar -xzf mag_distortion_v1.0.1.tgz
> Error: target 'software/em/mag_distortion_v1.0.1' not built (after running 'tar -xzf mag_distortion_v1.0.1.tgz')

Solution: rename the folder with binary (mag_distortion->mag_distortion-1.0.1) and update the archive

**Comment by pconesa** [comment]
I think this is fixed now, Thanks @azazellochg
