### ISSUE TITLE
Example command fails "How to install wiki"

### ISSUE THREAD

**Issue by ploszpe** [I2PC/scipion#828]
The "How to Install" wiki (https://github.com/I2PC/scipion/wiki/How-to-Install) has the following example command in "Installing other EM Packages" section:
> ./scipion install --no-xmipp -j 5 relion resmap spider

The command above fails with the following error:
> Error: Unknown target: relion

The correct command include relion version.

Thanks,
Peter

**Comment by delarosatrevin** [comment]
Hi Peter, 

Thanks a lot for reporting this issue. It was my fault, the other day I was testing the installation of the 'release-1.1' branch, that will be the next release and in this case it works without specifying the package version. I have reverted to the previous state of the wikipage until we define how we are going to deal with different versions of the wiki addressing different versions of the software.

Thanks again.
Jose Miguel.

**Comment by ploszpe** [comment]
Thank you.
