### ISSUE TITLE
Update all tutorials for 1.1 release

### ISSUE THREAD

**Issue by pconesa** [I2PC/scipion#829]

**Comment by pconesa** [comment]
@ldelcano , you've updated the tutorials, didn't you?

**Comment by ldelcano** [comment]
I though so but I have checked and only the betagal tutorial was updated, not yet the introduction and initial volume (although I am not sure if the latest has changed at all).

**Comment by ldelcano** [comment]
I checked on sharelatex and they were all updated in June so I copied new pdfs to wiki.
