### ISSUE TITLE
add mask 2d to Relion 2d protocols

### ISSUE THREAD

**Issue by josuegbl** [I2PC/scipion#836]
Mr. Jaime demand this issue for his processes, to know which mask is used

**Comment by azazellochg** [comment]
@josuegbl could you please elaborate? :) I didn't quite understand. Does he want a create mask 2d protocol? Or add the option to use a mask in 2d classification?

**Comment by josuegbl** [comment]
@azazellochg this issue was to add a mask in 2d classification, and its done. I close the issue.
