### ISSUE TITLE
Generate averages and std from images, fails for some cases

### ISSUE THREAD

**Issue by josuegbl** [I2PC/scipion#837]
In some cases, when generate averages and std from images, java crash with the following error:
# A fatal error has been detected by the Java Runtime Environment:
#
#  SIGSEGV (0xb) at pc=0x00007f1f2ab4b0be, pid=3528, tid=0x00007f1f1bfff700
#
# JRE version: OpenJDK Runtime Environment (8.0_111-b14) (build 1.8.0_111-b14)
# Java VM: OpenJDK 64-Bit Server VM (25.111-b14 mixed mode linux-amd64 compressed oops)
# Derivative: IcedTea 3.2.0
# Distribution: Custom build (Wed Nov 23 13:15:13 UTC 2016)
# Problematic frame:
# C  [libXmippData.so+0x47f0be]  MDL::isTextFile(MDLabel)+0x18
#
# Failed to write core dump. Core dumps have been disabled. To enable core dumping, try "ulimit -c unlimited" before starting Java again
#
# An error report file with more information is saved as:
# /disco4/RNP_WSN_CAMBRIDGE/RNP_WSN_SCIPION/hs_err_pid3528.log
#
# If you would like to submit a bug report, please include
# instructions on how to reproduce the bug and visit:
#   http://icedtea.classpath.org/bugzilla
# The crash happened outside the Java Virtual Machine in native code.
# See problematic frame for where to report the bug.

**Comment by pconesa** [comment]
Same as #1055

**Comment by pconesa** [comment]
Duplicated,#1055  I'm closing this
