### ISSUE TITLE
Buildbot: tests.em.protocols.test_protocols_xmipp_mics.TestXmippExtractParticles.testExtractSort fails

### ISSUE THREAD

**Issue by ldelcano** [I2PC/scipion#840]
AssertionError: 267 != 249 within 10 delta
in this line:
self.assertAlmostEquals(outputParts.getSize(), 249, delta=10)
After modifying default value for dust removal threshold from 3.5 to 5 the number of particles extracted on the tests pass from 254 to 267 which makes the assertion above to fail.
It seems that zScore values change when modifying dust removal threshold value, and it shouldn't.

**Comment by 1aviervargas** [comment]
Checked and confirmed that there is no error
