### ISSUE TITLE
Review threads and MPI for Steps_Paralell

### ISSUE THREAD

**Issue by pconesa** [I2PC/scipion#851]
0 in MPI or Threads (I'm guessing this second part) will not show the parallel section.

**Comment by ldelcano** [comment]
If execution mode is STEPS_PARALLEL protocol cannot have numberOfThreads or numberOfMpis set to 0 but It should be 1 by default.
Also add an Excetion to form.py code to warn when it is zero.

**Comment by ldelcano** [comment]
Updated protocols (now it shows both Threads and Mpi labels but just one input for the numberOf):
- ProtMagDistCorr: set mpi=1
- XmippProtCTFDiscrepancy: set mpi=1, threads=1

**Comment by ldelcano** [comment]
- ProtFrealignBase: set mpi=1
- ProtUnblur: set mpi=1
- ProtSummovie: set mpi=1
- XmippProtMovieAverage: set mpi=1
- XmippProtOFAlignment: set mpi=1
- XmippProtSubtractProjection: set mpi=1

**Comment by pconesa** [comment]
Can we close this?

**Comment by pconesa** [comment]
where is this fixed? @ldelcano .

**Comment by ldelcano** [comment]
Yes, close it
