### ISSUE TITLE
Buildbot: tests.em.protocols.test_protocols_highres.TestHighres

### ISSUE THREAD

**Issue by ldelcano** [I2PC/scipion#862]
It fails.

**Comment by ldelcano** [comment]
It gives timeout on step 24: localAssignment after 2h 10'.

**Comment by ldelcano** [comment]
When running it on my laptop it collapsed it and I had to restart.
I will run it on nolan with user scipion (no timeout as in buildbot setup)

**Comment by ldelcano** [comment]
File "/home/local/scipion/software/lib/python2.7/unittest/case.py", line 422, in assertTrue
    raise self.failureException(msg)
AssertionError: Resolution is not below 8A

COSS, could you check why this is happening? Maybe you can have  look at the resolution reached without having to rerun it (it takes ages!). Somewhere on the DB or output file?

**Comment by pconesa** [comment]
It seems it's a buildbot timeout due to there is no output for 1200 seconds. I'll take a look at it. Test works outside buildbot.
