### ISSUE TITLE
local_resolution

### ISSUE THREAD

**Issue by rmarabini** [I2PC/scipion#876]
#Vilax xmipp_local_resolution form allows users to choose number of  MPIs  and number of threads. I understand that this prococol cannot handle CPUs or threads therefore these options should be removed. That is, do not use 

   self.stepsExecutionMode = STEPS_PARALLEL

   Roberto

**Comment by Vilax** [comment]
I agree, MonoRes does not allow a MPI/threads.

Now it has been fixed. Next days, a merge will be performed

Regards

Vilas
