### ISSUE TITLE
Buildbot: tests.em.protocols.test_protocol_volume_homogenizer.TestVolumeHomogenizer

### ISSUE THREAD

**Issue by ldelcano** [I2PC/scipion#878]
It fails.

**Comment by ldelcano** [comment]
Missing sh_alignment package.

**Comment by cossorzano** [comment]
This package is installed with

scipion install sh_alignment

Cheers, Carlos Oscar

**Comment by ldelcano** [comment]
I know coss :) I will do it on heisenberg when Pablo gives me the ok (I need to modify buildbot master configuration and restart)

**Comment by pconesa** [comment]
You don't need my OK......go ahead if you know haw to solve it. ;-)
