### ISSUE TITLE
Buildbot: tests.em.protocols.test_protocol_localized_reconstruction.TestLocalizedRecons

### ISSUE THREAD

**Issue by ldelcano** [I2PC/scipion#879]
It fails due to:
00022:       import localrec
00023:   ImportError: No module named localrec

**Comment by ldelcano** [comment]
Install localrec package.

**Comment by pconesa** [comment]
now it's installed but still fails:
>>>>> python  /home/buildbot-slave/data/slave/release11_Protocol_Tests/build/pyworkflow/apps/pw_protocol_run.py "/services/buildbot-slave/data/slave/ScipionUserData/projects/TestLocalizedRecons" "Runs/000002_ProtImportParticles/logs/run.db" "2"
42ERROR: output directory does not exist!
43File: /home/buildbot-slave/data/slave/release11_Protocol_Tests/build/software/em/relion-2.0.3/src/ml_optimiser.cpp line: 1152
44
45Scipion  release-1.1 (2017-03-03) 0144300
46
47>>>>> python  /home/buildbot-slave/data/slave/release11_Protocol_Tests/build/pyworkflow/apps/pw_protocol_run.py "/services/buildbot-slave/data/slave/ScipionUserData/projects/TestLocalizedRecons" "Runs/000078_ProtLocalizedRecons/logs/run.db" "78"
48[   FAILED ] TestLocalizedRecons.testProtLocalizedReconstruction
49
50Traceback (most recent call last):
51  File "/home/buildbot-slave/data/slave/release11_Protocol_Tests/build/software/lib/python2.7/unittest/case.py", line 329, in run
52    testMethod()
53  File "/home/buildbot-slave/data/slave/release11_Protocol_Tests/build/pyworkflow/tests/em/protocols/test_protocol_localized_reconstruction.py", line 103, in testProtLocalizedReconstruction
54    localSubparticles = self._runSubparticles(120)
55  File "/home/buildbot-slave/data/slave/release11_Protocol_Tests/build/pyworkflow/tests/em/protocols/test_protocol_localized_reconstruction.py", line 96, in _runSubparticles
56    self.assertEqual(checkSize, prot.outputCoordinates.getSize())
57  File "/home/buildbot-slave/data/slave/release11_Protocol_Tests/build/software/lib/python2.7/unittest/case.py", line 513, in assertEqual
58    assertion_func(first, second, msg=msg)
59  File "/home/buildbot-slave/data/slave/release11_Protocol_Tests/build/software/lib/python2.7/unittest/case.py", line 506, in _baseAssertEqual
60    raise self.failureException(msg)
61AssertionError: 120 != 0

**Comment by pconesa** [comment]
@josuegbl, does locrec works exclusively with relion-1.4 or can do with 1.3?

**Comment by josuegbl** [comment]
According its requirements, localrec uses Relion-1.4. We can try launch it with Relion-1.3, but the probabilities to fails can be high.
