### ISSUE TITLE
Optical flow does not show parallel section

### ISSUE THREAD

**Issue by cossorzano** [I2PC/scipion#881]

**Comment by pconesa** [comment]
What's the status of this?

**Comment by cossorzano** [comment]
I saw Josue working on this and the issue under review. However, I do 
not know in which branch it is and in release-1.1-fixes it is not fixed.

**Comment by pconesa** [comment]
Ah! Now I remember. Laura reviewed all the STEPS_PARALELL protcolols. This should be fixed. I'll check with @ldelcano . I can confirm the bug is still present in release-1.1-fixes.

**Comment by pconesa** [comment]
I close it since #885 includes this case.
