### ISSUE TITLE
Handle ':' in micrograph import

### ISSUE THREAD

**Issue by jmichalon** [I2PC/scipion#892]
Hi,

If by chance you have a colon ':' in a path, import micrograph fails with not-so-useful error:
> Error reading the following images:
followed by the list of files. It takes some time to understand that it comes from the colon, as it is a valid char in a path. Maybe this is easy to fix?

**Comment by delarosatrevin** [comment]
Hi @jmichalon, 

This should be easy to validate in most the import protocols. I will open a new issue for that. In which branch are you working? We are doing now the bugfixing in 'release-1.1' branch that will be the release v1.1.0. Could you try again after this is fixed?

Thanks for your feedback.

**Comment by delarosatrevin** [comment]
Ok, this is already an 'issue'.

**Comment by pconesa** [comment]
Do you think we can deal with this?

**Comment by pconesa** [comment]
@yaizar , I had an "eureka" moment yesterday while driving back home. The regular expression pattern is wrong!.

You were testing this case:

Mics folders: 
/homes/yaiza/Desktop/hi3/mic.mrc
/homes/yaiza/Desktop/hi4/mic.mrc

Form values:
Folder: /homes/yaiza/Desktop/hi#/
File pattern: *.mrc

And we were getting the message that:

/homes/yaiza/Desktop/hi3/mic.mrc does not match the pattern /homes/yaiza/Desktop/hi[0-9]/*.mrc

And if we think in regexp terms, this is true. The key is at the *. The pattern accepts 0 or more / and then .mrc. So the pattern in this case should be:
 /homes/yaiza/Desktop/hi[0-9]/.*.mrc

And maybe escaping the . before mrc (although is not a problem).

As we said we need to be very careful with these and consider, most common cases and ideally all possible combinations. So the key here is how our patters in the form (more a pattern for glob) must be converted accurately to a regexp pattern.

**Comment by delarosatrevin** [comment]
@pconesa I think for the path here we should not think completely in regex terms, but in the regex accepted from bash as file patterns. We designed in this way to not introduce another level of complexity for the users.

**Comment by pconesa** [comment]
I know Jose, we do not intend to change what the user enters, but later in the code that bash file pattern (?* plus our #) is converted into a regexp and there is where we plan to fix that.

Just to be clear, we do not intent to allow regex entered by the user, it should remain as it is now.

**Comment by delarosatrevin** [comment]
Ok, great...I'm sorry for the confusion.

**Comment by yaizar** [comment]
@pconesa I've been checking this! So the pattern is wrong in regexp terms, but it is accepted by glob. So this works great and finds the files:
 `glob('/homes/yaiza/Desktop/hi[0-9]/*.mrc')` 

 However the field _idRegex, like you say, is wrong and it should be :
 `re.compile('home/yaiza/Desktop/hi[0-9]/(.*).mrc')`. 

Using this we avoid the exception saying "/homes/yaiza/Desktop/hi3/mic.mrc does not match the pattern /homes/yaiza/Desktop/hi[0-9]/*.mrc"

BUT the program still fails later if we have more than one .mrc inside the folder 
(the log tells us `00585:   Protocol failed: PRIMARY KEY must be unique` ). 
This makes sense to me, but maybe we would need a more explicit error message for this too?

Independently of this, I'm still not sure of how to proceed when the special characters are in the filename itself (not in the form). The ones I've found so far are **%**, **#** and **:** . Do we want just a message saying they can't be part of the path?
