### ISSUE TITLE
Still different package version appears for motioncorr 2.1 (cuda 7.5)

### ISSUE THREAD

**Issue by delarosatrevin** [I2PC/scipion#894]
@pconesa , at some point we discussed about it and we all decided to generated a new tgz file with the cuda7.5 version inside, but not as a different package version.

**Comment by pconesa** [comment]
Yes, I realized yesterday that my changes werent there. I've a local 
branch to check and if ok, will push it. If i'm right the tar.gz in the 
server already contains both binaries.

**Comment by delarosatrevin** [comment]
Ok, so if the binary in the server contains both, then I guess there is less work to do. 
Thanks @pconesa
