### ISSUE TITLE
Ctf consensus is not calculating the correct discrepancy in resolution

### ISSUE THREAD

**Issue by cossorzano** [I2PC/scipion#900]

**Comment by rmarabini** [comment]
Hi @coss.

May I have a bit of help here? Can you attach the sqlite files with the
input CTFs and describe for a particular pair of CTFs which is the obtained
result and which is the correct one?

   Thanks

**Comment by cossorzano** [comment]
Sure, here you are the sqlite files. One is coming from CTFfind, another 
from Xmipp and the last one is the discrepancy. For ID=12, CTFFind 
reports a maximum frequency of 7.7456 (ctffind4_ctfResolution), Xmipp of 
8.1379 (xmipp_ctfCritMaxFreq), but the discrepancy is calculated as 2.

Cheers, Carlos Oscar

**Comment by pconesa** [comment]
What is the status of this?

**Comment by pconesa** [comment]
Do we need to clarify the concepts in the help?

**Comment by rmarabini** [comment]
Uhm,

  Right now the help says:

    Protocol to estimate the agreement between different estimation of the
CTF for the same set of micrographs. The algorithm assumes that two CTF are
consistent if the phase (wave aberration function) of the two CTFs are
closer than 90 degrees. The reported resolution is the resolution at which
the two CTF phases differ in 90 degrees.

   The help seems to be clear enough. Of course, most of the users will
never read it but I do not know what else can be done. So far as I am
concerned we may close this.

          Roberto

**Comment by cossorzano** [comment]
That's fine
