### ISSUE TITLE
Sparx Gaussian fails

### ISSUE THREAD

**Issue by cossorzano** [I2PC/scipion#901]
It cannot find sxprocess.py

**Comment by pconesa** [comment]
Is the package installed?

**Comment by delarosatrevin** [comment]
Yes, make sure that Eman2 is installed and properly pointed in the
scipion.conf file.

**Comment by cossorzano** [comment]
Yes, that seems to be the problem, there is something wrong with my 
installation of eman, but I haven't done anything special. It seems to 
be there, but it cannot be seen by Scipion, despite the fact that it is 
correctly pointed by scipion.conf. I will investigae a little bit more

**Comment by cossorzano** [comment]
Jose Miguel was right, Eman leaves in some file the path after installation. I have changed my external disk so that the absolute path had changed. Removing the current installation and reinstalling Eman from Scipion solved the issue.
