### ISSUE TITLE
Scaling 2D averages does not work

### ISSUE THREAD

**Issue by cossorzano** [I2PC/scipion#903]
00028:     2017-03-14 09:11:48.108861
00029:   Traceback (most recent call last):
00030:     File "/media/coss/f3cf45f0-2cc3-4161-94e7-5f1c70af2e45/scipion/scipion/pyworkflow/protocol/protocol.py", line 184, in run
00031:       self._run()
00032:     File "/media/coss/f3cf45f0-2cc3-4161-94e7-5f1c70af2e45/scipion/scipion/pyworkflow/protocol/protocol.py", line 230, in _run
00033:       resultFiles = self._runFunc()
00034:     File "/media/coss/f3cf45f0-2cc3-4161-94e7-5f1c70af2e45/scipion/scipion/pyworkflow/protocol/protocol.py", line 226, in _runFunc
00035:       return self._func(*self._args)
00036:     File "/media/coss/f3cf45f0-2cc3-4161-94e7-5f1c70af2e45/scipion/scipion/pyworkflow/em/packages/xmipp3/protocol_preprocess/protocol_process.py", line 97, in createOutputStep
00037:       itemDataIterator=md.iterRows(self.outputMd, sortByLabel=md.MDL_ITEM_ID))
00038:     File "/media/coss/f3cf45f0-2cc3-4161-94e7-5f1c70af2e45/scipion/scipion/pyworkflow/em/data.py", line 694, in copyItems
00039:       updateItemCallback(newItem, row)
00040:     File "/media/coss/f3cf45f0-2cc3-4161-94e7-5f1c70af2e45/scipion/scipion/pyworkflow/em/packages/xmipp3/protocol_preprocess/protocol_crop_resize.py", line 252, in _updateItem
00041:       item.getTransform().scaleShifts(self.factor)
00042:   AttributeError: 'NoneType' object has no attribute 'scaleShifts'
00043:   Protocol failed: 'NoneType' object has no attribute 'scaleShifts'

**Comment by pconesa** [comment]
I'm able to reproduce it here, thanks @cossorzano

**Comment by pconesa** [comment]
Averages have _aligment = 2D. Is this right? Because of that the crop-resize protocols runs through:

`      if self.inputHasAlign:`
`                item.getTransform().scaleShifts(self.factor)`

And item (in this case average) does not have a Transform object.

So we can test for the transform object...or we can go back and remove "2D" alignment info if it does not make sense.
