### ISSUE TITLE
Eman initial volume fails

### ISSUE THREAD

**Issue by cossorzano** [I2PC/scipion#904]
It seems to be a general problem of Eman installation. It is launched

/media/coss/f3cf45f0-2cc3-4161-94e7-5f1c70af2e45/scipion/scipion/software/em/eman2.12.linux64/Python/bin/python /media/coss/f3cf45f0-2cc3-4161-94e7-5f1c70af2e45/scipion/scipion/software/em/eman2.12.linux64/bin/e2initialmodel.py   --input=../representatives.stk iter=8 --sym=d2 --tries=10 --parallel=thread:8

I have checked that these programs exist. In fact, it starts processing and prints
00019:   Models will be 1.000 A/pix

But then it suddenly stops with the error message

00020:   Exception in thread Thread-1:
00021:   Traceback (most recent call last):
00022:     File "/media/coss/f3cf45f0-2cc3-4161-94e7-5f1c70af2e45/scipion/scipion/software/em/eman2.12.linux64/Python/lib/python2.7/threading.py", line 551, in __bootstrap_inner
00023:       self.run()
00024:     File "/media/coss/f3cf45f0-2cc3-4161-94e7-5f1c70af2e45/scipion/scipion/software/em/eman2.12.linux64/Python/lib/python2.7/threading.py", line 504, in run
00025:       self.__target(*self.__args, **self.__kwargs)
00026:     File "/media/coss/f3cf45f0-2cc3-4161-94e7-5f1c70af2e45/scipion/scipion/software/em/eman2.12.linux64/lib/EMAN2PAR.py", line 577, in run
00027:       proc=subprocess.Popen(["e2parallel.py","localclient","--taskin=%s/%07d"%(self.scratchdir,self.nextid),"--taskout=%s/%07d.out"%(self.scratchdir,self.nextid)])
00028:     File "/media/coss/f3cf45f0-2cc3-4161-94e7-5f1c70af2e45/scipion/scipion/software/em/eman2.12.linux64/Python/lib/python2.7/subprocess.py", line 679, in __init__
00029:       errread, errwrite)
00030:     File "/media/coss/f3cf45f0-2cc3-4161-94e7-5f1c70af2e45/scipion/scipion/software/em/eman2.12.linux64/Python/lib/python2.7/subprocess.py", line 1249, in _execute_child
00031:       raise child_exception
00032:   OSError: [Errno 2] No such file or directory

Can it be an interference with our own python?

**Comment by azazellochg** [comment]
just a wild guess, could it be that scratch dir is not created? (no permissions or smth else)

**Comment by delarosatrevin** [comment]
Where is the scratch dir for this protocol?

**Comment by azazellochg** [comment]
usually in /tmp/e2tmp.xxxxx Does user have writing permissions to /tmp?

**Comment by cossorzano** [comment]
I am in release-1.1-fixes branch and I do have permissions to create directories in /tmp. I don't know what it can be

**Comment by ldelcano** [comment]
Hi Coss, I have run the same test on my laptop and on a fresh new machine Ubuntu 14 with just Scipion (release_1.1) and eman 2.12 and it passes. See the output log.
We will have to look at your installation.

00001:   RUNNING PROTOCOL -----------------
00002:             PID: 25642
00003:         Scipion:  release-1.1 (2017-03-10) a955d6d
00004:      currentDir: /home/ldelcano/ScipionUserData/projects/TestBPV
00005:      workingDir: Runs/000129_EmanProtInitModel
00006:         runMode: Restart
00007:             MPI: 1
00008:         threads: 4
00009:    Starting at step: 1
00010:    Running steps 
00011:   STARTED: createStackImgsStep, step 1
00012:     2017-03-15 12:36:33.949836
00013:   FINISHED: createStackImgsStep, step 1
00014:     2017-03-15 12:36:34.249427
00015:   STARTED: createInitialModelStep, step 2
00016:     2017-03-15 12:36:34.768294
00017:   /home/ldelcano/scipion/software/em/eman2.12/Python/bin/python /home/ldelcano/scipion/software/em/eman2.12/bin/e2initialmodel.py   --input=../representatives.stk iter=8 --sym=d2 --tries=10 --parallel=thread:4
00018:   Models will be 1.000 A/pix
00019:   initial_models/model_00_01.hdf 5.66730672121 -0.868337079883 1.0
00020:   initial_models/model_00_02.hdf 5.35725367069 -0.862330324948 1.0
00021:   initial_models/model_00_03.hdf 4.6514211297 -0.857332661748 1.0
00022:   initial_models/model_00_04.hdf 5.11006170511 -0.833594806492 1.0
00023:   initial_models/model_00_05.hdf 4.65107917786 -0.825514376163 1.0
00024:   initial_models/model_00_06.hdf 5.16406732798 -0.795103788376 1.0
00025:   initial_models/model_00_07.hdf 4.51061165333 -0.786140799522 1.0
00026:   initial_models/model_00_08.hdf 4.60475450754 -0.782524451613 1.0
00027:   initial_models/model_00_09.hdf 4.64872246981 -0.779542908072 1.0
00028:   initial_models/model_00_10.hdf 4.97033858299 -0.739675357938 1.0
00029:   Cleaning up thread server. Please wait.
00030:   FINISHED: createInitialModelStep, step 2
00031:     2017-03-15 12:39:22.095181
00032:   STARTED: createOutputStep, step 3
00033:     2017-03-15 12:39:22.697945
00034:   FINISHED: createOutputStep, step 3
00035:     2017-03-15 12:39:24.680531
00036:   Cleaning temporarly files....
00037:   ------------------- PROTOCOL FINISHED

**Comment by cossorzano** [comment]
It seems to be something with my installation of Eman, but I can't see what

**Comment by delarosatrevin** [comment]
@cossorzano , Another wild guess about your problem. I see that you are running the Scipion installation from your external hard-drive. Do you know that EMAN2 installation folder can not moved after installed? They put some absolute path in the python scripts. Could be the case that your external hdd is mounted in a different path?

**Comment by cossorzano** [comment]
You may be right, I recently changed the hard drive

**Comment by delarosatrevin** [comment]
Try removing EMAN2 from software/em and install it agin with 'scipion
install eman2 --no-xmipp'

**Comment by cossorzano** [comment]
Yes, this solved the issue. Thanks
