### ISSUE TITLE
Importing movies starts from beginning when continue is selected

### ISSUE THREAD

**Issue by JuhaHuiskonen** [I2PC/scipion#909]
Trying to import movies using 'scipion - import movies' (as individual frames). The process had failed so had to restart (using continue). However it doesn't actually continue but starts from beginning

**Comment by delarosatrevin** [comment]
Hi @JuhaHuiskonen, the same problem is happening to other streaming protocols...I'm looking into this problem. I will let you know when fixed.

**Comment by delarosatrevin** [comment]
Hi @JuhaHuiskonen, I has fixed this issue in #920, among other enhancements related to streaming. Would be good if you could take a look and test if working properly in your hands.
