### ISSUE TITLE
ctfModel for particles

### ISSUE THREAD

**Issue by azazellochg** [I2PC/scipion#912]
A while ago I was thinking to add local ctf refinement at particle level (by Gctf). I was wondering how much modification of CTFModel class will be required, also to keep backward compatibility?

**Comment by delarosatrevin** [comment]
Hi @azazellochg, I don't know exactly how the Gctf estimation works, but I think we don't need much change in the current CTFModel. As you know, after extraction each particle has its own CTFModel attribute, so I think that it can be further re-estimated and not longer the same for all the particles from the same micrograph. Can you comment more about this per-particle estimation in Gctf and what changes do you think are need in the model?

**Comment by azazellochg** [comment]
Hi @delarosatrevin , I saw that CTFModel can be used with any EMobject, but somehow was not sure that it is not only a "micrograph property". I will start to work on it and post here the progress/problems :)

**Comment by delarosatrevin** [comment]
Great!

**Comment by delarosatrevin** [comment]
Any progress on this, @azazellochg ?

**Comment by azazellochg** [comment]
@delarosatrevin unfortunately I haven't started to look into this yet.

**Comment by delarosatrevin** [comment]
Ok, I just wanted to know.

**Comment by azazellochg** [comment]
@delarosatrevin 
So, I have got a first draft for a separate protocol (my fork, branch local_ctf). Few things to note:
1) Gctf estimates CTF de-novo for the full mic, and then refines locally for each particle. This is default behaviour.
2) This means the separate protocol is almost the same as original one, but input particles and mics are required. I didn't find a way to get mics' sampling and full filename from particles set only.
3) Right now particle set is matched with output from Gctf by looking at micname + coordinates.
4) The protocol works sequentially on each micrograph.

**Comment by delarosatrevin** [comment]
Thanks @azazellochg. I will take a look as soon as I can.

**Comment by JuhaHuiskonen** [comment]
I discussed this with @delarosatrevin - which branch is this? Would be very useful... Thanks

**Comment by azazellochg** [comment]
Hi @JuhaHuiskonen , I am afraid it's still half-done - alignment/acquisition/coords params are not passed from input particles yet. Also the branch is not tested at all.
[this is the branch](https://github.com/azazellochg/scipion/tree/local-ctf) based on release-1.1-facilities-devel

**Comment by DmitrySemchonok** [comment]
Dear @azazellochg and @delarosatrevin i& @pconesa s it possible to do the CTF refinement/Bayesian polishing in SCIPION? If yes then how?
Sincerely,
Dmitry
