### ISSUE TITLE
add run ID to the list of input objects

### ISSUE THREAD

**Issue by JuhaHuiskonen** [I2PC/scipion#928]
With complicated workflows it is sometimes difficult to know which input object to select for a new run (unless everything is named manually with unique names of course). When selecting inputs for a new run from a list, it would be useful to see the run ID that produced each of the objects (in addition to the name of the object, info and creation time stamp).

**Comment by delarosatrevin** [comment]
Yes, I agree with your idea. We were considering about addind the ID a while ago when we discussed about some cases that were not very intuitive what is displayed there.

**Comment by azazellochg** [comment]
protocol id column was added
