### ISSUE TITLE
fix notifier.py for scipion old version

### ISSUE THREAD

**Issue by azazellochg** [I2PC/scipion#930]
> Dear colleagues
>  we experiencing the  problem going from the old scipion version 1.0.1 to
> the new one 1.1
> 
> The error we are getting trying to open the project is Error 2 No such file
> or directory: 'Logs/data.log'
> 
> In the version 1.0.1. you can open the project and don't have this error
> 
> Sincerely
> Dmitry

**Comment by pconesa** [comment]
Thanks Gregory!

**Comment by rmarabini** [comment]
Summary: when a project created with scipio 1.0 is open with scipion 1.1 the follwing Error appears

   " Error 2 No such file or directory: 'Logs/data.log'"

1) It seems that the notifier system (new in scipion 1.1) creates a file called data.log in the directory $PROJECT_NAME/Logs.
2) it seems that scipion 1.0 does NOT create this directory by default (scipion 1.1 does)
3) notifier routine has been modified so it checks and creates the Log directory (if needed) before writting the data.log file

  I close this issue

**Comment by pconesa** [comment]
Great! many thanks Roberto.
