### ISSUE TITLE
trouble w/ eman install

### ISSUE THREAD

**Issue by connollypj** [I2PC/scipion#933]
I haven't seen this issue reported, but I'm having the following problem installing the EMAN software package. It doesn't create the expected link and scipion doesn't think it's installed. Everything else seems to have installed w/o problem.  I get the following

> scipion install eman2.12

Scipion v1.0.1 (2016-06-30) Augusto

Building eman2.12 ...
  Skipping command: wget -nv -c -O software/em/eman2.12.linux64.tgz.part http://scipion.cnb.csic.es/downloads/scipion/software/em/eman2.12.linux64.tgz
mv -v software/em/eman2.12.linux64.tgz.part software/em/eman2.12.linux64.tgz
  All targets exist.
  Skipping command: tar -xzf eman2.12.linux64.tgz
  All targets exist.
cd software/em/eman2.12.linux64
./eman2-installer
setenv LC_CTYPE=en_US.utf8
setenv LC_ALL=en_US.utf8
Please add the following line to the end of your /cluster/home/connolly/.cshrc :
source /cluster/home/connolly/EM_Software/scipion/scipion/software/em/eman2.12.linux64/eman2.cshrc
Error: target 'software/em/eman2.12.linux64/eman2.bashrc' not built (after running './eman2-installer')

**Comment by delarosatrevin** [comment]
Hi, this issues was reported here #506, it is already fixed in the current development and a workaround is specified there.

If you want to give a try to the release candidate version you should use the branch 'release-1.1'.

**Comment by connollypj** [comment]
Thanks Jose!

PJC

Peter Connolly Ph.D
Research Fellow 1, Exploratory Biology
Vertex Pharmaceuticals
50 Northern Ave Boston MA 02210

(617)-341-6431 (voice)

**Comment by azazellochg** [comment]
@delarosatrevin actually this bug is back, since I started to look into eman2.2 I saw it. [this](https://github.com/I2PC/scipion/blob/release-1.1/install/script.py#L400) should be changed to `eman2.*rc`

**Comment by connollypj** [comment]
Thanks!   This seems to have my problem!

Best,  peter

Typos by my iPad

On Mar 30, 2017, at 08:48, Gregory Sharov <notifications@github.com<mailto:notifications@github.com>> wrote:


@delarosatrevin<https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_delarosatrevin&d=DwMCaQ&c=TzEZu9LIcihmW37vx9Ah6w&r=knZtYo85USJ35yzn6aCwH4RPy3thX77OYb2aBN-6zG0&m=Ed2pHMD5xD_8XRTocz9CgXnvIpXubsLOFmincbEQd6c&s=SbfKCjQRMD-e-M_7b6IRRCg2ZF7Sd88abNfMynVjY3E&e=> actually this bug is back, since I started to look into eman2.2 I saw it. this<https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_I2PC_scipion_blob_release-2D1.1_install_script.py-23L400&d=DwMCaQ&c=TzEZu9LIcihmW37vx9Ah6w&r=knZtYo85USJ35yzn6aCwH4RPy3thX77OYb2aBN-6zG0&m=Ed2pHMD5xD_8XRTocz9CgXnvIpXubsLOFmincbEQd6c&s=M-Ed9hFr14Whb0hX4XeGQw-6JwRxascZpY7BEdATg0Y&e=> should be changed to eman2.*rc

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub<https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_I2PC_scipion_issues_933-23issuecomment-2D290400286&d=DwMCaQ&c=TzEZu9LIcihmW37vx9Ah6w&r=knZtYo85USJ35yzn6aCwH4RPy3thX77OYb2aBN-6zG0&m=Ed2pHMD5xD_8XRTocz9CgXnvIpXubsLOFmincbEQd6c&s=DbgmGAH3ZUlZRB3hT-Vkjp19tp9Boh3wAbvsNJfc5Xs&e=>, or mute the thread<https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_notifications_unsubscribe-2Dauth_AZiY-2DmHJIdBX2xNg5JJHOrWv0hDhcZ4tks5rq6ShgaJpZM4MtjZ9&d=DwMCaQ&c=TzEZu9LIcihmW37vx9Ah6w&r=knZtYo85USJ35yzn6aCwH4RPy3thX77OYb2aBN-6zG0&m=Ed2pHMD5xD_8XRTocz9CgXnvIpXubsLOFmincbEQd6c&s=nuEFZxoHU2UG1aT2QE1Pb-NSPCr4jxKEU9e4waW3JU0&e=>.


This email message and any attachments are confidential and intended for use by the addressee(s) only. If you are not the intended recipient, please notify me immediately by replying to this message, and destroy all copies of this message and any attachments. Thank you.

**Comment by pconesa** [comment]
Can we close this?

**Comment by delarosatrevin** [comment]
It seems that it is in the code...in install.py
