### ISSUE TITLE
TestExtractMoviesParticle...fails

### ISSUE THREAD

**Issue by pconesa** [I2PC/scipion#937]
it seems there is a .pos file missing.

Command that fails:
./scipion test tests.em.protocols.test_protocols_xmipp_movies.TestExtractMovieParticles

The input coordinates is looking for *.pos at scipion/data/tests/movies/cct, and there are no .pos files in the server for that dataset.

**Comment by pconesa** [comment]
related to #895

**Comment by josuegbl** [comment]
All new files are uploaded. Test again, and close the issue.
