### ISSUE TITLE
Scipion:ERROR running protocol scipion - frealign

### ISSUE THREAD

**Issue by ashraf1111** [I2PC/scipion#943]
Hi all, 
when running the one of the listed scipion tests, I get following error:

**>>> ERROR running protocol scipion - frealign
[   FAILED ] TestMixedBPV.test_workflow
Traceback (most recent call last):
  File "/usr/local/scipion/software/lib/python2.7/unittest/case.py", line 329, in run
    testMethod()
  File "/usr/local/scipion/pyworkflow/tests/em/workflows/test_workflow_mixed.py", line 93, in test_workflow
    self.launchProtocol(protFrealign)
  File "/usr/local/scipion/pyworkflow/tests/tests.py", line 87, in launchProtocol
    raise Exception("ERROR: Protocol not finished")
Exception: ERROR: Protocol not finished**

It looks like the program fails to locate the libmpi.so.1 file "ImportError: libmpi.so.1: cannot open shared object file: No such file or directory" which is present in /usr/lib64/openmpi/lib and not in /usr/lib.
Could anyone suggest how to resolve this issue?

Best,
Ashraf.

**Comment by delarosatrevin** [comment]
Have you run './scipion config' and checked that the MPI path are properly found?
If not found, you could edit the scipion/config/scipion.conf file and set the proper values.

**Comment by ashraf1111** [comment]
Thank you for your reply. When I configured the scipion.conf, everything looked ok.
Here is the excerpt from scipion.conf related to mpi
MPI_LIB = mpi
MPI_LIBDIR = /usr/lib64/openmpi/lib
MPI_INCLUDE = /usr/include/openmpi-x86_64
MPI_BINDIR = /usr/lib64/openmpi/bin

Do I have to change the path in MPI_LIB as well?  

Best,
Ashraf.

**Comment by azazellochg** [comment]
@ashraf1111 What if you check mpi by running ```scipion run mpirun -np 4 hostname```? Does it show the same error?

**Comment by ashraf1111** [comment]
Thank you for your suggestion. I executed the command from terminal and I got an output with four lines of the hostname. I don't see the error that I reported. 

Best,
Ashraf.

**Comment by ashraf1111** [comment]
I am putting here the output from the terminal when I executed the test command so that it may help others to understand the problem in a better way.
[scipion_error.pdf](https://github.com/I2PC/scipion/files/903368/scipion_error.pdf)

Ashraf.

**Comment by azazellochg** [comment]
Hi @ashraf1111 , I think the error was fixed in development version (1.1.0 is coming soon), so you could either update your installation or fix the error by replacing ```numberOfMpi=5```  with ```numberOfThreads=4``` in [this line](https://github.com/I2PC/scipion/blob/master/pyworkflow/tests/em/workflows/test_workflow_mixed.py#L90)

**Comment by ashraf1111** [comment]
Thank you. I changed it as you suggested and it worked. Thank you.

Would it have affected any actual processing if I would have ignored this error?

Best regards,
Ashraf.

**Comment by ashraf1111** [comment]
And, do I have to make this change in every test_workflow_*.py? I executed "scipion tests em.workflows.test_workflow_xmipp" and got following error.

**>>> ERROR running protocol scipion - ml2d
    FAILED with error: 

[   FAILED ] TestXmippWorkflow.testXmippWorkflow

Traceback (most recent call last):
  File "/usr/local/scipion/software/lib/python2.7/unittest/case.py", line 329, in run
    testMethod()
  File "/usr/local/scipion/pyworkflow/tests/em/workflows/test_workflow_xmipp.py", line 116, in testXmippWorkflow
    self.launchProtocol(protML2D)
  File "/usr/local/scipion/pyworkflow/tests/tests.py", line 83, in launchProtocol
    raise Exception("ERROR launching protocol.")
Exception: ERROR launching protocol.

[==========] run 1 tests (90.917 secs)
[  FAILED  ] 1 tests
[  PASSED  ] 0 tests**

Best,
Ashraf.

**Comment by azazellochg** [comment]
@ashraf1111 No. I would suggest to wait for the official release and update then, since there are a lot of changes incorporated. In any case, you are trying to run test protocols, the actual protocols should work in 1.0.1 version.

**Comment by ashraf1111** [comment]
Thank you for the info. I will update it once the new version is released.
Best regards,
Asfarul.
