### ISSUE TITLE
Consensus picking does not work with MPI

### ISSUE THREAD

**Issue by cossorzano** [I2PC/scipion#948]

**Comment by pconesa** [comment]
Hi @cossorzano , it seems to be working here. May be it's a data issue? I've seen it failing in your machine. May be we can explore your case.

**Comment by delarosatrevin** [comment]
Anyway, the consensus picking protocol is implemented purely in Python, so it does not make any sense to use MPI for this protocol. I would recommend changing the default parallel parameters to threads=4, mpi=1....I can't remember if we could disable MPI. If so, mpi=0 would be even better.

**Comment by pconesa** [comment]
Well, I'm not able to run it here now. Not even with threads + STEPS_PARALELL. In serial mode it works fine and looks fast. Is this a bad option?

**Comment by pconesa** [comment]
@cossorzano does this make sense?
![image](https://cloud.githubusercontent.com/assets/785633/25275248/8ddd20c6-2694-11e7-92b2-91c8adf008af.png)

Is the radius "collapsing" particles? I was expecting at least 5948 particles.
