### ISSUE TITLE
--scratch_dir should be removed from command line

### ISSUE THREAD

**Issue by azazellochg** [I2PC/scipion#958]
..when it's not defined. Now it always stays there
https://github.com/I2PC/scipion/blob/release-1.1-relion2/pyworkflow/em/packages/relion/protocol_base.py#L632
for some reason hasValue is not working

**Comment by pconesa** [comment]
Branch is gone, link is here:
https://github.com/I2PC/scipion/blob/release-1.1/pyworkflow/em/packages/relion/protocol_base.py#L632

@josuegbl, how do you see this?

**Comment by pconesa** [comment]
@josuegbl , did you fix this? I remember commenting about this.

**Comment by josuegbl** [comment]
Yes, it is fixed in release-1.1-fixes-relion2

2017-06-02 18:40 GMT+02:00 Pablo Conesa <notifications@github.com>:
