### ISSUE TITLE
gautomatch doesnt work properly

### ISSUE THREAD

**Issue by josuegbl** [I2PC/scipion#970]
In release-1.1 balbino, gautomatch doesnt pick anything. This is reported by Pablo Perez (JR Lab), with an old successful case

**Comment by azazellochg** [comment]
@josuegbl could you share the input data & params he used? If it's gautomatch-related then I could show this to Kai.

**Comment by pconesa** [comment]
@josuegbl I was thinking about this ......did you check gautomach path?. May be it is a configuration problem?

**Comment by josuegbl** [comment]
Im sorry, false alarm :). We (Carlos Perez and me) re-launched the protocol in v. Balbino and it ran perfectly both wizard and protocol execution. Ill close the issue
