### ISSUE TITLE
color tag by ages

### ISSUE THREAD

**Issue by rmarabini** [I2PC/scipion#972]
Suggestions given in user meeting (28-apr-2017)

1) color tags by age. Make relation between age and color stronger. For example
Compute last modification time and set to
red: no more than 24 hours older than the last modification
green: no more than 24 * 7  hours older than the last modification
blue: no more than 24 * 30 hours older than the last modification
grey: rest 

asked by ????

**Comment by delarosatrevin** [comment]
@rmarabini I think this is already implemented...can we close the issue?

**Comment by rmarabini** [comment]
Yes
