### ISSUE TITLE
execute all

### ISSUE THREAD

**Issue by rmarabini** [I2PC/scipion#973]
We plan to implement execute all that will execute a workflow protocol after protocol. Implement the possibility to make a sequential  execution of workflows (in the same project) that are unrelated. Ideally this will be wait until this resource is free and then lunch this protocol.

**Comment by delarosatrevin** [comment]
@rmarabini , I have started working on this and now I'm able to schedule jobs even if the input is not ready. The are in "scheduled" state until the input become ready and then the protocol is launched (either locally or in a queuing system). Now the next step is to schedule many at once, that it is the "run all" mentioned here. This should not be difficult.

Still missing:
* Allow dependencies just by computing resources, i. e. the sequential execution of two unrelated workflows (now the dependencies are by data input)
* A nicer way to select "future" output from scratch (right now you can only schedule jobs if you have loaded from a template or copied a branch where the relations are already established). My plan for this is to allow the 'Browse object' dialog to include "possible output", but this will requires that each protocol can define it "possible output" object types.

**Comment by delarosatrevin** [comment]
By the way, it seems to me that this issue is duplicated...there is somewhere another issue related to "run all". Maybe we can add any previous comment to this thread and close the older one.

**Comment by yaizar** [comment]
duplicated issue was #503 : Implement Run-All, Stop-All and Restart-All
This utility could improve the user experience in the Scipion-Box, although it can also be useful in other context for a few steps in a processing branch.
Closing old one.

**Comment by pconesa** [comment]
Done already in Scipion 2.0
