### ISSUE TITLE
Optical flow protocol

### ISSUE THREAD

**Issue by 1aviervargas** [I2PC/scipion#978]
In Optical Flow-> additional parameters -> Use previous movie alignment to sum frames 

No default parameter. Gives an error

**Comment by delarosatrevin** [comment]
This is intentional, to force users to select one option.

**Comment by cossorzano** [comment]
I agree with Javi, I still don't understand why we cannot take the 
default parameter of using the previous alignment if it is present. 
Optical flow is supposed to be executed after a global alignment, it 
would be weird to have a previous global alignment and not use it.

**Comment by delarosatrevin** [comment]
This parameter is inherited from a base class, so the same, for some protocols make sense to use the previous alignment while for others not.

**Comment by pconesa** [comment]
XmippProtOFAlignment has it's own "_defineAlignmentParams" where "useAlignment" is defined. I guess we are talking about this and we can safely change it to:

group.addParam('useAlignment', params.BooleanParam, default=True,

Right?
