### ISSUE TITLE
In Project, Export tree graph 

### ISSUE THREAD

**Issue by 1aviervargas** [I2PC/scipion#979]
It does not work

**Comment by yaizar** [comment]
I don't see any errors or unexpected behavior here, when we click on this option we get this output on the console:

```
digraph {
   PROJECT -> 2; 
   PROJECT -> 455; 
   2 -> 55; 
   2 -> 341; 
   2 -> 519; 
   2 -> 1077; 
   2 -> 2084; 
   55 -> 105; 
   55 -> 151; 
...}
export SCIPION_TREE_NAME=1 # to use names instead of ids
```

What is the expected outcome here?

**Comment by delarosatrevin** [comment]
This is the expected behavior, export the graph information to DOT format (rarely used). Anyway, maybe it can be confusing for users and maybe we could consider hiding it a little bit.

**Comment by yaizar** [comment]
Maybe opening it with the text editor instead of printing it in the console?

**Comment by yaizar** [comment]
I'm going to have a text editor open the info in DOT format when we click this option unless someone thinks there's a more convenient idea
