### ISSUE TITLE
Xmipp particle extraction protocol

### ISSUE THREAD

**Issue by 1aviervargas** [I2PC/scipion#981]
In xmipp particle extraction

Phase flip has not a default value
Invert Contrast has not a default value

This gives an error...

**Comment by delarosatrevin** [comment]
Again, this is not an error, is an option that "we want" the user to
select.
For this cases there is not good default option. For example, the phase
flip is
recommended for some packages (Xmipp, Spider, etc) while not recommended
for other (Frealign, Relion, etc). So, the best is the user to explicitly
select what it wants to do.

**Comment by cossorzano** [comment]
Here, I agree with the logic of making the user to select. These choices 
are important and any combination makes sense.
