### ISSUE TITLE
Spider refinement finished without correct output

### ISSUE THREAD

**Issue by yaizar** [I2PC/scipion#989]
When running spider refinement, the protocol finished successfully but the output was wrong:
- There was no output SetOfParticles
- It outputs a non existing volume: Volume(no-dim, 3.54Å/px)

**Comment by azazellochg** [comment]
For the first problem, the function rowToAlignment not implemented yet for Spider. Also it cannot yet parse output alignment file. I am working on it but it won't be ready for 1.1 release

**Comment by pconesa** [comment]
Thanks @azazellochg , we'll try a fix
