### ISSUE TITLE
ethan picker missing in 1.1-beta

### ISSUE THREAD

**Issue by JuhaHuiskonen** [I2PC/scipion#994]
Hi all, it seems Ethan particle picker is missing in 1.1-beta.

**Comment by delarosatrevin** [comment]
I will check this.

**Comment by pconesa** [comment]
We are releasing tomorrow. Ethan picker is in a PR: https://github.com/I2PC/scipion/pull/1007
But @josuegbl  has reported an issue with the particle radius.

**Comment by delarosatrevin** [comment]
@pconesa I could try to get the wizard working tomorrow (just to add some dramatic touch to the last moments before the release). Anyway, I think in the worse case, could could disable the wizard and include it in the release. It would be better for users to have the functionality of this picker even if not with the wizard included.

**Comment by delarosatrevin** [comment]
@pconesa I think I will not be able to make the wizard work before the release. Still I will propose to include the Ethan picker but with the wizard disabled.

**Comment by pconesa** [comment]
Ok, thanks @delarosatrevin, we can always include it in the "service pack".
